module OpenAI
  module Resources
    class Videos
      def create_and_poll: (
        prompt: String,
        ?input_reference: OpenAI::Models::VideoCreateParams::input_reference,
        ?model: OpenAI::Models::video_model,
        ?seconds: OpenAI::Models::video_seconds,
        ?size: OpenAI::Models::video_size,
        ?poll_interval: Numeric?,
        ?request_options: OpenAI::request_opts
      ) -> OpenAI::Video

      def poll: (
        String video_id,
        ?poll_interval: Numeric?,
        ?request_options: OpenAI::request_opts
      ) -> OpenAI::Video
    end
  end
end
