module OpenAI
  module Models
    module Live
      type client_delegation = { ?type: :client }

      class ClientDelegation < OpenAI::Internal::Type::BaseModel
        # The delegation owner. Always `client` for tasks handled by your application.
        attr_accessor type: :client

        # @param type
        #   The delegation owner. Always `client` for tasks handled by your application.
        def initialize: (?type: :client) -> void

        def to_hash: -> { ?type: :client }
      end
    end
  end
end
