module OpenAI
  module Models
    module Live
      type live_create_params =
        {
          session: OpenAI::Live::MediaSessionConfig,
          transport: OpenAI::Live::LiveCreateParams::Transport,
          ?request_options: OpenAI::request_opts
        }

      class LiveCreateParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        # Startup configuration for the Live session.
        attr_accessor session: OpenAI::Live::MediaSessionConfig

        # WebRTC transport with the browser's SDP offer.
        attr_accessor transport: OpenAI::Live::LiveCreateParams::Transport

        # @param session
        #   Startup configuration for the Live session.
        # @param transport
        #   WebRTC transport with the browser's SDP offer.
        def initialize: (
          session: OpenAI::Live::MediaSessionConfig,
          transport: OpenAI::Live::LiveCreateParams::Transport,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          session: OpenAI::Live::MediaSessionConfig,
          transport: OpenAI::Live::LiveCreateParams::Transport,
          ?request_options: OpenAI::RequestOptions
        }

        type transport = { sdp: String, ?type: :webrtc }

        class Transport < OpenAI::Internal::Type::BaseModel
          # Session Description Protocol message for the WebRTC connection.
          attr_accessor sdp: String

          # The transport used for the Live session. Always `webrtc`.
          attr_accessor type: :webrtc

          # @param sdp
          #   Session Description Protocol message for the WebRTC connection.
          # @param type
          #   The transport used for the Live session. Always `webrtc`.
          def initialize: (sdp: String, ?type: :webrtc) -> void

          def to_hash: -> { sdp: String, ?type: :webrtc }
        end
      end
    end
  end
end
