module OpenAI
  module Models
    module Live
      type session_download_recording_params =
        { session_id: String, ?request_options: OpenAI::request_opts }

      class SessionDownloadRecordingParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor session_id: String

        def initialize: (
          session_id: String,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          session_id: String,
          ?request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
