module OpenAI
  module Models
    module Live
      type session_updated_event =
        {
          event_id: String,
          session: OpenAI::Live::SessionResource,
          ?type: :"session.updated",
          ?client_event_id: String
        }

      class SessionUpdatedEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor event_id: String

        attr_accessor session: OpenAI::Live::SessionResource

        attr_accessor type: :"session.updated"

        attr_reader client_event_id: String?

        def client_event_id=: (String) -> String

        def initialize: (
          event_id: String,
          session: OpenAI::Live::SessionResource,
          ?client_event_id: String,
          ?type: :"session.updated"
        ) -> void

        def to_hash: -> {
          event_id: String,
          session: OpenAI::Live::SessionResource,
          ?type: :"session.updated",
          ?client_event_id: String
        }
      end
    end
  end
end
