module OpenAI
  module Resources
    class FineTuning
      class Alpha
        class Graders
          def with_raw_response: -> Graders::WithRawResponse
          def run: (
            grader: OpenAI::Models::FineTuning::Alpha::GraderRunParams::grader,
            model_sample: String,
            ?item: top,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::Models::FineTuning::Alpha::GraderRunResponse

          def validate: (
            grader: OpenAI::Models::FineTuning::Alpha::GraderValidateParams::grader,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::Models::FineTuning::Alpha::GraderValidateResponse

          def initialize: (client: OpenAI::Internal::Transport::_RequestClient) -> void

          class WithRawResponse
            def run: (
            grader: OpenAI::Models::FineTuning::Alpha::GraderRunParams::grader,
            model_sample: String,
            ?item: top,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::RawResponse[OpenAI::Models::FineTuning::Alpha::GraderRunResponse]

            def validate: (
            grader: OpenAI::Models::FineTuning::Alpha::GraderValidateParams::grader,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::RawResponse[OpenAI::Models::FineTuning::Alpha::GraderValidateResponse]

            def initialize: (resource: Graders) -> void
          end
        end
      end
    end
  end
end
