module OpenAI
  module Resources
    class FineTuning
      class Alpha
        class Graders
          def run: (
            grader: OpenAI::Models::FineTuning::Alpha::GraderRunParams::grader,
            model_sample: String,
            ?item: top,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::Models::FineTuning::Alpha::GraderRunResponse

          def validate: (
            grader: OpenAI::Models::FineTuning::Alpha::GraderValidateParams::grader,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::Models::FineTuning::Alpha::GraderValidateResponse

          def initialize: (client: OpenAI::Client) -> void
        end
      end
    end
  end
end
