# typed: strong

module OpenAI
  module Resources
    class ContentProvenanceChecks
      # Check whether an image or audio file contains known OpenAI provenance signals.
      # [Learn more about content provenance](/api/docs/guides/content-provenance).
      #
      # If `not_detected`, it means the tool did not find supported signals in the
      # uploaded file. The content could still have been generated by OpenAI if the
      # metadata was stripped or has evidence of tampering, the watermark was degraded,
      # it comes from a legacy generation model, or it was created before provenance
      # signals were available. Content could also still be AI-generated by another
      # company's model, which the tool currently does not detect.
      sig do
        params(
          file: OpenAI::Internal::FileInput,
          request_options: OpenAI::RequestOptions::OrHash
        ).returns(OpenAI::ContentProvenanceCheck)
      end
      def create(
        # The image or audio file to check for supported OpenAI provenance signals.
        #
        # `String`, `StringIO`, and pathless `IO` inputs are sent with generic upload
        # metadata. Use `OpenAI::FilePart` when you need to override the filename or
        # content type.
        file:,
        request_options: {}
      )
      end

      # @api private
      sig { params(client: OpenAI::Client).returns(T.attached_class) }
      def self.new(client:)
      end
    end
  end
end
