module OpenAI
  module Resources
    class Admin
      class Organization
        class Projects
          class ServiceAccounts
            class APIKeys
              def create: (
                String service_account_id,
                project_id: String,
                ?name: String,
                ?scopes: ::Array[String],
                ?request_options: OpenAI::request_opts
              ) -> OpenAI::Models::Admin::Organization::Projects::ServiceAccounts::APIKeyCreateResponse

              def initialize: (client: OpenAI::Client) -> void
            end
          end
        end
      end
    end
  end
end
