# typed: strong

module OpenAI
  module Models
    module Beta
      module Threads
        class RefusalContentBlock < OpenAI::Internal::Type::BaseModel
          sig { returns(String) }
          attr_accessor :refusal

          # Always `refusal`.
          sig { returns(Symbol) }
          attr_accessor :type

          # The refusal content generated by the assistant.
          sig { params(refusal: String, type: Symbol).returns(T.attached_class) }
          def self.new(refusal:, type: :refusal)
          end

          sig { override.returns({refusal: String, type: Symbol}) }
          def to_hash
          end
        end
      end
    end
  end
end
