# frozen_string_literal: true

module OpenAI
  module Models
    # @see OpenAI::Resources::ContentProvenanceChecks#create
    class ContentProvenanceCheck < OpenAI::Internal::Type::BaseModel
      # @!attribute created_at
      #   The Unix timestamp, in seconds, when the provenance check was created.
      #
      #   @return [Integer]
      required :created_at, Integer

      # @!attribute object
      #   The object type. Always `content_provenance_check` for this endpoint.
      #
      #   @return [Symbol, OpenAI::Models::ContentProvenanceCheck::Object]
      required :object, enum: -> { OpenAI::ContentProvenanceCheck::Object }

      # @!attribute results
      #   The provenance results that apply to the uploaded file. Image results include
      #   C2PA and SynthID; audio results include SynthID.
      #
      #   @return [Array<OpenAI::Models::ContentProvenanceCheck::Result::C2PA, OpenAI::Models::ContentProvenanceCheck::Result::SynthID>]
      required :results, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::ContentProvenanceCheck::Result] }

      # @!method initialize(created_at:, object:, results:)
      #   Some parameter documentations has been truncated, see
      #   {OpenAI::Models::ContentProvenanceCheck} for more details.
      #
      #   @param created_at [Integer] The Unix timestamp, in seconds, when the provenance check was created.
      #
      #   @param object [Symbol, OpenAI::Models::ContentProvenanceCheck::Object] The object type. Always `content_provenance_check` for this endpoint.
      #
      #   @param results [Array<OpenAI::Models::ContentProvenanceCheck::Result::C2PA, OpenAI::Models::ContentProvenanceCheck::Result::SynthID>] The provenance results that apply to the uploaded file. Image results include C2

      # The object type. Always `content_provenance_check` for this endpoint.
      #
      # @see OpenAI::Models::ContentProvenanceCheck#object
      module Object
        extend OpenAI::Internal::Type::Enum

        CONTENT_PROVENANCE_CHECK = :content_provenance_check

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      module Result
        extend OpenAI::Internal::Type::Union

        discriminator :type

        variant :c2pa, -> { OpenAI::ContentProvenanceCheck::Result::C2PA }

        variant :synthid, -> { OpenAI::ContentProvenanceCheck::Result::SynthID }

        class C2PA < OpenAI::Internal::Type::BaseModel
          # @!attribute generated_at
          #   The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
          #   was generated, when available.
          #
          #   @return [String, nil]
          required :generated_at, String, nil?: true

          # @!attribute issuer
          #   The C2PA manifest issuer, when available.
          #
          #   @return [String, nil]
          required :issuer, String, nil?: true

          # @!attribute model
          #   The OpenAI model recorded by the provenance signal, when available.
          #
          #   @return [String, nil]
          required :model, String, nil?: true

          # @!attribute outcome
          #   Whether a supported OpenAI C2PA provenance signal was detected. If
          #   `not_detected`, it means the tool did not find supported signals in the uploaded
          #   file. The content could still have been generated by OpenAI if the metadata was
          #   stripped or has evidence of tampering, the watermark was degraded, it comes from
          #   a legacy generation model, or it was created before provenance signals were
          #   available. Content could also still be AI-generated by another company's model,
          #   which the tool currently does not detect.
          #
          #   @return [Symbol, OpenAI::Models::ContentProvenanceCheck::Result::C2PA::Outcome]
          required :outcome, enum: -> { OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome }

          # @!attribute type
          #   The provenance signal type. Always `c2pa`.
          #
          #   @return [Symbol, :c2pa]
          required :type, const: :c2pa

          # @!attribute validation_state
          #   The validation status of the C2PA manifest in the uploaded image.
          #
          #   @return [Symbol, OpenAI::Models::ContentProvenanceCheck::Result::C2PA::ValidationState]
          required :validation_state, enum: -> { OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState }

          # @!method initialize(generated_at:, issuer:, model:, outcome:, validation_state:, type: :c2pa)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::ContentProvenanceCheck::Result::C2PA} for more details.
          #
          #   @param generated_at [String, nil] The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
          #
          #   @param issuer [String, nil] The C2PA manifest issuer, when available.
          #
          #   @param model [String, nil] The OpenAI model recorded by the provenance signal, when available.
          #
          #   @param outcome [Symbol, OpenAI::Models::ContentProvenanceCheck::Result::C2PA::Outcome] Whether a supported OpenAI C2PA provenance signal was detected.
          #
          #   @param validation_state [Symbol, OpenAI::Models::ContentProvenanceCheck::Result::C2PA::ValidationState] The validation status of the C2PA manifest in the uploaded image.
          #
          #   @param type [Symbol, :c2pa] The provenance signal type. Always `c2pa`.

          # Whether a supported OpenAI C2PA provenance signal was detected. If
          # `not_detected`, it means the tool did not find supported signals in the uploaded
          # file. The content could still have been generated by OpenAI if the metadata was
          # stripped or has evidence of tampering, the watermark was degraded, it comes from
          # a legacy generation model, or it was created before provenance signals were
          # available. Content could also still be AI-generated by another company's model,
          # which the tool currently does not detect.
          #
          # @see OpenAI::Models::ContentProvenanceCheck::Result::C2PA#outcome
          module Outcome
            extend OpenAI::Internal::Type::Enum

            DETECTED = :detected
            NOT_DETECTED = :not_detected

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # The validation status of the C2PA manifest in the uploaded image.
          #
          # @see OpenAI::Models::ContentProvenanceCheck::Result::C2PA#validation_state
          module ValidationState
            extend OpenAI::Internal::Type::Enum

            TRUSTED = :trusted
            VALID = :valid
            INVALID = :invalid
            NOT_PRESENT = :not_present

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        class SynthID < OpenAI::Internal::Type::BaseModel
          # @!attribute generated_at
          #   The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
          #   was generated, when available.
          #
          #   @return [String, nil]
          required :generated_at, String, nil?: true

          # @!attribute model
          #   The OpenAI model recorded by the provenance signal, when available.
          #
          #   @return [String, nil]
          required :model, String, nil?: true

          # @!attribute outcome
          #   Whether a supported OpenAI SynthID watermark was detected. If `not_detected`, it
          #   means the tool did not find supported signals in the uploaded file. The content
          #   could still have been generated by OpenAI if the metadata was stripped or has
          #   evidence of tampering, the watermark was degraded, it comes from a legacy
          #   generation model, or it was created before provenance signals were available.
          #   Content could also still be AI-generated by another company's model, which the
          #   tool currently does not detect.
          #
          #   @return [Symbol, OpenAI::Models::ContentProvenanceCheck::Result::SynthID::Outcome]
          required :outcome, enum: -> { OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome }

          # @!attribute type
          #   The provenance signal type. Always `synthid`.
          #
          #   @return [Symbol, :synthid]
          required :type, const: :synthid

          # @!method initialize(generated_at:, model:, outcome:, type: :synthid)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::ContentProvenanceCheck::Result::SynthID} for more details.
          #
          #   @param generated_at [String, nil] The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
          #
          #   @param model [String, nil] The OpenAI model recorded by the provenance signal, when available.
          #
          #   @param outcome [Symbol, OpenAI::Models::ContentProvenanceCheck::Result::SynthID::Outcome] Whether a supported OpenAI SynthID watermark was detected.
          #
          #   @param type [Symbol, :synthid] The provenance signal type. Always `synthid`.

          # Whether a supported OpenAI SynthID watermark was detected. If `not_detected`, it
          # means the tool did not find supported signals in the uploaded file. The content
          # could still have been generated by OpenAI if the metadata was stripped or has
          # evidence of tampering, the watermark was degraded, it comes from a legacy
          # generation model, or it was created before provenance signals were available.
          # Content could also still be AI-generated by another company's model, which the
          # tool currently does not detect.
          #
          # @see OpenAI::Models::ContentProvenanceCheck::Result::SynthID#outcome
          module Outcome
            extend OpenAI::Internal::Type::Enum

            DETECTED = :detected
            NOT_DETECTED = :not_detected

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end

        # @!method self.variants
        #   @return [Array(OpenAI::Models::ContentProvenanceCheck::Result::C2PA, OpenAI::Models::ContentProvenanceCheck::Result::SynthID)]
      end
    end
  end
end
