# frozen_string_literal: true

module OpenAI
  module Models
    class Image < OpenAI::Internal::Type::BaseModel
      # @!attribute b64_json
      #   The base64-encoded JSON of the generated image. Returned by default for GPT
      #   image models, or when `response_format` is set to `b64_json` for models that
      #   support that parameter.
      #
      #   @return [String, nil]
      optional :b64_json, String

      # @!attribute revised_prompt
      #   The revised prompt used to generate the image, for models that support prompt
      #   revision. Not returned by GPT image models.
      #
      #   @return [String, nil]
      optional :revised_prompt, String

      # @!attribute url
      #   The URL of the generated image when `response_format` is set to `url` for models
      #   that support that parameter. Unsupported for GPT image models.
      #
      #   @return [String, nil]
      optional :url, String

      # @!method initialize(b64_json: nil, revised_prompt: nil, url: nil)
      #   Represents the content or the URL of an image generated by the OpenAI API.
      #
      #   @param b64_json [String]
      #     The base64-encoded JSON of the generated image. Returned by default for GPT
      #     image models, or when `response_format` is set to `b64_json` for models that
      #     support that parameter.
      #
      #   @param revised_prompt [String]
      #     The revised prompt used to generate the image, for models that support prompt
      #     revision. Not returned by GPT image models.
      #
      #   @param url [String]
      #     The URL of the generated image when `response_format` is set to `url` for models
      #     that support that parameter. Unsupported for GPT image models.
    end
  end
end
