# frozen_string_literal: true

module OpenAI
  module Models
    class Image < OpenAI::Internal::Type::BaseModel
      # @!attribute b64_json
      #   The base64-encoded image data. Returned by default for the GPT image models. For
      #   the retired `dall-e-2` and `dall-e-3` models, this field was present only when
      #   `response_format` was set to `b64_json`.
      #
      #   @return [String, nil]
      optional :b64_json, String

      # @!attribute revised_prompt
      #   Legacy field for the retired `dall-e-3` model: the revised prompt that was used
      #   to generate the image.
      #
      #   @return [String, nil]
      optional :revised_prompt, String

      # @!attribute url
      #   Legacy field for the retired `dall-e-2` and `dall-e-3` models: the URL of the
      #   generated image when `response_format` was set to `url`, the legacy default.
      #   Unsupported for the GPT image models.
      #
      #   @return [String, nil]
      optional :url, String

      # @!method initialize(b64_json: nil, revised_prompt: nil, url: nil)
      #   Represents the content or the URL of an image generated by the OpenAI API.
      #
      #   @param b64_json [String]
      #     The base64-encoded image data. Returned by default for the GPT image models. For
      #     the retired `dall-e-2` and `dall-e-3` models, this field was present only when
      #     `response_format` was set to `b64_json`.
      #
      #   @param revised_prompt [String]
      #     Legacy field for the retired `dall-e-3` model: the revised prompt that was used
      #     to generate the image.
      #
      #   @param url [String]
      #     Legacy field for the retired `dall-e-2` and `dall-e-3` models: the URL of the
      #     generated image when `response_format` was set to `url`, the legacy default.
      #     Unsupported for the GPT image models.
    end
  end
end
