# frozen_string_literal: true

module OpenAI
  module Models
    # @see OpenAI::Resources::Images#generate
    #
    # @see OpenAI::Resources::Images#generate_stream_raw
    class ImageGenerateParams < OpenAI::Internal::Type::BaseModel
      extend OpenAI::Internal::Type::RequestParameters::Converter
      include OpenAI::Internal::Type::RequestParameters

      # @!attribute prompt
      #   A text description of the desired image(s). The maximum length is 32000
      #   characters for the GPT image models. Legacy limits for the retired models were
      #   1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
      #
      #   @return [String]
      required :prompt, String

      # @!attribute background
      #   Allows to set transparency for the background of the generated image(s). Must be
      #   one of `transparent`, `opaque`, or `auto` (default value). When `auto` is used,
      #   the model will automatically determine the best background for the image.
      #
      #   `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their `2026-09-08`
      #   snapshots, support `opaque` and `transparent` backgrounds. Transparent
      #   backgrounds are available for supported GPT Image models. For `gpt-image-2` and
      #   `gpt-image-2-2026-04-21`, this support is in preview. When using `transparent`,
      #   set the output format to `png` or `webp`.
      #
      #   @return [Symbol, OpenAI::Models::ImageGenerateParams::Background, nil]
      optional :background, enum: -> { OpenAI::ImageGenerateParams::Background }, nil?: true

      # @!attribute model
      #   The GPT Image model to use for image generation. Specify a supported model
      #   explicitly, such as `gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`,
      #   `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`,
      #   `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, or
      #   `gpt-image-2.5-flare-2026-09-08`. DALL·E 2 (`dall-e-2`) and DALL·E 3
      #   (`dall-e-3`) were retired from the API on May 12, 2026; see
      #   [deprecations](https://developers.openai.com/api/docs/deprecations).
      #
      #   @return [String, Symbol, OpenAI::Models::ImageModel, nil]
      optional :model, union: -> { OpenAI::ImageGenerateParams::Model }, nil?: true

      # @!attribute moderation
      #   Control the content-moderation level for images generated by the GPT image
      #   models. Must be either `low` for less restrictive filtering or `auto` (default
      #   value).
      #
      #   @return [Symbol, OpenAI::Models::ImageGenerateParams::Moderation, nil]
      optional :moderation, enum: -> { OpenAI::ImageGenerateParams::Moderation }, nil?: true

      # @!attribute n
      #   The number of images to generate. Must be between 1 and 10. The retired
      #   `dall-e-3` model only supported `n=1`.
      #
      #   @return [Integer, nil]
      optional :n, Integer, nil?: true

      # @!attribute output_compression
      #   The compression level (0-100%) for the generated images. This parameter is only
      #   supported for the GPT image models with the `webp` or `jpeg` output formats, and
      #   defaults to 100.
      #
      #   @return [Integer, nil]
      optional :output_compression, Integer, nil?: true

      # @!attribute output_format
      #   The format in which the generated images are returned. This parameter is only
      #   supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
      #
      #   @return [Symbol, OpenAI::Models::ImageGenerateParams::OutputFormat, nil]
      optional :output_format, enum: -> { OpenAI::ImageGenerateParams::OutputFormat }, nil?: true

      # @!attribute partial_images
      #   The number of partial images to generate. This parameter is used for streaming
      #   responses that return partial images. Value must be between 0 and 3. When set to
      #   0, the response will be a single image sent in one streaming event.
      #
      #   Note that the final image may be sent before the full number of partial images
      #   are generated if the full image is generated more quickly.
      #
      #   @return [Integer, nil]
      optional :partial_images, Integer, nil?: true

      # @!attribute quality
      #   The quality of the image that will be generated.
      #
      #   - `auto` (default value) will automatically select the best quality for the
      #     given model.
      #   - `high`, `medium` and `low` are supported for the GPT image models.
      #   - `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their
      #     `2026-09-08` snapshots, also support `xhigh` and `max`.
      #   - The retired `dall-e-3` model supported the legacy values `hd` and `standard`.
      #   - The retired `dall-e-2` model only supported the legacy value `standard`.
      #
      #   @return [Symbol, OpenAI::Models::ImageGenerateParams::Quality, nil]
      optional :quality, enum: -> { OpenAI::ImageGenerateParams::Quality }, nil?: true

      # @!attribute response_format
      #   Legacy response format: `url` or `b64_json`, for the retired `dall-e-2` and
      #   `dall-e-3` models. Returned URLs were valid for 60 minutes after image
      #   generation. This parameter is not supported for the GPT image models, which
      #   always return base64-encoded images.
      #
      #   @return [Symbol, OpenAI::Models::ImageGenerateParams::ResponseFormat, nil]
      optional :response_format, enum: -> { OpenAI::ImageGenerateParams::ResponseFormat }, nil?: true

      # @!attribute size
      #   The size of the generated images. For `gpt-image-2`, `gpt-image-2-2026-04-21`,
      #   `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`,
      #   `gpt-image-2.5-flare`, and `gpt-image-2.5-flare-2026-09-08`, arbitrary
      #   resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`.
      #   Width and height must both be divisible by 16 and the requested aspect ratio
      #   must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and
      #   the maximum supported resolution is `3840x2160`. The requested size must also
      #   satisfy the model's current pixel and edge limits. The standard sizes
      #   `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models;
      #   `auto` is supported for models that allow automatic sizing. Legacy sizes for the
      #   retired `dall-e-2` model were `256x256`, `512x512`, and `1024x1024`. Legacy
      #   sizes for the retired `dall-e-3` model were `1024x1024`, `1792x1024`, and
      #   `1024x1792`.
      #
      #   @return [String, Symbol, OpenAI::Models::ImageGenerateParams::Size, nil]
      optional :size, union: -> { OpenAI::ImageGenerateParams::Size }, nil?: true

      # @!attribute style
      #   Legacy style options `vivid` and `natural` for the retired `dall-e-3` model.
      #   Vivid produced hyper-real and dramatic images; natural produced more natural,
      #   less hyper-real looking images. This parameter is not supported for the GPT
      #   image models.
      #
      #   @return [Symbol, OpenAI::Models::ImageGenerateParams::Style, nil]
      optional :style, enum: -> { OpenAI::ImageGenerateParams::Style }, nil?: true

      # @!attribute user
      #   A unique identifier representing your end-user, which can help OpenAI to monitor
      #   and detect abuse.
      #   [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers).
      #
      #   @return [String, nil]
      optional :user, String

      # @!method initialize(prompt:, background: nil, model: nil, moderation: nil, n: nil, output_compression: nil, output_format: nil, partial_images: nil, quality: nil, response_format: nil, size: nil, style: nil, user: nil, request_options: {})
      #   @param prompt [String]
      #     A text description of the desired image(s). The maximum length is 32000
      #     characters for the GPT image models. Legacy limits for the retired models were
      #     1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
      #
      #   @param background [Symbol, OpenAI::Models::ImageGenerateParams::Background, nil]
      #     Allows to set transparency for the background of the generated image(s). Must be
      #     one of `transparent`, `opaque`, or `auto` (default value). When `auto` is used,
      #     the model will automatically determine the best background for the image.
      #
      #     `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their `2026-09-08`
      #     snapshots, support `opaque` and `transparent` backgrounds. Transparent
      #     backgrounds are available for supported GPT Image models. For `gpt-image-2` and
      #     `gpt-image-2-2026-04-21`, this support is in preview. When using `transparent`,
      #     set the output format to `png` or `webp`.
      #
      #   @param model [String, Symbol, OpenAI::Models::ImageModel, nil]
      #     The GPT Image model to use for image generation. Specify a supported model
      #     explicitly, such as `gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`,
      #     `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`,
      #     `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, or
      #     `gpt-image-2.5-flare-2026-09-08`. DALL·E 2 (`dall-e-2`) and DALL·E 3
      #     (`dall-e-3`) were retired from the API on May 12, 2026; see
      #     [deprecations](https://developers.openai.com/api/docs/deprecations).
      #
      #   @param moderation [Symbol, OpenAI::Models::ImageGenerateParams::Moderation, nil]
      #     Control the content-moderation level for images generated by the GPT image
      #     models. Must be either `low` for less restrictive filtering or `auto` (default
      #     value).
      #
      #   @param n [Integer, nil]
      #     The number of images to generate. Must be between 1 and 10. The retired
      #     `dall-e-3` model only supported `n=1`.
      #
      #   @param output_compression [Integer, nil]
      #     The compression level (0-100%) for the generated images. This parameter is only
      #     supported for the GPT image models with the `webp` or `jpeg` output formats, and
      #     defaults to 100.
      #
      #   @param output_format [Symbol, OpenAI::Models::ImageGenerateParams::OutputFormat, nil]
      #     The format in which the generated images are returned. This parameter is only
      #     supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
      #
      #   @param partial_images [Integer, nil]
      #     The number of partial images to generate. This parameter is used for streaming
      #     responses that return partial images. Value must be between 0 and 3. When set to
      #     0, the response will be a single image sent in one streaming event.
      #
      #     Note that the final image may be sent before the full number of partial images
      #     are generated if the full image is generated more quickly.
      #
      #   @param quality [Symbol, OpenAI::Models::ImageGenerateParams::Quality, nil]
      #     The quality of the image that will be generated.
      #
      #     - `auto` (default value) will automatically select the best quality for the
      #       given model.
      #     - `high`, `medium` and `low` are supported for the GPT image models.
      #     - `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their
      #       `2026-09-08` snapshots, also support `xhigh` and `max`.
      #     - The retired `dall-e-3` model supported the legacy values `hd` and `standard`.
      #     - The retired `dall-e-2` model only supported the legacy value `standard`.
      #
      #   @param response_format [Symbol, OpenAI::Models::ImageGenerateParams::ResponseFormat, nil]
      #     Legacy response format: `url` or `b64_json`, for the retired `dall-e-2` and
      #     `dall-e-3` models. Returned URLs were valid for 60 minutes after image
      #     generation. This parameter is not supported for the GPT image models, which
      #     always return base64-encoded images.
      #
      #   @param size [String, Symbol, OpenAI::Models::ImageGenerateParams::Size, nil]
      #     The size of the generated images. For `gpt-image-2`, `gpt-image-2-2026-04-21`,
      #     `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`,
      #     `gpt-image-2.5-flare`, and `gpt-image-2.5-flare-2026-09-08`, arbitrary
      #     resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`.
      #     Width and height must both be divisible by 16 and the requested aspect ratio
      #     must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and
      #     the maximum supported resolution is `3840x2160`. The requested size must also
      #     satisfy the model's current pixel and edge limits. The standard sizes
      #     `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models;
      #     `auto` is supported for models that allow automatic sizing. Legacy sizes for the
      #     retired `dall-e-2` model were `256x256`, `512x512`, and `1024x1024`. Legacy
      #     sizes for the retired `dall-e-3` model were `1024x1024`, `1792x1024`, and
      #     `1024x1792`.
      #
      #   @param style [Symbol, OpenAI::Models::ImageGenerateParams::Style, nil]
      #     Legacy style options `vivid` and `natural` for the retired `dall-e-3` model.
      #     Vivid produced hyper-real and dramatic images; natural produced more natural,
      #     less hyper-real looking images. This parameter is not supported for the GPT
      #     image models.
      #
      #   @param user [String]
      #     A unique identifier representing your end-user, which can help OpenAI to monitor
      #     and detect abuse.
      #     [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers).
      #
      #   @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}]

      # Allows to set transparency for the background of the generated image(s). Must be
      # one of `transparent`, `opaque`, or `auto` (default value). When `auto` is used,
      # the model will automatically determine the best background for the image.
      #
      # `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their `2026-09-08`
      # snapshots, support `opaque` and `transparent` backgrounds. Transparent
      # backgrounds are available for supported GPT Image models. For `gpt-image-2` and
      # `gpt-image-2-2026-04-21`, this support is in preview. When using `transparent`,
      # set the output format to `png` or `webp`.
      module Background
        extend OpenAI::Internal::Type::Enum

        TRANSPARENT = :transparent
        OPAQUE = :opaque
        AUTO = :auto

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # The GPT Image model to use for image generation. Specify a supported model
      # explicitly, such as `gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`,
      # `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`,
      # `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, or
      # `gpt-image-2.5-flare-2026-09-08`. DALL·E 2 (`dall-e-2`) and DALL·E 3
      # (`dall-e-3`) were retired from the API on May 12, 2026; see
      # [deprecations](https://developers.openai.com/api/docs/deprecations).
      module Model
        extend OpenAI::Internal::Type::Union

        variant String

        # The GPT Image model to use for image generation. Specify a supported model explicitly, such as `gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`, `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, or `gpt-image-2.5-flare-2026-09-08`. DALL·E 2 (`dall-e-2`) and DALL·E 3 (`dall-e-3`) were retired from the API on May 12, 2026; see [deprecations](https://developers.openai.com/api/docs/deprecations).
        variant enum: -> { OpenAI::ImageModel }

        # @!method self.variants
        #   @return [Array(String, Symbol, OpenAI::Models::ImageModel)]
      end

      # Control the content-moderation level for images generated by the GPT image
      # models. Must be either `low` for less restrictive filtering or `auto` (default
      # value).
      module Moderation
        extend OpenAI::Internal::Type::Enum

        LOW = :low
        AUTO = :auto

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # The format in which the generated images are returned. This parameter is only
      # supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
      module OutputFormat
        extend OpenAI::Internal::Type::Enum

        PNG = :png
        JPEG = :jpeg
        WEBP = :webp

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # The quality of the image that will be generated.
      #
      # - `auto` (default value) will automatically select the best quality for the
      #   given model.
      # - `high`, `medium` and `low` are supported for the GPT image models.
      # - `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their
      #   `2026-09-08` snapshots, also support `xhigh` and `max`.
      # - The retired `dall-e-3` model supported the legacy values `hd` and `standard`.
      # - The retired `dall-e-2` model only supported the legacy value `standard`.
      module Quality
        extend OpenAI::Internal::Type::Enum

        STANDARD = :standard
        HD = :hd
        LOW = :low
        MEDIUM = :medium
        HIGH = :high
        XHIGH = :xhigh
        MAX = :max
        AUTO = :auto

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # Legacy response format: `url` or `b64_json`, for the retired `dall-e-2` and
      # `dall-e-3` models. Returned URLs were valid for 60 minutes after image
      # generation. This parameter is not supported for the GPT image models, which
      # always return base64-encoded images.
      module ResponseFormat
        extend OpenAI::Internal::Type::Enum

        URL = :url
        B64_JSON = :b64_json

        # @!method self.values
        #   @return [Array<Symbol>]
      end

      # The size of the generated images. For `gpt-image-2`, `gpt-image-2-2026-04-21`,
      # `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`,
      # `gpt-image-2.5-flare`, and `gpt-image-2.5-flare-2026-09-08`, arbitrary
      # resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`.
      # Width and height must both be divisible by 16 and the requested aspect ratio
      # must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and
      # the maximum supported resolution is `3840x2160`. The requested size must also
      # satisfy the model's current pixel and edge limits. The standard sizes
      # `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models;
      # `auto` is supported for models that allow automatic sizing. Legacy sizes for the
      # retired `dall-e-2` model were `256x256`, `512x512`, and `1024x1024`. Legacy
      # sizes for the retired `dall-e-3` model were `1024x1024`, `1792x1024`, and
      # `1024x1792`.
      module Size
        extend OpenAI::Internal::Type::Union

        variant String

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::AUTO }

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::SIZE_1024X1024 }

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::SIZE_1536X1024 }

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::SIZE_1024X1536 }

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::SIZE_256X256 }

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::SIZE_512X512 }

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::SIZE_1792X1024 }

        variant const: -> { OpenAI::Models::ImageGenerateParams::Size::SIZE_1024X1792 }

        # @!method self.variants
        #   @return [Array(String, Symbol)]

        define_sorbet_constant!(:Variants) do
          T.type_alias { T.any(String, OpenAI::ImageGenerateParams::Size::TaggedSymbol) }
        end

        # @!group

        AUTO = :auto
        SIZE_1024X1024 = :"1024x1024"
        SIZE_1536X1024 = :"1536x1024"
        SIZE_1024X1536 = :"1024x1536"
        SIZE_256X256 = :"256x256"
        SIZE_512X512 = :"512x512"
        SIZE_1792X1024 = :"1792x1024"
        SIZE_1024X1792 = :"1024x1792"

        # @!endgroup
      end

      # Legacy style options `vivid` and `natural` for the retired `dall-e-3` model.
      # Vivid produced hyper-real and dramatic images; natural produced more natural,
      # less hyper-real looking images. This parameter is not supported for the GPT
      # image models.
      module Style
        extend OpenAI::Internal::Type::Enum

        VIVID = :vivid
        NATURAL = :natural

        # @!method self.values
        #   @return [Array<Symbol>]
      end
    end
  end
end
