# frozen_string_literal: true

module OpenAI
  module Models
    class Image < OpenAI::BaseModel
      # @!attribute [r] b64_json
      #   The base64-encoded JSON of the generated image, if `response_format` is
      #     `b64_json`.
      #
      #   @return [String, nil]
      optional :b64_json, String

      # @!parse
      #   # @return [String]
      #   attr_writer :b64_json

      # @!attribute [r] revised_prompt
      #   The prompt that was used to generate the image, if there was any revision to the
      #     prompt.
      #
      #   @return [String, nil]
      optional :revised_prompt, String

      # @!parse
      #   # @return [String]
      #   attr_writer :revised_prompt

      # @!attribute [r] url
      #   The URL of the generated image, if `response_format` is `url` (default).
      #
      #   @return [String, nil]
      optional :url, String

      # @!parse
      #   # @return [String]
      #   attr_writer :url

      # @!parse
      #   # Represents the url or the content of an image generated by the OpenAI API.
      #   #
      #   # @param b64_json [String]
      #   # @param revised_prompt [String]
      #   # @param url [String]
      #   #
      #   def initialize(b64_json: nil, revised_prompt: nil, url: nil, **) = super

      # def initialize: (Hash | OpenAI::BaseModel) -> void
    end
  end
end
