module OpenAI
  module Resources
    class Uploads
      class Parts
        def create: (
          String upload_id,
          data: Pathname | StringIO | IO | OpenAI::FilePart,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::Models::Uploads::UploadPart

        def initialize: (client: OpenAI::Client) -> void
      end
    end
  end
end
