module OpenAI
  module Models
    module Beta
      type agent_interrupt_subagent_call_item =
        {
          id: String,
          recipient_agent_id: String,
          sender_agent_id: String,
          status: OpenAI::Models::Beta::agent_function_call_status,
          turn_id: String,
          ?type: :interrupt_subagent_call
        }

      class AgentInterruptSubagentCallItem < OpenAI::Internal::Type::BaseModel
        # The ID of the tool call item.
        attr_accessor id: String

        # The ID of the agent to interrupt.
        attr_accessor recipient_agent_id: String

        # The ID of the agent requesting the interrupt.
        attr_accessor sender_agent_id: String

        # The status of the tool call.
        attr_accessor status: OpenAI::Models::Beta::agent_function_call_status

        # The ID of the turn that contains this item.
        attr_accessor turn_id: String

        # The item type. Always `interrupt_subagent_call`.
        attr_accessor type: :interrupt_subagent_call

        # @param id
        #   The ID of the tool call item.
        # @param recipient_agent_id
        #   The ID of the agent to interrupt.
        # @param sender_agent_id
        #   The ID of the agent requesting the interrupt.
        # @param status
        #   The status of the tool call.
        # @param turn_id
        #   The ID of the turn that contains this item.
        # @param type
        #   The item type. Always `interrupt_subagent_call`.
        def initialize: (
          id: String,
          recipient_agent_id: String,
          sender_agent_id: String,
          status: OpenAI::Models::Beta::agent_function_call_status,
          turn_id: String,
          ?type: :interrupt_subagent_call
        ) -> void

        def to_hash: -> {
          id: String,
          recipient_agent_id: String,
          sender_agent_id: String,
          status: OpenAI::Models::Beta::agent_function_call_status,
          turn_id: String,
          ?type: :interrupt_subagent_call
        }
      end
    end
  end
end
