module OpenAI
  module Models
    module Beta
      type agent_interrupt_subagent_call_item =
        {
          id: String,
          recipient_agent_id: String,
          sender_agent_id: String,
          status: OpenAI::Models::Beta::agent_function_call_status,
          turn_id: String,
          ?type: :interrupt_subagent_call
        }

      class AgentInterruptSubagentCallItem < OpenAI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor recipient_agent_id: String

        attr_accessor sender_agent_id: String

        attr_accessor status: OpenAI::Models::Beta::agent_function_call_status

        attr_accessor turn_id: String

        attr_accessor type: :interrupt_subagent_call

        def initialize: (
          id: String,
          recipient_agent_id: String,
          sender_agent_id: String,
          status: OpenAI::Models::Beta::agent_function_call_status,
          turn_id: String,
          ?type: :interrupt_subagent_call
        ) -> void

        def to_hash: -> {
          id: String,
          recipient_agent_id: String,
          sender_agent_id: String,
          status: OpenAI::Models::Beta::agent_function_call_status,
          turn_id: String,
          ?type: :interrupt_subagent_call
        }
      end
    end
  end
end
