module OpenAI
  module Models
    module Beta
      type assistant_delete_params =
        {  } & OpenAI::Internal::Type::request_parameters

      class AssistantDeleteParams < OpenAI::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        def initialize: (?request_options: OpenAI::request_opts) -> void

        def to_hash: -> OpenAI::Models::Beta::assistant_delete_params
      end
    end
  end
end
