module OpenAI
  module Models
    module Beta
      type assistant_tool =
        OpenAI::Beta::CodeInterpreterTool
        | OpenAI::Beta::FileSearchTool
        | OpenAI::Beta::FunctionTool

      module AssistantTool
        extend OpenAI::Internal::Type::Union

        def self?.variants: -> ::Array[OpenAI::Models::Beta::assistant_tool]
      end
    end
  end
end
