module OpenAI
  module Models
    module Beta
      type assistant_deleted =
        { id: String, deleted: bool, object: :"assistant.deleted" }

      class AssistantDeleted < OpenAI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor deleted: bool

        attr_accessor object: :"assistant.deleted"

        def initialize: (
          id: String,
          deleted: bool,
          ?object: :"assistant.deleted"
        ) -> void
      end
    end
  end
end
