module OpenAI
  module Models
    class BetaResponsePrompt = Beta::BetaResponsePrompt

    module Beta
      type beta_response_prompt =
        {
          id: String,
          ?variables: ::Hash[Symbol, OpenAI::Models::Beta::BetaResponsePrompt::variable]?,
          ?version: String?
        }

      class BetaResponsePrompt < OpenAI::Internal::Type::BaseModel
        # The unique identifier of the prompt template to use.
        attr_accessor id: String

        # Optional map of values to substitute in for variables in your prompt. The
        # substitution values can either be strings, or other Response input types like
        # images or files.
        attr_accessor variables: ::Hash[Symbol, OpenAI::Models::Beta::BetaResponsePrompt::variable]?

        # Optional version of the prompt template.
        attr_accessor version: String?

        # @param id
        #   The unique identifier of the prompt template to use.
        # @param variables
        #   Optional map of values to substitute in for variables in your prompt. The
        #   substitution values can either be strings, or other Response input types like
        #   images or files.
        # @param version
        #   Optional version of the prompt template.
        def initialize: (
          id: String,
          ?variables: ::Hash[Symbol, OpenAI::Models::Beta::BetaResponsePrompt::variable]?,
          ?version: String?
        ) -> void

        def to_hash: -> {
          id: String,
          ?variables: ::Hash[Symbol, OpenAI::Models::Beta::BetaResponsePrompt::variable]?,
          ?version: String?
        }

        type variable =
          String
          | OpenAI::Beta::BetaResponseInputText
          | OpenAI::Beta::BetaResponseInputImage
          | OpenAI::Beta::BetaResponseInputFile

        module Variable
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::Beta::BetaResponsePrompt::variable]
        end
      end
    end
  end
end
