module OpenAI
  module Models
    class BetaResponseInputFileContent = Beta::BetaResponseInputFileContent

    module Beta
      type beta_response_input_file_content =
        {
          type: :input_file,
          detail: OpenAI::Models::Beta::BetaResponseInputFileContent::detail,
          file_data: String?,
          file_id: String?,
          file_url: String?,
          filename: String?,
          prompt_cache_breakpoint: OpenAI::Beta::BetaResponseInputFileContent::PromptCacheBreakpoint?
        }

      class BetaResponseInputFileContent < OpenAI::Internal::Type::BaseModel
        attr_accessor type: :input_file

        attr_reader detail: OpenAI::Models::Beta::BetaResponseInputFileContent::detail?

        def detail=: (
          OpenAI::Models::Beta::BetaResponseInputFileContent::detail
        ) -> OpenAI::Models::Beta::BetaResponseInputFileContent::detail

        attr_accessor file_data: String?

        attr_accessor file_id: String?

        attr_accessor file_url: String?

        attr_accessor filename: String?

        attr_accessor prompt_cache_breakpoint: OpenAI::Beta::BetaResponseInputFileContent::PromptCacheBreakpoint?

        def initialize: (
          ?detail: OpenAI::Models::Beta::BetaResponseInputFileContent::detail,
          ?file_data: String?,
          ?file_id: String?,
          ?file_url: String?,
          ?filename: String?,
          ?prompt_cache_breakpoint: OpenAI::Beta::BetaResponseInputFileContent::PromptCacheBreakpoint?,
          ?type: :input_file
        ) -> void

        def to_hash: -> {
          type: :input_file,
          detail: OpenAI::Models::Beta::BetaResponseInputFileContent::detail,
          file_data: String?,
          file_id: String?,
          file_url: String?,
          filename: String?,
          prompt_cache_breakpoint: OpenAI::Beta::BetaResponseInputFileContent::PromptCacheBreakpoint?
        }

        type detail = :auto | :low | :high

        module Detail
          extend OpenAI::Internal::Type::Enum

          AUTO: :auto
          LOW: :low
          HIGH: :high

          def self?.values: -> ::Array[OpenAI::Models::Beta::BetaResponseInputFileContent::detail]
        end

        type prompt_cache_breakpoint = { mode: :explicit }

        class PromptCacheBreakpoint < OpenAI::Internal::Type::BaseModel
          attr_accessor mode: :explicit

          def initialize: (?mode: :explicit) -> void

          def to_hash: -> { mode: :explicit }
        end
      end
    end
  end
end
