module OpenAI
  module Models
    class BetaResponseCompletedEvent = Beta::BetaResponseCompletedEvent

    module Beta
      type beta_response_completed_event =
        {
          response: OpenAI::Beta::BetaResponse,
          sequence_number: Integer,
          ?type: :"response.completed",
          ?agent: OpenAI::Beta::BetaResponseCompletedEvent::Agent?
        }

      class BetaResponseCompletedEvent < OpenAI::Internal::Type::BaseModel
        # Properties of the completed response.
        attr_accessor response: OpenAI::Beta::BetaResponse

        # The sequence number for this event.
        attr_accessor sequence_number: Integer

        # The type of the event. Always `response.completed`.
        attr_accessor type: :"response.completed"

        # The agent that owns this multi-agent streaming event.
        attr_accessor agent: OpenAI::Beta::BetaResponseCompletedEvent::Agent?

        # @param response
        #   Properties of the completed response.
        # @param sequence_number
        #   The sequence number for this event.
        # @param agent
        #   The agent that owns this multi-agent streaming event.
        # @param type
        #   The type of the event. Always `response.completed`.
        def initialize: (
          response: OpenAI::Beta::BetaResponse,
          sequence_number: Integer,
          ?agent: OpenAI::Beta::BetaResponseCompletedEvent::Agent?,
          ?type: :"response.completed"
        ) -> void

        def to_hash: -> {
          response: OpenAI::Beta::BetaResponse,
          sequence_number: Integer,
          ?type: :"response.completed",
          ?agent: OpenAI::Beta::BetaResponseCompletedEvent::Agent?
        }

        type agent = { agent_name: String }

        class Agent < OpenAI::Internal::Type::BaseModel
          # The canonical name of the agent that produced this item.
          attr_accessor agent_name: String

          # @param agent_name
          #   The canonical name of the agent that produced this item.
          def initialize: (agent_name: String) -> void

          def to_hash: -> { agent_name: String }
        end
      end
    end
  end
end
