module OpenAI
  module Models
    module BetaResponsesServerEvent = Beta::BetaResponsesServerEvent

    module Beta
      type beta_responses_server_event =
        OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError
        | OpenAI::Beta::BetaResponseInjectCreatedEvent
        | OpenAI::Beta::BetaResponseInjectFailedEvent
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseAudioWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseAudioWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseAudioTranscriptWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseAudioTranscriptWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseCodeInterpreterCallCodeWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseCodeInterpreterCallCodeWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseCodeInterpreterCallWsCompleted
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseCodeInterpreterCallInWsProgress
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseCodeInterpreterCallWsInterpreting
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsCompleted
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseContentPartWsAdded
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseContentPartWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsCreated
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseFileSearchCallWsCompleted
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseFileSearchCallInWsProgress
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseFileSearchCallWsSearching
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseFunctionCallArgumentsWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseFunctionCallArgumentsWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseInWsProgress
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsFailed
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsIncomplete
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseOutputItemWsAdded
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseOutputItemWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseReasoningSummaryPartWsAdded
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseReasoningSummaryPartWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseReasoningSummaryTextWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseReasoningSummaryTextWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseReasoningTextWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseReasoningTextWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseRefusalWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseRefusalWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseTextWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseTextWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWebSearchCallWsCompleted
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWebSearchCallInWsProgress
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWebSearchCallWsSearching
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseImageGenCallWsCompleted
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseImageGenCallWsGenerating
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseImageGenCallInWsProgress
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseImageGenCallPartialWsImage
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpCallArgumentsWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpCallArgumentsWsDone
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpCallWsCompleted
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpCallWsFailed
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpCallInWsProgress
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpListToolsWsCompleted
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpListToolsWsFailed
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseMcpListToolsInWsProgress
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseOutputTextAnnotationWsAdded
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsQueued
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseCustomToolCallInputWsDelta
        | OpenAI::Beta::BetaResponsesServerEvent::BetaResponseCustomToolCallInputWsDone

      module BetaResponsesServerEvent
        extend OpenAI::Internal::Type::Union

        type beta_response_audio_ws_delta =
          {
            delta: String,
            sequence_number: Integer,
            type: :"response.audio.delta",
            agent: OpenAI::Beta::BetaResponseAudioDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseAudioWsDelta < OpenAI::Models::Beta::BetaResponseAudioDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            delta: String,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseAudioDeltaEvent::Agent?,
            ?type: :"response.audio.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            delta: String,
            sequence_number: Integer,
            type: :"response.audio.delta",
            agent: OpenAI::Beta::BetaResponseAudioDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_audio_ws_done =
          {
            sequence_number: Integer,
            type: :"response.audio.done",
            agent: OpenAI::Beta::BetaResponseAudioDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseAudioWsDone < OpenAI::Models::Beta::BetaResponseAudioDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseAudioDoneEvent::Agent?,
            ?type: :"response.audio.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            sequence_number: Integer,
            type: :"response.audio.done",
            agent: OpenAI::Beta::BetaResponseAudioDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_audio_transcript_ws_delta =
          {
            delta: String,
            sequence_number: Integer,
            type: :"response.audio.transcript.delta",
            agent: OpenAI::Beta::BetaResponseAudioTranscriptDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseAudioTranscriptWsDelta < OpenAI::Models::Beta::BetaResponseAudioTranscriptDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            delta: String,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseAudioTranscriptDeltaEvent::Agent?,
            ?type: :"response.audio.transcript.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            delta: String,
            sequence_number: Integer,
            type: :"response.audio.transcript.delta",
            agent: OpenAI::Beta::BetaResponseAudioTranscriptDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_audio_transcript_ws_done =
          {
            sequence_number: Integer,
            type: :"response.audio.transcript.done",
            agent: OpenAI::Beta::BetaResponseAudioTranscriptDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseAudioTranscriptWsDone < OpenAI::Models::Beta::BetaResponseAudioTranscriptDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseAudioTranscriptDoneEvent::Agent?,
            ?type: :"response.audio.transcript.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            sequence_number: Integer,
            type: :"response.audio.transcript.done",
            agent: OpenAI::Beta::BetaResponseAudioTranscriptDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_code_interpreter_call_code_ws_delta =
          {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call_code.delta",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCodeDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseCodeInterpreterCallCodeWsDelta < OpenAI::Models::Beta::BetaResponseCodeInterpreterCallCodeDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCodeDeltaEvent::Agent?,
            ?type: :"response.code_interpreter_call_code.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call_code.delta",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCodeDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_code_interpreter_call_code_ws_done =
          {
            code: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call_code.done",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCodeDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseCodeInterpreterCallCodeWsDone < OpenAI::Models::Beta::BetaResponseCodeInterpreterCallCodeDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            code: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCodeDoneEvent::Agent?,
            ?type: :"response.code_interpreter_call_code.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            code: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call_code.done",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCodeDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_code_interpreter_call_ws_completed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call.completed",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCompletedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseCodeInterpreterCallWsCompleted < OpenAI::Models::Beta::BetaResponseCodeInterpreterCallCompletedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCompletedEvent::Agent?,
            ?type: :"response.code_interpreter_call.completed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call.completed",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallCompletedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_code_interpreter_call_in_ws_progress =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call.in_progress",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallInProgressEvent::Agent?,
            stream_id: String
          }

        class BetaResponseCodeInterpreterCallInWsProgress < OpenAI::Models::Beta::BetaResponseCodeInterpreterCallInProgressEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCodeInterpreterCallInProgressEvent::Agent?,
            ?type: :"response.code_interpreter_call.in_progress",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call.in_progress",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallInProgressEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_code_interpreter_call_ws_interpreting =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call.interpreting",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallInterpretingEvent::Agent?,
            stream_id: String
          }

        class BetaResponseCodeInterpreterCallWsInterpreting < OpenAI::Models::Beta::BetaResponseCodeInterpreterCallInterpretingEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCodeInterpreterCallInterpretingEvent::Agent?,
            ?type: :"response.code_interpreter_call.interpreting",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.code_interpreter_call.interpreting",
            agent: OpenAI::Beta::BetaResponseCodeInterpreterCallInterpretingEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_ws_completed =
          {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.completed",
            agent: OpenAI::Beta::BetaResponseCompletedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWsCompleted < OpenAI::Models::Beta::BetaResponseCompletedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCompletedEvent::Agent?,
            ?type: :"response.completed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.completed",
            agent: OpenAI::Beta::BetaResponseCompletedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_content_part_ws_added =
          {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            part: OpenAI::Models::Beta::BetaResponseContentPartAddedEvent::part,
            sequence_number: Integer,
            type: :"response.content_part.added",
            agent: OpenAI::Beta::BetaResponseContentPartAddedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseContentPartWsAdded < OpenAI::Models::Beta::BetaResponseContentPartAddedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            part: OpenAI::Models::Beta::BetaResponseContentPartAddedEvent::part,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseContentPartAddedEvent::Agent?,
            ?type: :"response.content_part.added",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            part: OpenAI::Models::Beta::BetaResponseContentPartAddedEvent::part,
            sequence_number: Integer,
            type: :"response.content_part.added",
            agent: OpenAI::Beta::BetaResponseContentPartAddedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_content_part_ws_done =
          {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            part: OpenAI::Models::Beta::BetaResponseContentPartDoneEvent::part,
            sequence_number: Integer,
            type: :"response.content_part.done",
            agent: OpenAI::Beta::BetaResponseContentPartDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseContentPartWsDone < OpenAI::Models::Beta::BetaResponseContentPartDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            part: OpenAI::Models::Beta::BetaResponseContentPartDoneEvent::part,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseContentPartDoneEvent::Agent?,
            ?type: :"response.content_part.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            part: OpenAI::Models::Beta::BetaResponseContentPartDoneEvent::part,
            sequence_number: Integer,
            type: :"response.content_part.done",
            agent: OpenAI::Beta::BetaResponseContentPartDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_ws_created =
          {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.created",
            agent: OpenAI::Beta::BetaResponseCreatedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWsCreated < OpenAI::Models::Beta::BetaResponseCreatedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCreatedEvent::Agent?,
            ?type: :"response.created",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.created",
            agent: OpenAI::Beta::BetaResponseCreatedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_file_search_call_ws_completed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.file_search_call.completed",
            agent: OpenAI::Beta::BetaResponseFileSearchCallCompletedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseFileSearchCallWsCompleted < OpenAI::Models::Beta::BetaResponseFileSearchCallCompletedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseFileSearchCallCompletedEvent::Agent?,
            ?type: :"response.file_search_call.completed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.file_search_call.completed",
            agent: OpenAI::Beta::BetaResponseFileSearchCallCompletedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_file_search_call_in_ws_progress =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.file_search_call.in_progress",
            agent: OpenAI::Beta::BetaResponseFileSearchCallInProgressEvent::Agent?,
            stream_id: String
          }

        class BetaResponseFileSearchCallInWsProgress < OpenAI::Models::Beta::BetaResponseFileSearchCallInProgressEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseFileSearchCallInProgressEvent::Agent?,
            ?type: :"response.file_search_call.in_progress",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.file_search_call.in_progress",
            agent: OpenAI::Beta::BetaResponseFileSearchCallInProgressEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_file_search_call_ws_searching =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.file_search_call.searching",
            agent: OpenAI::Beta::BetaResponseFileSearchCallSearchingEvent::Agent?,
            stream_id: String
          }

        class BetaResponseFileSearchCallWsSearching < OpenAI::Models::Beta::BetaResponseFileSearchCallSearchingEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseFileSearchCallSearchingEvent::Agent?,
            ?type: :"response.file_search_call.searching",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.file_search_call.searching",
            agent: OpenAI::Beta::BetaResponseFileSearchCallSearchingEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_function_call_arguments_ws_delta =
          {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.function_call_arguments.delta",
            agent: OpenAI::Beta::BetaResponseFunctionCallArgumentsDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseFunctionCallArgumentsWsDelta < OpenAI::Models::Beta::BetaResponseFunctionCallArgumentsDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseFunctionCallArgumentsDeltaEvent::Agent?,
            ?type: :"response.function_call_arguments.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.function_call_arguments.delta",
            agent: OpenAI::Beta::BetaResponseFunctionCallArgumentsDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_function_call_arguments_ws_done =
          {
            arguments: String,
            item_id: String,
            name: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.function_call_arguments.done",
            agent: OpenAI::Beta::BetaResponseFunctionCallArgumentsDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseFunctionCallArgumentsWsDone < OpenAI::Models::Beta::BetaResponseFunctionCallArgumentsDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            arguments: String,
            item_id: String,
            name: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseFunctionCallArgumentsDoneEvent::Agent?,
            ?type: :"response.function_call_arguments.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            arguments: String,
            item_id: String,
            name: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.function_call_arguments.done",
            agent: OpenAI::Beta::BetaResponseFunctionCallArgumentsDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_in_ws_progress =
          {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.in_progress",
            agent: OpenAI::Beta::BetaResponseInProgressEvent::Agent?,
            stream_id: String
          }

        class BetaResponseInWsProgress < OpenAI::Models::Beta::BetaResponseInProgressEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseInProgressEvent::Agent?,
            ?type: :"response.in_progress",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.in_progress",
            agent: OpenAI::Beta::BetaResponseInProgressEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_ws_failed =
          {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.failed",
            agent: OpenAI::Beta::BetaResponseFailedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWsFailed < OpenAI::Models::Beta::BetaResponseFailedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseFailedEvent::Agent?,
            ?type: :"response.failed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.failed",
            agent: OpenAI::Beta::BetaResponseFailedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_ws_incomplete =
          {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.incomplete",
            agent: OpenAI::Beta::BetaResponseIncompleteEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWsIncomplete < OpenAI::Models::Beta::BetaResponseIncompleteEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseIncompleteEvent::Agent?,
            ?type: :"response.incomplete",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.incomplete",
            agent: OpenAI::Beta::BetaResponseIncompleteEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_output_item_ws_added =
          {
            item: OpenAI::Models::Beta::beta_response_output_item,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_item.added",
            agent: OpenAI::Beta::BetaResponseOutputItemAddedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseOutputItemWsAdded < OpenAI::Models::Beta::BetaResponseOutputItemAddedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item: OpenAI::Models::Beta::beta_response_output_item,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseOutputItemAddedEvent::Agent?,
            ?type: :"response.output_item.added",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item: OpenAI::Models::Beta::beta_response_output_item,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_item.added",
            agent: OpenAI::Beta::BetaResponseOutputItemAddedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_output_item_ws_done =
          {
            item: OpenAI::Models::Beta::beta_response_output_item,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_item.done",
            agent: OpenAI::Beta::BetaResponseOutputItemDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseOutputItemWsDone < OpenAI::Models::Beta::BetaResponseOutputItemDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item: OpenAI::Models::Beta::beta_response_output_item,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseOutputItemDoneEvent::Agent?,
            ?type: :"response.output_item.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item: OpenAI::Models::Beta::beta_response_output_item,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_item.done",
            agent: OpenAI::Beta::BetaResponseOutputItemDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_reasoning_summary_part_ws_added =
          {
            item_id: String,
            output_index: Integer,
            part: OpenAI::Beta::BetaResponseReasoningSummaryPartAddedEvent::Part,
            sequence_number: Integer,
            summary_index: Integer,
            type: :"response.reasoning_summary_part.added",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryPartAddedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseReasoningSummaryPartWsAdded < OpenAI::Models::Beta::BetaResponseReasoningSummaryPartAddedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            part: OpenAI::Beta::BetaResponseReasoningSummaryPartAddedEvent::Part,
            sequence_number: Integer,
            summary_index: Integer,
            ?agent: OpenAI::Beta::BetaResponseReasoningSummaryPartAddedEvent::Agent?,
            ?type: :"response.reasoning_summary_part.added",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            part: OpenAI::Beta::BetaResponseReasoningSummaryPartAddedEvent::Part,
            sequence_number: Integer,
            summary_index: Integer,
            type: :"response.reasoning_summary_part.added",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryPartAddedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_reasoning_summary_part_ws_done =
          {
            item_id: String,
            output_index: Integer,
            part: OpenAI::Beta::BetaResponseReasoningSummaryPartDoneEvent::Part,
            sequence_number: Integer,
            summary_index: Integer,
            type: :"response.reasoning_summary_part.done",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryPartDoneEvent::Agent?,
            status: OpenAI::Models::Beta::BetaResponseReasoningSummaryPartDoneEvent::status,
            stream_id: String
          }

        class BetaResponseReasoningSummaryPartWsDone < OpenAI::Models::Beta::BetaResponseReasoningSummaryPartDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            part: OpenAI::Beta::BetaResponseReasoningSummaryPartDoneEvent::Part,
            sequence_number: Integer,
            summary_index: Integer,
            ?agent: OpenAI::Beta::BetaResponseReasoningSummaryPartDoneEvent::Agent?,
            ?status: OpenAI::Models::Beta::BetaResponseReasoningSummaryPartDoneEvent::status,
            ?type: :"response.reasoning_summary_part.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            part: OpenAI::Beta::BetaResponseReasoningSummaryPartDoneEvent::Part,
            sequence_number: Integer,
            summary_index: Integer,
            type: :"response.reasoning_summary_part.done",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryPartDoneEvent::Agent?,
            status: OpenAI::Models::Beta::BetaResponseReasoningSummaryPartDoneEvent::status,
            stream_id: String
          }
        end

        type beta_response_reasoning_summary_text_ws_delta =
          {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            summary_index: Integer,
            type: :"response.reasoning_summary_text.delta",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryTextDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseReasoningSummaryTextWsDelta < OpenAI::Models::Beta::BetaResponseReasoningSummaryTextDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            summary_index: Integer,
            ?agent: OpenAI::Beta::BetaResponseReasoningSummaryTextDeltaEvent::Agent?,
            ?type: :"response.reasoning_summary_text.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            summary_index: Integer,
            type: :"response.reasoning_summary_text.delta",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryTextDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_reasoning_summary_text_ws_done =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            summary_index: Integer,
            text: String,
            type: :"response.reasoning_summary_text.done",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryTextDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseReasoningSummaryTextWsDone < OpenAI::Models::Beta::BetaResponseReasoningSummaryTextDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            summary_index: Integer,
            text: String,
            ?agent: OpenAI::Beta::BetaResponseReasoningSummaryTextDoneEvent::Agent?,
            ?type: :"response.reasoning_summary_text.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            summary_index: Integer,
            text: String,
            type: :"response.reasoning_summary_text.done",
            agent: OpenAI::Beta::BetaResponseReasoningSummaryTextDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_reasoning_text_ws_delta =
          {
            content_index: Integer,
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.reasoning_text.delta",
            agent: OpenAI::Beta::BetaResponseReasoningTextDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseReasoningTextWsDelta < OpenAI::Models::Beta::BetaResponseReasoningTextDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseReasoningTextDeltaEvent::Agent?,
            ?type: :"response.reasoning_text.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.reasoning_text.delta",
            agent: OpenAI::Beta::BetaResponseReasoningTextDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_reasoning_text_ws_done =
          {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            text: String,
            type: :"response.reasoning_text.done",
            agent: OpenAI::Beta::BetaResponseReasoningTextDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseReasoningTextWsDone < OpenAI::Models::Beta::BetaResponseReasoningTextDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            text: String,
            ?agent: OpenAI::Beta::BetaResponseReasoningTextDoneEvent::Agent?,
            ?type: :"response.reasoning_text.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            text: String,
            type: :"response.reasoning_text.done",
            agent: OpenAI::Beta::BetaResponseReasoningTextDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_refusal_ws_delta =
          {
            content_index: Integer,
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.refusal.delta",
            agent: OpenAI::Beta::BetaResponseRefusalDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseRefusalWsDelta < OpenAI::Models::Beta::BetaResponseRefusalDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseRefusalDeltaEvent::Agent?,
            ?type: :"response.refusal.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.refusal.delta",
            agent: OpenAI::Beta::BetaResponseRefusalDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_refusal_ws_done =
          {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            refusal: String,
            sequence_number: Integer,
            type: :"response.refusal.done",
            agent: OpenAI::Beta::BetaResponseRefusalDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseRefusalWsDone < OpenAI::Models::Beta::BetaResponseRefusalDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            refusal: String,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseRefusalDoneEvent::Agent?,
            ?type: :"response.refusal.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            refusal: String,
            sequence_number: Integer,
            type: :"response.refusal.done",
            agent: OpenAI::Beta::BetaResponseRefusalDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_text_ws_delta =
          {
            content_index: Integer,
            delta: String,
            item_id: String,
            logprobs: ::Array[OpenAI::Beta::BetaResponseTextDeltaEvent::Logprob],
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_text.delta",
            agent: OpenAI::Beta::BetaResponseTextDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseTextWsDelta < OpenAI::Models::Beta::BetaResponseTextDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            delta: String,
            item_id: String,
            logprobs: ::Array[OpenAI::Beta::BetaResponseTextDeltaEvent::Logprob],
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseTextDeltaEvent::Agent?,
            ?type: :"response.output_text.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            delta: String,
            item_id: String,
            logprobs: ::Array[OpenAI::Beta::BetaResponseTextDeltaEvent::Logprob],
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_text.delta",
            agent: OpenAI::Beta::BetaResponseTextDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_text_ws_done =
          {
            content_index: Integer,
            item_id: String,
            logprobs: ::Array[OpenAI::Beta::BetaResponseTextDoneEvent::Logprob],
            output_index: Integer,
            sequence_number: Integer,
            text: String,
            type: :"response.output_text.done",
            agent: OpenAI::Beta::BetaResponseTextDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseTextWsDone < OpenAI::Models::Beta::BetaResponseTextDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            content_index: Integer,
            item_id: String,
            logprobs: ::Array[OpenAI::Beta::BetaResponseTextDoneEvent::Logprob],
            output_index: Integer,
            sequence_number: Integer,
            text: String,
            ?agent: OpenAI::Beta::BetaResponseTextDoneEvent::Agent?,
            ?type: :"response.output_text.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            content_index: Integer,
            item_id: String,
            logprobs: ::Array[OpenAI::Beta::BetaResponseTextDoneEvent::Logprob],
            output_index: Integer,
            sequence_number: Integer,
            text: String,
            type: :"response.output_text.done",
            agent: OpenAI::Beta::BetaResponseTextDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_web_search_call_ws_completed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.web_search_call.completed",
            agent: OpenAI::Beta::BetaResponseWebSearchCallCompletedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWebSearchCallWsCompleted < OpenAI::Models::Beta::BetaResponseWebSearchCallCompletedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseWebSearchCallCompletedEvent::Agent?,
            ?type: :"response.web_search_call.completed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.web_search_call.completed",
            agent: OpenAI::Beta::BetaResponseWebSearchCallCompletedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_web_search_call_in_ws_progress =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.web_search_call.in_progress",
            agent: OpenAI::Beta::BetaResponseWebSearchCallInProgressEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWebSearchCallInWsProgress < OpenAI::Models::Beta::BetaResponseWebSearchCallInProgressEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseWebSearchCallInProgressEvent::Agent?,
            ?type: :"response.web_search_call.in_progress",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.web_search_call.in_progress",
            agent: OpenAI::Beta::BetaResponseWebSearchCallInProgressEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_web_search_call_ws_searching =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.web_search_call.searching",
            agent: OpenAI::Beta::BetaResponseWebSearchCallSearchingEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWebSearchCallWsSearching < OpenAI::Models::Beta::BetaResponseWebSearchCallSearchingEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseWebSearchCallSearchingEvent::Agent?,
            ?type: :"response.web_search_call.searching",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.web_search_call.searching",
            agent: OpenAI::Beta::BetaResponseWebSearchCallSearchingEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_image_gen_call_ws_completed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.completed",
            agent: OpenAI::Beta::BetaResponseImageGenCallCompletedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseImageGenCallWsCompleted < OpenAI::Models::Beta::BetaResponseImageGenCallCompletedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseImageGenCallCompletedEvent::Agent?,
            ?type: :"response.image_generation_call.completed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.completed",
            agent: OpenAI::Beta::BetaResponseImageGenCallCompletedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_image_gen_call_ws_generating =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.generating",
            agent: OpenAI::Beta::BetaResponseImageGenCallGeneratingEvent::Agent?,
            stream_id: String
          }

        class BetaResponseImageGenCallWsGenerating < OpenAI::Models::Beta::BetaResponseImageGenCallGeneratingEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseImageGenCallGeneratingEvent::Agent?,
            ?type: :"response.image_generation_call.generating",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.generating",
            agent: OpenAI::Beta::BetaResponseImageGenCallGeneratingEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_image_gen_call_in_ws_progress =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.in_progress",
            agent: OpenAI::Beta::BetaResponseImageGenCallInProgressEvent::Agent?,
            stream_id: String
          }

        class BetaResponseImageGenCallInWsProgress < OpenAI::Models::Beta::BetaResponseImageGenCallInProgressEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseImageGenCallInProgressEvent::Agent?,
            ?type: :"response.image_generation_call.in_progress",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.in_progress",
            agent: OpenAI::Beta::BetaResponseImageGenCallInProgressEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_image_gen_call_partial_ws_image =
          {
            item_id: String,
            output_index: Integer,
            :partial_image_b64 => String,
            partial_image_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.partial_image",
            agent: OpenAI::Beta::BetaResponseImageGenCallPartialImageEvent::Agent?,
            stream_id: String
          }

        class BetaResponseImageGenCallPartialWsImage < OpenAI::Models::Beta::BetaResponseImageGenCallPartialImageEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            partial_image_b64: String,
            partial_image_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseImageGenCallPartialImageEvent::Agent?,
            ?type: :"response.image_generation_call.partial_image",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            :partial_image_b64 => String,
            partial_image_index: Integer,
            sequence_number: Integer,
            type: :"response.image_generation_call.partial_image",
            agent: OpenAI::Beta::BetaResponseImageGenCallPartialImageEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_call_arguments_ws_delta =
          {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call_arguments.delta",
            agent: OpenAI::Beta::BetaResponseMcpCallArgumentsDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpCallArgumentsWsDelta < OpenAI::Models::Beta::BetaResponseMcpCallArgumentsDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpCallArgumentsDeltaEvent::Agent?,
            ?type: :"response.mcp_call_arguments.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call_arguments.delta",
            agent: OpenAI::Beta::BetaResponseMcpCallArgumentsDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_call_arguments_ws_done =
          {
            arguments: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call_arguments.done",
            agent: OpenAI::Beta::BetaResponseMcpCallArgumentsDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpCallArgumentsWsDone < OpenAI::Models::Beta::BetaResponseMcpCallArgumentsDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            arguments: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpCallArgumentsDoneEvent::Agent?,
            ?type: :"response.mcp_call_arguments.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            arguments: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call_arguments.done",
            agent: OpenAI::Beta::BetaResponseMcpCallArgumentsDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_call_ws_completed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call.completed",
            agent: OpenAI::Beta::BetaResponseMcpCallCompletedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpCallWsCompleted < OpenAI::Models::Beta::BetaResponseMcpCallCompletedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpCallCompletedEvent::Agent?,
            ?type: :"response.mcp_call.completed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call.completed",
            agent: OpenAI::Beta::BetaResponseMcpCallCompletedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_call_ws_failed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call.failed",
            agent: OpenAI::Beta::BetaResponseMcpCallFailedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpCallWsFailed < OpenAI::Models::Beta::BetaResponseMcpCallFailedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpCallFailedEvent::Agent?,
            ?type: :"response.mcp_call.failed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call.failed",
            agent: OpenAI::Beta::BetaResponseMcpCallFailedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_call_in_ws_progress =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call.in_progress",
            agent: OpenAI::Beta::BetaResponseMcpCallInProgressEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpCallInWsProgress < OpenAI::Models::Beta::BetaResponseMcpCallInProgressEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpCallInProgressEvent::Agent?,
            ?type: :"response.mcp_call.in_progress",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_call.in_progress",
            agent: OpenAI::Beta::BetaResponseMcpCallInProgressEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_list_tools_ws_completed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_list_tools.completed",
            agent: OpenAI::Beta::BetaResponseMcpListToolsCompletedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpListToolsWsCompleted < OpenAI::Models::Beta::BetaResponseMcpListToolsCompletedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpListToolsCompletedEvent::Agent?,
            ?type: :"response.mcp_list_tools.completed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_list_tools.completed",
            agent: OpenAI::Beta::BetaResponseMcpListToolsCompletedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_list_tools_ws_failed =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_list_tools.failed",
            agent: OpenAI::Beta::BetaResponseMcpListToolsFailedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpListToolsWsFailed < OpenAI::Models::Beta::BetaResponseMcpListToolsFailedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpListToolsFailedEvent::Agent?,
            ?type: :"response.mcp_list_tools.failed",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_list_tools.failed",
            agent: OpenAI::Beta::BetaResponseMcpListToolsFailedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_mcp_list_tools_in_ws_progress =
          {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_list_tools.in_progress",
            agent: OpenAI::Beta::BetaResponseMcpListToolsInProgressEvent::Agent?,
            stream_id: String
          }

        class BetaResponseMcpListToolsInWsProgress < OpenAI::Models::Beta::BetaResponseMcpListToolsInProgressEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseMcpListToolsInProgressEvent::Agent?,
            ?type: :"response.mcp_list_tools.in_progress",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.mcp_list_tools.in_progress",
            agent: OpenAI::Beta::BetaResponseMcpListToolsInProgressEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_output_text_annotation_ws_added =
          {
            annotation: OpenAI::Models::Beta::BetaResponseOutputTextAnnotationAddedEvent::annotation?,
            annotation_index: Integer,
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_text.annotation.added",
            agent: OpenAI::Beta::BetaResponseOutputTextAnnotationAddedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseOutputTextAnnotationWsAdded < OpenAI::Models::Beta::BetaResponseOutputTextAnnotationAddedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            annotation: OpenAI::Models::Beta::BetaResponseOutputTextAnnotationAddedEvent::annotation?,
            annotation_index: Integer,
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseOutputTextAnnotationAddedEvent::Agent?,
            ?type: :"response.output_text.annotation.added",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            annotation: OpenAI::Models::Beta::BetaResponseOutputTextAnnotationAddedEvent::annotation?,
            annotation_index: Integer,
            content_index: Integer,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.output_text.annotation.added",
            agent: OpenAI::Beta::BetaResponseOutputTextAnnotationAddedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_ws_queued =
          {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.queued",
            agent: OpenAI::Beta::BetaResponseQueuedEvent::Agent?,
            stream_id: String
          }

        class BetaResponseWsQueued < OpenAI::Models::Beta::BetaResponseQueuedEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseQueuedEvent::Agent?,
            ?type: :"response.queued",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            response: OpenAI::Beta::BetaResponse,
            sequence_number: Integer,
            type: :"response.queued",
            agent: OpenAI::Beta::BetaResponseQueuedEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_custom_tool_call_input_ws_delta =
          {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.custom_tool_call_input.delta",
            agent: OpenAI::Beta::BetaResponseCustomToolCallInputDeltaEvent::Agent?,
            stream_id: String
          }

        class BetaResponseCustomToolCallInputWsDelta < OpenAI::Models::Beta::BetaResponseCustomToolCallInputDeltaEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCustomToolCallInputDeltaEvent::Agent?,
            ?type: :"response.custom_tool_call_input.delta",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            delta: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.custom_tool_call_input.delta",
            agent: OpenAI::Beta::BetaResponseCustomToolCallInputDeltaEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_custom_tool_call_input_ws_done =
          {
            input: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.custom_tool_call_input.done",
            agent: OpenAI::Beta::BetaResponseCustomToolCallInputDoneEvent::Agent?,
            stream_id: String
          }

        class BetaResponseCustomToolCallInputWsDone < OpenAI::Models::Beta::BetaResponseCustomToolCallInputDoneEvent
          def stream_id: -> String?

          def stream_id=: (String _) -> String

          def initialize: (
            input: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            ?agent: OpenAI::Beta::BetaResponseCustomToolCallInputDoneEvent::Agent?,
            ?type: :"response.custom_tool_call_input.done",
            ?stream_id: String
          ) -> void

          def to_hash: -> {
            input: String,
            item_id: String,
            output_index: Integer,
            sequence_number: Integer,
            type: :"response.custom_tool_call_input.done",
            agent: OpenAI::Beta::BetaResponseCustomToolCallInputDoneEvent::Agent?,
            stream_id: String
          }
        end

        type beta_response_ws_error =
          {
            error: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Error,
            type: :error,
            agent: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Agent?,
            sequence_number: Integer,
            status: Integer,
            stream_id: String
          }

        class BetaResponseWsError < OpenAI::Internal::Type::BaseModel
          attr_accessor error: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Error

          attr_accessor type: :error

          attr_accessor agent: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Agent?

          attr_reader sequence_number: Integer?

          def sequence_number=: (Integer) -> Integer

          attr_reader status: Integer?

          def status=: (Integer) -> Integer

          attr_reader stream_id: String?

          def stream_id=: (String) -> String

          def initialize: (
            error: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Error,
            ?agent: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Agent?,
            ?sequence_number: Integer,
            ?status: Integer,
            ?stream_id: String,
            ?type: :error
          ) -> void

          def to_hash: -> {
            error: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Error,
            type: :error,
            agent: OpenAI::Beta::BetaResponsesServerEvent::BetaResponseWsError::Agent?,
            sequence_number: Integer,
            status: Integer,
            stream_id: String
          }

          type error =
            {
              code: String?,
              message: String,
              param: String?,
              type: String,
              headers: ::Hash[Symbol, String]
            }

          class Error < OpenAI::Internal::Type::BaseModel
            attr_accessor code: String?

            attr_accessor message: String

            attr_accessor param: String?

            attr_accessor type: String

            attr_reader headers: ::Hash[Symbol, String]?

            def headers=: (::Hash[Symbol, String]) -> ::Hash[Symbol, String]

            def initialize: (
              code: String?,
              message: String,
              param: String?,
              type: String,
              ?headers: ::Hash[Symbol, String]
            ) -> void

            def to_hash: -> {
              code: String?,
              message: String,
              param: String?,
              type: String,
              headers: ::Hash[Symbol, String]
            }
          end

          type agent = { agent_name: String }

          class Agent < OpenAI::Internal::Type::BaseModel
            attr_accessor agent_name: String

            def initialize: (agent_name: String) -> void

            def to_hash: -> { agent_name: String }
          end
        end

        def self?.variants: -> ::Array[OpenAI::Models::Beta::beta_responses_server_event]
      end
    end
  end
end
