module OpenAI
  module Models
    class BetaResponseImageGenCallPartialImageEvent = Beta::BetaResponseImageGenCallPartialImageEvent

    module Beta
      type beta_response_image_gen_call_partial_image_event =
        {
          item_id: String,
          output_index: Integer,
          :partial_image_b64 => String,
          partial_image_index: Integer,
          sequence_number: Integer,
          type: :"response.image_generation_call.partial_image",
          agent: OpenAI::Beta::BetaResponseImageGenCallPartialImageEvent::Agent?,
          background: String,
          output_format: String,
          quality: String,
          size: String
        }

      class BetaResponseImageGenCallPartialImageEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor item_id: String

        attr_accessor output_index: Integer

        attr_accessor partial_image_b64: String

        attr_accessor partial_image_index: Integer

        attr_accessor sequence_number: Integer

        attr_accessor type: :"response.image_generation_call.partial_image"

        attr_accessor agent: OpenAI::Beta::BetaResponseImageGenCallPartialImageEvent::Agent?

        attr_reader background: String?

        def background=: (String) -> String

        attr_reader output_format: String?

        def output_format=: (String) -> String

        attr_reader quality: String?

        def quality=: (String) -> String

        attr_reader size: String?

        def size=: (String) -> String

        def initialize: (
          item_id: String,
          output_index: Integer,
          partial_image_b64: String,
          partial_image_index: Integer,
          sequence_number: Integer,
          ?agent: OpenAI::Beta::BetaResponseImageGenCallPartialImageEvent::Agent?,
          ?background: String,
          ?output_format: String,
          ?quality: String,
          ?size: String,
          ?type: :"response.image_generation_call.partial_image"
        ) -> void

        def to_hash: -> {
          item_id: String,
          output_index: Integer,
          :partial_image_b64 => String,
          partial_image_index: Integer,
          sequence_number: Integer,
          type: :"response.image_generation_call.partial_image",
          agent: OpenAI::Beta::BetaResponseImageGenCallPartialImageEvent::Agent?,
          background: String,
          output_format: String,
          quality: String,
          size: String
        }

        type agent = { agent_name: String }

        class Agent < OpenAI::Internal::Type::BaseModel
          attr_accessor agent_name: String

          def initialize: (agent_name: String) -> void

          def to_hash: -> { agent_name: String }
        end
      end
    end
  end
end
