module OpenAI
  module Models
    module BetaResponseSteerInput = Beta::BetaResponseSteerInput

    module Beta
      type beta_response_steer_input =
        String
        | ::Array[OpenAI::Models::Beta::BetaResponseSteerInput::response_steer_input_item_list]

      module BetaResponseSteerInput
        extend OpenAI::Internal::Type::Union

        type response_steer_input_item_list =
          OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message
          | OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput

        module ResponseSteerInputItemList
          extend OpenAI::Internal::Type::Union

          type message =
            {
              content: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::content,
              role: :user,
              type: :message,
              id: String?,
              agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::Agent?,
              status: String?
            }

          class Message < OpenAI::Internal::Type::BaseModel
            attr_accessor content: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::content

            attr_accessor role: :user

            attr_accessor type: :message

            attr_accessor id: String?

            attr_accessor agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::Agent?

            attr_accessor status: String?

            def initialize: (
              content: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::content,
              ?id: String?,
              ?agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::Agent?,
              ?status: String?,
              ?role: :user,
              ?type: :message
            ) -> void

            def to_hash: -> {
              content: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::content,
              role: :user,
              type: :message,
              id: String?,
              agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::Agent?,
              status: String?
            }

            type content =
              ::Array[OpenAI::Models::Beta::beta_response_steer_input_content]
              | String

            module Content
              extend OpenAI::Internal::Type::Union

              def self?.variants: -> ::Array[OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::Message::content]

              BetaResponseSteerInputContentArray: OpenAI::Internal::Type::Converter
            end

            type agent = { agent_name: String }

            class Agent < OpenAI::Internal::Type::BaseModel
              attr_accessor agent_name: String

              def initialize: (agent_name: String) -> void

              def to_hash: -> { agent_name: String }
            end
          end

          type function_call_output =
            {
              output: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::output,
              type: :function_call_output,
              id: String?,
              agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::Agent?,
              call_id: String?,
              caller_: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::caller_?,
              name: String?,
              namespace: String?,
              status: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::status?
            }

          class FunctionCallOutput < OpenAI::Internal::Type::BaseModel
            attr_accessor output: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::output

            attr_accessor type: :function_call_output

            attr_accessor id: String?

            attr_accessor agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::Agent?

            attr_accessor call_id: String?

            attr_accessor caller_: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::caller_?

            attr_accessor name: String?

            attr_accessor namespace: String?

            attr_accessor status: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::status?

            def initialize: (
              output: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::output,
              ?id: String?,
              ?agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::Agent?,
              ?call_id: String?,
              ?caller_: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::caller_?,
              ?name: String?,
              ?namespace: String?,
              ?status: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::status?,
              ?type: :function_call_output
            ) -> void

            def to_hash: -> {
              output: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::output,
              type: :function_call_output,
              id: String?,
              agent: OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::Agent?,
              call_id: String?,
              caller_: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::caller_?,
              name: String?,
              namespace: String?,
              status: OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::status?
            }

            type output =
              String
              | OpenAI::Models::Beta::beta_response_function_call_output_item_list

            module Output
              extend OpenAI::Internal::Type::Union

              def self?.variants: -> ::Array[OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::output]
            end

            type agent = { agent_name: String }

            class Agent < OpenAI::Internal::Type::BaseModel
              attr_accessor agent_name: String

              def initialize: (agent_name: String) -> void

              def to_hash: -> { agent_name: String }
            end

            type caller_ =
              OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::Caller::Direct
              | OpenAI::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::Caller::Program

            module Caller
              extend OpenAI::Internal::Type::Union

              type direct = { type: :direct }

              class Direct < OpenAI::Internal::Type::BaseModel
                attr_accessor type: :direct

                def initialize: (?type: :direct) -> void

                def to_hash: -> { type: :direct }
              end

              type program = { caller_id: String, type: :program }

              class Program < OpenAI::Internal::Type::BaseModel
                attr_accessor caller_id: String

                attr_accessor type: :program

                def initialize: (caller_id: String, ?type: :program) -> void

                def to_hash: -> { caller_id: String, type: :program }
              end

              def self?.variants: -> ::Array[OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::caller_]
            end

            type status = :in_progress | :completed | :incomplete

            module Status
              extend OpenAI::Internal::Type::Enum

              IN_PROGRESS: :in_progress
              COMPLETED: :completed
              INCOMPLETE: :incomplete

              def self?.values: -> ::Array[OpenAI::Models::Beta::BetaResponseSteerInput::ResponseSteerInputItemList::FunctionCallOutput::status]
            end
          end

          def self?.variants: -> ::Array[OpenAI::Models::Beta::BetaResponseSteerInput::response_steer_input_item_list]
        end

        def self?.variants: -> ::Array[OpenAI::Models::Beta::beta_response_steer_input]

        ResponseSteerInputItemListArray: OpenAI::Internal::Type::Converter
      end
    end
  end
end
