module OpenAI
  module Models
    module Beta
      type chatkit_upload_file_params =
        { file: OpenAI::Internal::file_input }
        & OpenAI::Internal::Type::request_parameters

      class ChatKitUploadFileParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor file: OpenAI::Internal::file_input

        def initialize: (
          file: OpenAI::Internal::file_input,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          file: OpenAI::Internal::file_input,
          request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
