module OpenAI
  module Models
    module Beta
      type code_interpreter_tool = { type: :code_interpreter }

      class CodeInterpreterTool < OpenAI::Internal::Type::BaseModel
        attr_accessor type: :code_interpreter

        def initialize: (?type: :code_interpreter) -> void

        def to_hash: -> { type: :code_interpreter }
      end
    end
  end
end
