module OpenAI
  module Models
    module Beta
      type image_part =
        {
          id: String,
          mime_type: String,
          name: String?,
          preview_url: String,
          type: :image,
          upload_url: String?
        }

      class ImagePart < OpenAI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor mime_type: String

        attr_accessor name: String?

        attr_accessor preview_url: String

        attr_accessor type: :image

        attr_accessor upload_url: String?

        def initialize: (
          id: String,
          mime_type: String,
          name: String?,
          preview_url: String,
          upload_url: String?,
          ?type: :image
        ) -> void

        def to_hash: -> {
          id: String,
          mime_type: String,
          name: String?,
          preview_url: String,
          type: :image,
          upload_url: String?
        }
      end
    end
  end
end
