module OpenAI
  module Models
    module Beta
      type output_text = { text: String, ?type: :output_text }

      class OutputText < OpenAI::Internal::Type::BaseModel
        attr_accessor text: String

        attr_accessor type: :output_text

        def initialize: (text: String, ?type: :output_text) -> void

        def to_hash: -> { text: String, ?type: :output_text }
      end
    end
  end
end
