module OpenAI
  module Models
    module Beta
      type static_file_chunking_strategy_object_param =
        {
          static: OpenAI::Models::Beta::StaticFileChunkingStrategy,
          type: :static
        }

      class StaticFileChunkingStrategyObjectParam < OpenAI::BaseModel
        attr_accessor static: OpenAI::Models::Beta::StaticFileChunkingStrategy

        attr_accessor type: :static

        def initialize:
          (
            static: OpenAI::Models::Beta::StaticFileChunkingStrategy,
            type: :static
          ) -> void
          | (
            ?OpenAI::Models::Beta::static_file_chunking_strategy_object_param
            | OpenAI::BaseModel data
          ) -> void

        def to_hash: -> OpenAI::Models::Beta::static_file_chunking_strategy_object_param
      end
    end
  end
end
