module OpenAI
  module Models
    module Beta
      type thread_create_params =
        {
          ?messages: ::Array[OpenAI::Beta::ThreadCreateParams::Message],
          ?metadata: OpenAI::Models::metadata?,
          ?tool_resources: OpenAI::Beta::ThreadCreateParams::ToolResources?,
          ?request_options: OpenAI::request_opts
        }

      class ThreadCreateParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        # A list of
        # [messages](https://developers.openai.com/api/docs/assistants/migration) to start
        # the thread with.
        attr_reader messages: ::Array[OpenAI::Beta::ThreadCreateParams::Message]?

        # A list of
        # [messages](https://developers.openai.com/api/docs/assistants/migration) to start
        # the thread with.
        def messages=: (
          ::Array[OpenAI::Beta::ThreadCreateParams::Message]
        ) -> ::Array[OpenAI::Beta::ThreadCreateParams::Message]

        # Set of 16 key-value pairs that can be attached to an object. This can be useful
        # for storing additional information about the object in a structured format, and
        # querying for objects via API or the dashboard.
        #
        # Keys are strings with a maximum length of 64 characters. Values are strings with
        # a maximum length of 512 characters.
        attr_accessor metadata: OpenAI::Models::metadata?

        # A set of resources that are made available to the assistant's tools in this
        # thread. The resources are specific to the type of tool. For example, the
        # `code_interpreter` tool requires a list of file IDs, while the `file_search`
        # tool requires a list of vector store IDs.
        attr_accessor tool_resources: OpenAI::Beta::ThreadCreateParams::ToolResources?

        # @param messages
        #   A list of
        #   [messages](https://developers.openai.com/api/docs/assistants/migration) to start
        #   the thread with.
        # @param metadata
        #   Set of 16 key-value pairs that can be attached to an object. This can be useful
        #   for storing additional information about the object in a structured format, and
        #   querying for objects via API or the dashboard.
        #
        #   Keys are strings with a maximum length of 64 characters. Values are strings with
        #   a maximum length of 512 characters.
        # @param tool_resources
        #   A set of resources that are made available to the assistant's tools in this
        #   thread. The resources are specific to the type of tool. For example, the
        #   `code_interpreter` tool requires a list of file IDs, while the `file_search`
        #   tool requires a list of vector store IDs.
        def initialize: (
          ?messages: ::Array[OpenAI::Beta::ThreadCreateParams::Message],
          ?metadata: OpenAI::Models::metadata?,
          ?tool_resources: OpenAI::Beta::ThreadCreateParams::ToolResources?,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          ?messages: ::Array[OpenAI::Beta::ThreadCreateParams::Message],
          ?metadata: OpenAI::Models::metadata?,
          ?tool_resources: OpenAI::Beta::ThreadCreateParams::ToolResources?,
          ?request_options: OpenAI::RequestOptions
        }

        type message =
          {
            content: OpenAI::Models::Beta::ThreadCreateParams::Message::content,
            role: OpenAI::Models::Beta::ThreadCreateParams::Message::role,
            ?attachments: ::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment]?,
            ?metadata: OpenAI::Models::metadata?
          }

        class Message < OpenAI::Internal::Type::BaseModel
          # The text contents of the message.
          attr_accessor content: OpenAI::Models::Beta::ThreadCreateParams::Message::content

          # The role of the entity that is creating the message. Allowed values include:
          #
          # - `user`: Indicates the message is sent by an actual user and should be used in
          #   most cases to represent user-generated messages.
          # - `assistant`: Indicates the message is generated by the assistant. Use this
          #   value to insert messages from the assistant into the conversation.
          attr_accessor role: OpenAI::Models::Beta::ThreadCreateParams::Message::role

          # A list of files attached to the message, and the tools they should be added to.
          attr_accessor attachments: ::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment]?

          # Set of 16 key-value pairs that can be attached to an object. This can be useful
          # for storing additional information about the object in a structured format, and
          # querying for objects via API or the dashboard.
          #
          # Keys are strings with a maximum length of 64 characters. Values are strings with
          # a maximum length of 512 characters.
          attr_accessor metadata: OpenAI::Models::metadata?

          # @param content
          #   The text contents of the message.
          # @param role
          #   The role of the entity that is creating the message. Allowed values include:
          #
          #   - `user`: Indicates the message is sent by an actual user and should be used in
          #     most cases to represent user-generated messages.
          #   - `assistant`: Indicates the message is generated by the assistant. Use this
          #     value to insert messages from the assistant into the conversation.
          # @param attachments
          #   A list of files attached to the message, and the tools they should be added to.
          # @param metadata
          #   Set of 16 key-value pairs that can be attached to an object. This can be useful
          #   for storing additional information about the object in a structured format, and
          #   querying for objects via API or the dashboard.
          #
          #   Keys are strings with a maximum length of 64 characters. Values are strings with
          #   a maximum length of 512 characters.
          def initialize: (
            content: OpenAI::Models::Beta::ThreadCreateParams::Message::content,
            role: OpenAI::Models::Beta::ThreadCreateParams::Message::role,
            ?attachments: ::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment]?,
            ?metadata: OpenAI::Models::metadata?
          ) -> void

          def to_hash: -> {
            content: OpenAI::Models::Beta::ThreadCreateParams::Message::content,
            role: OpenAI::Models::Beta::ThreadCreateParams::Message::role,
            ?attachments: ::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment]?,
            ?metadata: OpenAI::Models::metadata?
          }

          type content =
            String
            | ::Array[OpenAI::Models::Beta::Threads::message_content_part_param]

          module Content
            extend OpenAI::Internal::Type::Union

            def self?.variants: -> ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::content]

            MessageContentPartParamArray: OpenAI::Internal::Type::Converter
          end

          type role = :user | :assistant

          module Role
            extend OpenAI::Internal::Type::Enum

            USER: :user
            ASSISTANT: :assistant

            def self?.values: -> ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::role]
          end

          type attachment =
            {
              ?file_id: String,
              ?tools: ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::Attachment::tool]
            }

          class Attachment < OpenAI::Internal::Type::BaseModel
            # The ID of the file to attach to the message.
            attr_reader file_id: String?

            # The ID of the file to attach to the message.
            def file_id=: (String) -> String

            # The tools to add this file to.
            attr_reader tools: ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::Attachment::tool]?

            # The tools to add this file to.
            def tools=: (
              ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::Attachment::tool]
            ) -> ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::Attachment::tool]

            # @param file_id
            #   The ID of the file to attach to the message.
            # @param tools
            #   The tools to add this file to.
            def initialize: (
              ?file_id: String,
              ?tools: ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::Attachment::tool]
            ) -> void

            def to_hash: -> {
              ?file_id: String,
              ?tools: ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::Attachment::tool]
            }

            type tool =
              OpenAI::Beta::CodeInterpreterTool
              | OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::FileSearch

            module Tool
              extend OpenAI::Internal::Type::Union

              type file_search = { ?type: :file_search }

              class FileSearch < OpenAI::Internal::Type::BaseModel
                # The type of tool being defined: `file_search`
                attr_accessor type: :file_search

                # @param type
                #   The type of tool being defined: `file_search`
                def initialize: (?type: :file_search) -> void

                def to_hash: -> { ?type: :file_search }
              end

              def self?.variants: -> ::Array[OpenAI::Models::Beta::ThreadCreateParams::Message::Attachment::tool]
            end
          end
        end

        type tool_resources =
          {
            ?code_interpreter: OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter,
            ?file_search: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch
          }

        class ToolResources < OpenAI::Internal::Type::BaseModel
          attr_reader code_interpreter: OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter?

          def code_interpreter=: (
            OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter
          ) -> OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter

          attr_reader file_search: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch?

          def file_search=: (
            OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch
          ) -> OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch

          def initialize: (
            ?code_interpreter: OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter,
            ?file_search: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch
          ) -> void

          def to_hash: -> {
            ?code_interpreter: OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter,
            ?file_search: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch
          }

          type code_interpreter = { ?file_ids: ::Array[String] }

          class CodeInterpreter < OpenAI::Internal::Type::BaseModel
            # A list of [file](https://developers.openai.com/api/reference/resources/files)
            # IDs made available to the `code_interpreter` tool. There can be a maximum of 20
            # files associated with the tool.
            attr_reader file_ids: ::Array[String]?

            # A list of [file](https://developers.openai.com/api/reference/resources/files)
            # IDs made available to the `code_interpreter` tool. There can be a maximum of 20
            # files associated with the tool.
            def file_ids=: (::Array[String]) -> ::Array[String]

            # @param file_ids
            #   A list of [file](https://developers.openai.com/api/reference/resources/files)
            #   IDs made available to the `code_interpreter` tool. There can be a maximum of 20
            #   files associated with the tool.
            def initialize: (?file_ids: ::Array[String]) -> void

            def to_hash: -> { ?file_ids: ::Array[String] }
          end

          type file_search =
            {
              ?vector_store_ids: ::Array[String],
              ?vector_stores: ::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]
            }

          class FileSearch < OpenAI::Internal::Type::BaseModel
            # The
            # [vector store](https://developers.openai.com/api/reference/resources/vector_stores)
            # attached to this thread. There can be a maximum of 1 vector store attached to
            # the thread.
            attr_reader vector_store_ids: ::Array[String]?

            # The
            # [vector store](https://developers.openai.com/api/reference/resources/vector_stores)
            # attached to this thread. There can be a maximum of 1 vector store attached to
            # the thread.
            def vector_store_ids=: (::Array[String]) -> ::Array[String]

            # A helper to create a
            # [vector store](https://developers.openai.com/api/reference/resources/vector_stores)
            # with file_ids and attach it to this thread. There can be a maximum of 1 vector
            # store attached to the thread.
            attr_reader vector_stores: ::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]?

            # A helper to create a
            # [vector store](https://developers.openai.com/api/reference/resources/vector_stores)
            # with file_ids and attach it to this thread. There can be a maximum of 1 vector
            # store attached to the thread.
            def vector_stores=: (
              ::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]
            ) -> ::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]

            # @param vector_store_ids
            #   The
            #   [vector store](https://developers.openai.com/api/reference/resources/vector_stores)
            #   attached to this thread. There can be a maximum of 1 vector store attached to
            #   the thread.
            # @param vector_stores
            #   A helper to create a
            #   [vector store](https://developers.openai.com/api/reference/resources/vector_stores)
            #   with file_ids and attach it to this thread. There can be a maximum of 1 vector
            #   store attached to the thread.
            def initialize: (
              ?vector_store_ids: ::Array[String],
              ?vector_stores: ::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]
            ) -> void

            def to_hash: -> {
              ?vector_store_ids: ::Array[String],
              ?vector_stores: ::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]
            }

            type vector_store =
              {
                ?chunking_strategy: OpenAI::Models::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::chunking_strategy,
                ?file_ids: ::Array[String],
                ?metadata: OpenAI::Models::metadata?
              }

            class VectorStore < OpenAI::Internal::Type::BaseModel
              # The chunking strategy used to chunk the file(s). If not set, will use the `auto`
              # strategy.
              attr_reader chunking_strategy: OpenAI::Models::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::chunking_strategy?

              # The chunking strategy used to chunk the file(s). If not set, will use the `auto`
              # strategy.
              def chunking_strategy=: (
                OpenAI::Models::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::chunking_strategy
              ) -> OpenAI::Models::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::chunking_strategy

              # A list of [file](https://developers.openai.com/api/reference/resources/files)
              # IDs to add to the vector store. For vector stores created before Nov 2025, there
              # can be a maximum of 10,000 files in a vector store. For vector stores created
              # starting in Nov 2025, the limit is 100,000,000 files.
              attr_reader file_ids: ::Array[String]?

              # A list of [file](https://developers.openai.com/api/reference/resources/files)
              # IDs to add to the vector store. For vector stores created before Nov 2025, there
              # can be a maximum of 10,000 files in a vector store. For vector stores created
              # starting in Nov 2025, the limit is 100,000,000 files.
              def file_ids=: (::Array[String]) -> ::Array[String]

              # Set of 16 key-value pairs that can be attached to an object. This can be useful
              # for storing additional information about the object in a structured format, and
              # querying for objects via API or the dashboard.
              #
              # Keys are strings with a maximum length of 64 characters. Values are strings with
              # a maximum length of 512 characters.
              attr_accessor metadata: OpenAI::Models::metadata?

              # @param chunking_strategy
              #   The chunking strategy used to chunk the file(s). If not set, will use the `auto`
              #   strategy.
              # @param file_ids
              #   A list of [file](https://developers.openai.com/api/reference/resources/files)
              #   IDs to add to the vector store. For vector stores created before Nov 2025, there
              #   can be a maximum of 10,000 files in a vector store. For vector stores created
              #   starting in Nov 2025, the limit is 100,000,000 files.
              # @param metadata
              #   Set of 16 key-value pairs that can be attached to an object. This can be useful
              #   for storing additional information about the object in a structured format, and
              #   querying for objects via API or the dashboard.
              #
              #   Keys are strings with a maximum length of 64 characters. Values are strings with
              #   a maximum length of 512 characters.
              def initialize: (
                ?chunking_strategy: OpenAI::Models::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::chunking_strategy,
                ?file_ids: ::Array[String],
                ?metadata: OpenAI::Models::metadata?
              ) -> void

              def to_hash: -> {
                ?chunking_strategy: OpenAI::Models::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::chunking_strategy,
                ?file_ids: ::Array[String],
                ?metadata: OpenAI::Models::metadata?
              }

              type chunking_strategy =
                OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Auto
                | OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static

              module ChunkingStrategy
                extend OpenAI::Internal::Type::Union

                type auto = { ?type: :auto }

                class Auto < OpenAI::Internal::Type::BaseModel
                  # Always `auto`.
                  attr_accessor type: :auto

                  # @param type
                  #   Always `auto`.
                  def initialize: (?type: :auto) -> void

                  def to_hash: -> { ?type: :auto }
                end

                type static =
                  {
                    static: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static,
                    ?type: :static
                  }

                class Static < OpenAI::Internal::Type::BaseModel
                  attr_accessor static: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static

                  # Always `static`.
                  attr_accessor type: :static

                  # @param type
                  #   Always `static`.
                  def initialize: (
                    static: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static,
                    ?type: :static
                  ) -> void

                  def to_hash: -> {
                    static: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static,
                    ?type: :static
                  }

                  type static =
                    {
                      chunk_overlap_tokens: Integer,
                      max_chunk_size_tokens: Integer
                    }

                  class Static < OpenAI::Internal::Type::BaseModel
                    # The number of tokens that overlap between chunks. The default value is `400`.
                    #
                    # Note that the overlap must not exceed half of `max_chunk_size_tokens`.
                    attr_accessor chunk_overlap_tokens: Integer

                    # The maximum number of tokens in each chunk. The default value is `800`. The
                    # minimum value is `100` and the maximum value is `4096`.
                    attr_accessor max_chunk_size_tokens: Integer

                    # @param chunk_overlap_tokens
                    #   The number of tokens that overlap between chunks. The default value is `400`.
                    #
                    #   Note that the overlap must not exceed half of `max_chunk_size_tokens`.
                    # @param max_chunk_size_tokens
                    #   The maximum number of tokens in each chunk. The default value is `800`. The
                    #   minimum value is `100` and the maximum value is `4096`.
                    def initialize: (
                      chunk_overlap_tokens: Integer,
                      max_chunk_size_tokens: Integer
                    ) -> void

                    def to_hash: -> {
                      chunk_overlap_tokens: Integer,
                      max_chunk_size_tokens: Integer
                    }
                  end
                end

                def self?.variants: -> ::Array[OpenAI::Models::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::chunking_strategy]
              end
            end
          end
        end
      end
    end
  end
end
