module OpenAI
  module Models
    module Beta
      type truncation_object =
        { type: OpenAI::Beta::TruncationObject::type_, last_messages: Integer? }

      class TruncationObject < OpenAI::Internal::Type::BaseModel
        attr_accessor type: OpenAI::Beta::TruncationObject::type_

        attr_accessor last_messages: Integer?

        def initialize: (
          type: OpenAI::Beta::TruncationObject::type_,
          ?last_messages: Integer?
        ) -> void

        type type_ = :auto | :last_messages

        module Type
          extend OpenAI::Internal::Type::Enum

          AUTO: :auto
          LAST_MESSAGES: :last_messages

          def self?.values: -> ::Array[OpenAI::Beta::TruncationObject::type_]
        end
      end
    end
  end
end
