module OpenAI
  module Resources
    class Realtime
      class Translations
        class ClientSecrets
          def initialize: (client: OpenAI::Client) -> void
        end
      end
    end
  end
end
