module OpenAI
  module Resources
    class Realtime
      class Translations
        class ClientSecrets
          def create: (
            session: OpenAI::Realtime::RealtimeTranslationSessionCreateRequest,
            ?expires_after: OpenAI::Realtime::RealtimeTranslationClientSecretCreateRequest::ExpiresAfter,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::Realtime::RealtimeTranslationClientSecretCreateResponse

          def initialize: (client: OpenAI::Client) -> void
        end
      end
    end
  end
end
