module OpenAI
  module Models
    module Realtime
      type call_reject_params =
        {
          call_id: String,
          ?status_code: Integer,
          ?request_options: OpenAI::request_opts
        }

      class CallRejectParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor call_id: String

        # SIP response code to send back to the caller. Defaults to `603` (Decline) when
        # omitted.
        attr_reader status_code: Integer?

        # SIP response code to send back to the caller. Defaults to `603` (Decline) when
        # omitted.
        def status_code=: (Integer) -> Integer

        # @param status_code
        #   SIP response code to send back to the caller. Defaults to `603` (Decline) when
        #   omitted.
        def initialize: (
          call_id: String,
          ?status_code: Integer,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          call_id: String,
          ?status_code: Integer,
          ?request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
