module OpenAI
  module Models
    module Realtime
      type call_refer_params =
        { target_uri: String } & OpenAI::Internal::Type::request_parameters

      class CallReferParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor target_uri: String

        def initialize: (
          target_uri: String,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          target_uri: String,
          request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
