module OpenAI
  module Models
    module Realtime
      type call_refer_params =
        {
          call_id: String,
          target_uri: String,
          ?request_options: OpenAI::request_opts
        }

      class CallReferParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor call_id: String

        # URI that should appear in the SIP Refer-To header. Supports values like
        # `tel:+14155550123` or `sip:agent@example.com`.
        attr_accessor target_uri: String

        # @param target_uri
        #   URI that should appear in the SIP Refer-To header. Supports values like
        #   `tel:+14155550123` or `sip:agent@example.com`.
        def initialize: (
          call_id: String,
          target_uri: String,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          call_id: String,
          target_uri: String,
          ?request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
