module OpenAI
  module Models
    module Realtime
      type client_secret_create_params =
        {
          ?expires_after: OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter,
          ?session: OpenAI::Models::Realtime::ClientSecretCreateParams::session,
          ?request_options: OpenAI::request_opts
        }

      class ClientSecretCreateParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        # Configuration for the client secret expiration. Expiration refers to the time
        # after which a client secret will no longer be valid for creating sessions. The
        # session itself may continue after that time once started. A secret can be used
        # to create multiple sessions until it expires.
        attr_reader expires_after: OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter?

        # Configuration for the client secret expiration. Expiration refers to the time
        # after which a client secret will no longer be valid for creating sessions. The
        # session itself may continue after that time once started. A secret can be used
        # to create multiple sessions until it expires.
        def expires_after=: (
          OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter
        ) -> OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter

        # Session configuration to use for the client secret. Choose either a realtime
        # session or a transcription session.
        attr_reader session: OpenAI::Models::Realtime::ClientSecretCreateParams::session?

        # Session configuration to use for the client secret. Choose either a realtime
        # session or a transcription session.
        def session=: (
          OpenAI::Models::Realtime::ClientSecretCreateParams::session
        ) -> OpenAI::Models::Realtime::ClientSecretCreateParams::session

        # @param expires_after
        #   Configuration for the client secret expiration. Expiration refers to the time
        #   after which a client secret will no longer be valid for creating sessions. The
        #   session itself may continue after that time once started. A secret can be used
        #   to create multiple sessions until it expires.
        # @param session
        #   Session configuration to use for the client secret. Choose either a realtime
        #   session or a transcription session.
        def initialize: (
          ?expires_after: OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter,
          ?session: OpenAI::Models::Realtime::ClientSecretCreateParams::session,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          ?expires_after: OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter,
          ?session: OpenAI::Models::Realtime::ClientSecretCreateParams::session,
          ?request_options: OpenAI::RequestOptions
        }

        type expires_after =
          {
            ?anchor: OpenAI::Models::Realtime::ClientSecretCreateParams::ExpiresAfter::anchor,
            ?seconds: Integer
          }

        class ExpiresAfter < OpenAI::Internal::Type::BaseModel
          # The anchor point for the client secret expiration, meaning that `seconds` will
          # be added to the `created_at` time of the client secret to produce an expiration
          # timestamp. Only `created_at` is currently supported.
          attr_reader anchor: OpenAI::Models::Realtime::ClientSecretCreateParams::ExpiresAfter::anchor?

          # The anchor point for the client secret expiration, meaning that `seconds` will
          # be added to the `created_at` time of the client secret to produce an expiration
          # timestamp. Only `created_at` is currently supported.
          def anchor=: (
            OpenAI::Models::Realtime::ClientSecretCreateParams::ExpiresAfter::anchor
          ) -> OpenAI::Models::Realtime::ClientSecretCreateParams::ExpiresAfter::anchor

          # The number of seconds from the anchor point to the expiration. Select a value
          # between `10` and `7200` (2 hours). This default to 600 seconds (10 minutes) if
          # not specified.
          attr_reader seconds: Integer?

          # The number of seconds from the anchor point to the expiration. Select a value
          # between `10` and `7200` (2 hours). This default to 600 seconds (10 minutes) if
          # not specified.
          def seconds=: (Integer) -> Integer

          # @param anchor
          #   The anchor point for the client secret expiration, meaning that `seconds` will
          #   be added to the `created_at` time of the client secret to produce an expiration
          #   timestamp. Only `created_at` is currently supported.
          # @param seconds
          #   The number of seconds from the anchor point to the expiration. Select a value
          #   between `10` and `7200` (2 hours). This default to 600 seconds (10 minutes) if
          #   not specified.
          def initialize: (
            ?anchor: OpenAI::Models::Realtime::ClientSecretCreateParams::ExpiresAfter::anchor,
            ?seconds: Integer
          ) -> void

          def to_hash: -> {
            ?anchor: OpenAI::Models::Realtime::ClientSecretCreateParams::ExpiresAfter::anchor,
            ?seconds: Integer
          }

          type anchor = :created_at

          module Anchor
            extend OpenAI::Internal::Type::Enum

            CREATED_AT: :created_at

            def self?.values: -> ::Array[OpenAI::Models::Realtime::ClientSecretCreateParams::ExpiresAfter::anchor]
          end
        end

        type session =
          OpenAI::Realtime::RealtimeSessionCreateRequest
          | OpenAI::Realtime::RealtimeTranscriptionSessionCreateRequest

        module Session
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::Realtime::ClientSecretCreateParams::session]
        end
      end
    end
  end
end
