module OpenAI
  module Models
    module Realtime
      type input_audio_buffer_append_event =
        {
          audio: String,
          ?type: :"input_audio_buffer.append",
          ?event_id: String
        }

      class InputAudioBufferAppendEvent < OpenAI::Internal::Type::BaseModel
        # Base64-encoded audio bytes. This must be in the format specified by the
        # `input_audio_format` field in the session configuration.
        attr_accessor audio: String

        # The event type, must be `input_audio_buffer.append`.
        attr_accessor type: :"input_audio_buffer.append"

        # Optional client-generated ID used to identify this event.
        attr_reader event_id: String?

        # Optional client-generated ID used to identify this event.
        def event_id=: (String) -> String

        # @param audio
        #   Base64-encoded audio bytes. This must be in the format specified by the
        #   `input_audio_format` field in the session configuration.
        # @param event_id
        #   Optional client-generated ID used to identify this event.
        # @param type
        #   The event type, must be `input_audio_buffer.append`.
        def initialize: (
          audio: String,
          ?event_id: String,
          ?type: :"input_audio_buffer.append"
        ) -> void

        def to_hash: -> {
          audio: String,
          ?type: :"input_audio_buffer.append",
          ?event_id: String
        }
      end
    end
  end
end
