module OpenAI
  module Models
    module Realtime
      type mcp_list_tools_in_progress =
        {
          event_id: String,
          item_id: String,
          type: :"mcp_list_tools.in_progress"
        }

      class McpListToolsInProgress < OpenAI::Internal::Type::BaseModel
        attr_accessor event_id: String

        attr_accessor item_id: String

        attr_accessor type: :"mcp_list_tools.in_progress"

        def initialize: (
          event_id: String,
          item_id: String,
          ?type: :"mcp_list_tools.in_progress"
        ) -> void

        def to_hash: -> {
          event_id: String,
          item_id: String,
          type: :"mcp_list_tools.in_progress"
        }
      end
    end
  end
end
