module OpenAI
  module Models
    module Realtime
      type mcp_list_tools_completed =
        {
          event_id: String,
          item_id: String,
          ?type: :"mcp_list_tools.completed"
        }

      class McpListToolsCompleted < OpenAI::Internal::Type::BaseModel
        # The unique ID of the server event.
        attr_accessor event_id: String

        # The ID of the MCP list tools item.
        attr_accessor item_id: String

        # The event type, must be `mcp_list_tools.completed`.
        attr_accessor type: :"mcp_list_tools.completed"

        # @param event_id
        #   The unique ID of the server event.
        # @param item_id
        #   The ID of the MCP list tools item.
        # @param type
        #   The event type, must be `mcp_list_tools.completed`.
        def initialize: (
          event_id: String,
          item_id: String,
          ?type: :"mcp_list_tools.completed"
        ) -> void

        def to_hash: -> {
          event_id: String,
          item_id: String,
          ?type: :"mcp_list_tools.completed"
        }
      end
    end
  end
end
