module OpenAI
  module Models
    module Realtime
      type realtime_translation_client_secret_create_response =
        {
          expires_at: Integer,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          value: String
        }

      class RealtimeTranslationClientSecretCreateResponse < OpenAI::Internal::Type::BaseModel
        attr_accessor expires_at: Integer

        attr_accessor session: OpenAI::Realtime::RealtimeTranslationSession

        attr_accessor value: String

        def initialize: (
          expires_at: Integer,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          value: String
        ) -> void

        def to_hash: -> {
          expires_at: Integer,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          value: String
        }
      end
    end
  end
end
