module OpenAI
  module Models
    module Realtime
      type realtime_translation_session_updated_event =
        {
          event_id: String,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          ?type: :"session.updated"
        }

      class RealtimeTranslationSessionUpdatedEvent < OpenAI::Internal::Type::BaseModel
        # The unique ID of the server event.
        attr_accessor event_id: String

        # The translation session configuration.
        attr_accessor session: OpenAI::Realtime::RealtimeTranslationSession

        # The event type, must be `session.updated`.
        attr_accessor type: :"session.updated"

        # @param event_id
        #   The unique ID of the server event.
        # @param session
        #   The translation session configuration.
        # @param type
        #   The event type, must be `session.updated`.
        def initialize: (
          event_id: String,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          ?type: :"session.updated"
        ) -> void

        def to_hash: -> {
          event_id: String,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          ?type: :"session.updated"
        }
      end
    end
  end
end
