module OpenAI
  module Models
    class RealtimeSessionClientSecret = Realtime::RealtimeSessionClientSecret

    module Realtime
      type realtime_session_client_secret =
        { expires_at: Integer, value: String }

      class RealtimeSessionClientSecret < OpenAI::Internal::Type::BaseModel
        attr_accessor expires_at: Integer

        attr_accessor value: String

        def initialize: (expires_at: Integer, value: String) -> void

        def to_hash: -> { expires_at: Integer, value: String }
      end
    end
  end
end
