module OpenAI
  module Models
    module Realtime
      type realtime_translation_client_secret_create_response =
        {
          expires_at: Integer,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          value: String
        }

      class RealtimeTranslationClientSecretCreateResponse < OpenAI::Internal::Type::BaseModel
        # Expiration timestamp for the client secret, in seconds since epoch.
        attr_accessor expires_at: Integer

        # A Realtime translation session. Translation sessions continuously translate
        # input audio into the configured output language.
        attr_accessor session: OpenAI::Realtime::RealtimeTranslationSession

        # The generated client secret value.
        attr_accessor value: String

        # @param expires_at
        #   Expiration timestamp for the client secret, in seconds since epoch.
        # @param session
        #   A Realtime translation session. Translation sessions continuously translate
        #   input audio into the configured output language.
        # @param value
        #   The generated client secret value.
        def initialize: (
          expires_at: Integer,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          value: String
        ) -> void

        def to_hash: -> {
          expires_at: Integer,
          session: OpenAI::Realtime::RealtimeTranslationSession,
          value: String
        }
      end
    end
  end
end
