module OpenAI
  module Models
    module Realtime
      type realtime_translation_session_update_event =
        {
          session: OpenAI::Realtime::RealtimeTranslationSessionUpdateRequest,
          type: :"session.update",
          event_id: String
        }

      class RealtimeTranslationSessionUpdateEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor session: OpenAI::Realtime::RealtimeTranslationSessionUpdateRequest

        attr_accessor type: :"session.update"

        attr_reader event_id: String?

        def event_id=: (String) -> String

        def initialize: (
          session: OpenAI::Realtime::RealtimeTranslationSessionUpdateRequest,
          ?event_id: String,
          ?type: :"session.update"
        ) -> void

        def to_hash: -> {
          session: OpenAI::Realtime::RealtimeTranslationSessionUpdateRequest,
          type: :"session.update",
          event_id: String
        }
      end
    end
  end
end
