module OpenAI
  module Models
    module Realtime
      type realtime_reasoning_effort =
        :minimal | :low | :medium | :high | :xhigh

      module RealtimeReasoningEffort
        extend OpenAI::Internal::Type::Enum

        MINIMAL: :minimal
        LOW: :low
        MEDIUM: :medium
        HIGH: :high
        XHIGH: :xhigh

        def self?.values: -> ::Array[OpenAI::Models::Realtime::realtime_reasoning_effort]
      end
    end
  end
end
