module OpenAI
  module Models
    module Realtime
      type realtime_response_usage_output_token_details =
        { audio_tokens: Integer, text_tokens: Integer }

      class RealtimeResponseUsageOutputTokenDetails < OpenAI::Internal::Type::BaseModel
        attr_reader audio_tokens: Integer?

        def audio_tokens=: (Integer) -> Integer

        attr_reader text_tokens: Integer?

        def text_tokens=: (Integer) -> Integer

        def initialize: (?audio_tokens: Integer, ?text_tokens: Integer) -> void

        def to_hash: -> { audio_tokens: Integer, text_tokens: Integer }
      end
    end
  end
end
