module OpenAI
  module Models
    module Realtime
      type response_output_item_added_event =
        {
          event_id: String,
          item: OpenAI::Models::Realtime::conversation_item,
          output_index: Integer,
          response_id: String,
          ?type: :"response.output_item.added"
        }

      class ResponseOutputItemAddedEvent < OpenAI::Internal::Type::BaseModel
        # The unique ID of the server event.
        attr_accessor event_id: String

        # A single item within a Realtime conversation.
        attr_accessor item: OpenAI::Models::Realtime::conversation_item

        # The index of the output item in the Response.
        attr_accessor output_index: Integer

        # The ID of the Response to which the item belongs.
        attr_accessor response_id: String

        # The event type, must be `response.output_item.added`.
        attr_accessor type: :"response.output_item.added"

        # @param event_id
        #   The unique ID of the server event.
        # @param item
        #   A single item within a Realtime conversation.
        # @param output_index
        #   The index of the output item in the Response.
        # @param response_id
        #   The ID of the Response to which the item belongs.
        # @param type
        #   The event type, must be `response.output_item.added`.
        def initialize: (
          event_id: String,
          item: OpenAI::Models::Realtime::conversation_item,
          output_index: Integer,
          response_id: String,
          ?type: :"response.output_item.added"
        ) -> void

        def to_hash: -> {
          event_id: String,
          item: OpenAI::Models::Realtime::conversation_item,
          output_index: Integer,
          response_id: String,
          ?type: :"response.output_item.added"
        }
      end
    end
  end
end
