module OpenAI
  module Models
    module Realtime
      type response_text_done_event =
        {
          content_index: Integer,
          event_id: String,
          item_id: String,
          output_index: Integer,
          response_id: String,
          text: String,
          type: :"response.output_text.done"
        }

      class ResponseTextDoneEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor content_index: Integer

        attr_accessor event_id: String

        attr_accessor item_id: String

        attr_accessor output_index: Integer

        attr_accessor response_id: String

        attr_accessor text: String

        attr_accessor type: :"response.output_text.done"

        def initialize: (
          content_index: Integer,
          event_id: String,
          item_id: String,
          output_index: Integer,
          response_id: String,
          text: String,
          ?type: :"response.output_text.done"
        ) -> void

        def to_hash: -> {
          content_index: Integer,
          event_id: String,
          item_id: String,
          output_index: Integer,
          response_id: String,
          text: String,
          type: :"response.output_text.done"
        }
      end
    end
  end
end
