module OpenAI
  module Models
    module Realtime
      type response_mcp_call_in_progress =
        {
          event_id: String,
          item_id: String,
          output_index: Integer,
          type: :"response.mcp_call.in_progress"
        }

      class ResponseMcpCallInProgress < OpenAI::Internal::Type::BaseModel
        attr_accessor event_id: String

        attr_accessor item_id: String

        attr_accessor output_index: Integer

        attr_accessor type: :"response.mcp_call.in_progress"

        def initialize: (
          event_id: String,
          item_id: String,
          output_index: Integer,
          ?type: :"response.mcp_call.in_progress"
        ) -> void

        def to_hash: -> {
          event_id: String,
          item_id: String,
          output_index: Integer,
          type: :"response.mcp_call.in_progress"
        }
      end
    end
  end
end
