module OpenAI
  module Models
    module Realtime
      type session_updated_event =
        {
          event_id: String,
          session: OpenAI::Models::Realtime::SessionUpdatedEvent::session,
          ?type: :"session.updated"
        }

      class SessionUpdatedEvent < OpenAI::Internal::Type::BaseModel
        # The unique ID of the server event.
        attr_accessor event_id: String

        # The session configuration.
        attr_accessor session: OpenAI::Models::Realtime::SessionUpdatedEvent::session

        # The event type, must be `session.updated`.
        attr_accessor type: :"session.updated"

        # @param event_id
        #   The unique ID of the server event.
        # @param session
        #   The session configuration.
        # @param type
        #   The event type, must be `session.updated`.
        def initialize: (
          event_id: String,
          session: OpenAI::Models::Realtime::SessionUpdatedEvent::session,
          ?type: :"session.updated"
        ) -> void

        def to_hash: -> {
          event_id: String,
          session: OpenAI::Models::Realtime::SessionUpdatedEvent::session,
          ?type: :"session.updated"
        }

        type session =
          OpenAI::Realtime::RealtimeSessionCreateRequest
          | OpenAI::Realtime::RealtimeTranscriptionSessionCreateRequest

        module Session
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::Realtime::SessionUpdatedEvent::session]
        end
      end
    end
  end
end
