module OpenAI
  module Models
    type audio_model =
      :"whisper-1" | :"gpt-4o-transcribe" | :"gpt-4o-mini-transcribe"

    module AudioModel
      extend OpenAI::Enum

      WHISPER_1: :"whisper-1"
      GPT_4O_TRANSCRIBE: :"gpt-4o-transcribe"
      GPT_4O_MINI_TRANSCRIBE: :"gpt-4o-mini-transcribe"

      def self?.values: -> ::Array[OpenAI::Models::audio_model]
    end
  end
end
