module OpenAI
  module Models
    type batch_retrieve_params =
      {  } & OpenAI::Internal::Type::request_parameters

    class BatchRetrieveParams < OpenAI::BaseModel
      extend OpenAI::Internal::Type::RequestParameters::Converter
      include OpenAI::Internal::Type::RequestParameters

      def initialize: (?request_options: OpenAI::request_opts) -> void

      def to_hash: -> OpenAI::Models::batch_retrieve_params
    end
  end
end
