module OpenAI
  module Models
    type batch_request_counts =
      { completed: Integer, failed: Integer, total: Integer }

    class BatchRequestCounts < OpenAI::Internal::Type::BaseModel
      attr_accessor completed: Integer

      attr_accessor failed: Integer

      attr_accessor total: Integer

      def initialize: (
        completed: Integer,
        failed: Integer,
        total: Integer
      ) -> void

      def to_hash: -> { completed: Integer, failed: Integer, total: Integer }
    end
  end
end
