module OpenAI
  module Models
    type container_list_response =
      {
        id: String,
        created_at: Integer,
        name: String,
        object: String,
        status: String,
        expires_after: OpenAI::Models::ContainerListResponse::ExpiresAfter,
        last_active_at: Integer,
        memory_limit: OpenAI::Models::ContainerListResponse::memory_limit
      }

    class ContainerListResponse < OpenAI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor created_at: Integer

      attr_accessor name: String

      attr_accessor object: String

      attr_accessor status: String

      attr_reader expires_after: OpenAI::Models::ContainerListResponse::ExpiresAfter?

      def expires_after=: (
        OpenAI::Models::ContainerListResponse::ExpiresAfter
      ) -> OpenAI::Models::ContainerListResponse::ExpiresAfter

      attr_reader last_active_at: Integer?

      def last_active_at=: (Integer) -> Integer

      attr_reader memory_limit: OpenAI::Models::ContainerListResponse::memory_limit?

      def memory_limit=: (
        OpenAI::Models::ContainerListResponse::memory_limit
      ) -> OpenAI::Models::ContainerListResponse::memory_limit

      def initialize: (
        id: String,
        created_at: Integer,
        name: String,
        object: String,
        status: String,
        ?expires_after: OpenAI::Models::ContainerListResponse::ExpiresAfter,
        ?last_active_at: Integer,
        ?memory_limit: OpenAI::Models::ContainerListResponse::memory_limit
      ) -> void

      def to_hash: -> {
        id: String,
        created_at: Integer,
        name: String,
        object: String,
        status: String,
        expires_after: OpenAI::Models::ContainerListResponse::ExpiresAfter,
        last_active_at: Integer,
        memory_limit: OpenAI::Models::ContainerListResponse::memory_limit
      }

      type expires_after =
        {
          anchor: OpenAI::Models::ContainerListResponse::ExpiresAfter::anchor,
          minutes: Integer
        }

      class ExpiresAfter < OpenAI::Internal::Type::BaseModel
        attr_reader anchor: OpenAI::Models::ContainerListResponse::ExpiresAfter::anchor?

        def anchor=: (
          OpenAI::Models::ContainerListResponse::ExpiresAfter::anchor
        ) -> OpenAI::Models::ContainerListResponse::ExpiresAfter::anchor

        attr_reader minutes: Integer?

        def minutes=: (Integer) -> Integer

        def initialize: (
          ?anchor: OpenAI::Models::ContainerListResponse::ExpiresAfter::anchor,
          ?minutes: Integer
        ) -> void

        def to_hash: -> {
          anchor: OpenAI::Models::ContainerListResponse::ExpiresAfter::anchor,
          minutes: Integer
        }

        type anchor = :last_active_at

        module Anchor
          extend OpenAI::Internal::Type::Enum

          LAST_ACTIVE_AT: :last_active_at

          def self?.values: -> ::Array[OpenAI::Models::ContainerListResponse::ExpiresAfter::anchor]
        end
      end

      type memory_limit = :"1g" | :"4g" | :"16g" | :"64g"

      module MemoryLimit
        extend OpenAI::Internal::Type::Enum

        MEMORY_LIMIT_1G: :"1g"
        MEMORY_LIMIT_4G: :"4g"
        MEMORY_LIMIT_16G: :"16g"
        MEMORY_LIMIT_64G: :"64g"

        def self?.values: -> ::Array[OpenAI::Models::ContainerListResponse::memory_limit]
      end
    end
  end
end
