module OpenAI
  module Models
    type custom_tool_input_format =
      OpenAI::CustomToolInputFormat::Text
      | OpenAI::CustomToolInputFormat::Grammar

    module CustomToolInputFormat
      extend OpenAI::Internal::Type::Union

      type text = { ?type: :text }

      class Text < OpenAI::Internal::Type::BaseModel
        # Unconstrained text format. Always `text`.
        attr_accessor type: :text

        # @param type
        #   Unconstrained text format. Always `text`.
        def initialize: (?type: :text) -> void

        def to_hash: -> { ?type: :text }
      end

      type grammar =
        {
          definition: String,
          syntax: OpenAI::Models::CustomToolInputFormat::Grammar::syntax,
          ?type: :grammar
        }

      class Grammar < OpenAI::Internal::Type::BaseModel
        # The grammar definition.
        attr_accessor definition: String

        # The syntax of the grammar definition. One of `lark` or `regex`.
        attr_accessor syntax: OpenAI::Models::CustomToolInputFormat::Grammar::syntax

        # Grammar format. Always `grammar`.
        attr_accessor type: :grammar

        # @param definition
        #   The grammar definition.
        # @param syntax
        #   The syntax of the grammar definition. One of `lark` or `regex`.
        # @param type
        #   Grammar format. Always `grammar`.
        def initialize: (
          definition: String,
          syntax: OpenAI::Models::CustomToolInputFormat::Grammar::syntax,
          ?type: :grammar
        ) -> void

        def to_hash: -> {
          definition: String,
          syntax: OpenAI::Models::CustomToolInputFormat::Grammar::syntax,
          ?type: :grammar
        }

        type syntax = :lark | :regex

        module Syntax
          extend OpenAI::Internal::Type::Enum

          LARK: :lark
          REGEX: :regex

          def self?.values: -> ::Array[OpenAI::Models::CustomToolInputFormat::Grammar::syntax]
        end
      end

      def self?.variants: -> ::Array[OpenAI::Models::custom_tool_input_format]
    end
  end
end
