module OpenAI
  module Models
    type embedding =
      { embedding: ::Array[Float], index: Integer, object: :embedding }

    class Embedding < OpenAI::Internal::Type::BaseModel
      attr_accessor embedding: ::Array[Float]

      attr_accessor index: Integer

      attr_accessor object: :embedding

      def initialize: (
        embedding: ::Array[Float],
        index: Integer,
        ?object: :embedding
      ) -> void

      def to_hash: -> {
        embedding: ::Array[Float],
        index: Integer,
        object: :embedding
      }
    end
  end
end
