module OpenAI
  module Models
    type file_chunking_strategy =
      OpenAI::Models::StaticFileChunkingStrategyObject
      | OpenAI::Models::OtherFileChunkingStrategyObject

    module FileChunkingStrategy
      extend OpenAI::Union

      def self?.variants: -> [OpenAI::Models::StaticFileChunkingStrategyObject, OpenAI::Models::OtherFileChunkingStrategyObject]
    end
  end
end
