module OpenAI
  module Models
    type file_chunking_strategy_param =
      OpenAI::AutoFileChunkingStrategyParam
      | OpenAI::StaticFileChunkingStrategyObjectParam

    module FileChunkingStrategyParam
      extend OpenAI::Internal::Type::Union

      def self?.variants: -> ::Array[OpenAI::Models::file_chunking_strategy_param]
    end
  end
end
