module OpenAI
  module Models
    type file_deleted = { id: String, deleted: bool, object: :file }

    class FileDeleted < OpenAI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor deleted: bool

      attr_accessor object: :file

      def initialize: (id: String, deleted: bool, ?object: :file) -> void
    end
  end
end
