module OpenAI
  module Models
    type image_edit_params =
      {
        image: (IO | StringIO),
        prompt: String,
        mask: (IO | StringIO),
        model: OpenAI::Models::ImageEditParams::model?,
        n: Integer?,
        response_format: OpenAI::Models::ImageEditParams::response_format?,
        size: OpenAI::Models::ImageEditParams::size?,
        user: String
      }
      & OpenAI::request_parameters

    class ImageEditParams < OpenAI::BaseModel
      extend OpenAI::RequestParameters::Converter
      include OpenAI::RequestParameters

      attr_accessor image: IO | StringIO

      attr_accessor prompt: String

      attr_reader mask: (IO | StringIO)?

      def mask=: (IO | StringIO) -> (IO | StringIO)

      attr_accessor model: OpenAI::Models::ImageEditParams::model?

      attr_accessor n: Integer?

      attr_accessor response_format: OpenAI::Models::ImageEditParams::response_format?

      attr_accessor size: OpenAI::Models::ImageEditParams::size?

      attr_reader user: String?

      def user=: (String) -> String

      def initialize:
        (
          image: IO | StringIO,
          prompt: String,
          ?mask: IO | StringIO,
          ?model: OpenAI::Models::ImageEditParams::model?,
          ?n: Integer?,
          ?response_format: OpenAI::Models::ImageEditParams::response_format?,
          ?size: OpenAI::Models::ImageEditParams::size?,
          ?user: String,
          ?request_options: OpenAI::request_opts
        ) -> void
        | (?OpenAI::Models::image_edit_params | OpenAI::BaseModel data) -> void

      def to_hash: -> OpenAI::Models::image_edit_params

      type model = String | OpenAI::Models::image_model

      class Model < OpenAI::Union
        def self.variants: -> [String, OpenAI::Models::image_model]
      end

      type response_format = :url | :b64_json

      class ResponseFormat < OpenAI::Enum
        URL: :url
        B64_JSON: :b64_json

        def self.values: -> ::Array[OpenAI::Models::ImageEditParams::response_format]
      end

      type size = :"256x256" | :"512x512" | :"1024x1024"

      class Size < OpenAI::Enum
        NUMBER_256X256: :"256x256"
        NUMBER_512X512: :"512x512"
        NUMBER_1024X1024: :"1024x1024"

        def self.values: -> ::Array[OpenAI::Models::ImageEditParams::size]
      end
    end
  end
end
