module OpenAI
  module Models
    type model_deleted = { id: String, deleted: bool, object: String }

    class ModelDeleted < OpenAI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor deleted: bool

      attr_accessor object: String

      def initialize: (id: String, deleted: bool, object: String) -> void
    end
  end
end
