module OpenAI
  module Models
    type moderation_create_response =
      {
        id: String,
        model: String,
        results: ::Array[OpenAI::Models::Moderation]
      }

    class ModerationCreateResponse < OpenAI::BaseModel
      attr_accessor id: String

      attr_accessor model: String

      attr_accessor results: ::Array[OpenAI::Models::Moderation]

      def initialize:
        (
          id: String,
          model: String,
          results: ::Array[OpenAI::Models::Moderation]
        ) -> void
        | (
          ?OpenAI::Models::moderation_create_response | OpenAI::BaseModel data
        ) -> void

      def to_hash: -> OpenAI::Models::moderation_create_response
    end
  end
end
