module OpenAI
  module Models
    type moderation_image_url_input =
      {
        image_url: OpenAI::Models::ModerationImageURLInput::ImageURL,
        type: :image_url
      }

    class ModerationImageURLInput < OpenAI::Internal::Type::BaseModel
      attr_accessor image_url: OpenAI::Models::ModerationImageURLInput::ImageURL

      attr_accessor type: :image_url

      def initialize: (
        image_url: OpenAI::Models::ModerationImageURLInput::ImageURL,
        ?type: :image_url
      ) -> void

      def to_hash: -> OpenAI::Models::moderation_image_url_input

      type image_url = { url: String }

      class ImageURL < OpenAI::Internal::Type::BaseModel
        attr_accessor url: String

        def initialize: (url: String) -> void

        def to_hash: -> OpenAI::Models::ModerationImageURLInput::image_url
      end
    end
  end
end
