module OpenAI
  module Models
    type other_file_chunking_strategy_object = { type: :other }

    class OtherFileChunkingStrategyObject < OpenAI::BaseModel
      attr_accessor type: :other

      def initialize:
        (type: :other) -> void
        | (
          ?OpenAI::Models::other_file_chunking_strategy_object
          | OpenAI::BaseModel data
        ) -> void

      def to_hash: -> OpenAI::Models::other_file_chunking_strategy_object
    end
  end
end
