module OpenAI
  module Models
    type reasoning_effort = :low | :medium | :high

    module ReasoningEffort
      extend OpenAI::Enum

      LOW: :low
      MEDIUM: :medium
      HIGH: :high

      def self.values: -> ::Array[OpenAI::Models::reasoning_effort]
    end
  end
end
