module OpenAI
  module Models
    type reasoning_effort = :minimal | :low | :medium | :high

    module ReasoningEffort
      extend OpenAI::Internal::Type::Enum

      MINIMAL: :minimal
      LOW: :low
      MEDIUM: :medium
      HIGH: :high

      def self?.values: -> ::Array[OpenAI::Models::reasoning_effort]
    end
  end
end
