module OpenAI
  module Models
    type static_file_chunking_strategy_object_param =
      { static: OpenAI::StaticFileChunkingStrategy, type: :static }

    class StaticFileChunkingStrategyObjectParam < OpenAI::Internal::Type::BaseModel
      attr_accessor static: OpenAI::StaticFileChunkingStrategy

      attr_accessor type: :static

      def initialize: (
        static: OpenAI::StaticFileChunkingStrategy,
        ?type: :static
      ) -> void

      def to_hash: -> {
        static: OpenAI::StaticFileChunkingStrategy,
        type: :static
      }
    end
  end
end
