module OpenAI
  module Models
    type upload_create_params =
      {
        bytes: Integer,
        filename: String,
        mime_type: String,
        purpose: OpenAI::Models::file_purpose
      }
      & OpenAI::Internal::Type::request_parameters

    class UploadCreateParams < OpenAI::Internal::Type::BaseModel
      extend OpenAI::Internal::Type::RequestParameters::Converter
      include OpenAI::Internal::Type::RequestParameters

      attr_accessor bytes: Integer

      attr_accessor filename: String

      attr_accessor mime_type: String

      attr_accessor purpose: OpenAI::Models::file_purpose

      def initialize: (
        bytes: Integer,
        filename: String,
        mime_type: String,
        purpose: OpenAI::Models::file_purpose,
        ?request_options: OpenAI::request_opts
      ) -> void

      def to_hash: -> OpenAI::Models::upload_create_params
    end
  end
end
