module OpenAI
  module Models
    type vector_store_delete_params =
      { vector_store_id: String } & OpenAI::Internal::Type::request_parameters

    class VectorStoreDeleteParams < OpenAI::Internal::Type::BaseModel
      extend OpenAI::Internal::Type::RequestParameters::Converter
      include OpenAI::Internal::Type::RequestParameters

      attr_accessor vector_store_id: String

      def initialize: (
        vector_store_id: String,
        ?request_options: OpenAI::request_opts
      ) -> void

      def to_hash: -> {
        vector_store_id: String,
        request_options: OpenAI::RequestOptions
      }
    end
  end
end
