module OpenAI
  module Models
    type vector_store_delete_params = {  } & OpenAI::request_parameters

    class VectorStoreDeleteParams < OpenAI::BaseModel
      extend OpenAI::RequestParameters::Converter
      include OpenAI::RequestParameters

      def initialize:
        (request_options: OpenAI::request_opts) -> void
        | (
          ?OpenAI::Models::vector_store_delete_params | OpenAI::BaseModel data
        ) -> void

      def to_hash: -> OpenAI::Models::vector_store_delete_params
    end
  end
end
