module OpenAI
  module Models
    type vector_store_expiration_after =
      { anchor: :last_active_at, days: Integer }

    class VectorStoreExpirationAfter < OpenAI::Internal::Type::BaseModel
      attr_accessor anchor: :last_active_at

      attr_accessor days: Integer

      def initialize: (days: Integer, ?anchor: :last_active_at) -> void
    end
  end
end
