module OpenAI
  module Models
    type vector_store_search_response =
      {
        attributes: ::Hash[Symbol, OpenAI::Models::VectorStoreSearchResponse::attribute]?,
        content: ::Array[OpenAI::Models::VectorStoreSearchResponse::Content],
        file_id: String,
        filename: String,
        score: Float
      }

    class VectorStoreSearchResponse < OpenAI::Internal::Type::BaseModel
      # Set of 16 key-value pairs that can be attached to an object. This can be useful
      # for storing additional information about the object in a structured format, and
      # querying for objects via API or the dashboard. Keys are strings with a maximum
      # length of 64 characters. Values are strings with a maximum length of 512
      # characters, booleans, or numbers.
      attr_accessor attributes: ::Hash[Symbol, OpenAI::Models::VectorStoreSearchResponse::attribute]?

      # Content chunks from the file.
      attr_accessor content: ::Array[OpenAI::Models::VectorStoreSearchResponse::Content]

      # The ID of the vector store file.
      attr_accessor file_id: String

      # The name of the vector store file.
      attr_accessor filename: String

      # The similarity score for the result.
      attr_accessor score: Float

      # @param attributes
      #   Set of 16 key-value pairs that can be attached to an object. This can be useful
      #   for storing additional information about the object in a structured format, and
      #   querying for objects via API or the dashboard. Keys are strings with a maximum
      #   length of 64 characters. Values are strings with a maximum length of 512
      #   characters, booleans, or numbers.
      # @param content
      #   Content chunks from the file.
      # @param file_id
      #   The ID of the vector store file.
      # @param filename
      #   The name of the vector store file.
      # @param score
      #   The similarity score for the result.
      def initialize: (
        attributes: ::Hash[Symbol, OpenAI::Models::VectorStoreSearchResponse::attribute]?,
        content: ::Array[OpenAI::Models::VectorStoreSearchResponse::Content],
        file_id: String,
        filename: String,
        score: Float
      ) -> void

      def to_hash: -> {
        attributes: ::Hash[Symbol, OpenAI::Models::VectorStoreSearchResponse::attribute]?,
        content: ::Array[OpenAI::Models::VectorStoreSearchResponse::Content],
        file_id: String,
        filename: String,
        score: Float
      }

      type attribute = String | Float | bool

      module Attribute
        extend OpenAI::Internal::Type::Union

        def self?.variants: -> ::Array[OpenAI::Models::VectorStoreSearchResponse::attribute]
      end

      type content =
        {
          text: String,
          type: OpenAI::Models::VectorStoreSearchResponse::Content::type_
        }

      class Content < OpenAI::Internal::Type::BaseModel
        # The text content returned from search.
        attr_accessor text: String

        # The type of content.
        attr_accessor type: OpenAI::Models::VectorStoreSearchResponse::Content::type_

        # @param text
        #   The text content returned from search.
        # @param type
        #   The type of content.
        def initialize: (
          text: String,
          type: OpenAI::Models::VectorStoreSearchResponse::Content::type_
        ) -> void

        def to_hash: -> {
          text: String,
          type: OpenAI::Models::VectorStoreSearchResponse::Content::type_
        }

        type type_ = :text

        module Type
          extend OpenAI::Internal::Type::Enum

          TEXT: :text

          def self?.values: -> ::Array[OpenAI::Models::VectorStoreSearchResponse::Content::type_]
        end
      end
    end
  end
end
