module OpenAI
  module Models
    type video_extend_params =
      {
        prompt: String,
        seconds: OpenAI::Models::video_seconds,
        video: OpenAI::VideoExtendParams::Video
      }
      & OpenAI::Internal::Type::request_parameters

    class VideoExtendParams < OpenAI::Internal::Type::BaseModel
      extend OpenAI::Internal::Type::RequestParameters::Converter
      include OpenAI::Internal::Type::RequestParameters

      attr_accessor prompt: String

      attr_accessor seconds: OpenAI::Models::video_seconds

      attr_accessor video: OpenAI::VideoExtendParams::Video

      def initialize: (
        prompt: String,
        seconds: OpenAI::Models::video_seconds,
        video: OpenAI::VideoExtendParams::Video,
        ?request_options: OpenAI::request_opts
      ) -> void

      def to_hash: -> {
        prompt: String,
        seconds: OpenAI::Models::video_seconds,
        video: OpenAI::VideoExtendParams::Video,
        request_options: OpenAI::RequestOptions
      }

      type video = { id: String }

      class Video < OpenAI::Internal::Type::BaseModel
        attr_accessor id: String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
