module OpenAI
  module Models
    type video_delete_response =
      { id: String, deleted: bool, object: :"video.deleted" }

    class VideoDeleteResponse < OpenAI::Internal::Type::BaseModel
      attr_accessor id: String

      attr_accessor deleted: bool

      attr_accessor object: :"video.deleted"

      def initialize: (
        id: String,
        deleted: bool,
        ?object: :"video.deleted"
      ) -> void

      def to_hash: -> { id: String, deleted: bool, object: :"video.deleted" }
    end
  end
end
