module OpenAI
  module Models
    type video_model =
      String
      | :"sora-2"
      | :"sora-2-pro"
      | :"sora-2-2025-10-06"
      | :"sora-2-pro-2025-10-06"
      | :"sora-2-2025-12-08"

    module VideoModel
      extend OpenAI::Internal::Type::Union

      def self?.variants: -> ::Array[OpenAI::Models::video_model]

      SORA_2: :"sora-2"
      SORA_2_PRO: :"sora-2-pro"
      SORA_2_2025_10_06: :"sora-2-2025-10-06"
      SORA_2_PRO_2025_10_06: :"sora-2-pro-2025-10-06"
      SORA_2_2025_12_08: :"sora-2-2025-12-08"
    end
  end
end
