module OpenAI
  module Models
    type video_extend_params =
      {
        prompt: String,
        seconds: OpenAI::Models::video_seconds,
        video: OpenAI::Models::VideoExtendParams::video
      }
      & OpenAI::Internal::Type::request_parameters

    class VideoExtendParams < OpenAI::Internal::Type::BaseModel
      extend OpenAI::Internal::Type::RequestParameters::Converter
      include OpenAI::Internal::Type::RequestParameters

      attr_accessor prompt: String

      attr_accessor seconds: OpenAI::Models::video_seconds

      attr_accessor video: OpenAI::Models::VideoExtendParams::video

      def initialize: (
        prompt: String,
        seconds: OpenAI::Models::video_seconds,
        video: OpenAI::Models::VideoExtendParams::video,
        ?request_options: OpenAI::request_opts
      ) -> void

      def to_hash: -> {
        prompt: String,
        seconds: OpenAI::Models::video_seconds,
        video: OpenAI::Models::VideoExtendParams::video,
        request_options: OpenAI::RequestOptions
      }

      type video =
        OpenAI::Internal::file_input
        | OpenAI::VideoExtendParams::Video::VideoReferenceInputParam

      module Video
        extend OpenAI::Internal::Type::Union

        type video_reference_input_param = { id: String }

        class VideoReferenceInputParam < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          def initialize: (id: String) -> void

          def to_hash: -> { id: String }
        end

        def self?.variants: -> ::Array[OpenAI::Models::VideoExtendParams::video]
      end
    end
  end
end
