module OpenAI
  module Models
    module Beta
      module Agents
        module Vaults
          type credential_deleted =
            { id: String, deleted: bool, ?object: :"vault.credential.deleted" }

          class CredentialDeleted < OpenAI::Internal::Type::BaseModel
            # The ID of the deleted credential.
            attr_accessor id: String

            # Whether the resource was deleted. Always `true`.
            attr_accessor deleted: bool

            # The object type. Always `vault.credential.deleted`.
            attr_accessor object: :"vault.credential.deleted"

            # @param id
            #   The ID of the deleted credential.
            # @param deleted
            #   Whether the resource was deleted. Always `true`.
            # @param object
            #   The object type. Always `vault.credential.deleted`.
            def initialize: (
              id: String,
              deleted: bool,
              ?object: :"vault.credential.deleted"
            ) -> void

            def to_hash: -> {
              id: String,
              deleted: bool,
              ?object: :"vault.credential.deleted"
            }
          end
        end
      end
    end
  end
end
