module OpenAI
  module Models
    module Beta
      module Agents
        module Vaults
          type credential_list_params =
            {
              vault_id: String,
              ?after: String,
              ?limit: Integer?,
              ?order: OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order,
              ?status: OpenAI::Models::Beta::Agents::vault_status_filter,
              ?request_options: OpenAI::request_opts
            }

          class CredentialListParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor vault_id: String

            attr_reader after: String?

            def after=: (String) -> String

            attr_accessor limit: Integer?

            attr_reader order: OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order?

            def order=: (
              OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order
            ) -> OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order

            attr_reader status: OpenAI::Models::Beta::Agents::vault_status_filter?

            def status=: (
              OpenAI::Models::Beta::Agents::vault_status_filter
            ) -> OpenAI::Models::Beta::Agents::vault_status_filter

            def initialize: (
              vault_id: String,
              ?after: String,
              ?limit: Integer?,
              ?order: OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order,
              ?status: OpenAI::Models::Beta::Agents::vault_status_filter,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              vault_id: String,
              ?after: String,
              ?limit: Integer?,
              ?order: OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order,
              ?status: OpenAI::Models::Beta::Agents::vault_status_filter,
              ?request_options: OpenAI::RequestOptions
            }

            type order = :asc | :desc

            module Order
              extend OpenAI::Internal::Type::Enum

              # Returns resources in ascending order.
              ASC: :asc

              # Returns resources in descending order.
              DESC: :desc

              def self?.values: -> ::Array[OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order]
            end
          end
        end
      end
    end
  end
end
