module OpenAI
  module Models
    module Beta
      module Agents
        module Vaults
          type credential =
            {
              id: String,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth,
              created_at: Integer,
              name: String,
              ?object: :"vault.credential",
              updated_at: Integer,
              vault_id: String
            }

          class Credential < OpenAI::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth

            attr_accessor created_at: Integer

            attr_accessor name: String

            attr_accessor object: :"vault.credential"

            attr_accessor updated_at: Integer

            attr_accessor vault_id: String

            def initialize: (
              id: String,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth,
              created_at: Integer,
              name: String,
              updated_at: Integer,
              vault_id: String,
              ?object: :"vault.credential"
            ) -> void

            def to_hash: -> {
              id: String,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth,
              created_at: Integer,
              name: String,
              ?object: :"vault.credential",
              updated_at: Integer,
              vault_id: String
            }
          end
        end
      end
    end
  end
end
