module OpenAI
  module Models
    module Beta
      module Agents
        module Vaults
          type credential_update_params =
            {
              vault_id: String,
              credential_id: String,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth_rotate_param,
              ?request_options: OpenAI::request_opts
            }

          class CredentialUpdateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor vault_id: String

            attr_accessor credential_id: String

            attr_accessor auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth_rotate_param

            def initialize: (
              vault_id: String,
              credential_id: String,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth_rotate_param,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              vault_id: String,
              credential_id: String,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth_rotate_param,
              ?request_options: OpenAI::RequestOptions
            }
          end
        end
      end
    end
  end
end
