module OpenAI
  module Models
    module Beta
      module Agents
        module Vaults
          type mcp_oauth_token_endpoint_auth =
            OpenAI::Beta::Agents::Vaults::McpOauthTokenEndpointAuth::None
            | OpenAI::Beta::Agents::Vaults::McpOauthTokenEndpointAuth::ClientSecretBasic
            | OpenAI::Beta::Agents::Vaults::McpOauthTokenEndpointAuth::ClientSecretPost

          module McpOauthTokenEndpointAuth
            extend OpenAI::Internal::Type::Union

            type none = { ?type: :none }

            class None < OpenAI::Internal::Type::BaseModel
              attr_accessor type: :none

              def initialize: (?type: :none) -> void

              def to_hash: -> { ?type: :none }
            end

            type client_secret_basic = { ?type: :client_secret_basic }

            class ClientSecretBasic < OpenAI::Internal::Type::BaseModel
              attr_accessor type: :client_secret_basic

              def initialize: (?type: :client_secret_basic) -> void

              def to_hash: -> { ?type: :client_secret_basic }
            end

            type client_secret_post = { ?type: :client_secret_post }

            class ClientSecretPost < OpenAI::Internal::Type::BaseModel
              attr_accessor type: :client_secret_post

              def initialize: (?type: :client_secret_post) -> void

              def to_hash: -> { ?type: :client_secret_post }
            end

            def self?.variants: -> ::Array[OpenAI::Models::Beta::Agents::Vaults::mcp_oauth_token_endpoint_auth]
          end
        end
      end
    end
  end
end
