module OpenAI
  module Models
    class ChatCompletionStreamOptions = Chat::ChatCompletionStreamOptions

    module Chat
      type chat_completion_stream_options =
        { ?include_obfuscation: bool, ?include_usage: bool }

      class ChatCompletionStreamOptions < OpenAI::Internal::Type::BaseModel
        # When true, stream obfuscation will be enabled. Stream obfuscation adds random
        # characters to an `obfuscation` field on streaming delta events to normalize
        # payload sizes as a mitigation to certain side-channel attacks. These obfuscation
        # fields are included by default, but add a small amount of overhead to the data
        # stream. You can set `include_obfuscation` to false to optimize for bandwidth if
        # you trust the network links between your application and the OpenAI API.
        attr_reader include_obfuscation: bool?

        # When true, stream obfuscation will be enabled. Stream obfuscation adds random
        # characters to an `obfuscation` field on streaming delta events to normalize
        # payload sizes as a mitigation to certain side-channel attacks. These obfuscation
        # fields are included by default, but add a small amount of overhead to the data
        # stream. You can set `include_obfuscation` to false to optimize for bandwidth if
        # you trust the network links between your application and the OpenAI API.
        def include_obfuscation=: (bool) -> bool

        # If set, an additional chunk will be streamed before the `data: [DONE]` message.
        # The `usage` field on this chunk shows the token usage statistics for the entire
        # request, and the `choices` field will always be an empty array.
        #
        # All other chunks will also include a `usage` field, but with a null value.
        # **NOTE:** If the stream is interrupted, you may not receive the final usage
        # chunk which contains the total token usage for the request.
        attr_reader include_usage: bool?

        # If set, an additional chunk will be streamed before the `data: [DONE]` message.
        # The `usage` field on this chunk shows the token usage statistics for the entire
        # request, and the `choices` field will always be an empty array.
        #
        # All other chunks will also include a `usage` field, but with a null value.
        # **NOTE:** If the stream is interrupted, you may not receive the final usage
        # chunk which contains the total token usage for the request.
        def include_usage=: (bool) -> bool

        # @param include_obfuscation
        #   When true, stream obfuscation will be enabled. Stream obfuscation adds random
        #   characters to an `obfuscation` field on streaming delta events to normalize
        #   payload sizes as a mitigation to certain side-channel attacks. These obfuscation
        #   fields are included by default, but add a small amount of overhead to the data
        #   stream. You can set `include_obfuscation` to false to optimize for bandwidth if
        #   you trust the network links between your application and the OpenAI API.
        # @param include_usage
        #   If set, an additional chunk will be streamed before the `data: [DONE]` message.
        #   The `usage` field on this chunk shows the token usage statistics for the entire
        #   request, and the `choices` field will always be an empty array.
        #
        #   All other chunks will also include a `usage` field, but with a null value.
        #   **NOTE:** If the stream is interrupted, you may not receive the final usage
        #   chunk which contains the total token usage for the request.
        def initialize: (
          ?include_obfuscation: bool,
          ?include_usage: bool
        ) -> void

        def to_hash: -> { ?include_obfuscation: bool, ?include_usage: bool }
      end
    end
  end
end
