module OpenAI
  module Models
    class ChatCompletionNamedToolChoice = Chat::ChatCompletionNamedToolChoice

    module Chat
      type chat_completion_named_tool_choice =
        {
          function: OpenAI::Models::Chat::ChatCompletionNamedToolChoice::Function,
          type: :function
        }

      class ChatCompletionNamedToolChoice < OpenAI::Internal::Type::BaseModel
        attr_accessor function: OpenAI::Models::Chat::ChatCompletionNamedToolChoice::Function

        attr_accessor type: :function

        def initialize: (
          function: OpenAI::Models::Chat::ChatCompletionNamedToolChoice::Function,
          ?type: :function
        ) -> void

        def to_hash: -> OpenAI::Models::Chat::chat_completion_named_tool_choice

        type function = { name: String }

        class Function < OpenAI::Internal::Type::BaseModel
          attr_accessor name: String

          def initialize: (name: String) -> void

          def to_hash: -> OpenAI::Models::Chat::ChatCompletionNamedToolChoice::function
        end
      end
    end
  end
end
