module OpenAI
  module Models
    class ChatCompletionTool = Chat::ChatCompletionTool

    module Chat
      type chat_completion_tool =
        { function: OpenAI::FunctionDefinition, type: :function }

      class ChatCompletionTool < OpenAI::Internal::Type::BaseModel
        attr_accessor function: OpenAI::FunctionDefinition

        attr_accessor type: :function

        def initialize: (
          function: OpenAI::FunctionDefinition,
          ?type: :function
        ) -> void

        def to_hash: -> {
          function: OpenAI::FunctionDefinition,
          type: :function
        }
      end
    end
  end
end
