module OpenAI
  module Models
    
    class ChatCompletionContentPartInputAudio = Chat::ChatCompletionContentPartInputAudio

    module Chat
      type chat_completion_content_part_input_audio =
        {
          input_audio: OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::InputAudio,
          type: :input_audio
        }

      class ChatCompletionContentPartInputAudio < OpenAI::BaseModel
        attr_accessor input_audio: OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::InputAudio

        attr_accessor type: :input_audio

        def initialize: (
          input_audio: OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::InputAudio,
          ?type: :input_audio
        ) -> void

        def to_hash: -> OpenAI::Models::Chat::chat_completion_content_part_input_audio

        type input_audio =
          {
            data: String,
            format_: OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::InputAudio::format_
          }

        class InputAudio < OpenAI::BaseModel
          attr_accessor data: String

          attr_accessor format_: OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::InputAudio::format_

          def initialize: (
            data: String,
            format_: OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::InputAudio::format_
          ) -> void

          def to_hash: -> OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::input_audio

          type format_ = :wav | :mp3

          class Format < OpenAI::Enum
            WAV: :wav
            MP3: :mp3

            def self.values: -> ::Array[OpenAI::Models::Chat::ChatCompletionContentPartInputAudio::InputAudio::format_]
          end
        end
      end
    end
  end
end
