module OpenAI
  module Models
    class ChatCompletionMessageFunctionToolCall = Chat::ChatCompletionMessageFunctionToolCall

    module Chat
      type chat_completion_message_function_tool_call =
        {
          id: String,
          function: OpenAI::Chat::ChatCompletionMessageFunctionToolCall::Function,
          ?type: :function
        }

      class ChatCompletionMessageFunctionToolCall < OpenAI::Internal::Type::BaseModel
        # The ID of the tool call.
        attr_accessor id: String

        # The function that the model called.
        attr_accessor function: OpenAI::Chat::ChatCompletionMessageFunctionToolCall::Function

        # The type of the tool. Currently, only `function` is supported.
        attr_accessor type: :function

        # @param id
        #   The ID of the tool call.
        # @param function
        #   The function that the model called.
        # @param type
        #   The type of the tool. Currently, only `function` is supported.
        def initialize: (
          id: String,
          function: OpenAI::Chat::ChatCompletionMessageFunctionToolCall::Function,
          ?type: :function
        ) -> void

        def to_hash: -> {
          id: String,
          function: OpenAI::Chat::ChatCompletionMessageFunctionToolCall::Function,
          ?type: :function
        }

        type function = { arguments: String, name: String }

        class Function < OpenAI::Internal::Type::BaseModel
          # The arguments to call the function with, as generated by the model in JSON
          # format. Note that the model does not always generate valid JSON, and may
          # hallucinate parameters not defined by your function schema. Validate the
          # arguments in your code before calling your function.
          attr_accessor arguments: String

          # The name of the function to call.
          attr_accessor name: String

          # @param arguments
          #   The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          # @param name
          #   The name of the function to call.
          def initialize: (arguments: String, name: String) -> void

          def to_hash: -> { arguments: String, name: String }
        end
      end
    end
  end
end
