module OpenAI
  module Models
    class ChatCompletionStoreMessage = Chat::ChatCompletionStoreMessage

    module Chat
      type chat_completion_store_message = { id: String }

      class ChatCompletionStoreMessage < OpenAI::Models::Chat::ChatCompletionMessage
        def id: -> String

        def id=: (String _) -> String

        def initialize: (id: String) -> void
      end
    end
  end
end
