module OpenAI
  module Models
    
    class ChatCompletionMessageParam = Chat::ChatCompletionMessageParam

    module Chat
      type chat_completion_message_param =
        OpenAI::Models::Chat::ChatCompletionDeveloperMessageParam
        | OpenAI::Models::Chat::ChatCompletionSystemMessageParam
        | OpenAI::Models::Chat::ChatCompletionUserMessageParam
        | OpenAI::Models::Chat::ChatCompletionAssistantMessageParam
        | OpenAI::Models::Chat::ChatCompletionToolMessageParam
        | OpenAI::Models::Chat::ChatCompletionFunctionMessageParam

      class ChatCompletionMessageParam < OpenAI::Union
        def self.variants: -> [OpenAI::Models::Chat::ChatCompletionDeveloperMessageParam, OpenAI::Models::Chat::ChatCompletionSystemMessageParam, OpenAI::Models::Chat::ChatCompletionUserMessageParam, OpenAI::Models::Chat::ChatCompletionAssistantMessageParam, OpenAI::Models::Chat::ChatCompletionToolMessageParam, OpenAI::Models::Chat::ChatCompletionFunctionMessageParam]
      end
    end
  end
end
