module OpenAI
  module Models
    class ChatCompletionUserMessageParam = Chat::ChatCompletionUserMessageParam

    module Chat
      type chat_completion_user_message_param =
        {
          content: OpenAI::Models::Chat::ChatCompletionUserMessageParam::content,
          role: :user,
          name: String
        }

      class ChatCompletionUserMessageParam < OpenAI::Internal::Type::BaseModel
        attr_accessor content: OpenAI::Models::Chat::ChatCompletionUserMessageParam::content

        attr_accessor role: :user

        attr_reader name: String?

        def name=: (String) -> String

        def initialize: (
          content: OpenAI::Models::Chat::ChatCompletionUserMessageParam::content,
          ?name: String,
          ?role: :user
        ) -> void

        def to_hash: -> {
          content: OpenAI::Models::Chat::ChatCompletionUserMessageParam::content,
          role: :user,
          name: String
        }

        type content =
          String | ::Array[OpenAI::Models::Chat::chat_completion_content_part]

        module Content
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::Chat::ChatCompletionUserMessageParam::content]

          ChatCompletionContentPartArray: OpenAI::Internal::Type::Converter
        end
      end
    end
  end
end
