module OpenAI
  module Models
    
    class ChatCompletionContentPart = Chat::ChatCompletionContentPart

    module Chat
      type chat_completion_content_part =
        OpenAI::Models::Chat::ChatCompletionContentPartText
        | OpenAI::Models::Chat::ChatCompletionContentPartImage
        | OpenAI::Models::Chat::ChatCompletionContentPartInputAudio

      class ChatCompletionContentPart < OpenAI::Union
        def self.variants: -> [OpenAI::Models::Chat::ChatCompletionContentPartText, OpenAI::Models::Chat::ChatCompletionContentPartImage, OpenAI::Models::Chat::ChatCompletionContentPartInputAudio]
      end
    end
  end
end
