module OpenAI
  module Models
    
    class ChatCompletionMessage = Chat::ChatCompletionMessage

    module Chat
      type chat_completion_message =
        {
          content: String?,
          refusal: String?,
          role: :assistant,
          annotations: ::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation],
          audio: OpenAI::Models::Chat::ChatCompletionAudio?,
          function_call: OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall,
          tool_calls: ::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall]
        }

      class ChatCompletionMessage < OpenAI::BaseModel
        attr_accessor content: String?

        attr_accessor refusal: String?

        attr_accessor role: :assistant

        attr_reader annotations: ::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation]?

        def annotations=: (
          ::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation]
        ) -> ::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation]

        attr_accessor audio: OpenAI::Models::Chat::ChatCompletionAudio?

        attr_reader function_call: OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall?

        def function_call=: (
          OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall
        ) -> OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall

        attr_reader tool_calls: ::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall]?

        def tool_calls=: (
          ::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall]
        ) -> ::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall]

        def initialize: (
          content: String?,
          refusal: String?,
          ?annotations: ::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation],
          ?audio: OpenAI::Models::Chat::ChatCompletionAudio?,
          ?function_call: OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall,
          ?tool_calls: ::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall],
          ?role: :assistant
        ) -> void

        def to_hash: -> OpenAI::Models::Chat::chat_completion_message

        type annotation =
          {
            type: :url_citation,
            url_citation: OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation
          }

        class Annotation < OpenAI::BaseModel
          attr_accessor type: :url_citation

          attr_accessor url_citation: OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation

          def initialize: (
            url_citation: OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation,
            ?type: :url_citation
          ) -> void

          def to_hash: -> OpenAI::Models::Chat::ChatCompletionMessage::annotation

          type url_citation =
            {
              end_index: Integer,
              start_index: Integer,
              title: String,
              url: String
            }

          class URLCitation < OpenAI::BaseModel
            attr_accessor end_index: Integer

            attr_accessor start_index: Integer

            attr_accessor title: String

            attr_accessor url: String

            def initialize: (
              end_index: Integer,
              start_index: Integer,
              title: String,
              url: String
            ) -> void

            def to_hash: -> OpenAI::Models::Chat::ChatCompletionMessage::Annotation::url_citation
          end
        end

        type function_call = { arguments: String, name: String }

        class FunctionCall < OpenAI::BaseModel
          attr_accessor arguments: String

          attr_accessor name: String

          def initialize: (arguments: String, name: String) -> void

          def to_hash: -> OpenAI::Models::Chat::ChatCompletionMessage::function_call
        end
      end
    end
  end
end
