module OpenAI
  module Models
    class ChatCompletionDeveloperMessageParam = Chat::ChatCompletionDeveloperMessageParam

    module Chat
      type chat_completion_developer_message_param =
        {
          content: OpenAI::Models::Chat::ChatCompletionDeveloperMessageParam::content,
          ?role: :developer,
          ?name: String
        }

      class ChatCompletionDeveloperMessageParam < OpenAI::Internal::Type::BaseModel
        # The contents of the developer message.
        attr_accessor content: OpenAI::Models::Chat::ChatCompletionDeveloperMessageParam::content

        # The role of the messages author, in this case `developer`.
        attr_accessor role: :developer

        # An optional name for the participant. Provides the model information to
        # differentiate between participants of the same role.
        attr_reader name: String?

        # An optional name for the participant. Provides the model information to
        # differentiate between participants of the same role.
        def name=: (String) -> String

        # @param content
        #   The contents of the developer message.
        # @param name
        #   An optional name for the participant. Provides the model information to
        #   differentiate between participants of the same role.
        # @param role
        #   The role of the messages author, in this case `developer`.
        def initialize: (
          content: OpenAI::Models::Chat::ChatCompletionDeveloperMessageParam::content,
          ?name: String,
          ?role: :developer
        ) -> void

        def to_hash: -> {
          content: OpenAI::Models::Chat::ChatCompletionDeveloperMessageParam::content,
          ?role: :developer,
          ?name: String
        }

        type content =
          String | ::Array[OpenAI::Chat::ChatCompletionContentPartText]

        module Content
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::Chat::ChatCompletionDeveloperMessageParam::content]

          ChatCompletionContentPartTextArray: OpenAI::Internal::Type::Converter
        end
      end
    end
  end
end
