module OpenAI
  module Models
    class ChatCompletionStoreMessage = Chat::ChatCompletionStoreMessage

    module Chat
      type chat_completion_store_message =
        {
          content: String?,
          refusal: String?,
          id: String,
          ?role: :assistant,
          ?annotations: ::Array[OpenAI::Chat::ChatCompletionMessage::Annotation],
          ?audio: OpenAI::Chat::ChatCompletionAudio?,
          ?function_call: OpenAI::Chat::ChatCompletionMessage::FunctionCall,
          ?tool_calls: ::Array[OpenAI::Models::Chat::chat_completion_message_tool_call],
          ?content_parts: ::Array[OpenAI::Models::Chat::ChatCompletionStoreMessage::content_part]?
        }

      class ChatCompletionStoreMessage < OpenAI::Models::Chat::ChatCompletionMessage
        # The identifier of the chat message.
        def id: -> String

        # The identifier of the chat message.
        def id=: (String _) -> String

        # If a content parts array was provided, this is an array of `text` and
        # `image_url` parts. Otherwise, null.
        def content_parts: -> ::Array[OpenAI::Models::Chat::ChatCompletionStoreMessage::content_part]?

        # If a content parts array was provided, this is an array of `text` and
        # `image_url` parts. Otherwise, null.
        def content_parts=: (
          ::Array[OpenAI::Models::Chat::ChatCompletionStoreMessage::content_part]? _
        ) -> ::Array[OpenAI::Models::Chat::ChatCompletionStoreMessage::content_part]?

        # @param content
        #   The contents of the message.
        # @param refusal
        #   The refusal message generated by the model.
        # @param id
        #   The identifier of the chat message.
        # @param annotations
        #   Annotations for the message, when applicable, as when using the
        #   [web search tool](https://developers.openai.com/api/docs/guides/tools-web-search).
        # @param audio
        #   If the audio output modality is requested, this object contains data about the
        #   audio response from the model.
        #   [Learn more](https://developers.openai.com/api/docs/guides/audio).
        # @param function_call
        #   Deprecated and replaced by `tool_calls`. The name and arguments of a function
        #   that should be called, as generated by the model.
        # @param tool_calls
        #   The tool calls generated by the model, such as function calls.
        # @param content_parts
        #   If a content parts array was provided, this is an array of `text` and
        #   `image_url` parts. Otherwise, null.
        # @param role
        #   The role of the author of this message.
        def initialize: (
          content: String?,
          refusal: String?,
          id: String,
          ?annotations: ::Array[OpenAI::Chat::ChatCompletionMessage::Annotation],
          ?audio: OpenAI::Chat::ChatCompletionAudio?,
          ?function_call: OpenAI::Chat::ChatCompletionMessage::FunctionCall,
          ?tool_calls: ::Array[OpenAI::Models::Chat::chat_completion_message_tool_call],
          ?content_parts: ::Array[OpenAI::Models::Chat::ChatCompletionStoreMessage::content_part]?,
          ?role: :assistant
        ) -> void

        def to_hash: -> {
          content: String?,
          refusal: String?,
          id: String,
          ?role: :assistant,
          ?annotations: ::Array[OpenAI::Chat::ChatCompletionMessage::Annotation],
          ?audio: OpenAI::Chat::ChatCompletionAudio?,
          ?function_call: OpenAI::Chat::ChatCompletionMessage::FunctionCall,
          ?tool_calls: ::Array[OpenAI::Models::Chat::chat_completion_message_tool_call],
          ?content_parts: ::Array[OpenAI::Models::Chat::ChatCompletionStoreMessage::content_part]?
        }

        type content_part =
          OpenAI::Chat::ChatCompletionContentPartText
          | OpenAI::Chat::ChatCompletionContentPartImage

        module ContentPart
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::Chat::ChatCompletionStoreMessage::content_part]
        end
      end
    end
  end
end
