module OpenAI
  module Models
    module Chat
      type completion_update_params =
        { completion_id: String, metadata: OpenAI::Models::metadata? }
        & OpenAI::Internal::Type::request_parameters

      class CompletionUpdateParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor completion_id: String

        attr_accessor metadata: OpenAI::Models::metadata?

        def initialize: (
          completion_id: String,
          metadata: OpenAI::Models::metadata?,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          completion_id: String,
          metadata: OpenAI::Models::metadata?,
          request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
