module OpenAI
  module Models
    module Admin
      module Organization
        module Groups
          type role_list_params =
            {
              group_id: String,
              ?after: String,
              ?limit: Integer,
              ?order: OpenAI::Models::Admin::Organization::Groups::RoleListParams::order,
              ?request_options: OpenAI::request_opts
            }

          class RoleListParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor group_id: String

            # Cursor for pagination. Provide the value from the previous response's `next`
            # field to continue listing organization roles.
            attr_reader after: String?

            # Cursor for pagination. Provide the value from the previous response's `next`
            # field to continue listing organization roles.
            def after=: (String) -> String

            # A limit on the number of organization role assignments to return.
            attr_reader limit: Integer?

            # A limit on the number of organization role assignments to return.
            def limit=: (Integer) -> Integer

            # Sort order for the returned organization roles.
            attr_reader order: OpenAI::Models::Admin::Organization::Groups::RoleListParams::order?

            # Sort order for the returned organization roles.
            def order=: (
              OpenAI::Models::Admin::Organization::Groups::RoleListParams::order
            ) -> OpenAI::Models::Admin::Organization::Groups::RoleListParams::order

            # @param after
            #   Cursor for pagination. Provide the value from the previous response's `next`
            #   field to continue listing organization roles.
            # @param limit
            #   A limit on the number of organization role assignments to return.
            # @param order
            #   Sort order for the returned organization roles.
            def initialize: (
              group_id: String,
              ?after: String,
              ?limit: Integer,
              ?order: OpenAI::Models::Admin::Organization::Groups::RoleListParams::order,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              group_id: String,
              ?after: String,
              ?limit: Integer,
              ?order: OpenAI::Models::Admin::Organization::Groups::RoleListParams::order,
              ?request_options: OpenAI::RequestOptions
            }

            type order = :asc | :desc

            module Order
              extend OpenAI::Internal::Type::Enum

              ASC: :asc
              DESC: :desc

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Groups::RoleListParams::order]
            end
          end
        end
      end
    end
  end
end
