module OpenAI
  module Models
    module Admin
      module Organization
        module Groups
          type user_create_params =
            {
              group_id: String,
              user_id: String,
              ?request_options: OpenAI::request_opts
            }

          class UserCreateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor group_id: String

            # Identifier of the user to add to the group.
            attr_accessor user_id: String

            # @param user_id
            #   Identifier of the user to add to the group.
            def initialize: (
              group_id: String,
              user_id: String,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              group_id: String,
              user_id: String,
              ?request_options: OpenAI::RequestOptions
            }
          end
        end
      end
    end
  end
end
