# typed: strong

module OpenAI
  module Models

    ChatCompletionContentPartRefusal = Chat::ChatCompletionContentPartRefusal

    module Chat

      class ChatCompletionContentPartRefusal < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Chat::ChatCompletionContentPartRefusal,
            OpenAI::Internal::AnyHash
          )
        end

        # The refusal message generated by the model.
        sig { returns(String) }
        attr_accessor :refusal

        # The type of the content part.
        sig { returns(Symbol) }
        attr_accessor :type

        sig do
          params(

            refusal: String,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The refusal message generated by the model.
          refusal:,

          # The type of the content part.

          type: :refusal
        )
        end

        sig do
          override.returns(
            {refusal: String, type: Symbol}
          )
        end
        def to_hash
        end

      end

    end

  end
end
