# typed: strong

module OpenAI
  module Models
    module Chat
      class ChatCompletionStoreMessage < OpenAI::Models::Chat::ChatCompletionMessage
        # The identifier of the chat message.
        sig { returns(String) }
        attr_accessor :id

        # A chat completion message generated by the model.
        sig { params(id: String).returns(T.attached_class) }
        def self.new(
          # The identifier of the chat message.
          id:
        ); end
        sig { override.returns({id: String}) }
        def to_hash; end
      end
    end

    ChatCompletionStoreMessage = Chat::ChatCompletionStoreMessage
  end
end
