# typed: strong

module OpenAI
  module Models
    ChatCompletionStoreMessage = Chat::ChatCompletionStoreMessage

    module Chat
      class ChatCompletionStoreMessage < OpenAI::Models::Chat::ChatCompletionMessage
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Chat::ChatCompletionStoreMessage,
              OpenAI::Internal::AnyHash
            )
          end

        # The identifier of the chat message.
        sig { returns(String) }
        attr_accessor :id

        # If a content parts array was provided, this is an array of `text` and
        # `image_url` parts. Otherwise, null.
        sig do
          returns(
            T.nilable(
              T::Array[
                OpenAI::Chat::ChatCompletionStoreMessage::ContentPart::Variants
              ]
            )
          )
        end
        attr_accessor :content_parts

        # A chat completion message generated by the model.
        sig do
          params(
            content: T.nilable(String),
            refusal: T.nilable(String),
            id: String,
            annotations:
              T::Array[OpenAI::Chat::ChatCompletionMessage::Annotation::OrHash],
            audio: T.nilable(OpenAI::Chat::ChatCompletionAudio::OrHash),
            function_call:
              OpenAI::Chat::ChatCompletionMessage::FunctionCall::OrHash,
            tool_calls:
              T::Array[
                T.any(
                  OpenAI::Chat::ChatCompletionMessageFunctionToolCall::OrHash,
                  OpenAI::Chat::ChatCompletionMessageCustomToolCall::OrHash
                )
              ],
            content_parts:
              T.nilable(
                T::Array[
                  T.any(
                    OpenAI::Chat::ChatCompletionContentPartText::OrHash,
                    OpenAI::Chat::ChatCompletionContentPartImage::OrHash
                  )
                ]
              ),
            role: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The contents of the message.
          content:,
          # The refusal message generated by the model.
          refusal:,
          # The identifier of the chat message.
          id:,
          # Annotations for the message, when applicable, as when using the
          # [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
          annotations: nil,
          # If the audio output modality is requested, this object contains data about the
          # audio response from the model.
          # [Learn more](https://platform.openai.com/docs/guides/audio).
          audio: nil,
          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          # that should be called, as generated by the model.
          function_call: nil,
          # The tool calls generated by the model, such as function calls.
          tool_calls: nil,
          # If a content parts array was provided, this is an array of `text` and
          # `image_url` parts. Otherwise, null.
          content_parts: nil,
          # The role of the author of this message.
          role: :assistant
        )
        end

        sig do
          override.returns(
            {
              content: T.nilable(String),
              refusal: T.nilable(String),
              id: String,
              role: Symbol,
              annotations:
                T::Array[OpenAI::Chat::ChatCompletionMessage::Annotation],
              audio: T.nilable(OpenAI::Chat::ChatCompletionAudio),
              function_call: OpenAI::Chat::ChatCompletionMessage::FunctionCall,
              tool_calls:
                T::Array[OpenAI::Chat::ChatCompletionMessageToolCall::Variants],
              content_parts:
                T.nilable(
                  T::Array[
                    OpenAI::Chat::ChatCompletionStoreMessage::ContentPart::Variants
                  ]
                )
            }
          )
        end
        def to_hash
        end

        # Learn about
        # [text inputs](https://platform.openai.com/docs/guides/text-generation).
        module ContentPart
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Chat::ChatCompletionContentPartText,
                OpenAI::Chat::ChatCompletionContentPartImage
              )
            end

          sig do
            override.returns(
              T::Array[
                OpenAI::Chat::ChatCompletionStoreMessage::ContentPart::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
