# typed: strong

module OpenAI
  module Models

    ChatCompletionMessageCustomToolCall = Chat::ChatCompletionMessageCustomToolCall

    module Chat

      class ChatCompletionMessageCustomToolCall < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Chat::ChatCompletionMessageCustomToolCall,
            OpenAI::Internal::AnyHash
          )
        end

        # The ID of the tool call.
        sig { returns(String) }
        attr_accessor :id

        # The custom tool that the model called.
        sig { returns(OpenAI::Chat::ChatCompletionMessageCustomToolCall::Custom) }
        attr_reader :custom

        sig { params(custom: OpenAI::Chat::ChatCompletionMessageCustomToolCall::Custom::OrHash).void }
        attr_writer :custom

        # The type of the tool. Always `custom`.
        sig { returns(Symbol) }
        attr_accessor :type

        # A call to a custom tool created by the model.
        sig do
          params(

            id: String,

            custom: OpenAI::Chat::ChatCompletionMessageCustomToolCall::Custom::OrHash,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The ID of the tool call.
          id:,

          # The custom tool that the model called.
          custom:,

          # The type of the tool. Always `custom`.

          type: :custom
        )
        end

        sig do
          override.returns(
            {id: String, custom: OpenAI::Chat::ChatCompletionMessageCustomToolCall::Custom, type: Symbol}
          )
        end
        def to_hash
        end

        class Custom < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Chat::ChatCompletionMessageCustomToolCall::Custom,
              OpenAI::Internal::AnyHash
            )
          end

          # The input for the custom tool call generated by the model.
          sig { returns(String) }
          attr_accessor :input

          # The name of the custom tool to call.
          sig { returns(String) }
          attr_accessor :name

          # The custom tool that the model called.
          sig do
            params(

              input: String,

              name: String
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The input for the custom tool call generated by the model.
            input:,

            # The name of the custom tool to call.

            name:
          )
          end

          sig do
            override.returns(
              {input: String, name: String}
            )
          end
          def to_hash
          end

        end

      end

    end

  end
end
