module OpenAI
  module Resources
    class Graders
      attr_reader grader_models: OpenAI::Resources::Graders::GraderModels

      def initialize: (client: OpenAI::Internal::Transport::_RequestClient) -> void
    end
  end
end
