module OpenAI
  module Resources
    class Webhooks
      def unwrap: (
        String payload
      ) -> (OpenAI::Webhooks::BatchCancelledWebhookEvent
      | OpenAI::Webhooks::BatchCompletedWebhookEvent
      | OpenAI::Webhooks::BatchExpiredWebhookEvent
      | OpenAI::Webhooks::BatchFailedWebhookEvent
      | OpenAI::Webhooks::EvalRunCanceledWebhookEvent
      | OpenAI::Webhooks::EvalRunFailedWebhookEvent
      | OpenAI::Webhooks::EvalRunSucceededWebhookEvent
      | OpenAI::Webhooks::FineTuningJobCancelledWebhookEvent
      | OpenAI::Webhooks::FineTuningJobFailedWebhookEvent
      | OpenAI::Webhooks::FineTuningJobSucceededWebhookEvent
      | OpenAI::Webhooks::ResponseCancelledWebhookEvent
      | OpenAI::Webhooks::ResponseCompletedWebhookEvent
      | OpenAI::Webhooks::ResponseFailedWebhookEvent
      | OpenAI::Webhooks::ResponseIncompleteWebhookEvent)

      def initialize: (client: OpenAI::Client) -> void
    end
  end
end
