# typed: strong

module OpenAI
  module Models

    class ContentProvenanceCheck < OpenAI::Internal::Type::BaseModel

      OrHash = T.type_alias do
        T.any(
          OpenAI::ContentProvenanceCheck,
          OpenAI::Internal::AnyHash
        )
      end

      # The Unix timestamp, in seconds, when the provenance check was created.
      sig { returns(Integer) }
      attr_accessor :created_at

      # The object type. Always `content_provenance_check` for this endpoint.
      sig { returns(OpenAI::ContentProvenanceCheck::Object::TaggedSymbol) }
      attr_accessor :object

      # The provenance results that apply to the uploaded file. Image results include
      # C2PA and SynthID; audio results include SynthID.
      sig { returns(T::Array[OpenAI::ContentProvenanceCheck::Result::Variants]) }
      attr_accessor :results

      sig do
        params(

          created_at: Integer,

          object: OpenAI::ContentProvenanceCheck::Object::OrSymbol,

          results: T::Array[
            T.any(
              OpenAI::ContentProvenanceCheck::Result::C2PA::OrHash,
              OpenAI::ContentProvenanceCheck::Result::SynthID::OrHash
            )
          ]
        )
          .returns(T.attached_class)
      end
      def self.new(

        # The Unix timestamp, in seconds, when the provenance check was created.
        created_at:,

        # The object type. Always `content_provenance_check` for this endpoint.
        object:,

        # The provenance results that apply to the uploaded file. Image results include
        # C2PA and SynthID; audio results include SynthID.

        results:
      )
      end

      sig do
        override.returns(
          {
            created_at: Integer,
            object: OpenAI::ContentProvenanceCheck::Object::TaggedSymbol,
            results: T::Array[OpenAI::ContentProvenanceCheck::Result::Variants]
          }
        )
      end
      def to_hash
      end

      # The object type. Always `content_provenance_check` for this endpoint.
      module Object
        extend OpenAI::Internal::Type::Enum

        TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ContentProvenanceCheck::Object) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        CONTENT_PROVENANCE_CHECK = T.let(
          :content_provenance_check,
          OpenAI::ContentProvenanceCheck::Object::TaggedSymbol
        )

        sig { override.returns(T::Array[OpenAI::ContentProvenanceCheck::Object::TaggedSymbol]) }
        def self.values
        end
      end

      module Result
        extend OpenAI::Internal::Type::Union

        Variants = T.type_alias {
          T.any(OpenAI::ContentProvenanceCheck::Result::C2PA, OpenAI::ContentProvenanceCheck::Result::SynthID)
        }

        class C2PA < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::ContentProvenanceCheck::Result::C2PA,
              OpenAI::Internal::AnyHash
            )
          end

          # The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
          # was generated, when available.
          sig { returns(T.nilable(String)) }
          attr_accessor :generated_at

          # The C2PA manifest issuer, when available.
          sig { returns(T.nilable(String)) }
          attr_accessor :issuer

          # The OpenAI model recorded by the provenance signal, when available.
          sig { returns(T.nilable(String)) }
          attr_accessor :model

          # Whether a supported OpenAI C2PA provenance signal was detected. If
          # `not_detected`, it means the tool did not find supported signals in the uploaded
          # file. The content could still have been generated by OpenAI if the metadata was
          # stripped or has evidence of tampering, the watermark was degraded, it comes from
          # a legacy generation model, or it was created before provenance signals were
          # available. Content could also still be AI-generated by another company's model,
          # which the tool currently does not detect.
          sig { returns(OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome::TaggedSymbol) }
          attr_accessor :outcome

          # The provenance signal type. Always `c2pa`.
          sig { returns(Symbol) }
          attr_accessor :type

          # The validation status of the C2PA manifest in the uploaded image.
          sig { returns(OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::TaggedSymbol) }
          attr_accessor :validation_state

          sig do
            params(

              generated_at: T.nilable(String),

              issuer: T.nilable(String),

              model: T.nilable(String),

              outcome: OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome::OrSymbol,

              validation_state: OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::OrSymbol,

              type: Symbol
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
            # was generated, when available.
            generated_at:,

            # The C2PA manifest issuer, when available.
            issuer:,

            # The OpenAI model recorded by the provenance signal, when available.
            model:,

            # Whether a supported OpenAI C2PA provenance signal was detected. If
            # `not_detected`, it means the tool did not find supported signals in the uploaded
            # file. The content could still have been generated by OpenAI if the metadata was
            # stripped or has evidence of tampering, the watermark was degraded, it comes from
            # a legacy generation model, or it was created before provenance signals were
            # available. Content could also still be AI-generated by another company's model,
            # which the tool currently does not detect.
            outcome:,

            # The validation status of the C2PA manifest in the uploaded image.
            validation_state:,

            # The provenance signal type. Always `c2pa`.

            type: :c2pa
          )
          end

          sig do
            override.returns(
              {
                generated_at: T.nilable(String),
                issuer: T.nilable(String),
                model: T.nilable(String),
                outcome: OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome::TaggedSymbol,
                type: Symbol,
                validation_state: OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::TaggedSymbol
              }
            )
          end
          def to_hash
          end

          # Whether a supported OpenAI C2PA provenance signal was detected. If
          # `not_detected`, it means the tool did not find supported signals in the uploaded
          # file. The content could still have been generated by OpenAI if the metadata was
          # stripped or has evidence of tampering, the watermark was degraded, it comes from
          # a legacy generation model, or it was created before provenance signals were
          # available. Content could also still be AI-generated by another company's model,
          # which the tool currently does not detect.
          module Outcome
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome) }
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            DETECTED = T.let(:detected, OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome::TaggedSymbol)
            NOT_DETECTED = T.let(:not_detected, OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome::TaggedSymbol)

            sig { override.returns(T::Array[OpenAI::ContentProvenanceCheck::Result::C2PA::Outcome::TaggedSymbol]) }
            def self.values
            end
          end

          # The validation status of the C2PA manifest in the uploaded image.
          module ValidationState
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol = T.type_alias {
              T.all(Symbol, OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState)
            }
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            TRUSTED = T.let(:trusted, OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::TaggedSymbol)
            VALID = T.let(:valid, OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::TaggedSymbol)
            INVALID = T.let(:invalid, OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::TaggedSymbol)
            NOT_PRESENT = T.let(
              :not_present,
              OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::TaggedSymbol
            )

            sig {
              override.returns(T::Array[OpenAI::ContentProvenanceCheck::Result::C2PA::ValidationState::TaggedSymbol])
            }
            def self.values
            end
          end
        end

        class SynthID < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::ContentProvenanceCheck::Result::SynthID,
              OpenAI::Internal::AnyHash
            )
          end

          # The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
          # was generated, when available.
          sig { returns(T.nilable(String)) }
          attr_accessor :generated_at

          # The OpenAI model recorded by the provenance signal, when available.
          sig { returns(T.nilable(String)) }
          attr_accessor :model

          # Whether a supported OpenAI SynthID watermark was detected. If `not_detected`, it
          # means the tool did not find supported signals in the uploaded file. The content
          # could still have been generated by OpenAI if the metadata was stripped or has
          # evidence of tampering, the watermark was degraded, it comes from a legacy
          # generation model, or it was created before provenance signals were available.
          # Content could also still be AI-generated by another company's model, which the
          # tool currently does not detect.
          sig { returns(OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome::TaggedSymbol) }
          attr_accessor :outcome

          # The provenance signal type. Always `synthid`.
          sig { returns(Symbol) }
          attr_accessor :type

          sig do
            params(

              generated_at: T.nilable(String),

              model: T.nilable(String),

              outcome: OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome::OrSymbol,

              type: Symbol
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The UTC RFC 3339 timestamp recorded by the provenance signal for when the asset
            # was generated, when available.
            generated_at:,

            # The OpenAI model recorded by the provenance signal, when available.
            model:,

            # Whether a supported OpenAI SynthID watermark was detected. If `not_detected`, it
            # means the tool did not find supported signals in the uploaded file. The content
            # could still have been generated by OpenAI if the metadata was stripped or has
            # evidence of tampering, the watermark was degraded, it comes from a legacy
            # generation model, or it was created before provenance signals were available.
            # Content could also still be AI-generated by another company's model, which the
            # tool currently does not detect.
            outcome:,

            # The provenance signal type. Always `synthid`.

            type: :synthid
          )
          end

          sig do
            override.returns(
              {
                generated_at: T.nilable(String),
                model: T.nilable(String),
                outcome: OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome::TaggedSymbol,
                type: Symbol
              }
            )
          end
          def to_hash
          end

          # Whether a supported OpenAI SynthID watermark was detected. If `not_detected`, it
          # means the tool did not find supported signals in the uploaded file. The content
          # could still have been generated by OpenAI if the metadata was stripped or has
          # evidence of tampering, the watermark was degraded, it comes from a legacy
          # generation model, or it was created before provenance signals were available.
          # Content could also still be AI-generated by another company's model, which the
          # tool currently does not detect.
          module Outcome
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome) }
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            DETECTED = T.let(:detected, OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome::TaggedSymbol)
            NOT_DETECTED = T.let(:not_detected, OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome::TaggedSymbol)

            sig { override.returns(T::Array[OpenAI::ContentProvenanceCheck::Result::SynthID::Outcome::TaggedSymbol]) }
            def self.values
            end
          end
        end

        sig { override.returns(T::Array[OpenAI::ContentProvenanceCheck::Result::Variants]) }
        def self.variants
        end

      end

    end

  end
end
