# typed: strong

module OpenAI
  module Models

    class Image < OpenAI::Internal::Type::BaseModel

      OrHash = T.type_alias do
        T.any(
          OpenAI::Image,
          OpenAI::Internal::AnyHash
        )
      end

      # The base64-encoded JSON of the generated image. Returned by default for GPT
      # image models, or when `response_format` is set to `b64_json` for models that
      # support that parameter.
      sig { returns(T.nilable(String)) }
      attr_reader :b64_json

      sig { params(b64_json: String).void }
      attr_writer :b64_json

      # The revised prompt used to generate the image, for models that support prompt
      # revision. Not returned by GPT image models.
      sig { returns(T.nilable(String)) }
      attr_reader :revised_prompt

      sig { params(revised_prompt: String).void }
      attr_writer :revised_prompt

      # The URL of the generated image when `response_format` is set to `url` for models
      # that support that parameter. Unsupported for GPT image models.
      sig { returns(T.nilable(String)) }
      attr_reader :url

      sig { params(url: String).void }
      attr_writer :url

      # Represents the content or the URL of an image generated by the OpenAI API.
      sig do
        params(

          b64_json: String,

          revised_prompt: String,

          url: String
        )
          .returns(T.attached_class)
      end
      def self.new(

        # The base64-encoded JSON of the generated image. Returned by default for GPT
        # image models, or when `response_format` is set to `b64_json` for models that
        # support that parameter.
        b64_json: nil,

        # The revised prompt used to generate the image, for models that support prompt
        # revision. Not returned by GPT image models.
        revised_prompt: nil,

        # The URL of the generated image when `response_format` is set to `url` for models
        # that support that parameter. Unsupported for GPT image models.

        url: nil
      )
      end

      sig do
        override.returns(
          {b64_json: String, revised_prompt: String, url: String}
        )
      end
      def to_hash
      end

    end

  end
end
