# typed: strong

module OpenAI
  module Models

    class Image < OpenAI::Internal::Type::BaseModel

      OrHash = T.type_alias do
        T.any(
          OpenAI::Image,
          OpenAI::Internal::AnyHash
        )
      end

      # The base64-encoded image data. Returned by default for the GPT image models. For
      # the retired `dall-e-2` and `dall-e-3` models, this field was present only when
      # `response_format` was set to `b64_json`.
      sig { returns(T.nilable(String)) }
      attr_reader :b64_json

      sig { params(b64_json: String).void }
      attr_writer :b64_json

      # Legacy field for the retired `dall-e-3` model: the revised prompt that was used
      # to generate the image.
      sig { returns(T.nilable(String)) }
      attr_reader :revised_prompt

      sig { params(revised_prompt: String).void }
      attr_writer :revised_prompt

      # Legacy field for the retired `dall-e-2` and `dall-e-3` models: the URL of the
      # generated image when `response_format` was set to `url`, the legacy default.
      # Unsupported for the GPT image models.
      sig { returns(T.nilable(String)) }
      attr_reader :url

      sig { params(url: String).void }
      attr_writer :url

      # Represents the content or the URL of an image generated by the OpenAI API.
      sig do
        params(

          b64_json: String,

          revised_prompt: String,

          url: String
        )
          .returns(T.attached_class)
      end
      def self.new(

        # The base64-encoded image data. Returned by default for the GPT image models. For
        # the retired `dall-e-2` and `dall-e-3` models, this field was present only when
        # `response_format` was set to `b64_json`.
        b64_json: nil,

        # Legacy field for the retired `dall-e-3` model: the revised prompt that was used
        # to generate the image.
        revised_prompt: nil,

        # Legacy field for the retired `dall-e-2` and `dall-e-3` models: the URL of the
        # generated image when `response_format` was set to `url`, the legacy default.
        # Unsupported for the GPT image models.

        url: nil
      )
      end

      sig do
        override.returns(
          {b64_json: String, revised_prompt: String, url: String}
        )
      end
      def to_hash
      end

    end

  end
end
