# typed: strong

module OpenAI
  module Models

    class ImageGenerateParams < OpenAI::Internal::Type::BaseModel

      extend OpenAI::Internal::Type::RequestParameters::Converter
      include OpenAI::Internal::Type::RequestParameters

      OrHash = T.type_alias do
        T.any(
          OpenAI::ImageGenerateParams,
          OpenAI::Internal::AnyHash
        )
      end

      # A text description of the desired image(s). The maximum length is 32000
      # characters for the GPT image models. Legacy limits for the retired models were
      # 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
      sig { returns(String) }
      attr_accessor :prompt

      # Allows to set transparency for the background of the generated image(s). Must be
      # one of `transparent`, `opaque`, or `auto` (default value). When `auto` is used,
      # the model will automatically determine the best background for the image.
      #
      # `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their `2026-09-08`
      # snapshots, support `opaque` and `transparent` backgrounds. Transparent
      # backgrounds are available for supported GPT Image models. For `gpt-image-2` and
      # `gpt-image-2-2026-04-21`, this support is in preview. When using `transparent`,
      # set the output format to `png` or `webp`.
      sig { returns(T.nilable(OpenAI::ImageGenerateParams::Background::OrSymbol)) }
      attr_accessor :background

      # The GPT Image model to use for image generation. Specify a supported model
      # explicitly, such as `gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`,
      # `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`,
      # `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, or
      # `gpt-image-2.5-flare-2026-09-08`. DALL·E 2 (`dall-e-2`) and DALL·E 3
      # (`dall-e-3`) were retired from the API on May 12, 2026; see
      # [deprecations](https://developers.openai.com/api/docs/deprecations).
      sig { returns(T.nilable(T.any(String, OpenAI::ImageModel::OrSymbol))) }
      attr_accessor :model

      # Control the content-moderation level for images generated by the GPT image
      # models. Must be either `low` for less restrictive filtering or `auto` (default
      # value).
      sig { returns(T.nilable(OpenAI::ImageGenerateParams::Moderation::OrSymbol)) }
      attr_accessor :moderation

      # The number of images to generate. Must be between 1 and 10. The retired
      # `dall-e-3` model only supported `n=1`.
      sig { returns(T.nilable(Integer)) }
      attr_accessor :n

      # The compression level (0-100%) for the generated images. This parameter is only
      # supported for the GPT image models with the `webp` or `jpeg` output formats, and
      # defaults to 100.
      sig { returns(T.nilable(Integer)) }
      attr_accessor :output_compression

      # The format in which the generated images are returned. This parameter is only
      # supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
      sig { returns(T.nilable(OpenAI::ImageGenerateParams::OutputFormat::OrSymbol)) }
      attr_accessor :output_format

      # The number of partial images to generate. This parameter is used for streaming
      # responses that return partial images. Value must be between 0 and 3. When set to
      # 0, the response will be a single image sent in one streaming event.
      #
      # Note that the final image may be sent before the full number of partial images
      # are generated if the full image is generated more quickly.
      sig { returns(T.nilable(Integer)) }
      attr_accessor :partial_images

      # The quality of the image that will be generated.
      #
      # - `auto` (default value) will automatically select the best quality for the
      #   given model.
      # - `high`, `medium` and `low` are supported for the GPT image models.
      # - `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their
      #   `2026-09-08` snapshots, also support `xhigh` and `max`.
      # - The retired `dall-e-3` model supported the legacy values `hd` and `standard`.
      # - The retired `dall-e-2` model only supported the legacy value `standard`.
      sig { returns(T.nilable(OpenAI::ImageGenerateParams::Quality::OrSymbol)) }
      attr_accessor :quality

      # Legacy response format: `url` or `b64_json`, for the retired `dall-e-2` and
      # `dall-e-3` models. Returned URLs were valid for 60 minutes after image
      # generation. This parameter is not supported for the GPT image models, which
      # always return base64-encoded images.
      sig { returns(T.nilable(OpenAI::ImageGenerateParams::ResponseFormat::OrSymbol)) }
      attr_accessor :response_format

      # The size of the generated images. For `gpt-image-2`, `gpt-image-2-2026-04-21`,
      # `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`,
      # `gpt-image-2.5-flare`, and `gpt-image-2.5-flare-2026-09-08`, arbitrary
      # resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`.
      # Width and height must both be divisible by 16 and the requested aspect ratio
      # must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and
      # the maximum supported resolution is `3840x2160`. The requested size must also
      # satisfy the model's current pixel and edge limits. The standard sizes
      # `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models;
      # `auto` is supported for models that allow automatic sizing. Legacy sizes for the
      # retired `dall-e-2` model were `256x256`, `512x512`, and `1024x1024`. Legacy
      # sizes for the retired `dall-e-3` model were `1024x1024`, `1792x1024`, and
      # `1024x1792`.
      sig { returns(T.nilable(T.any(String, OpenAI::ImageGenerateParams::Size::OrSymbol))) }
      attr_accessor :size

      # Legacy style options `vivid` and `natural` for the retired `dall-e-3` model.
      # Vivid produced hyper-real and dramatic images; natural produced more natural,
      # less hyper-real looking images. This parameter is not supported for the GPT
      # image models.
      sig { returns(T.nilable(OpenAI::ImageGenerateParams::Style::OrSymbol)) }
      attr_accessor :style

      # A unique identifier representing your end-user, which can help OpenAI to monitor
      # and detect abuse.
      # [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers).
      sig { returns(T.nilable(String)) }
      attr_reader :user

      sig { params(user: String).void }
      attr_writer :user

      sig do
        params(

          prompt: String,

          background: T.nilable(OpenAI::ImageGenerateParams::Background::OrSymbol),

          model: T.nilable(T.any(String, OpenAI::ImageModel::OrSymbol)),

          moderation: T.nilable(OpenAI::ImageGenerateParams::Moderation::OrSymbol),

          n: T.nilable(Integer),

          output_compression: T.nilable(Integer),

          output_format: T.nilable(OpenAI::ImageGenerateParams::OutputFormat::OrSymbol),

          partial_images: T.nilable(Integer),

          quality: T.nilable(OpenAI::ImageGenerateParams::Quality::OrSymbol),

          response_format: T.nilable(OpenAI::ImageGenerateParams::ResponseFormat::OrSymbol),

          size: T.nilable(T.any(String, OpenAI::ImageGenerateParams::Size::OrSymbol)),

          style: T.nilable(OpenAI::ImageGenerateParams::Style::OrSymbol),

          user: String,

          request_options: OpenAI::RequestOptions::OrHash
        )
          .returns(T.attached_class)
      end
      def self.new(

        # A text description of the desired image(s). The maximum length is 32000
        # characters for the GPT image models. Legacy limits for the retired models were
        # 1000 characters for `dall-e-2` and 4000 characters for `dall-e-3`.
        prompt:,

        # Allows to set transparency for the background of the generated image(s). Must be
        # one of `transparent`, `opaque`, or `auto` (default value). When `auto` is used,
        # the model will automatically determine the best background for the image.
        #
        # `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their `2026-09-08`
        # snapshots, support `opaque` and `transparent` backgrounds. Transparent
        # backgrounds are available for supported GPT Image models. For `gpt-image-2` and
        # `gpt-image-2-2026-04-21`, this support is in preview. When using `transparent`,
        # set the output format to `png` or `webp`.
        background: nil,

        # The GPT Image model to use for image generation. Specify a supported model
        # explicitly, such as `gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`,
        # `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`,
        # `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, or
        # `gpt-image-2.5-flare-2026-09-08`. DALL·E 2 (`dall-e-2`) and DALL·E 3
        # (`dall-e-3`) were retired from the API on May 12, 2026; see
        # [deprecations](https://developers.openai.com/api/docs/deprecations).
        model: nil,

        # Control the content-moderation level for images generated by the GPT image
        # models. Must be either `low` for less restrictive filtering or `auto` (default
        # value).
        moderation: nil,

        # The number of images to generate. Must be between 1 and 10. The retired
        # `dall-e-3` model only supported `n=1`.
        n: nil,

        # The compression level (0-100%) for the generated images. This parameter is only
        # supported for the GPT image models with the `webp` or `jpeg` output formats, and
        # defaults to 100.
        output_compression: nil,

        # The format in which the generated images are returned. This parameter is only
        # supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
        output_format: nil,

        # The number of partial images to generate. This parameter is used for streaming
        # responses that return partial images. Value must be between 0 and 3. When set to
        # 0, the response will be a single image sent in one streaming event.
        #
        # Note that the final image may be sent before the full number of partial images
        # are generated if the full image is generated more quickly.
        partial_images: nil,

        # The quality of the image that will be generated.
        #
        # - `auto` (default value) will automatically select the best quality for the
        #   given model.
        # - `high`, `medium` and `low` are supported for the GPT image models.
        # - `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their
        #   `2026-09-08` snapshots, also support `xhigh` and `max`.
        # - The retired `dall-e-3` model supported the legacy values `hd` and `standard`.
        # - The retired `dall-e-2` model only supported the legacy value `standard`.
        quality: nil,

        # Legacy response format: `url` or `b64_json`, for the retired `dall-e-2` and
        # `dall-e-3` models. Returned URLs were valid for 60 minutes after image
        # generation. This parameter is not supported for the GPT image models, which
        # always return base64-encoded images.
        response_format: nil,

        # The size of the generated images. For `gpt-image-2`, `gpt-image-2-2026-04-21`,
        # `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`,
        # `gpt-image-2.5-flare`, and `gpt-image-2.5-flare-2026-09-08`, arbitrary
        # resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`.
        # Width and height must both be divisible by 16 and the requested aspect ratio
        # must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and
        # the maximum supported resolution is `3840x2160`. The requested size must also
        # satisfy the model's current pixel and edge limits. The standard sizes
        # `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models;
        # `auto` is supported for models that allow automatic sizing. Legacy sizes for the
        # retired `dall-e-2` model were `256x256`, `512x512`, and `1024x1024`. Legacy
        # sizes for the retired `dall-e-3` model were `1024x1024`, `1792x1024`, and
        # `1024x1792`.
        size: nil,

        # Legacy style options `vivid` and `natural` for the retired `dall-e-3` model.
        # Vivid produced hyper-real and dramatic images; natural produced more natural,
        # less hyper-real looking images. This parameter is not supported for the GPT
        # image models.
        style: nil,

        # A unique identifier representing your end-user, which can help OpenAI to monitor
        # and detect abuse.
        # [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers).
        user: nil,

        request_options: {}
      )
      end

      sig do
        override.returns(
          {
            prompt: String,
            background: T.nilable(OpenAI::ImageGenerateParams::Background::OrSymbol),
            model: T.nilable(T.any(String, OpenAI::ImageModel::OrSymbol)),
            moderation: T.nilable(OpenAI::ImageGenerateParams::Moderation::OrSymbol),
            n: T.nilable(Integer),
            output_compression: T.nilable(Integer),
            output_format: T.nilable(OpenAI::ImageGenerateParams::OutputFormat::OrSymbol),
            partial_images: T.nilable(Integer),
            quality: T.nilable(OpenAI::ImageGenerateParams::Quality::OrSymbol),
            response_format: T.nilable(OpenAI::ImageGenerateParams::ResponseFormat::OrSymbol),
            size: T.nilable(T.any(String, OpenAI::ImageGenerateParams::Size::OrSymbol)),
            style: T.nilable(OpenAI::ImageGenerateParams::Style::OrSymbol),
            user: String,
            request_options: OpenAI::RequestOptions
          }
        )
      end
      def to_hash
      end

      # Allows to set transparency for the background of the generated image(s). Must be
      # one of `transparent`, `opaque`, or `auto` (default value). When `auto` is used,
      # the model will automatically determine the best background for the image.
      #
      # `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their `2026-09-08`
      # snapshots, support `opaque` and `transparent` backgrounds. Transparent
      # backgrounds are available for supported GPT Image models. For `gpt-image-2` and
      # `gpt-image-2-2026-04-21`, this support is in preview. When using `transparent`,
      # set the output format to `png` or `webp`.
      module Background
        extend OpenAI::Internal::Type::Enum

        TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ImageGenerateParams::Background) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        TRANSPARENT = T.let(:transparent, OpenAI::ImageGenerateParams::Background::TaggedSymbol)
        OPAQUE = T.let(:opaque, OpenAI::ImageGenerateParams::Background::TaggedSymbol)
        AUTO = T.let(:auto, OpenAI::ImageGenerateParams::Background::TaggedSymbol)

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::Background::TaggedSymbol]) }
        def self.values
        end
      end

      # The GPT Image model to use for image generation. Specify a supported model
      # explicitly, such as `gpt-image-1`, `gpt-image-1-mini`, `gpt-image-1.5`,
      # `gpt-image-2`, `gpt-image-2-2026-04-21`, `gpt-image-2.5-sunburst`,
      # `gpt-image-2.5-sunburst-2026-09-08`, `gpt-image-2.5-flare`, or
      # `gpt-image-2.5-flare-2026-09-08`. DALL·E 2 (`dall-e-2`) and DALL·E 3
      # (`dall-e-3`) were retired from the API on May 12, 2026; see
      # [deprecations](https://developers.openai.com/api/docs/deprecations).
      module Model
        extend OpenAI::Internal::Type::Union

        Variants = T.type_alias { T.any(String, OpenAI::ImageModel::TaggedSymbol) }

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::Model::Variants]) }
        def self.variants
        end

      end

      # Control the content-moderation level for images generated by the GPT image
      # models. Must be either `low` for less restrictive filtering or `auto` (default
      # value).
      module Moderation
        extend OpenAI::Internal::Type::Enum

        TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ImageGenerateParams::Moderation) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        LOW = T.let(:low, OpenAI::ImageGenerateParams::Moderation::TaggedSymbol)
        AUTO = T.let(:auto, OpenAI::ImageGenerateParams::Moderation::TaggedSymbol)

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::Moderation::TaggedSymbol]) }
        def self.values
        end
      end

      # The format in which the generated images are returned. This parameter is only
      # supported for the GPT image models. Must be one of `png`, `jpeg`, or `webp`.
      module OutputFormat
        extend OpenAI::Internal::Type::Enum

        TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ImageGenerateParams::OutputFormat) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        PNG = T.let(:png, OpenAI::ImageGenerateParams::OutputFormat::TaggedSymbol)
        JPEG = T.let(:jpeg, OpenAI::ImageGenerateParams::OutputFormat::TaggedSymbol)
        WEBP = T.let(:webp, OpenAI::ImageGenerateParams::OutputFormat::TaggedSymbol)

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::OutputFormat::TaggedSymbol]) }
        def self.values
        end
      end

      # The quality of the image that will be generated.
      #
      # - `auto` (default value) will automatically select the best quality for the
      #   given model.
      # - `high`, `medium` and `low` are supported for the GPT image models.
      # - `gpt-image-2.5-sunburst` and `gpt-image-2.5-flare`, including their
      #   `2026-09-08` snapshots, also support `xhigh` and `max`.
      # - The retired `dall-e-3` model supported the legacy values `hd` and `standard`.
      # - The retired `dall-e-2` model only supported the legacy value `standard`.
      module Quality
        extend OpenAI::Internal::Type::Enum

        TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ImageGenerateParams::Quality) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        STANDARD = T.let(:standard, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)
        HD = T.let(:hd, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)
        LOW = T.let(:low, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)
        MEDIUM = T.let(:medium, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)
        HIGH = T.let(:high, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)
        XHIGH = T.let(:xhigh, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)
        MAX = T.let(:max, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)
        AUTO = T.let(:auto, OpenAI::ImageGenerateParams::Quality::TaggedSymbol)

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::Quality::TaggedSymbol]) }
        def self.values
        end
      end

      # Legacy response format: `url` or `b64_json`, for the retired `dall-e-2` and
      # `dall-e-3` models. Returned URLs were valid for 60 minutes after image
      # generation. This parameter is not supported for the GPT image models, which
      # always return base64-encoded images.
      module ResponseFormat
        extend OpenAI::Internal::Type::Enum

        TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ImageGenerateParams::ResponseFormat) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        URL = T.let(:url, OpenAI::ImageGenerateParams::ResponseFormat::TaggedSymbol)
        B64_JSON = T.let(:b64_json, OpenAI::ImageGenerateParams::ResponseFormat::TaggedSymbol)

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::ResponseFormat::TaggedSymbol]) }
        def self.values
        end
      end

      # The size of the generated images. For `gpt-image-2`, `gpt-image-2-2026-04-21`,
      # `gpt-image-2.5-sunburst`, `gpt-image-2.5-sunburst-2026-09-08`,
      # `gpt-image-2.5-flare`, and `gpt-image-2.5-flare-2026-09-08`, arbitrary
      # resolutions are supported as `WIDTHxHEIGHT` strings, for example `1536x864`.
      # Width and height must both be divisible by 16 and the requested aspect ratio
      # must be between 1:3 and 3:1. Resolutions above `2560x1440` are experimental, and
      # the maximum supported resolution is `3840x2160`. The requested size must also
      # satisfy the model's current pixel and edge limits. The standard sizes
      # `1024x1024`, `1536x1024`, and `1024x1536` are supported by the GPT image models;
      # `auto` is supported for models that allow automatic sizing. Legacy sizes for the
      # retired `dall-e-2` model were `256x256`, `512x512`, and `1024x1024`. Legacy
      # sizes for the retired `dall-e-3` model were `1024x1024`, `1792x1024`, and
      # `1024x1792`.
      module Size
        extend OpenAI::Internal::Type::Union

        Variants = T.type_alias { T.any(String, OpenAI::ImageGenerateParams::Size::TaggedSymbol) }

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::Size::Variants]) }
        def self.variants
        end

        TaggedSymbol = T.type_alias do
          T.all(Symbol, OpenAI::ImageGenerateParams::Size)
        end

        OrSymbol = T.type_alias { T.any(Symbol, String) }

        AUTO = T.let(:auto, OpenAI::ImageGenerateParams::Size::TaggedSymbol)
        SIZE_1024X1024 = T.let(:"1024x1024", OpenAI::ImageGenerateParams::Size::TaggedSymbol)
        SIZE_1536X1024 = T.let(:"1536x1024", OpenAI::ImageGenerateParams::Size::TaggedSymbol)
        SIZE_1024X1536 = T.let(:"1024x1536", OpenAI::ImageGenerateParams::Size::TaggedSymbol)
        SIZE_256X256 = T.let(:"256x256", OpenAI::ImageGenerateParams::Size::TaggedSymbol)
        SIZE_512X512 = T.let(:"512x512", OpenAI::ImageGenerateParams::Size::TaggedSymbol)
        SIZE_1792X1024 = T.let(:"1792x1024", OpenAI::ImageGenerateParams::Size::TaggedSymbol)
        SIZE_1024X1792 = T.let(:"1024x1792", OpenAI::ImageGenerateParams::Size::TaggedSymbol)

      end

      # Legacy style options `vivid` and `natural` for the retired `dall-e-3` model.
      # Vivid produced hyper-real and dramatic images; natural produced more natural,
      # less hyper-real looking images. This parameter is not supported for the GPT
      # image models.
      module Style
        extend OpenAI::Internal::Type::Enum

        TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::ImageGenerateParams::Style) }
        OrSymbol = T.type_alias { T.any(Symbol, String) }

        VIVID = T.let(:vivid, OpenAI::ImageGenerateParams::Style::TaggedSymbol)
        NATURAL = T.let(:natural, OpenAI::ImageGenerateParams::Style::TaggedSymbol)

        sig { override.returns(T::Array[OpenAI::ImageGenerateParams::Style::TaggedSymbol]) }
        def self.values
        end
      end

    end

  end
end
