module OpenAI
  module Models
    module Uploads
      type part_create_params =
        { data: (Pathname | StringIO | IO | OpenAI::FilePart) }
        & OpenAI::Internal::Type::request_parameters

      class PartCreateParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor data: Pathname | StringIO | IO | OpenAI::FilePart

        def initialize: (
          data: Pathname | StringIO | IO | OpenAI::FilePart,
          ?request_options: OpenAI::request_opts
        ) -> void
      end
    end
  end
end
