module OpenAI
  module Models
    module Uploads
      type part_create_params =
        { data: (IO | StringIO) } & OpenAI::Internal::Type::request_parameters

      class PartCreateParams < OpenAI::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor data: IO | StringIO

        def initialize: (
          data: IO | StringIO,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> OpenAI::Models::Uploads::part_create_params
      end
    end
  end
end
