# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseCustomToolCallItem < OpenAI::Models::Responses::ResponseCustomToolCall
        # @!attribute id
        #   The unique ID of the custom tool call item.
        #
        #   @return [String]
        required :id, String

        # @!attribute status
        #   The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        #   Populated when items are returned via API.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseCustomToolCallItem::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseCustomToolCallItem::Status }

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(call_id:, input:, name:, id:, status:, caller_: nil, namespace: nil, created_by: nil, type: :custom_tool_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseCustomToolCallItem} for more details.
        #
        #   A call to a custom tool created by the model.
        #
        #   @param call_id [String] An identifier used to map this custom tool call to a tool call output.
        #
        #   @param input [String] The input for the custom tool call generated by the model.
        #
        #   @param name [String] The name of the custom tool being called.
        #
        #   @param id [String] The unique ID of the custom tool call item.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseCustomToolCallItem::Status] The status of the item. One of `in_progress`, `completed`, or
        #
        #   @param caller_ [OpenAI::Models::Responses::ResponseCustomToolCall::Caller::Direct, OpenAI::Models::Responses::ResponseCustomToolCall::Caller::Program, nil] The execution context that produced this tool call.
        #
        #   @param namespace [String] The namespace of the custom tool being called.
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :custom_tool_call] The type of the custom tool call. Always `custom_tool_call`.

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
