# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseApplyPatchToolCallOutput < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the apply patch tool call output. Populated when this item is
        #   returned via API.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the apply patch tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute status
        #   The status of the apply patch tool call output. One of `completed` or `failed`.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status }

        # @!attribute type
        #   The type of the item. Always `apply_patch_call_output`.
        #
        #   @return [Symbol, :apply_patch_call_output]
        required :type, const: :apply_patch_call_output

        # @!attribute created_by
        #   The ID of the entity that created this tool call output.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!attribute output
        #   Optional textual output returned by the apply patch tool.
        #
        #   @return [String, nil]
        optional :output, String, nil?: true

        # @!method initialize(id:, call_id:, status:, created_by: nil, output: nil, type: :apply_patch_call_output)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput} for more details.
        #
        #   The output emitted by an apply patch tool call.
        #
        #   @param id [String] The unique ID of the apply patch tool call output. Populated when this item is r
        #
        #   @param call_id [String] The unique ID of the apply patch tool call generated by the model.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput::Status] The status of the apply patch tool call output. One of `completed` or `failed`.
        #
        #   @param created_by [String] The ID of the entity that created this tool call output.
        #
        #   @param output [String, nil] Optional textual output returned by the apply patch tool.
        #
        #   @param type [Symbol, :apply_patch_call_output] The type of the item. Always `apply_patch_call_output`.

        # The status of the apply patch tool call output. One of `completed` or `failed`.
        #
        # @see OpenAI::Models::Responses::ResponseApplyPatchToolCallOutput#status
        module Status
          extend OpenAI::Internal::Type::Enum

          COMPLETED = :completed
          FAILED = :failed

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
