# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseCustomToolCallOutputItem < OpenAI::Models::Responses::ResponseCustomToolCallOutput
        # @!attribute id
        #   The unique ID of the custom tool call output item.
        #
        #   @return [String]
        required :id, String

        # @!attribute status
        #   The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        #   Populated when items are returned via API.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseCustomToolCallOutputItem::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseCustomToolCallOutputItem::Status }

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(call_id:, output:, id:, status:, caller_: nil, created_by: nil, type: :custom_tool_call_output)
        #   The output of a custom tool call from your code, being sent back to the model.
        #
        #   @param call_id [String]
        #     The call ID, used to map this custom tool call output to a custom tool call.
        #
        #   @param output [String, Array<OpenAI::Models::Responses::ResponseInputText, OpenAI::Models::Responses::ResponseInputImage, OpenAI::Models::Responses::ResponseInputFile>]
        #     The output from the custom tool call generated by your code. Can be a string or
        #     an list of output content.
        #
        #   @param id [String]
        #     The unique ID of the custom tool call output item.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseCustomToolCallOutputItem::Status]
        #     The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        #     Populated when items are returned via API.
        #
        #   @param caller_ [OpenAI::Models::Responses::ResponseCustomToolCallOutput::Caller::Direct, OpenAI::Models::Responses::ResponseCustomToolCallOutput::Caller::Program, nil]
        #     The execution context that produced this tool call.
        #
        #   @param created_by [String]
        #     The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :custom_tool_call_output]
        #     The type of the custom tool call output. Always `custom_tool_call_output`.

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
