# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseCompactionItemParam < OpenAI::Internal::Type::BaseModel
        # @!attribute encrypted_content
        #
        #   @return [String]
        required :encrypted_content, String

        # @!attribute type
        #   The type of the item. Always `compaction`.
        #
        #   @return [Symbol, :compaction]
        required :type, const: :compaction

        # @!attribute id
        #   The ID of the compaction item.
        #
        #   @return [String, nil]
        optional :id, String, nil?: true

        # @!method initialize(encrypted_content:, id: nil, type: :compaction)
        #   A compaction item generated by the
        #   [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        #
        #   @param encrypted_content [String]
        #
        #   @param id [String, nil] The ID of the compaction item.
        #
        #   @param type [Symbol, :compaction] The type of the item. Always `compaction`.
      end
    end
  end
end
