# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseFunctionToolCallOutputItem < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the function call tool output.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the function tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute output
        #   The output from the function call generated by your code. Can be a string or an
        #   list of output content.
        #
        #   @return [String, Array<OpenAI::Models::Responses::ResponseInputText, OpenAI::Models::Responses::ResponseInputImage, OpenAI::Models::Responses::ResponseInputFile>]
        required :output, union: -> { OpenAI::Responses::ResponseFunctionToolCallOutputItem::Output }

        # @!attribute type
        #   The type of the function tool call output. Always `function_call_output`.
        #
        #   @return [Symbol, :function_call_output]
        required :type, const: :function_call_output

        # @!attribute status
        #   The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        #   Populated when items are returned via API.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem::Status, nil]
        optional :status, enum: -> { OpenAI::Responses::ResponseFunctionToolCallOutputItem::Status }

        # @!method initialize(id:, call_id:, output:, status: nil, type: :function_call_output)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem} for more
        #   details.
        #
        #   @param id [String] The unique ID of the function call tool output.
        #
        #   @param call_id [String] The unique ID of the function tool call generated by the model.
        #
        #   @param output [String, Array<OpenAI::Models::Responses::ResponseInputText, OpenAI::Models::Responses::ResponseInputImage, OpenAI::Models::Responses::ResponseInputFile>] The output from the function call generated by your code.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem::Status] The status of the item. One of `in_progress`, `completed`, or
        #
        #   @param type [Symbol, :function_call_output] The type of the function tool call output. Always `function_call_output`.

        # The output from the function call generated by your code. Can be a string or an
        # list of output content.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem#output
        module Output
          extend OpenAI::Internal::Type::Union

          # A string of the output of the function call.
          variant String

          # Text, image, or file output of the function call.
          variant -> { OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem::Output::OutputContentListArray }

          # A text input to the model.
          module OutputContentList
            extend OpenAI::Internal::Type::Union

            discriminator :type

            # A text input to the model.
            variant :input_text, -> { OpenAI::Responses::ResponseInputText }

            # An image input to the model. Learn about [image inputs](https://platform.openai.com/docs/guides/vision).
            variant :input_image, -> { OpenAI::Responses::ResponseInputImage }

            # A file input to the model.
            variant :input_file, -> { OpenAI::Responses::ResponseInputFile }

            # @!method self.variants
            #   @return [Array(OpenAI::Models::Responses::ResponseInputText, OpenAI::Models::Responses::ResponseInputImage, OpenAI::Models::Responses::ResponseInputFile)]
          end

          # @!method self.variants
          #   @return [Array(String, Array<OpenAI::Models::Responses::ResponseInputText, OpenAI::Models::Responses::ResponseInputImage, OpenAI::Models::Responses::ResponseInputFile>)]

          # @type [OpenAI::Internal::Type::Converter]
          OutputContentListArray =
            OpenAI::Internal::Type::ArrayOf[union: -> {
              OpenAI::Responses::ResponseFunctionToolCallOutputItem::Output::OutputContentList
            }]
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
