# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseFunctionShellToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the function shell tool call. Populated when this item is
        #   returned via API.
        #
        #   @return [String]
        required :id, String

        # @!attribute action
        #   The shell commands and limits that describe how to run the tool call.
        #
        #   @return [OpenAI::Models::Responses::ResponseFunctionShellToolCall::Action]
        required :action, -> { OpenAI::Responses::ResponseFunctionShellToolCall::Action }

        # @!attribute call_id
        #   The unique ID of the function shell tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute status
        #   The status of the shell call. One of `in_progress`, `completed`, or
        #   `incomplete`.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseFunctionShellToolCall::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseFunctionShellToolCall::Status }

        # @!attribute type
        #   The type of the item. Always `shell_call`.
        #
        #   @return [Symbol, :shell_call]
        required :type, const: :shell_call

        # @!attribute created_by
        #   The ID of the entity that created this tool call.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, action:, call_id:, status:, created_by: nil, type: :shell_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseFunctionShellToolCall} for more details.
        #
        #   A tool call that executes one or more shell commands in a managed environment.
        #
        #   @param id [String] The unique ID of the function shell tool call. Populated when this item is retur
        #
        #   @param action [OpenAI::Models::Responses::ResponseFunctionShellToolCall::Action] The shell commands and limits that describe how to run the tool call.
        #
        #   @param call_id [String] The unique ID of the function shell tool call generated by the model.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseFunctionShellToolCall::Status] The status of the shell call. One of `in_progress`, `completed`, or `incomplete`
        #
        #   @param created_by [String] The ID of the entity that created this tool call.
        #
        #   @param type [Symbol, :shell_call] The type of the item. Always `shell_call`.

        # @see OpenAI::Models::Responses::ResponseFunctionShellToolCall#action
        class Action < OpenAI::Internal::Type::BaseModel
          # @!attribute commands
          #
          #   @return [Array<String>]
          required :commands, OpenAI::Internal::Type::ArrayOf[String]

          # @!attribute max_output_length
          #   Optional maximum number of characters to return from each command.
          #
          #   @return [Integer, nil]
          required :max_output_length, Integer, nil?: true

          # @!attribute timeout_ms
          #   Optional timeout in milliseconds for the commands.
          #
          #   @return [Integer, nil]
          required :timeout_ms, Integer, nil?: true

          # @!method initialize(commands:, max_output_length:, timeout_ms:)
          #   The shell commands and limits that describe how to run the tool call.
          #
          #   @param commands [Array<String>]
          #
          #   @param max_output_length [Integer, nil] Optional maximum number of characters to return from each command.
          #
          #   @param timeout_ms [Integer, nil] Optional timeout in milliseconds for the commands.
        end

        # The status of the shell call. One of `in_progress`, `completed`, or
        # `incomplete`.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionShellToolCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
