# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseCustomToolCallOutput < OpenAI::Internal::Type::BaseModel
        # @!attribute call_id
        #   The call ID, used to map this custom tool call output to a custom tool call.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute output
        #   The output from the custom tool call generated by your code.
        #
        #   @return [String]
        required :output, String

        # @!attribute type
        #   The type of the custom tool call output. Always `custom_tool_call_output`.
        #
        #   @return [Symbol, :custom_tool_call_output]
        required :type, const: :custom_tool_call_output

        # @!attribute id
        #   The unique ID of the custom tool call output in the OpenAI platform.
        #
        #   @return [String, nil]
        optional :id, String

        # @!method initialize(call_id:, output:, id: nil, type: :custom_tool_call_output)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseCustomToolCallOutput} for more details.
        #
        #   The output of a custom tool call from your code, being sent back to the model.
        #
        #   @param call_id [String] The call ID, used to map this custom tool call output to a custom tool call.
        #
        #   @param output [String] The output from the custom tool call generated by your code.
        #
        #   @param id [String] The unique ID of the custom tool call output in the OpenAI platform.
        #
        #   @param type [Symbol, :custom_tool_call_output] The type of the custom tool call output. Always `custom_tool_call_output`.
      end
    end
  end
end
