# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseFunctionShellToolCallOutput < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the shell call output. Populated when this item is returned via
        #   API.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the shell tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute max_output_length
        #   The maximum length of the shell command output. This is generated by the model
        #   and should be passed back with the raw output.
        #
        #   @return [Integer, nil]
        required :max_output_length, Integer, nil?: true

        # @!attribute output
        #   An array of shell call output contents
        #
        #   @return [Array<OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output>]
        required :output,
                 -> { OpenAI::Internal::Type::ArrayOf[OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output] }

        # @!attribute status
        #   The status of the shell call output. One of `in_progress`, `completed`, or
        #   `incomplete`.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status }

        # @!attribute type
        #   The type of the shell call output. Always `shell_call_output`.
        #
        #   @return [Symbol, :shell_call_output]
        required :type, const: :shell_call_output

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, call_id:, max_output_length:, output:, status:, created_by: nil, type: :shell_call_output)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput} for more
        #   details.
        #
        #   The output of a shell tool call that was emitted.
        #
        #   @param id [String] The unique ID of the shell call output. Populated when this item is returned via
        #
        #   @param call_id [String] The unique ID of the shell tool call generated by the model.
        #
        #   @param max_output_length [Integer, nil] The maximum length of the shell command output. This is generated by the model a
        #
        #   @param output [Array<OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output>] An array of shell call output contents
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Status] The status of the shell call output. One of `in_progress`, `completed`, or `inco
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :shell_call_output] The type of the shell call output. Always `shell_call_output`.

        class Output < OpenAI::Internal::Type::BaseModel
          # @!attribute outcome
          #   Represents either an exit outcome (with an exit code) or a timeout outcome for a
          #   shell call output chunk.
          #
          #   @return [OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout, OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit]
          required :outcome, union: -> { OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome }

          # @!attribute stderr
          #   The standard error output that was captured.
          #
          #   @return [String]
          required :stderr, String

          # @!attribute stdout
          #   The standard output that was captured.
          #
          #   @return [String]
          required :stdout, String

          # @!attribute created_by
          #   The identifier of the actor that created the item.
          #
          #   @return [String, nil]
          optional :created_by, String

          # @!method initialize(outcome:, stderr:, stdout:, created_by: nil)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output} for
          #   more details.
          #
          #   The content of a shell tool call output that was emitted.
          #
          #   @param outcome [OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout, OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit] Represents either an exit outcome (with an exit code) or a timeout outcome for a
          #
          #   @param stderr [String] The standard error output that was captured.
          #
          #   @param stdout [String] The standard output that was captured.
          #
          #   @param created_by [String] The identifier of the actor that created the item.

          # Represents either an exit outcome (with an exit code) or a timeout outcome for a
          # shell call output chunk.
          #
          # @see OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output#outcome
          module Outcome
            extend OpenAI::Internal::Type::Union

            discriminator :type

            # Indicates that the shell call exceeded its configured time limit.
            variant :timeout, -> { OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout }

            # Indicates that the shell commands finished and returned an exit code.
            variant :exit, -> { OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit }

            class Timeout < OpenAI::Internal::Type::BaseModel
              # @!attribute type
              #   The outcome type. Always `timeout`.
              #
              #   @return [Symbol, :timeout]
              required :type, const: :timeout

              # @!method initialize(type: :timeout)
              #   Indicates that the shell call exceeded its configured time limit.
              #
              #   @param type [Symbol, :timeout] The outcome type. Always `timeout`.
            end

            class Exit < OpenAI::Internal::Type::BaseModel
              # @!attribute exit_code
              #   Exit code from the shell process.
              #
              #   @return [Integer]
              required :exit_code, Integer

              # @!attribute type
              #   The outcome type. Always `exit`.
              #
              #   @return [Symbol, :exit]
              required :type, const: :exit

              # @!method initialize(exit_code:, type: :exit)
              #   Indicates that the shell commands finished and returned an exit code.
              #
              #   @param exit_code [Integer] Exit code from the shell process.
              #
              #   @param type [Symbol, :exit] The outcome type. Always `exit`.
            end

            # @!method self.variants
            #   @return [Array(OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout, OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit)]
          end
        end

        # The status of the shell call output. One of `in_progress`, `completed`, or
        # `incomplete`.
        #
        # @see OpenAI::Models::Responses::ResponseFunctionShellToolCallOutput#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
