# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseApplyPatchToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the apply patch tool call. Populated when this item is returned
        #   via API.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the apply patch tool call generated by the model.
        #
        #   @return [String]
        required :call_id, String

        # @!attribute status
        #   The status of the apply patch tool call. One of `in_progress` or `completed`.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseApplyPatchToolCall::Status }

        # @!attribute type
        #   The type of the item. Always `apply_patch_call`.
        #
        #   @return [Symbol, :apply_patch_call]
        required :type, const: :apply_patch_call

        # @!attribute created_by
        #   The ID of the entity that created this tool call.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!attribute operation
        #   One of the create_file, delete_file, or update_file operations applied via
        #   apply_patch.
        #
        #   @return [OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::CreateFile, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile, nil]
        optional :operation, union: -> { OpenAI::Responses::ResponseApplyPatchToolCall::Operation }

        # @!method initialize(id:, call_id:, status:, created_by: nil, operation: nil, type: :apply_patch_call)
        #   Some parameter documentations has been truncated, see
        #   {OpenAI::Models::Responses::ResponseApplyPatchToolCall} for more details.
        #
        #   A tool call that applies file diffs by creating, deleting, or updating files.
        #
        #   @param id [String] The unique ID of the apply patch tool call. Populated when this item is returned
        #
        #   @param call_id [String] The unique ID of the apply patch tool call generated by the model.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Status] The status of the apply patch tool call. One of `in_progress` or `completed`.
        #
        #   @param created_by [String] The ID of the entity that created this tool call.
        #
        #   @param operation [OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::CreateFile, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile] One of the create_file, delete_file, or update_file operations applied via apply
        #
        #   @param type [Symbol, :apply_patch_call] The type of the item. Always `apply_patch_call`.

        # The status of the apply patch tool call. One of `in_progress` or `completed`.
        #
        # @see OpenAI::Models::Responses::ResponseApplyPatchToolCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # One of the create_file, delete_file, or update_file operations applied via
        # apply_patch.
        #
        # @see OpenAI::Models::Responses::ResponseApplyPatchToolCall#operation
        module Operation
          extend OpenAI::Internal::Type::Union

          discriminator :type

          # Instruction describing how to create a file via the apply_patch tool.
          variant :create_file, -> { OpenAI::Responses::ResponseApplyPatchToolCall::Operation::CreateFile }

          # Instruction describing how to delete a file via the apply_patch tool.
          variant :delete_file, -> { OpenAI::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile }

          # Instruction describing how to update a file via the apply_patch tool.
          variant :update_file, -> { OpenAI::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile }

          class CreateFile < OpenAI::Internal::Type::BaseModel
            # @!attribute diff
            #   Diff to apply.
            #
            #   @return [String]
            required :diff, String

            # @!attribute path
            #   Path of the file to create.
            #
            #   @return [String]
            required :path, String

            # @!attribute type
            #   Create a new file with the provided diff.
            #
            #   @return [Symbol, :create_file]
            required :type, const: :create_file

            # @!method initialize(diff:, path:, type: :create_file)
            #   Instruction describing how to create a file via the apply_patch tool.
            #
            #   @param diff [String] Diff to apply.
            #
            #   @param path [String] Path of the file to create.
            #
            #   @param type [Symbol, :create_file] Create a new file with the provided diff.
          end

          class DeleteFile < OpenAI::Internal::Type::BaseModel
            # @!attribute path
            #   Path of the file to delete.
            #
            #   @return [String]
            required :path, String

            # @!attribute type
            #   Delete the specified file.
            #
            #   @return [Symbol, :delete_file]
            required :type, const: :delete_file

            # @!method initialize(path:, type: :delete_file)
            #   Instruction describing how to delete a file via the apply_patch tool.
            #
            #   @param path [String] Path of the file to delete.
            #
            #   @param type [Symbol, :delete_file] Delete the specified file.
          end

          class UpdateFile < OpenAI::Internal::Type::BaseModel
            # @!attribute diff
            #   Diff to apply.
            #
            #   @return [String]
            required :diff, String

            # @!attribute path
            #   Path of the file to update.
            #
            #   @return [String]
            required :path, String

            # @!attribute type
            #   Update an existing file with the provided diff.
            #
            #   @return [Symbol, :update_file]
            required :type, const: :update_file

            # @!method initialize(diff:, path:, type: :update_file)
            #   Instruction describing how to update a file via the apply_patch tool.
            #
            #   @param diff [String] Diff to apply.
            #
            #   @param path [String] Path of the file to update.
            #
            #   @param type [Symbol, :update_file] Update an existing file with the provided diff.
          end

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::CreateFile, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile, OpenAI::Models::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile)]
        end
      end
    end
  end
end
