# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseToolSearchOutputItem < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the tool search output item.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the tool search call generated by the model.
        #
        #   @return [String, nil]
        required :call_id, String, nil?: true

        # @!attribute execution
        #   Whether tool search was executed by the server or by the client.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItem::Execution]
        required :execution, enum: -> { OpenAI::Responses::ResponseToolSearchOutputItem::Execution }

        # @!attribute status
        #   The status of the tool search output item that was recorded.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItem::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseToolSearchOutputItem::Status }

        # @!attribute tools
        #   The loaded tool definitions returned by tool search.
        #
        #   @return [Array<OpenAI::Models::Responses::FunctionTool, OpenAI::Models::Responses::FileSearchTool, OpenAI::Models::Responses::ComputerUseTool, OpenAI::Models::Responses::ComputerTool, OpenAI::Models::Responses::Tool::Mcp, OpenAI::Models::Responses::Tool::CodeInterpreter, OpenAI::Models::Responses::Tool::ImageGeneration, OpenAI::Models::Responses::Tool::LocalShell, OpenAI::Models::Responses::FunctionShellTool, OpenAI::Models::Responses::CustomTool, OpenAI::Models::Responses::NamespaceTool, OpenAI::Models::Responses::ToolSearchTool, OpenAI::Models::Responses::ApplyPatchTool, OpenAI::Models::Responses::WebSearchTool, OpenAI::Models::Responses::WebSearchPreviewTool>]
        required :tools, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Responses::Tool] }

        # @!attribute type
        #   The type of the item. Always `tool_search_output`.
        #
        #   @return [Symbol, :tool_search_output]
        required :type, const: :tool_search_output

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, call_id:, execution:, status:, tools:, created_by: nil, type: :tool_search_output)
        #   @param id [String] The unique ID of the tool search output item.
        #
        #   @param call_id [String, nil] The unique ID of the tool search call generated by the model.
        #
        #   @param execution [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItem::Execution] Whether tool search was executed by the server or by the client.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseToolSearchOutputItem::Status] The status of the tool search output item that was recorded.
        #
        #   @param tools [Array<OpenAI::Models::Responses::FunctionTool, OpenAI::Models::Responses::FileSearchTool, OpenAI::Models::Responses::ComputerUseTool, OpenAI::Models::Responses::ComputerTool, OpenAI::Models::Responses::Tool::Mcp, OpenAI::Models::Responses::Tool::CodeInterpreter, OpenAI::Models::Responses::Tool::ImageGeneration, OpenAI::Models::Responses::Tool::LocalShell, OpenAI::Models::Responses::FunctionShellTool, OpenAI::Models::Responses::CustomTool, OpenAI::Models::Responses::NamespaceTool, OpenAI::Models::Responses::ToolSearchTool, OpenAI::Models::Responses::ApplyPatchTool, OpenAI::Models::Responses::WebSearchTool, OpenAI::Models::Responses::WebSearchPreviewTool>] The loaded tool definitions returned by tool search.
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :tool_search_output] The type of the item. Always `tool_search_output`.

        # Whether tool search was executed by the server or by the client.
        #
        # @see OpenAI::Models::Responses::ResponseToolSearchOutputItem#execution
        module Execution
          extend OpenAI::Internal::Type::Enum

          SERVER = :server
          CLIENT = :client

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The status of the tool search output item that was recorded.
        #
        # @see OpenAI::Models::Responses::ResponseToolSearchOutputItem#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
