# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseToolSearchCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the tool search call item.
        #
        #   @return [String]
        required :id, String

        # @!attribute arguments
        #   Arguments used for the tool search call.
        #
        #   @return [Object]
        required :arguments, OpenAI::Internal::Type::Unknown

        # @!attribute call_id
        #   The unique ID of the tool search call generated by the model.
        #
        #   @return [String, nil]
        required :call_id, String, nil?: true

        # @!attribute execution
        #   Whether tool search was executed by the server or by the client.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseToolSearchCall::Execution]
        required :execution, enum: -> { OpenAI::Responses::ResponseToolSearchCall::Execution }

        # @!attribute status
        #   The status of the tool search call item that was recorded.
        #
        #   @return [Symbol, OpenAI::Models::Responses::ResponseToolSearchCall::Status]
        required :status, enum: -> { OpenAI::Responses::ResponseToolSearchCall::Status }

        # @!attribute type
        #   The type of the item. Always `tool_search_call`.
        #
        #   @return [Symbol, :tool_search_call]
        required :type, const: :tool_search_call

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, arguments:, call_id:, execution:, status:, created_by: nil, type: :tool_search_call)
        #   @param id [String] The unique ID of the tool search call item.
        #
        #   @param arguments [Object] Arguments used for the tool search call.
        #
        #   @param call_id [String, nil] The unique ID of the tool search call generated by the model.
        #
        #   @param execution [Symbol, OpenAI::Models::Responses::ResponseToolSearchCall::Execution] Whether tool search was executed by the server or by the client.
        #
        #   @param status [Symbol, OpenAI::Models::Responses::ResponseToolSearchCall::Status] The status of the tool search call item that was recorded.
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :tool_search_call] The type of the item. Always `tool_search_call`.

        # Whether tool search was executed by the server or by the client.
        #
        # @see OpenAI::Models::Responses::ResponseToolSearchCall#execution
        module Execution
          extend OpenAI::Internal::Type::Enum

          SERVER = :server
          CLIENT = :client

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The status of the tool search call item that was recorded.
        #
        # @see OpenAI::Models::Responses::ResponseToolSearchCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
