# frozen_string_literal: true

module OpenAI
  module Models
    module Responses
      class ResponseCompactionItem < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the compaction item.
        #
        #   @return [String]
        required :id, String

        # @!attribute encrypted_content
        #
        #   @return [String]
        required :encrypted_content, String

        # @!attribute type
        #   The type of the item. Always `compaction`.
        #
        #   @return [Symbol, :compaction]
        required :type, const: :compaction

        # @!attribute created_by
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, encrypted_content:, created_by: nil, type: :compaction)
        #   A compaction item generated by the
        #   [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        #
        #   @param id [String] The unique ID of the compaction item.
        #
        #   @param encrypted_content [String]
        #
        #   @param created_by [String]
        #
        #   @param type [Symbol, :compaction] The type of the item. Always `compaction`.
      end
    end
  end
end
