module OpenAI
  module Models
    module FineTuning
      type dpo_hyperparameters =
        {
          ?batch_size: OpenAI::Models::FineTuning::DpoHyperparameters::batch_size,
          ?beta: OpenAI::Models::FineTuning::DpoHyperparameters::beta,
          ?learning_rate_multiplier: OpenAI::Models::FineTuning::DpoHyperparameters::learning_rate_multiplier,
          ?n_epochs: OpenAI::Models::FineTuning::DpoHyperparameters::n_epochs
        }

      class DpoHyperparameters < OpenAI::Internal::Type::BaseModel
        # Number of examples in each batch. A larger batch size means that model
        # parameters are updated less frequently, but with lower variance.
        attr_reader batch_size: OpenAI::Models::FineTuning::DpoHyperparameters::batch_size?

        # Number of examples in each batch. A larger batch size means that model
        # parameters are updated less frequently, but with lower variance.
        def batch_size=: (
          OpenAI::Models::FineTuning::DpoHyperparameters::batch_size
        ) -> OpenAI::Models::FineTuning::DpoHyperparameters::batch_size

        # The beta value for the DPO method. A higher beta value will increase the weight
        # of the penalty between the policy and reference model.
        attr_reader beta: OpenAI::Models::FineTuning::DpoHyperparameters::beta?

        # The beta value for the DPO method. A higher beta value will increase the weight
        # of the penalty between the policy and reference model.
        def beta=: (
          OpenAI::Models::FineTuning::DpoHyperparameters::beta
        ) -> OpenAI::Models::FineTuning::DpoHyperparameters::beta

        # Scaling factor for the learning rate. A smaller learning rate may be useful to
        # avoid overfitting.
        attr_reader learning_rate_multiplier: OpenAI::Models::FineTuning::DpoHyperparameters::learning_rate_multiplier?

        # Scaling factor for the learning rate. A smaller learning rate may be useful to
        # avoid overfitting.
        def learning_rate_multiplier=: (
          OpenAI::Models::FineTuning::DpoHyperparameters::learning_rate_multiplier
        ) -> OpenAI::Models::FineTuning::DpoHyperparameters::learning_rate_multiplier

        # The number of epochs to train the model for. An epoch refers to one full cycle
        # through the training dataset.
        attr_reader n_epochs: OpenAI::Models::FineTuning::DpoHyperparameters::n_epochs?

        # The number of epochs to train the model for. An epoch refers to one full cycle
        # through the training dataset.
        def n_epochs=: (
          OpenAI::Models::FineTuning::DpoHyperparameters::n_epochs
        ) -> OpenAI::Models::FineTuning::DpoHyperparameters::n_epochs

        # @param batch_size
        #   Number of examples in each batch. A larger batch size means that model
        #   parameters are updated less frequently, but with lower variance.
        # @param beta
        #   The beta value for the DPO method. A higher beta value will increase the weight
        #   of the penalty between the policy and reference model.
        # @param learning_rate_multiplier
        #   Scaling factor for the learning rate. A smaller learning rate may be useful to
        #   avoid overfitting.
        # @param n_epochs
        #   The number of epochs to train the model for. An epoch refers to one full cycle
        #   through the training dataset.
        def initialize: (
          ?batch_size: OpenAI::Models::FineTuning::DpoHyperparameters::batch_size,
          ?beta: OpenAI::Models::FineTuning::DpoHyperparameters::beta,
          ?learning_rate_multiplier: OpenAI::Models::FineTuning::DpoHyperparameters::learning_rate_multiplier,
          ?n_epochs: OpenAI::Models::FineTuning::DpoHyperparameters::n_epochs
        ) -> void

        def to_hash: -> {
          ?batch_size: OpenAI::Models::FineTuning::DpoHyperparameters::batch_size,
          ?beta: OpenAI::Models::FineTuning::DpoHyperparameters::beta,
          ?learning_rate_multiplier: OpenAI::Models::FineTuning::DpoHyperparameters::learning_rate_multiplier,
          ?n_epochs: OpenAI::Models::FineTuning::DpoHyperparameters::n_epochs
        }

        type batch_size = :auto | Integer

        module BatchSize
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::FineTuning::DpoHyperparameters::batch_size]
        end

        type beta = :auto | Float

        module Beta
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::FineTuning::DpoHyperparameters::beta]
        end

        type learning_rate_multiplier = :auto | Float

        module LearningRateMultiplier
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::FineTuning::DpoHyperparameters::learning_rate_multiplier]
        end

        type n_epochs = :auto | Integer

        module NEpochs
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Models::FineTuning::DpoHyperparameters::n_epochs]
        end
      end
    end
  end
end
