module OpenAI
  module Models
    class FineTuningJobIntegration = FineTuning::FineTuningJobIntegration

    module FineTuning
      class FineTuningJobIntegration = OpenAI::Models::FineTuning::FineTuningJobWandbIntegrationObject
    end
  end
end
