module OpenAI
  module Models
    module FineTuning
      type job_retrieve_params =
        { fine_tuning_job_id: String }
        & OpenAI::Internal::Type::request_parameters

      class JobRetrieveParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor fine_tuning_job_id: String

        def initialize: (
          fine_tuning_job_id: String,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          fine_tuning_job_id: String,
          request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
