module OpenAI
  module Models
    module Containers
      type file_delete_params =
        { container_id: String } & OpenAI::Internal::Type::request_parameters

      class FileDeleteParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor container_id: String

        def initialize: (
          container_id: String,
          ?request_options: OpenAI::request_opts
        ) -> void
      end
    end
  end
end
