module OpenAI
  module Resources
    class Realtime
      class ClientSecrets
        def with_raw_response: -> ClientSecrets::WithRawResponse
        def create: (
          ?expires_after: OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter,
          ?session: OpenAI::Models::Realtime::ClientSecretCreateParams::session,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::Models::Realtime::ClientSecretCreateResponse

        def initialize: (client: OpenAI::Internal::Transport::_RequestClient) -> void

        class WithRawResponse
          def create: (
          ?expires_after: OpenAI::Realtime::ClientSecretCreateParams::ExpiresAfter,
          ?session: OpenAI::Models::Realtime::ClientSecretCreateParams::session,
          ?request_options: OpenAI::request_opts
        ) -> OpenAI::RawResponse[OpenAI::Models::Realtime::ClientSecretCreateResponse]

          def initialize: (resource: ClientSecrets) -> void
        end
      end
    end
  end
end
