# frozen_string_literal: true

module OpenAI
  module Resources
    class Beta
      class Threads
        # @deprecated The Assistants API is deprecated in favor of the Responses API
        #
        # Build Assistants that can call models and use tools.
        class Messages
          # @deprecated The Assistants API is deprecated in favor of the Responses API
          #
          # Create a message.
          #
          # @overload create(thread_id, content:, role:, attachments: nil, metadata: nil, request_options: {})
          #
          # @param thread_id [String]
          #   The ID of the
          #   [thread](https://developers.openai.com/api/docs/assistants/migration) to create
          #   a message for.
          #
          # @param content [String, Array<OpenAI::Models::Beta::Threads::ImageFileContentBlock, OpenAI::Models::Beta::Threads::ImageURLContentBlock, OpenAI::Models::Beta::Threads::TextContentBlockParam>]
          #   The text contents of the message.
          #
          # @param role [Symbol, OpenAI::Models::Beta::Threads::MessageCreateParams::Role]
          #   The role of the entity that is creating the message. Allowed values include:
          #
          #   - `user`: Indicates the message is sent by an actual user and should be used in
          #     most cases to represent user-generated messages.
          #   - `assistant`: Indicates the message is generated by the assistant. Use this
          #     value to insert messages from the assistant into the conversation.
          #
          # @param attachments [Array<OpenAI::Models::Beta::Threads::MessageCreateParams::Attachment>, nil]
          #   A list of files attached to the message, and the tools they should be added to.
          #
          # @param metadata [Hash{Symbol=>String}, nil]
          #   Set of 16 key-value pairs that can be attached to an object. This can be useful
          #   for storing additional information about the object in a structured format, and
          #   querying for objects via API or the dashboard.
          #
          #   Keys are strings with a maximum length of 64 characters. Values are strings with
          #   a maximum length of 512 characters.
          #
          # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [OpenAI::Models::Beta::Threads::Message]
          #
          # @see OpenAI::Models::Beta::Threads::MessageCreateParams
          def create(thread_id, params)
            parsed, options = OpenAI::Beta::Threads::MessageCreateParams.dump_request(params)
            @client.request(
              method: :post,
              path: ["threads/%1$s/messages", thread_id],
              body: parsed,
              model: OpenAI::Beta::Threads::Message,
              security: {bearer_auth: true},
              options: {extra_headers: {"OpenAI-Beta" => "assistants=v2"}, **options}
            )
          end

          # @deprecated The Assistants API is deprecated in favor of the Responses API
          #
          # Retrieve a message.
          #
          # @overload retrieve(message_id, thread_id:, request_options: {})
          #
          # @param message_id [String]
          #   The ID of the message to retrieve.
          #
          # @param thread_id [String]
          #   The ID of the
          #   [thread](https://developers.openai.com/api/docs/assistants/migration) to which
          #   this message belongs.
          #
          # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [OpenAI::Models::Beta::Threads::Message]
          #
          # @see OpenAI::Models::Beta::Threads::MessageRetrieveParams
          def retrieve(message_id, params)
            parsed, options = OpenAI::Beta::Threads::MessageRetrieveParams.dump_request(params)
            thread_id = parsed.delete(:thread_id) do
              raise ArgumentError.new("missing required path argument #{_1}")
            end

            @client.request(
              method: :get,
              path: ["threads/%1$s/messages/%2$s", thread_id, message_id],
              model: OpenAI::Beta::Threads::Message,
              security: {bearer_auth: true},
              options: {extra_headers: {"OpenAI-Beta" => "assistants=v2"}, **options}
            )
          end

          # @deprecated The Assistants API is deprecated in favor of the Responses API
          #
          # Modifies a message.
          #
          # @overload update(message_id, thread_id:, metadata: nil, request_options: {})
          #
          # @param message_id [String]
          #   Path param: The ID of the message to modify.
          #
          # @param thread_id [String]
          #   Path param: The ID of the thread to which this message belongs.
          #
          # @param metadata [Hash{Symbol=>String}, nil]
          #   Body param: Set of 16 key-value pairs that can be attached to an object. This
          #   can be useful for storing additional information about the object in a
          #   structured format, and querying for objects via API or the dashboard.
          #
          #   Keys are strings with a maximum length of 64 characters. Values are strings with
          #   a maximum length of 512 characters.
          #
          # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [OpenAI::Models::Beta::Threads::Message]
          #
          # @see OpenAI::Models::Beta::Threads::MessageUpdateParams
          def update(message_id, params)
            parsed, options = OpenAI::Beta::Threads::MessageUpdateParams.dump_request(params)
            thread_id = parsed.delete(:thread_id) do
              raise ArgumentError.new("missing required path argument #{_1}")
            end

            @client.request(
              method: :post,
              path: ["threads/%1$s/messages/%2$s", thread_id, message_id],
              body: parsed,
              model: OpenAI::Beta::Threads::Message,
              security: {bearer_auth: true},
              options: {extra_headers: {"OpenAI-Beta" => "assistants=v2"}, **options}
            )
          end

          # @deprecated The Assistants API is deprecated in favor of the Responses API
          #
          # Returns a list of messages for a given thread.
          #
          # @overload list(thread_id, after: nil, before: nil, limit: nil, order: nil, run_id: nil, request_options: {})
          #
          # @param thread_id [String]
          #   The ID of the
          #   [thread](https://developers.openai.com/api/docs/assistants/migration) the
          #   messages belong to.
          #
          # @param after [String]
          #   A cursor for use in pagination. `after` is an object ID that defines your place
          #   in the list. For instance, if you make a list request and receive 100 objects,
          #   ending with obj_foo, your subsequent call can include after=obj_foo in order to
          #   fetch the next page of the list.
          #
          # @param before [String]
          #   A cursor for use in pagination. `before` is an object ID that defines your place
          #   in the list. For instance, if you make a list request and receive 100 objects,
          #   starting with obj_foo, your subsequent call can include before=obj_foo in order
          #   to fetch the previous page of the list.
          #
          # @param limit [Integer]
          #   A limit on the number of objects to be returned. Limit can range between 1 and
          #   100, and the default is 20.
          #
          # @param order [Symbol, OpenAI::Models::Beta::Threads::MessageListParams::Order]
          #   Sort order by the `created_at` timestamp of the objects. `asc` for ascending
          #   order and `desc` for descending order.
          #
          # @param run_id [String]
          #   Filter messages by the run ID that generated them.
          #
          # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [OpenAI::Internal::CursorPage<OpenAI::Models::Beta::Threads::Message>]
          #
          # @see OpenAI::Models::Beta::Threads::MessageListParams
          def list(thread_id, params = {})
            parsed, options = OpenAI::Beta::Threads::MessageListParams.dump_request(params)
            query = OpenAI::Internal::Util.encode_query_params(parsed)
            @client.request(
              method: :get,
              path: ["threads/%1$s/messages", thread_id],
              query: query,
              page: OpenAI::Internal::CursorPage,
              model: OpenAI::Beta::Threads::Message,
              security: {bearer_auth: true},
              options: {extra_headers: {"OpenAI-Beta" => "assistants=v2"}, **options}
            )
          end

          # @deprecated The Assistants API is deprecated in favor of the Responses API
          #
          # Deletes a message.
          #
          # @overload delete(message_id, thread_id:, request_options: {})
          #
          # @param message_id [String]
          #   The ID of the message to delete.
          #
          # @param thread_id [String]
          #   The ID of the thread to which this message belongs.
          #
          # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
          #
          # @return [OpenAI::Models::Beta::Threads::MessageDeleted]
          #
          # @see OpenAI::Models::Beta::Threads::MessageDeleteParams
          def delete(message_id, params)
            parsed, options = OpenAI::Beta::Threads::MessageDeleteParams.dump_request(params)
            thread_id = parsed.delete(:thread_id) do
              raise ArgumentError.new("missing required path argument #{_1}")
            end

            @client.request(
              method: :delete,
              path: ["threads/%1$s/messages/%2$s", thread_id, message_id],
              model: OpenAI::Beta::Threads::MessageDeleted,
              security: {bearer_auth: true},
              options: {extra_headers: {"OpenAI-Beta" => "assistants=v2"}, **options}
            )
          end

          # @api private
          #
          # @param client [OpenAI::Client]
          def initialize(client:)
            @client = client
          end
        end
      end
    end
  end
end
