# typed: strong

module OpenAI
  module Models
    class Image < OpenAI::BaseModel
      # The base64-encoded JSON of the generated image, if `response_format` is
      #   `b64_json`.
      sig { returns(T.nilable(String)) }
      def b64_json
      end

      sig { params(_: String).returns(String) }
      def b64_json=(_)
      end

      # The prompt that was used to generate the image, if there was any revision to the
      #   prompt.
      sig { returns(T.nilable(String)) }
      def revised_prompt
      end

      sig { params(_: String).returns(String) }
      def revised_prompt=(_)
      end

      # The URL of the generated image, if `response_format` is `url` (default).
      sig { returns(T.nilable(String)) }
      def url
      end

      sig { params(_: String).returns(String) }
      def url=(_)
      end

      # Represents the url or the content of an image generated by the OpenAI API.
      sig { params(b64_json: String, revised_prompt: String, url: String).returns(T.attached_class) }
      def self.new(b64_json: nil, revised_prompt: nil, url: nil)
      end

      sig { override.returns({b64_json: String, revised_prompt: String, url: String}) }
      def to_hash
      end
    end
  end
end
