# typed: strong

module OpenAI
  module Models
    class Image < OpenAI::Internal::Type::BaseModel
      # The base64-encoded JSON of the generated image, if `response_format` is
      #   `b64_json`.
      sig { returns(T.nilable(String)) }
      attr_reader :b64_json

      sig { params(b64_json: String).void }
      attr_writer :b64_json

      # The prompt that was used to generate the image, if there was any revision to the
      #   prompt.
      sig { returns(T.nilable(String)) }
      attr_reader :revised_prompt

      sig { params(revised_prompt: String).void }
      attr_writer :revised_prompt

      # The URL of the generated image, if `response_format` is `url` (default).
      sig { returns(T.nilable(String)) }
      attr_reader :url

      sig { params(url: String).void }
      attr_writer :url

      # Represents the url or the content of an image generated by the OpenAI API.
      sig { params(b64_json: String, revised_prompt: String, url: String).returns(T.attached_class) }
      def self.new(b64_json: nil, revised_prompt: nil, url: nil); end

      sig { override.returns({b64_json: String, revised_prompt: String, url: String}) }
      def to_hash; end
    end
  end
end
