module OpenAI
  module Internal
    module Provider
      class Handle
        def inspect: -> String
      end

      class Runtime
        attr_accessor name: String
        attr_accessor base_url: String
        attr_accessor prepare_request: (^(
          OpenAI::Internal::Transport::BaseClient::request_input
        ) -> OpenAI::Internal::Transport::BaseClient::request_input)?

        def initialize: (
          name: String,
          base_url: String,
          prepare_request: (^(
            OpenAI::Internal::Transport::BaseClient::request_input
          ) -> OpenAI::Internal::Transport::BaseClient::request_input)?
        ) -> void
      end

      def self.create: (
        untyped definition
      ) -> OpenAI::Internal::Provider::Handle
      def self.name: (OpenAI::Internal::Provider::Handle provider) -> String
      def self.configure: (
        OpenAI::Internal::Provider::Handle provider
      ) -> OpenAI::Internal::Provider::Runtime
    end
  end
end
