# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      module Threads
        class RefusalContentBlock < OpenAI::Internal::Type::BaseModel
          # @!attribute refusal
          #
          #   @return [String]
          required :refusal, String

          # @!attribute type
          #   Always `refusal`.
          #
          #   @return [Symbol, :refusal]
          required :type, const: :refusal

          # @!method initialize(refusal:, type: :refusal)
          #   The refusal content generated by the assistant.
          #
          #   @param refusal [String]
          #
          #   @param type [Symbol, :refusal] Always `refusal`.
        end
      end
    end
  end
end
