# frozen_string_literal: true

module OpenAI
  module Models
    module Realtime
      # @see OpenAI::Resources::Realtime::Calls#create
      class CallCreateParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        # @!attribute sdp
        #   WebRTC Session Description Protocol (SDP) offer generated by the caller.
        #
        #   @return [String]
        required :sdp, String

        # @!attribute session
        #   Realtime session object configuration.
        #
        #   @return [OpenAI::Models::Realtime::RealtimeSessionCreateRequest, nil]
        optional :session, -> { OpenAI::Realtime::RealtimeSessionCreateRequest }

        # @!method initialize(sdp:, session: nil, request_options: {})
        #   @param sdp [String] WebRTC Session Description Protocol (SDP) offer generated by the caller.
        #
        #   @param session [OpenAI::Models::Realtime::RealtimeSessionCreateRequest] Realtime session object configuration.
        #
        #   @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}]
      end
    end
  end
end
