# typed: strong

module OpenAI
  module Models

    module Realtime

      class CallCreateParams < OpenAI::Internal::Type::BaseModel

        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        OrHash = T.type_alias do
          T.any(
            OpenAI::Realtime::CallCreateParams,
            OpenAI::Internal::AnyHash
          )
        end

        # WebRTC Session Description Protocol (SDP) offer generated by the caller.
        sig { returns(String) }
        attr_accessor :sdp

        # Realtime session object configuration.
        sig { returns(T.nilable(OpenAI::Realtime::RealtimeSessionCreateRequest)) }
        attr_reader :session

        sig { params(session: OpenAI::Realtime::RealtimeSessionCreateRequest::OrHash).void }
        attr_writer :session

        sig do
          params(

            sdp: String,

            session: OpenAI::Realtime::RealtimeSessionCreateRequest::OrHash,

            request_options: OpenAI::RequestOptions::OrHash
          )
            .returns(T.attached_class)
        end
        def self.new(

          # WebRTC Session Description Protocol (SDP) offer generated by the caller.
          sdp:,

          # Realtime session object configuration.
          session: nil,

          request_options: {}
        )
        end

        sig do
          override.returns(
            {
              sdp: String,
              session: OpenAI::Realtime::RealtimeSessionCreateRequest,
              request_options: OpenAI::RequestOptions
            }
          )
        end
        def to_hash
        end

      end

    end

  end
end
