module OpenAI
  module Models
    module Beta
      module Agents
        type vault_create_params =
          {
            ?metadata: ::Hash[Symbol, String]?,
            ?name: String,
            ?request_options: OpenAI::request_opts
          }

        class VaultCreateParams < OpenAI::Internal::Type::BaseModel
          extend OpenAI::Internal::Type::RequestParameters::Converter
          include OpenAI::Internal::Type::RequestParameters

          # Key-value pairs to associate with the vault, such as an application or team
          # identifier.
          attr_accessor metadata: ::Hash[Symbol, String]?

          # The name is trimmed before storage. It must contain 1 to 256 UTF-8 bytes after
          # trimming.
          attr_reader name: String?

          # The name is trimmed before storage. It must contain 1 to 256 UTF-8 bytes after
          # trimming.
          def name=: (String) -> String

          # @param metadata
          #   Key-value pairs to associate with the vault, such as an application or team
          #   identifier.
          # @param name
          #   The name is trimmed before storage. It must contain 1 to 256 UTF-8 bytes after
          #   trimming.
          def initialize: (
            ?metadata: ::Hash[Symbol, String]?,
            ?name: String,
            ?request_options: OpenAI::request_opts
          ) -> void

          def to_hash: -> {
            ?metadata: ::Hash[Symbol, String]?,
            ?name: String,
            ?request_options: OpenAI::RequestOptions
          }
        end
      end
    end
  end
end
