module OpenAI
  module Auth
    class WorkloadIdentityAuth
      def get_token: (?deadline: Float?) -> String

      def invalidate_token: (?String? rejected_token) -> void

      def inspect: -> String
    end
  end
end
