module OpenAI
  class CursorPage[Elem]
    include OpenAI::BasePage[Elem]

    attr_accessor data: ::Array[Elem]

    attr_accessor has_more: bool

    def initialize: (
      client: OpenAI::BaseClient,
      req: OpenAI::BaseClient::request_components,
      headers: ::Hash[String, String],
      page_data: ::Hash[Symbol, top]
    ) -> void
  end
end
