module OpenAI
  module Models
    module VectorStores
      type file_batch_retrieve_params =
        { vector_store_id: String } & OpenAI::request_parameters

      class FileBatchRetrieveParams < OpenAI::BaseModel
        extend OpenAI::Type::RequestParameters::Converter
        include OpenAI::RequestParameters

        attr_accessor vector_store_id: String

        def initialize: (
          vector_store_id: String,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> OpenAI::Models::VectorStores::file_batch_retrieve_params
      end
    end
  end
end
