module OpenAI
  module Models
    module VectorStores
      type file_content_params =
        { vector_store_id: String } & OpenAI::request_parameters

      class FileContentParams < OpenAI::BaseModel
        extend OpenAI::RequestParameters::Converter
        include OpenAI::RequestParameters

        attr_accessor vector_store_id: String

        def initialize:
          (
            vector_store_id: String,
            ?request_options: OpenAI::request_opts
          ) -> void
          | (
            ?OpenAI::Models::VectorStores::file_content_params
            | OpenAI::BaseModel data
          ) -> void

        def to_hash: -> OpenAI::Models::VectorStores::file_content_params
      end
    end
  end
end
