module OpenAI
  module Models
    module Audio
      type speech_model = :"tts-1" | :"tts-1-hd" | :"gpt-4o-mini-tts"

      class SpeechModel < OpenAI::Enum
        TTS_1: :"tts-1"
        TTS_1_HD: :"tts-1-hd"
        GPT_4O_MINI_TTS: :"gpt-4o-mini-tts"

        def self.values: -> ::Array[OpenAI::Models::Audio::speech_model]
      end
    end
  end
end
