module OpenAI
  module Models
    module Audio
      type translation_create_response =
        OpenAI::Models::Audio::Translation
        | OpenAI::Models::Audio::TranslationVerbose

      class TranslationCreateResponse < OpenAI::Union
        private def self.variants: -> [[nil, OpenAI::Models::Audio::Translation], [nil, OpenAI::Models::Audio::TranslationVerbose]]
      end
    end
  end
end
