module OpenAI
  module Models
    module Audio
      type translation_create_response =
        OpenAI::Models::Audio::Translation
        | OpenAI::Models::Audio::TranslationVerbose

      class TranslationCreateResponse < OpenAI::Union
        def self.variants: -> [OpenAI::Models::Audio::Translation, OpenAI::Models::Audio::TranslationVerbose]
      end
    end
  end
end
