module OpenAI
  module Models
    module Admin
      module Organization
        class ProjectServiceAccount = Projects::ProjectServiceAccount

        module Projects
          type project_service_account =
            {
              id: String,
              created_at: Integer,
              name: String,
              object: :"organization.project.service_account",
              role: OpenAI::Models::Admin::Organization::Projects::ProjectServiceAccount::role
            }

          class ProjectServiceAccount < OpenAI::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor created_at: Integer

            attr_accessor name: String

            attr_accessor object: :"organization.project.service_account"

            attr_accessor role: OpenAI::Models::Admin::Organization::Projects::ProjectServiceAccount::role

            def initialize: (
              id: String,
              created_at: Integer,
              name: String,
              role: OpenAI::Models::Admin::Organization::Projects::ProjectServiceAccount::role,
              ?object: :"organization.project.service_account"
            ) -> void

            def to_hash: -> {
              id: String,
              created_at: Integer,
              name: String,
              object: :"organization.project.service_account",
              role: OpenAI::Models::Admin::Organization::Projects::ProjectServiceAccount::role
            }

            type role = :owner | :member | :none

            module Role
              extend OpenAI::Internal::Type::Enum

              OWNER: :owner
              MEMBER: :member
              NONE: :none

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Projects::ProjectServiceAccount::role]
            end
          end
        end
      end
    end
  end
end
