module OpenAI
  module Models
    module Admin
      module Organization
        class ProjectUser = Projects::ProjectUser

        module Projects
          type project_user =
            {
              id: String,
              added_at: Integer,
              email: String,
              name: String,
              object: :"organization.project.user",
              role: OpenAI::Models::Admin::Organization::Projects::ProjectUser::role
            }

          class ProjectUser < OpenAI::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor added_at: Integer

            attr_accessor email: String

            attr_accessor name: String

            attr_accessor object: :"organization.project.user"

            attr_accessor role: OpenAI::Models::Admin::Organization::Projects::ProjectUser::role

            def initialize: (
              id: String,
              added_at: Integer,
              email: String,
              name: String,
              role: OpenAI::Models::Admin::Organization::Projects::ProjectUser::role,
              ?object: :"organization.project.user"
            ) -> void

            def to_hash: -> {
              id: String,
              added_at: Integer,
              email: String,
              name: String,
              object: :"organization.project.user",
              role: OpenAI::Models::Admin::Organization::Projects::ProjectUser::role
            }

            type role = :owner | :member

            module Role
              extend OpenAI::Internal::Type::Enum

              OWNER: :owner
              MEMBER: :member

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Projects::ProjectUser::role]
            end
          end
        end
      end
    end
  end
end
