module OpenAI
  module Models
    module Admin
      module Organization
        class ProjectAPIKey = Projects::ProjectAPIKey

        module Projects
          type project_api_key =
            {
              id: String,
              created_at: Integer,
              last_used_at: Integer?,
              name: String,
              object: :"organization.project.api_key",
              owner: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner,
              owner_project_access: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::owner_project_access,
              redacted_value: String
            }

          class ProjectAPIKey < OpenAI::Internal::Type::BaseModel
            attr_accessor id: String

            attr_accessor created_at: Integer

            attr_accessor last_used_at: Integer?

            attr_accessor name: String

            attr_accessor object: :"organization.project.api_key"

            attr_accessor owner: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner

            attr_accessor owner_project_access: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::owner_project_access

            attr_accessor redacted_value: String

            def initialize: (
              id: String,
              created_at: Integer,
              last_used_at: Integer?,
              name: String,
              owner: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner,
              owner_project_access: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::owner_project_access,
              redacted_value: String,
              ?object: :"organization.project.api_key"
            ) -> void

            def to_hash: -> {
              id: String,
              created_at: Integer,
              last_used_at: Integer?,
              name: String,
              object: :"organization.project.api_key",
              owner: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner,
              owner_project_access: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::owner_project_access,
              redacted_value: String
            }

            type owner =
              {
                service_account: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::ServiceAccount,
                type: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::Owner::type_,
                user: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::User
              }

            class Owner < OpenAI::Internal::Type::BaseModel
              attr_reader service_account: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::ServiceAccount?

              def service_account=: (
                OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::ServiceAccount
              ) -> OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::ServiceAccount

              attr_reader type: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::Owner::type_?

              def type=: (
                OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::Owner::type_
              ) -> OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::Owner::type_

              attr_reader user: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::User?

              def user=: (
                OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::User
              ) -> OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::User

              def initialize: (
                ?service_account: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::ServiceAccount,
                ?type: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::Owner::type_,
                ?user: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::User
              ) -> void

              def to_hash: -> {
                service_account: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::ServiceAccount,
                type: OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::Owner::type_,
                user: OpenAI::Admin::Organization::Projects::ProjectAPIKey::Owner::User
              }

              type service_account =
                { id: String, created_at: Integer, name: String, role: String }

              class ServiceAccount < OpenAI::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor created_at: Integer

                attr_accessor name: String

                attr_accessor role: String

                def initialize: (
                  id: String,
                  created_at: Integer,
                  name: String,
                  role: String
                ) -> void

                def to_hash: -> {
                  id: String,
                  created_at: Integer,
                  name: String,
                  role: String
                }
              end

              type type_ = :user | :service_account

              module Type
                extend OpenAI::Internal::Type::Enum

                USER: :user
                SERVICE_ACCOUNT: :service_account

                def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::Owner::type_]
              end

              type user =
                {
                  id: String,
                  created_at: Integer,
                  email: String,
                  name: String,
                  role: String
                }

              class User < OpenAI::Internal::Type::BaseModel
                attr_accessor id: String

                attr_accessor created_at: Integer

                attr_accessor email: String

                attr_accessor name: String

                attr_accessor role: String

                def initialize: (
                  id: String,
                  created_at: Integer,
                  email: String,
                  name: String,
                  role: String
                ) -> void

                def to_hash: -> {
                  id: String,
                  created_at: Integer,
                  email: String,
                  name: String,
                  role: String
                }
              end
            end

            type owner_project_access = :active | :inactive

            module OwnerProjectAccess
              extend OpenAI::Internal::Type::Enum

              ACTIVE: :active
              INACTIVE: :inactive

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Projects::ProjectAPIKey::owner_project_access]
            end
          end
        end
      end
    end
  end
end
