module OpenAI
  module Models
    module Admin
      module Organization
        module Projects
          type role_create_params =
            {
              project_id: String,
              permissions: ::Array[String],
              role_name: String,
              ?description: String?,
              ?request_options: OpenAI::request_opts
            }

          class RoleCreateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor project_id: String

            # Permissions to grant to the role.
            attr_accessor permissions: ::Array[String]

            # Unique name for the role.
            attr_accessor role_name: String

            # Optional description of the role.
            attr_accessor description: String?

            # @param permissions
            #   Permissions to grant to the role.
            # @param role_name
            #   Unique name for the role.
            # @param description
            #   Optional description of the role.
            def initialize: (
              project_id: String,
              permissions: ::Array[String],
              role_name: String,
              ?description: String?,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              project_id: String,
              permissions: ::Array[String],
              role_name: String,
              ?description: String?,
              ?request_options: OpenAI::RequestOptions
            }
          end
        end
      end
    end
  end
end
