module OpenAI
  module Models
    module Admin
      module Organization
        module Projects
          type service_account_update_params =
            {
              project_id: String,
              service_account_id: String,
              ?name: String,
              ?role: OpenAI::Models::Admin::Organization::Projects::ServiceAccountUpdateParams::role,
              ?request_options: OpenAI::request_opts
            }

          class ServiceAccountUpdateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor project_id: String

            attr_accessor service_account_id: String

            # The updated service account name.
            attr_reader name: String?

            # The updated service account name.
            def name=: (String) -> String

            # The updated service account role.
            attr_reader role: OpenAI::Models::Admin::Organization::Projects::ServiceAccountUpdateParams::role?

            # The updated service account role.
            def role=: (
              OpenAI::Models::Admin::Organization::Projects::ServiceAccountUpdateParams::role
            ) -> OpenAI::Models::Admin::Organization::Projects::ServiceAccountUpdateParams::role

            # @param name
            #   The updated service account name.
            # @param role
            #   The updated service account role.
            def initialize: (
              project_id: String,
              service_account_id: String,
              ?name: String,
              ?role: OpenAI::Models::Admin::Organization::Projects::ServiceAccountUpdateParams::role,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              project_id: String,
              service_account_id: String,
              ?name: String,
              ?role: OpenAI::Models::Admin::Organization::Projects::ServiceAccountUpdateParams::role,
              ?request_options: OpenAI::RequestOptions
            }

            type role = :member | :owner

            module Role
              extend OpenAI::Internal::Type::Enum

              MEMBER: :member
              OWNER: :owner

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Projects::ServiceAccountUpdateParams::role]
            end
          end
        end
      end
    end
  end
end
