module OpenAI
  module Models
    module Admin
      module Organization
        module Projects
          type service_account_create_api_key_params =
            {
              project_id: String,
              service_account_id: String,
              name: String,
              scopes: ::Array[String]
            }
            & OpenAI::Internal::Type::request_parameters

          class ServiceAccountCreateAPIKeyParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor project_id: String

            attr_accessor service_account_id: String

            attr_reader name: String?

            def name=: (String) -> String

            attr_reader scopes: ::Array[String]?

            def scopes=: (::Array[String]) -> ::Array[String]

            def initialize: (
              project_id: String,
              service_account_id: String,
              ?name: String,
              ?scopes: ::Array[String],
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              project_id: String,
              service_account_id: String,
              name: String,
              scopes: ::Array[String],
              request_options: OpenAI::RequestOptions
            }
          end
        end
      end
    end
  end
end
