module OpenAI
  module Models
    module Admin
      module Organization
        module Projects
          type spend_alert_create_params =
            {
              project_id: String,
              currency: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::currency,
              interval: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::interval,
              notification_channel: OpenAI::Admin::Organization::Projects::SpendAlertCreateParams::NotificationChannel,
              threshold_amount: Integer
            }
            & OpenAI::Internal::Type::request_parameters

          class SpendAlertCreateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor project_id: String

            attr_accessor currency: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::currency

            attr_accessor interval: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::interval

            attr_accessor notification_channel: OpenAI::Admin::Organization::Projects::SpendAlertCreateParams::NotificationChannel

            attr_accessor threshold_amount: Integer

            def initialize: (
              project_id: String,
              currency: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::currency,
              interval: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::interval,
              notification_channel: OpenAI::Admin::Organization::Projects::SpendAlertCreateParams::NotificationChannel,
              threshold_amount: Integer,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              project_id: String,
              currency: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::currency,
              interval: OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::interval,
              notification_channel: OpenAI::Admin::Organization::Projects::SpendAlertCreateParams::NotificationChannel,
              threshold_amount: Integer,
              request_options: OpenAI::RequestOptions
            }

            type currency = :USD

            module Currency
              extend OpenAI::Internal::Type::Enum

              USD: :USD

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::currency]
            end

            type interval = :month

            module Interval
              extend OpenAI::Internal::Type::Enum

              MONTH: :month

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Projects::SpendAlertCreateParams::interval]
            end

            type notification_channel =
              {
                recipients: ::Array[String],
                type: :email,
                subject_prefix: String?
              }

            class NotificationChannel < OpenAI::Internal::Type::BaseModel
              attr_accessor recipients: ::Array[String]

              attr_accessor type: :email

              attr_accessor subject_prefix: String?

              def initialize: (
                recipients: ::Array[String],
                ?subject_prefix: String?,
                ?type: :email
              ) -> void

              def to_hash: -> {
                recipients: ::Array[String],
                type: :email,
                subject_prefix: String?
              }
            end
          end
        end
      end
    end
  end
end
