module OpenAI
  module Models
    module Admin
      module Organization
        module Projects
          type user_create_params =
            {
              project_id: String,
              role: String,
              ?email: String?,
              ?user_id: String?,
              ?request_options: OpenAI::request_opts
            }

          class UserCreateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor project_id: String

            # `owner` or `member`
            attr_accessor role: String

            # Email of the user to add.
            attr_accessor email: String?

            # The ID of the user.
            attr_accessor user_id: String?

            # @param role
            #   `owner` or `member`
            # @param email
            #   Email of the user to add.
            # @param user_id
            #   The ID of the user.
            def initialize: (
              project_id: String,
              role: String,
              ?email: String?,
              ?user_id: String?,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              project_id: String,
              role: String,
              ?email: String?,
              ?user_id: String?,
              ?request_options: OpenAI::RequestOptions
            }
          end
        end
      end
    end
  end
end
