module OpenAI
  module Models
    module Admin
      module Organization
        module Projects
          type user_create_params =
            {
              project_id: String,
              role: String,
              email: String?,
              user_id: String?
            }
            & OpenAI::Internal::Type::request_parameters

          class UserCreateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor project_id: String

            attr_accessor role: String

            attr_accessor email: String?

            attr_accessor user_id: String?

            def initialize: (
              project_id: String,
              role: String,
              ?email: String?,
              ?user_id: String?,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              project_id: String,
              role: String,
              email: String?,
              user_id: String?,
              request_options: OpenAI::RequestOptions
            }
          end
        end
      end
    end
  end
end
