module OpenAI
  module Models
    module Admin
      module Organization
        module Projects
          type user_update_params =
            { project_id: String, user_id: String, role: String? }
            & OpenAI::Internal::Type::request_parameters

          class UserUpdateParams < OpenAI::Internal::Type::BaseModel
            extend OpenAI::Internal::Type::RequestParameters::Converter
            include OpenAI::Internal::Type::RequestParameters

            attr_accessor project_id: String

            attr_accessor user_id: String

            attr_accessor role: String?

            def initialize: (
              project_id: String,
              user_id: String,
              ?role: String?,
              ?request_options: OpenAI::request_opts
            ) -> void

            def to_hash: -> {
              project_id: String,
              user_id: String,
              role: String?,
              request_options: OpenAI::RequestOptions
            }
          end
        end
      end
    end
  end
end
