# typed: strong

module OpenAI
  module Models

    module Live

      class OutputAudioDeltaEvent < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Live::OutputAudioDeltaEvent,
            OpenAI::Internal::AnyHash
          )
        end

        # Base64-encoded raw audio. Primary WebSocket events use the session's configured
        # format; reflected sideband events use mono PCM16LE at 24 kHz.
        sig { returns(String) }
        attr_accessor :delta

        # The event type, always `session.output_audio.delta`.
        sig { returns(Symbol) }
        attr_accessor :type

        # Exclusive session-relative end in milliseconds. Required on reflected sideband
        # events; omitted on the primary WebSocket. Dropped output frames leave gaps
        # between reflected ranges.
        sig { returns(T.nilable(Integer)) }
        attr_reader :end_ms

        sig { params(end_ms: Integer).void }
        attr_writer :end_ms

        # Inclusive session-relative start in milliseconds. Required on reflected sideband
        # events; omitted on the primary WebSocket.
        sig { returns(T.nilable(Integer)) }
        attr_reader :start_ms

        sig { params(start_ms: Integer).void }
        attr_writer :start_ms

        # An audio chunk generated by the Live model. Decode and play primary WebSocket
        # chunks in delivery order using the configured session audio format. Sideband
        # connections receive reflected output audio with timestamps.
        sig do
          params(

            delta: String,

            end_ms: Integer,

            start_ms: Integer,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # Base64-encoded raw audio. Primary WebSocket events use the session's configured
          # format; reflected sideband events use mono PCM16LE at 24 kHz.
          delta:,

          # Exclusive session-relative end in milliseconds. Required on reflected sideband
          # events; omitted on the primary WebSocket. Dropped output frames leave gaps
          # between reflected ranges.
          end_ms: nil,

          # Inclusive session-relative start in milliseconds. Required on reflected sideband
          # events; omitted on the primary WebSocket.
          start_ms: nil,

          # The event type, always `session.output_audio.delta`.

          type: :"session.output_audio.delta"
        )
        end

        sig do
          override.returns(
            {delta: String, type: Symbol, end_ms: Integer, start_ms: Integer}
          )
        end
        def to_hash
        end

      end

    end

  end
end
