# frozen_string_literal: true

module OpenAI
  module Models
    module Chat
      class ChatCompletionMessageToolCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The ID of the tool call.
        #
        #   @return [String]
        required :id, String

        # @!attribute function
        #   The function that the model called.
        #
        #   @return [OpenAI::Chat::ChatCompletionMessageToolCall::Function]
        required :function, -> { OpenAI::Chat::ChatCompletionMessageToolCall::Function }

        # @!attribute type
        #   The type of the tool. Currently, only `function` is supported.
        #
        #   @return [Symbol, :function]
        required :type, const: :function

        # @!method initialize(id:, function:, type: :function)
        #   @param id [String] The ID of the tool call.
        #
        #   @param function [OpenAI::Chat::ChatCompletionMessageToolCall::Function] The function that the model called.
        #
        #   @param type [Symbol, :function] The type of the tool. Currently, only `function` is supported.

        # @see OpenAI::Chat::ChatCompletionMessageToolCall#function
        class Function < OpenAI::Internal::Type::BaseModel
          # @!attribute arguments
          #   The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          #
          #   @return [String]
          required :arguments, String

          # @!attribute name
          #   The name of the function to call.
          #
          #   @return [String]
          required :name, String

          # @!method initialize(arguments:, name:)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Chat::ChatCompletionMessageToolCall::Function} for more details.
          #
          #   The function that the model called.
          #
          #   @param arguments [String] The arguments to call the function with, as generated by the model in JSON forma
          #
          #   @param name [String] The name of the function to call.
        end
      end
    end

    ChatCompletionMessageToolCall = Chat::ChatCompletionMessageToolCall
  end
end
