# frozen_string_literal: true

module OpenAI
  module Models
    module Chat
      class ChatCompletionStoreMessage < OpenAI::Models::Chat::ChatCompletionMessage
        # @!attribute id
        #   The identifier of the chat message.
        #
        #   @return [String]
        required :id, String

        # @!attribute content_parts
        #   If a content parts array was provided, this is an array of `text` and
        #   `image_url` parts. Otherwise, null.
        #
        #   @return [Array<OpenAI::Models::Chat::ChatCompletionContentPartText, OpenAI::Models::Chat::ChatCompletionContentPartImage>, nil]
        optional(
          :content_parts,
          -> {
            OpenAI::Internal::Type::ArrayOf[union: OpenAI::Chat::ChatCompletionStoreMessage::ContentPart]
          },
          nil?: true
        )

        # @!method initialize(content:, refusal:, id:, annotations: nil, audio: nil, function_call: nil, tool_calls: nil, content_parts: nil, role: :assistant)
        #   A chat completion message generated by the model.
        #
        #   @param content [String, nil]
        #     The contents of the message.
        #
        #   @param refusal [String, nil]
        #     The refusal message generated by the model.
        #
        #   @param id [String]
        #     The identifier of the chat message.
        #
        #   @param annotations [Array<OpenAI::Models::Chat::ChatCompletionMessage::Annotation>]
        #     Annotations for the message, when applicable, as when using the
        #     [web search tool](https://developers.openai.com/api/docs/guides/tools-web-search).
        #
        #   @param audio [OpenAI::Models::Chat::ChatCompletionAudio, nil]
        #     If the audio output modality is requested, this object contains data about the
        #     audio response from the model.
        #     [Learn more](https://developers.openai.com/api/docs/guides/audio).
        #
        #   @param function_call [OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall]
        #     Deprecated and replaced by `tool_calls`. The name and arguments of a function
        #     that should be called, as generated by the model.
        #
        #   @param tool_calls [Array<OpenAI::Models::Chat::ChatCompletionMessageFunctionToolCall, OpenAI::Models::Chat::ChatCompletionMessageCustomToolCall>]
        #     The tool calls generated by the model, such as function calls.
        #
        #   @param content_parts [Array<OpenAI::Models::Chat::ChatCompletionContentPartText, OpenAI::Models::Chat::ChatCompletionContentPartImage>, nil]
        #     If a content parts array was provided, this is an array of `text` and
        #     `image_url` parts. Otherwise, null.
        #
        #   @param role [Symbol, :assistant]
        #     The role of the author of this message.

        # Learn about [text inputs](https://developers.openai.com/api/docs/guides/text).
        module ContentPart
          extend OpenAI::Internal::Type::Union

          # Learn about [text inputs](https://developers.openai.com/api/docs/guides/text).
          variant -> { OpenAI::Chat::ChatCompletionContentPartText }

          # Learn about [image inputs](https://developers.openai.com/api/docs/guides/images-vision).
          variant -> { OpenAI::Chat::ChatCompletionContentPartImage }

          # @!method self.variants
          #   @return [Array(OpenAI::Models::Chat::ChatCompletionContentPartText, OpenAI::Models::Chat::ChatCompletionContentPartImage)]
        end
      end
    end

    ChatCompletionStoreMessage = Chat::ChatCompletionStoreMessage
  end
end
