# frozen_string_literal: true

module OpenAI
  module Models
    module Chat
      class ChatCompletionContentPartRefusal < OpenAI::Internal::Type::BaseModel
        # @!attribute refusal
        #   The refusal message generated by the model.
        #
        #   @return [String]
        required :refusal, String

        # @!attribute type
        #   The type of the content part.
        #
        #   @return [Symbol, :refusal]
        required :type, const: :refusal

        # @!parse
        #   # @param refusal [String]
        #   # @param type [Symbol, :refusal]
        #   #
        #   def initialize(refusal:, type: :refusal, **) = super

        # def initialize: (Hash | OpenAI::Internal::Type::BaseModel) -> void
      end
    end

    ChatCompletionContentPartRefusal = Chat::ChatCompletionContentPartRefusal
  end
end
