# frozen_string_literal: true

module OpenAI
  module Models
    module Live
      class OutputAudioDeltaEvent < OpenAI::Internal::Type::BaseModel
        # @!attribute delta
        #   Base64-encoded raw audio. Primary WebSocket events use the session's configured
        #   format; reflected sideband events use mono PCM16LE at 24 kHz.
        #
        #   @return [String]
        required :delta, String

        # @!attribute type
        #   The event type, always `session.output_audio.delta`.
        #
        #   @return [Symbol, :"session.output_audio.delta"]
        required :type, const: :"session.output_audio.delta"

        # @!attribute end_ms
        #   Exclusive session-relative end in milliseconds. Required on reflected sideband
        #   events; omitted on the primary WebSocket. Dropped output frames leave gaps
        #   between reflected ranges.
        #
        #   @return [Integer, nil]
        optional :end_ms, Integer

        # @!attribute start_ms
        #   Inclusive session-relative start in milliseconds. Required on reflected sideband
        #   events; omitted on the primary WebSocket.
        #
        #   @return [Integer, nil]
        optional :start_ms, Integer

        # @!method initialize(delta:, end_ms: nil, start_ms: nil, type: :"session.output_audio.delta")
        #   An audio chunk generated by the Live model. Decode and play primary WebSocket
        #   chunks in delivery order using the configured session audio format. Sideband
        #   connections receive reflected output audio with timestamps.
        #
        #   @param delta [String]
        #     Base64-encoded raw audio. Primary WebSocket events use the session's configured
        #     format; reflected sideband events use mono PCM16LE at 24 kHz.
        #
        #   @param end_ms [Integer]
        #     Exclusive session-relative end in milliseconds. Required on reflected sideband
        #     events; omitted on the primary WebSocket. Dropped output frames leave gaps
        #     between reflected ranges.
        #
        #   @param start_ms [Integer]
        #     Inclusive session-relative start in milliseconds. Required on reflected sideband
        #     events; omitted on the primary WebSocket.
        #
        #   @param type [Symbol, :"session.output_audio.delta"]
        #     The event type, always `session.output_audio.delta`.
      end
    end
  end
end
