# frozen_string_literal: true

module OpenAI
  module Models
    module Live
      # Server events for Live. Response lifecycle events are wrapped inside
      # response.event; dispatch the nested event by its full type and tolerate new
      # response event types. Follow the
      # [Live prompting guide](https://developers.openai.com/api/docs/guides/live-prompting)
      # when designing the conversation and delegation policy.
      module ServerEvent
        extend OpenAI::Internal::Type::Union

        discriminator :type

        # Returned when a Live session has started. Contains the resolved session configuration, including server defaults.
        variant :"session.started", -> { OpenAI::Live::SessionStartedEvent }

        # Returned when a Live session update is accepted. Contains the resolved session configuration after the update.
        variant :"session.updated", -> { OpenAI::Live::SessionUpdatedEvent }

        # Returned when a session.input_audio.mute command is accepted. Input audio is no longer sent to the model; sideband audio reflection continues.
        variant :"session.input_audio.muted", -> { OpenAI::Live::InputAudioMutedEvent }

        # Returned when a session.input_audio.unmute command is accepted. Input audio is sent to the model again.
        variant :"session.input_audio.unmuted", -> { OpenAI::Live::InputAudioUnmutedEvent }

        # Returned when a session.instructions.append command is accepted into the Live session timeline. Acknowledges the appended instructions without guaranteeing that the model has acted on them.
        variant :"session.instructions.appended", -> { OpenAI::Live::InstructionsAppendedEvent }

        # Returned when a session.thinking.append command is accepted into the Live session timeline. Acknowledges the added reasoning context without guaranteeing any spoken output.
        variant :"session.thinking.appended", -> { OpenAI::Live::ThinkingAppendedEvent }

        # Returned when a session.commentary.append command is accepted into the Live session timeline. Acknowledges the added commentary without guaranteeing exact wording or completed audio playback.
        variant :"session.commentary.appended", -> { OpenAI::Live::CommentaryAppendedEvent }

        # Input audio received from the primary transport and reflected to a Live sideband connection before model-input muting.
        variant :"session.input_audio.append", -> { OpenAI::Live::ServerEvent::SessionInputAudioAppend }

        # An audio chunk generated by the Live model. Decode and play primary WebSocket chunks in delivery order using the configured session audio format. Sideband connections receive reflected output audio with timestamps.
        variant :"session.output_audio.delta", -> { OpenAI::Live::OutputAudioDeltaEvent }

        # A transcript fragment for user input audio in the Live session. Accumulate fragments in delivery order; these events do not define complete turns or include a transcript-done event.
        variant :"session.input_transcript.delta", -> { OpenAI::Live::InputTranscriptDeltaEvent }

        # A transcript fragment for assistant output audio in the Live session. Accumulate fragments in delivery order; these events do not define complete turns or include a transcript-done event.
        variant :"session.output_transcript.delta", -> { OpenAI::Live::OutputTranscriptDeltaEvent }

        # Returned when the Live model delegates work to your application or a Responses backend. Contains delegation metadata and the position on the session timeline where the work was delegated.
        variant :"session.delegation.created", -> { OpenAI::Live::DelegationCreatedEvent }

        # A streaming Responses API event from a backend delegated to by the Live session. Use the outer delegation_id to associate the nested stream with its Live delegation.
        variant :"response.event", -> { OpenAI::Live::ResponseEvent }

        # Reports cumulative Live audio usage and, when available, the most recent context-window usage. Delegated Responses token usage is reported separately in response.event events.
        variant :"session.usage.updated", -> { OpenAI::Live::SessionUsageUpdatedEvent }

        # Returned after the Live session finishes finalizing, with the close reason, final session snapshot, and cumulative audio usage. A connection closing without this event does not confirm successful finalization.
        variant :"session.closed", -> { OpenAI::Live::SessionClosedEvent }

        # Reports an error in the Live session, such as an invalid client command. Use error.client_event_id, when present, to identify the command that caused the error.
        variant :error, -> { OpenAI::Live::ErrorEvent }

        # An informational notice about the Live session, such as the event permissions applied to a frontend data channel.
        variant :info, -> { OpenAI::Live::InfoEvent }

        # A SIP DTMF keypress received from the caller. Delivered only to sideband observers.
        variant :"transport.dtmf.received", -> { OpenAI::Live::ServerEvent::TransportDtmfReceived }

        # A SIP DTMF keypress successfully sent by the hosted tool. Delivered only to sideband observers; this is not a client command.
        variant :"transport.dtmf.send", -> { OpenAI::Live::ServerEvent::TransportDtmfSend }

        # The outbound SIP provider leg is ringing or providing early media. Delivered only to sideband observers.
        variant :"transport.ringing", -> { OpenAI::Live::ServerEvent::TransportRinging }

        # The outbound SIP provider leg answered and media is established. Delivered only to sideband observers.
        variant :"transport.answered", -> { OpenAI::Live::ServerEvent::TransportAnswered }

        # An asynchronous outbound SIP setup failure. Delivered only to sideband observers.
        variant :"transport.failed", -> { OpenAI::Live::ServerEvent::TransportFailed }

        class SessionInputAudioAppend < OpenAI::Internal::Type::BaseModel
          # @!attribute audio
          #   Base64-encoded raw mono PCM16LE at 24 kHz received from the primary transport,
          #   reflected to the sideband before model-input muting. This server event uses the
          #   same audio key as the client command, but is not an acknowledgment of it.
          #
          #   @return [String]
          required :audio, String

          # @!attribute type
          #   The event type, always `session.input_audio.append`.
          #
          #   @return [Symbol, :"session.input_audio.append"]
          required :type, const: :"session.input_audio.append"

          # @!method initialize(audio:, type: :"session.input_audio.append")
          #   Input audio received from the primary transport and reflected to a Live sideband
          #   connection before model-input muting.
          #
          #   @param audio [String]
          #     Base64-encoded raw mono PCM16LE at 24 kHz received from the primary transport,
          #     reflected to the sideband before model-input muting. This server event uses the
          #     same audio key as the client command, but is not an acknowledgment of it.
          #
          #   @param type [Symbol, :"session.input_audio.append"]
          #     The event type, always `session.input_audio.append`.
        end

        class TransportDtmfReceived < OpenAI::Internal::Type::BaseModel
          # @!attribute event
          #
          #   @return [String]
          required :event, String

          # @!attribute event_id
          #
          #   @return [String]
          required :event_id, String

          # @!attribute type
          #
          #   @return [Symbol, :"transport.dtmf.received"]
          required :type, const: :"transport.dtmf.received"

          # @!method initialize(event:, event_id:, type: :"transport.dtmf.received")
          #   A SIP DTMF keypress received from the caller. Delivered only to sideband
          #   observers.
          #
          #   @param event [String]
          #   @param event_id [String]
          #   @param type [Symbol, :"transport.dtmf.received"]
        end

        class TransportDtmfSend < OpenAI::Internal::Type::BaseModel
          # @!attribute event
          #
          #   @return [String]
          required :event, String

          # @!attribute event_id
          #
          #   @return [String]
          required :event_id, String

          # @!attribute type
          #
          #   @return [Symbol, :"transport.dtmf.send"]
          required :type, const: :"transport.dtmf.send"

          # @!method initialize(event:, event_id:, type: :"transport.dtmf.send")
          #   A SIP DTMF keypress successfully sent by the hosted tool. Delivered only to
          #   sideband observers; this is not a client command.
          #
          #   @param event [String]
          #   @param event_id [String]
          #   @param type [Symbol, :"transport.dtmf.send"]
        end

        class TransportRinging < OpenAI::Internal::Type::BaseModel
          # @!attribute event_id
          #
          #   @return [String]
          required :event_id, String

          # @!attribute session_id
          #   The canonical Live session ID.
          #
          #   @return [String]
          required :session_id, String

          # @!attribute type
          #
          #   @return [Symbol, :"transport.ringing"]
          required :type, const: :"transport.ringing"

          # @!method initialize(event_id:, session_id:, type: :"transport.ringing")
          #   The outbound SIP provider leg is ringing or providing early media. Delivered
          #   only to sideband observers.
          #
          #   @param event_id [String]
          #
          #   @param session_id [String]
          #     The canonical Live session ID.
          #
          #   @param type [Symbol, :"transport.ringing"]
        end

        class TransportAnswered < OpenAI::Internal::Type::BaseModel
          # @!attribute event_id
          #
          #   @return [String]
          required :event_id, String

          # @!attribute session_id
          #   The canonical Live session ID.
          #
          #   @return [String]
          required :session_id, String

          # @!attribute type
          #
          #   @return [Symbol, :"transport.answered"]
          required :type, const: :"transport.answered"

          # @!method initialize(event_id:, session_id:, type: :"transport.answered")
          #   The outbound SIP provider leg answered and media is established. Delivered only
          #   to sideband observers.
          #
          #   @param event_id [String]
          #
          #   @param session_id [String]
          #     The canonical Live session ID.
          #
          #   @param type [Symbol, :"transport.answered"]
        end

        class TransportFailed < OpenAI::Internal::Type::BaseModel
          # @!attribute error
          #
          #   @return [OpenAI::Models::Live::ServerEvent::TransportFailed::Error]
          required :error, -> { OpenAI::Live::ServerEvent::TransportFailed::Error }

          # @!attribute event_id
          #
          #   @return [String]
          required :event_id, String

          # @!attribute session_id
          #   The canonical Live session ID.
          #
          #   @return [String]
          required :session_id, String

          # @!attribute type
          #
          #   @return [Symbol, :"transport.failed"]
          required :type, const: :"transport.failed"

          # @!method initialize(error:, event_id:, session_id:, type: :"transport.failed")
          #   An asynchronous outbound SIP setup failure. Delivered only to sideband
          #   observers.
          #
          #   @param error [OpenAI::Models::Live::ServerEvent::TransportFailed::Error]
          #
          #   @param event_id [String]
          #
          #   @param session_id [String]
          #     The canonical Live session ID.
          #
          #   @param type [Symbol, :"transport.failed"]

          # @see OpenAI::Models::Live::ServerEvent::TransportFailed#error
          class Error < OpenAI::Internal::Type::BaseModel
            # @!attribute code
            #   The call setup failure code.
            #
            #   @return [String]
            required :code, String

            # @!attribute message
            #
            #   @return [String]
            required :message, String

            # @!attribute type
            #
            #   @return [Symbol, :call_error]
            required :type, const: :call_error

            # @!attribute param
            #   The parameter related to the error, if any. Empty when no parameter applies.
            #
            #   @return [String, nil]
            optional :param, String

            # @!method initialize(code:, message:, param: nil, type: :call_error)
            #   @param code [String]
            #     The call setup failure code.
            #
            #   @param message [String]
            #
            #   @param param [String]
            #     The parameter related to the error, if any. Empty when no parameter applies.
            #
            #   @param type [Symbol, :call_error]
          end
        end

        # @!method self.variants
        #   @return [Array(OpenAI::Models::Live::SessionStartedEvent, OpenAI::Models::Live::SessionUpdatedEvent, OpenAI::Models::Live::InputAudioMutedEvent, OpenAI::Models::Live::InputAudioUnmutedEvent, OpenAI::Models::Live::InstructionsAppendedEvent, OpenAI::Models::Live::ThinkingAppendedEvent, OpenAI::Models::Live::CommentaryAppendedEvent, OpenAI::Models::Live::ServerEvent::SessionInputAudioAppend, OpenAI::Models::Live::OutputAudioDeltaEvent, OpenAI::Models::Live::InputTranscriptDeltaEvent, OpenAI::Models::Live::OutputTranscriptDeltaEvent, OpenAI::Models::Live::DelegationCreatedEvent, OpenAI::Models::Live::ResponseEvent, OpenAI::Models::Live::SessionUsageUpdatedEvent, OpenAI::Models::Live::SessionClosedEvent, OpenAI::Models::Live::ErrorEvent, OpenAI::Models::Live::InfoEvent, OpenAI::Models::Live::ServerEvent::TransportDtmfReceived, OpenAI::Models::Live::ServerEvent::TransportDtmfSend, OpenAI::Models::Live::ServerEvent::TransportRinging, OpenAI::Models::Live::ServerEvent::TransportAnswered, OpenAI::Models::Live::ServerEvent::TransportFailed)]
      end
    end
  end
end
