# typed: strong

module OpenAI
  module Models
    LabelModelGrader = Graders::LabelModelGrader

    module Graders
      class LabelModelGrader < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(OpenAI::Graders::LabelModelGrader, OpenAI::Internal::AnyHash)
          end

        sig { returns(T::Array[OpenAI::Graders::LabelModelGrader::Input]) }
        attr_accessor :input

        # The labels to assign to each item in the evaluation.
        sig { returns(T::Array[String]) }
        attr_accessor :labels

        # The model to use for the evaluation. Must support structured outputs.
        sig { returns(String) }
        attr_accessor :model

        # The name of the grader.
        sig { returns(String) }
        attr_accessor :name

        # The labels that indicate a passing result. Must be a subset of labels.
        sig { returns(T::Array[String]) }
        attr_accessor :passing_labels

        # The object type, which is always `label_model`.
        sig { returns(Symbol) }
        attr_accessor :type

        # A LabelModelGrader object which uses a model to assign labels to each item in
        # the evaluation.
        sig do
          params(
            input: T::Array[OpenAI::Graders::LabelModelGrader::Input::OrHash],
            labels: T::Array[String],
            model: String,
            name: String,
            passing_labels: T::Array[String],
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          input:,
          # The labels to assign to each item in the evaluation.
          labels:,
          # The model to use for the evaluation. Must support structured outputs.
          model:,
          # The name of the grader.
          name:,
          # The labels that indicate a passing result. Must be a subset of labels.
          passing_labels:,
          # The object type, which is always `label_model`.
          type: :label_model
        )
        end

        sig do
          override.returns(
            {
              input: T::Array[OpenAI::Graders::LabelModelGrader::Input],
              labels: T::Array[String],
              model: String,
              name: String,
              passing_labels: T::Array[String],
              type: Symbol
            }
          )
        end
        def to_hash
        end

        class Input < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Graders::LabelModelGrader::Input,
                OpenAI::Internal::AnyHash
              )
            end

          # Text inputs to the model - can contain template strings.
          sig do
            returns(
              T.any(
                String,
                OpenAI::Responses::ResponseInputText,
                OpenAI::Graders::LabelModelGrader::Input::Content::OutputText
              )
            )
          end
          attr_accessor :content

          # The role of the message input. One of `user`, `assistant`, `system`, or
          # `developer`.
          sig do
            returns(OpenAI::Graders::LabelModelGrader::Input::Role::OrSymbol)
          end
          attr_accessor :role

          # The type of the message input. Always `message`.
          sig do
            returns(
              T.nilable(
                OpenAI::Graders::LabelModelGrader::Input::Type::OrSymbol
              )
            )
          end
          attr_reader :type

          sig do
            params(
              type: OpenAI::Graders::LabelModelGrader::Input::Type::OrSymbol
            ).void
          end
          attr_writer :type

          # A message input to the model with a role indicating instruction following
          # hierarchy. Instructions given with the `developer` or `system` role take
          # precedence over instructions given with the `user` role. Messages with the
          # `assistant` role are presumed to have been generated by the model in previous
          # interactions.
          sig do
            params(
              content:
                T.any(
                  String,
                  OpenAI::Responses::ResponseInputText::OrHash,
                  OpenAI::Graders::LabelModelGrader::Input::Content::OutputText::OrHash
                ),
              role: OpenAI::Graders::LabelModelGrader::Input::Role::OrSymbol,
              type: OpenAI::Graders::LabelModelGrader::Input::Type::OrSymbol
            ).returns(T.attached_class)
          end
          def self.new(
            # Text inputs to the model - can contain template strings.
            content:,
            # The role of the message input. One of `user`, `assistant`, `system`, or
            # `developer`.
            role:,
            # The type of the message input. Always `message`.
            type: nil
          )
          end

          sig do
            override.returns(
              {
                content:
                  T.any(
                    String,
                    OpenAI::Responses::ResponseInputText,
                    OpenAI::Graders::LabelModelGrader::Input::Content::OutputText
                  ),
                role: OpenAI::Graders::LabelModelGrader::Input::Role::OrSymbol,
                type: OpenAI::Graders::LabelModelGrader::Input::Type::OrSymbol
              }
            )
          end
          def to_hash
          end

          # Text inputs to the model - can contain template strings.
          module Content
            extend OpenAI::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  String,
                  OpenAI::Responses::ResponseInputText,
                  OpenAI::Graders::LabelModelGrader::Input::Content::OutputText
                )
              end

            class OutputText < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Graders::LabelModelGrader::Input::Content::OutputText,
                    OpenAI::Internal::AnyHash
                  )
                end

              # The text output from the model.
              sig { returns(String) }
              attr_accessor :text

              # The type of the output text. Always `output_text`.
              sig { returns(Symbol) }
              attr_accessor :type

              # A text output from the model.
              sig do
                params(text: String, type: Symbol).returns(T.attached_class)
              end
              def self.new(
                # The text output from the model.
                text:,
                # The type of the output text. Always `output_text`.
                type: :output_text
              )
              end

              sig { override.returns({ text: String, type: Symbol }) }
              def to_hash
              end
            end

            sig do
              override.returns(
                T::Array[
                  OpenAI::Graders::LabelModelGrader::Input::Content::Variants
                ]
              )
            end
            def self.variants
            end
          end

          # The role of the message input. One of `user`, `assistant`, `system`, or
          # `developer`.
          module Role
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(Symbol, OpenAI::Graders::LabelModelGrader::Input::Role)
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            USER =
              T.let(
                :user,
                OpenAI::Graders::LabelModelGrader::Input::Role::TaggedSymbol
              )
            ASSISTANT =
              T.let(
                :assistant,
                OpenAI::Graders::LabelModelGrader::Input::Role::TaggedSymbol
              )
            SYSTEM =
              T.let(
                :system,
                OpenAI::Graders::LabelModelGrader::Input::Role::TaggedSymbol
              )
            DEVELOPER =
              T.let(
                :developer,
                OpenAI::Graders::LabelModelGrader::Input::Role::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Graders::LabelModelGrader::Input::Role::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end

          # The type of the message input. Always `message`.
          module Type
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(Symbol, OpenAI::Graders::LabelModelGrader::Input::Type)
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            MESSAGE =
              T.let(
                :message,
                OpenAI::Graders::LabelModelGrader::Input::Type::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Graders::LabelModelGrader::Input::Type::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end
      end
    end
  end
end
