# frozen_string_literal: true

module OpenAI
  module Resources
    class Realtime
      class Calls
        # Create a new Realtime API call over WebRTC and receive the SDP answer needed to
        # complete the peer connection.
        #
        # @overload create(sdp:, session: nil, request_options: {})
        #
        # @param sdp [String]
        #   WebRTC Session Description Protocol (SDP) offer generated by the caller.
        #
        # @param session [OpenAI::Models::Realtime::RealtimeSessionCreateRequest]
        #   Realtime session object configuration.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [OpenAI::HTTPClient::Response]
        #
        # @see OpenAI::Models::Realtime::CallCreateParams
        def create(params)
          parsed, options = OpenAI::Realtime::CallCreateParams.dump_request(params)
          normalize_keys = lambda do |value|
            case value
            when Hash
              value.to_h { |key, child| [key.to_s, normalize_keys.call(child)] }
            when Array
              value.map { |child| normalize_keys.call(child) }
            else
              value
            end
          end

          multipart_body = OpenAI::Internal::Util.deep_merge(
            normalize_keys.call(parsed),
            normalize_keys.call(options[:extra_body] || {})
          )
          options = options.except(:extra_body)
          if multipart_body.key?("sdp")
            multipart_body["sdp"] = OpenAI::FilePart.new(multipart_body["sdp"], content_type: "application/sdp")
          end

          if multipart_body.key?("session")
            multipart_body["session"] = OpenAI::FilePart.new(
              JSON.generate(multipart_body["session"]),
              content_type: "application/json"
            )
          end

          @client.request(
            method: :post,
            path: "realtime/calls",
            headers: {"content-type" => "multipart/form-data", "accept" => "application/sdp"},
            body: multipart_body,
            model: OpenAI::HTTPClient::Response,
            security: {bearer_auth: true},
            options: {**options, max_retries: options[:max_retries] || 0}
          )
        end

        # Accept an incoming SIP call and configure the realtime session that will handle
        # it.
        #
        # @overload accept(call_id, audio: nil, include: nil, instructions: nil, max_output_tokens: nil, model: nil, output_modalities: nil, parallel_tool_calls: nil, prompt: nil, reasoning: nil, tool_choice: nil, tools: nil, tracing: nil, truncation: nil, type: :realtime, request_options: {})
        #
        # @param call_id [String]
        #   The identifier for the call provided in the
        #   [`realtime.call.incoming`](https://developers.openai.com/api/reference/resources/webhooks#realtime.call.incoming)
        #   webhook.
        #
        # @param audio [OpenAI::Models::Realtime::RealtimeAudioConfig]
        #   Configuration for input and output audio.
        #
        # @param include [Array<Symbol, OpenAI::Models::Realtime::RealtimeSessionCreateRequest::Include>]
        #   Additional fields to include in server outputs.
        #
        #   `item.input_audio_transcription.logprobs`: Include logprobs for input audio
        #   transcription.
        #
        # @param instructions [String]
        #   The default system instructions (i.e. system message) prepended to model calls.
        #   This field allows the client to guide the model on desired responses. The model
        #   can be instructed on response content and format, (e.g. "be extremely succinct",
        #   "act friendly", "here are examples of good responses") and on audio behavior
        #   (e.g. "talk quickly", "inject emotion into your voice", "laugh frequently"). The
        #   instructions are not guaranteed to be followed by the model, but they provide
        #   guidance to the model on the desired behavior.
        #
        #   Note that the server sets default instructions which will be used if this field
        #   is not set and are visible in the `session.created` event at the start of the
        #   session.
        #
        # @param max_output_tokens [Integer, Symbol, :inf]
        #   Maximum number of output tokens for a single assistant response, inclusive of
        #   tool calls. Provide an integer between 1 and 4096 to limit output tokens, or
        #   `inf` for the maximum available tokens for a given model. Defaults to `inf`.
        #
        # @param model [String, Symbol, OpenAI::Models::Realtime::RealtimeSessionCreateRequest::Model]
        #   The Realtime model used for this session.
        #
        # @param output_modalities [Array<Symbol, OpenAI::Models::Realtime::RealtimeSessionCreateRequest::OutputModality>]
        #   The set of modalities the model can respond with. It defaults to `["audio"]`,
        #   indicating that the model will respond with audio plus a transcript. `["text"]`
        #   can be used to make the model respond with text only. It is not possible to
        #   request both `text` and `audio` at the same time.
        #
        # @param parallel_tool_calls [Boolean]
        #   Whether the model may call multiple tools in parallel. Only supported by
        #   reasoning Realtime models such as `gpt-realtime-2`.
        #
        # @param prompt [OpenAI::Models::Responses::ResponsePrompt, nil]
        #   Reference to a prompt template and its variables.
        #   [Learn more](https://developers.openai.com/api/docs/guides/text?api-mode=responses#version-prompts-in-code).
        #
        # @param reasoning [OpenAI::Models::Realtime::RealtimeReasoning]
        #   Configuration for reasoning-capable Realtime models such as `gpt-realtime-2`.
        #
        # @param tool_choice [Symbol, OpenAI::Models::Responses::ToolChoiceOptions, OpenAI::Models::Responses::ToolChoiceFunction, OpenAI::Models::Responses::ToolChoiceMcp]
        #   How the model chooses tools. Provide one of the string modes or force a specific
        #   function/MCP tool.
        #
        # @param tools [Array<OpenAI::Models::Realtime::RealtimeFunctionTool, OpenAI::Models::Realtime::RealtimeToolsConfigUnion::Mcp>]
        #   Tools available to the model.
        #
        # @param tracing [Symbol, :auto, OpenAI::Models::Realtime::RealtimeTracingConfig::TracingConfiguration, nil]
        #   Realtime API can write session traces to the
        #   [Traces Dashboard](https://platform.openai.com/logs?api=traces). Set to null to
        #   disable tracing. Once tracing is enabled for a session, the configuration cannot
        #   be modified.
        #
        #   `auto` will create a trace for the session with default values for the workflow
        #   name, group id, and metadata.
        #
        # @param truncation [Symbol, OpenAI::Models::Realtime::RealtimeTruncation::RealtimeTruncationStrategy, OpenAI::Models::Realtime::RealtimeTruncationRetentionRatio]
        #   When the number of tokens in a conversation exceeds the model's input token
        #   limit, the conversation be truncated, meaning messages (starting from the
        #   oldest) will not be included in the model's context. A 32k context model with
        #   4,096 max output tokens can only include 28,224 tokens in the context before
        #   truncation occurs.
        #
        #   Clients can configure truncation behavior to truncate with a lower max token
        #   limit, which is an effective way to control token usage and cost.
        #
        #   Truncation will reduce the number of cached tokens on the next turn (busting the
        #   cache), since messages are dropped from the beginning of the context. However,
        #   clients can also configure truncation to retain messages up to a fraction of the
        #   maximum context size, which will reduce the need for future truncations and thus
        #   improve the cache rate.
        #
        #   Truncation can be disabled entirely, which means the server will never truncate
        #   but would instead return an error if the conversation exceeds the model's input
        #   token limit.
        #
        # @param type [Symbol, :realtime]
        #   The type of session to create. Always `realtime` for the Realtime API.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [nil]
        #
        # @see OpenAI::Models::Realtime::CallAcceptParams
        def accept(call_id, params)
          parsed, options = OpenAI::Realtime::CallAcceptParams.dump_request(params)
          @client.request(
            method: :post,
            path: ["realtime/calls/%1$s/accept", call_id],
            body: parsed,
            model: NilClass,
            security: {bearer_auth: true},
            options: options
          )
        end

        # End an active Realtime API call, whether it was initiated over SIP or WebRTC.
        #
        # @overload hangup(call_id, request_options: {})
        #
        # @param call_id [String]
        #   The identifier for the call. For SIP calls, use the value provided in the
        #   [`realtime.call.incoming`](https://developers.openai.com/api/reference/resources/webhooks#realtime.call.incoming)
        #   webhook. For WebRTC sessions, reuse the call ID returned in the `Location`
        #   header when creating the call with
        #   [`POST /v1/realtime/calls`](https://developers.openai.com/api/reference/resources/realtime/subresources/calls/methods/create).
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [nil]
        #
        # @see OpenAI::Models::Realtime::CallHangupParams
        def hangup(call_id, params = {})
          @client.request(
            method: :post,
            path: ["realtime/calls/%1$s/hangup", call_id],
            model: NilClass,
            security: {bearer_auth: true},
            options: params[:request_options]
          )
        end

        # Transfer an active SIP call to a new destination using the SIP REFER verb.
        #
        # @overload refer(call_id, target_uri:, request_options: {})
        #
        # @param call_id [String]
        #   The identifier for the call provided in the
        #   [`realtime.call.incoming`](https://developers.openai.com/api/reference/resources/webhooks#realtime.call.incoming)
        #   webhook.
        #
        # @param target_uri [String]
        #   URI that should appear in the SIP Refer-To header. Supports values like
        #   `tel:+14155550123` or `sip:agent@example.com`.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [nil]
        #
        # @see OpenAI::Models::Realtime::CallReferParams
        def refer(call_id, params)
          parsed, options = OpenAI::Realtime::CallReferParams.dump_request(params)
          @client.request(
            method: :post,
            path: ["realtime/calls/%1$s/refer", call_id],
            body: parsed,
            model: NilClass,
            security: {bearer_auth: true},
            options: options
          )
        end

        # Decline an incoming SIP call by returning a SIP status code to the caller.
        #
        # @overload reject(call_id, status_code: nil, request_options: {})
        #
        # @param call_id [String]
        #   The identifier for the call provided in the
        #   [`realtime.call.incoming`](https://developers.openai.com/api/reference/resources/webhooks#realtime.call.incoming)
        #   webhook.
        #
        # @param status_code [Integer]
        #   SIP response code to send back to the caller. Defaults to `603` (Decline) when
        #   omitted.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [nil]
        #
        # @see OpenAI::Models::Realtime::CallRejectParams
        def reject(call_id, params = {})
          parsed, options = OpenAI::Realtime::CallRejectParams.dump_request(params)
          @client.request(
            method: :post,
            path: ["realtime/calls/%1$s/reject", call_id],
            body: parsed,
            model: NilClass,
            security: {bearer_auth: true},
            options: options
          )
        end

        # @api private
        #
        # @param client [OpenAI::Client]
        def initialize(client:)
          @client = client
        end
      end
    end
  end
end
