# typed: strong

module OpenAI
  module Models
    module Responses
      # A message input to the model with a role indicating instruction following
      #   hierarchy. Instructions given with the `developer` or `system` role take
      #   precedence over instructions given with the `user` role. Messages with the
      #   `assistant` role are presumed to have been generated by the model in previous
      #   interactions.
      module ResponseInputItem
        extend OpenAI::Union

        Variants =
          type_template(:out) do
            {
              fixed: T.any(
                OpenAI::Models::Responses::EasyInputMessage,
                OpenAI::Models::Responses::ResponseInputItem::Message,
                OpenAI::Models::Responses::ResponseOutputMessage,
                OpenAI::Models::Responses::ResponseFileSearchToolCall,
                OpenAI::Models::Responses::ResponseComputerToolCall,
                OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput,
                OpenAI::Models::Responses::ResponseFunctionWebSearch,
                OpenAI::Models::Responses::ResponseFunctionToolCall,
                OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput,
                OpenAI::Models::Responses::ResponseReasoningItem,
                OpenAI::Models::Responses::ResponseInputItem::ItemReference
              )
            }
          end

        class Message < OpenAI::BaseModel
          # A list of one or many input items to the model, containing different content
          #   types.
          sig do
            returns(
              T::Array[
              T.any(
                OpenAI::Models::Responses::ResponseInputText,
                OpenAI::Models::Responses::ResponseInputImage,
                OpenAI::Models::Responses::ResponseInputFile
              )
              ]
            )
          end
          def content
          end

          sig do
            params(
              _: T::Array[
              T.any(
                OpenAI::Models::Responses::ResponseInputText,
                OpenAI::Models::Responses::ResponseInputImage,
                OpenAI::Models::Responses::ResponseInputFile
              )
              ]
            )
              .returns(
                T::Array[
                T.any(
                  OpenAI::Models::Responses::ResponseInputText,
                  OpenAI::Models::Responses::ResponseInputImage,
                  OpenAI::Models::Responses::ResponseInputFile
                )
                ]
              )
          end
          def content=(_)
          end

          # The role of the message input. One of `user`, `system`, or `developer`.
          sig { returns(OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol) }
          def role
          end

          sig do
            params(_: OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol)
              .returns(OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol)
          end
          def role=(_)
          end

          # The status of item. One of `in_progress`, `completed`, or `incomplete`.
          #   Populated when items are returned via API.
          sig { returns(T.nilable(OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol)) }
          def status
          end

          sig do
            params(_: OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol)
              .returns(OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol)
          end
          def status=(_)
          end

          # The type of the message input. Always set to `message`.
          sig { returns(T.nilable(OpenAI::Models::Responses::ResponseInputItem::Message::Type::OrSymbol)) }
          def type
          end

          sig do
            params(_: OpenAI::Models::Responses::ResponseInputItem::Message::Type::OrSymbol)
              .returns(OpenAI::Models::Responses::ResponseInputItem::Message::Type::OrSymbol)
          end
          def type=(_)
          end

          # A message input to the model with a role indicating instruction following
          #   hierarchy. Instructions given with the `developer` or `system` role take
          #   precedence over instructions given with the `user` role.
          sig do
            params(
              content: T::Array[
              T.any(
                OpenAI::Models::Responses::ResponseInputText,
                OpenAI::Models::Responses::ResponseInputImage,
                OpenAI::Models::Responses::ResponseInputFile
              )
              ],
              role: OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol,
              status: OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol,
              type: OpenAI::Models::Responses::ResponseInputItem::Message::Type::OrSymbol
            )
              .returns(T.attached_class)
          end
          def self.new(content:, role:, status: nil, type: nil)
          end

          sig do
            override
              .returns(
                {
                  content: T::Array[
                  T.any(
                    OpenAI::Models::Responses::ResponseInputText,
                    OpenAI::Models::Responses::ResponseInputImage,
                    OpenAI::Models::Responses::ResponseInputFile
                  )
                  ],
                  role: OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol,
                  status: OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol,
                  type: OpenAI::Models::Responses::ResponseInputItem::Message::Type::OrSymbol
                }
              )
          end
          def to_hash
          end

          # The role of the message input. One of `user`, `system`, or `developer`.
          module Role
            extend OpenAI::Enum

            TaggedSymbol =
              T.type_alias { T.all(Symbol, OpenAI::Models::Responses::ResponseInputItem::Message::Role) }
            OrSymbol =
              T.type_alias { T.any(Symbol, OpenAI::Models::Responses::ResponseInputItem::Message::Role::TaggedSymbol) }

            USER = T.let(:user, OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol)
            SYSTEM = T.let(:system, OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol)
            DEVELOPER = T.let(:developer, OpenAI::Models::Responses::ResponseInputItem::Message::Role::OrSymbol)
          end

          # The status of item. One of `in_progress`, `completed`, or `incomplete`.
          #   Populated when items are returned via API.
          module Status
            extend OpenAI::Enum

            TaggedSymbol =
              T.type_alias { T.all(Symbol, OpenAI::Models::Responses::ResponseInputItem::Message::Status) }
            OrSymbol =
              T.type_alias { T.any(Symbol, OpenAI::Models::Responses::ResponseInputItem::Message::Status::TaggedSymbol) }

            IN_PROGRESS =
              T.let(:in_progress, OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol)
            COMPLETED = T.let(:completed, OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol)
            INCOMPLETE = T.let(:incomplete, OpenAI::Models::Responses::ResponseInputItem::Message::Status::OrSymbol)
          end

          # The type of the message input. Always set to `message`.
          module Type
            extend OpenAI::Enum

            TaggedSymbol =
              T.type_alias { T.all(Symbol, OpenAI::Models::Responses::ResponseInputItem::Message::Type) }
            OrSymbol =
              T.type_alias { T.any(Symbol, OpenAI::Models::Responses::ResponseInputItem::Message::Type::TaggedSymbol) }

            MESSAGE = T.let(:message, OpenAI::Models::Responses::ResponseInputItem::Message::Type::OrSymbol)
          end
        end

        class ComputerCallOutput < OpenAI::BaseModel
          # The ID of the computer tool call that produced the output.
          sig { returns(String) }
          def call_id
          end

          sig { params(_: String).returns(String) }
          def call_id=(_)
          end

          # A computer screenshot image used with the computer use tool.
          sig { returns(OpenAI::Models::Responses::ResponseComputerToolCallOutputScreenshot) }
          def output
          end

          sig do
            params(_: OpenAI::Models::Responses::ResponseComputerToolCallOutputScreenshot)
              .returns(OpenAI::Models::Responses::ResponseComputerToolCallOutputScreenshot)
          end
          def output=(_)
          end

          # The type of the computer tool call output. Always `computer_call_output`.
          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          # The ID of the computer tool call output.
          sig { returns(T.nilable(String)) }
          def id
          end

          sig { params(_: String).returns(String) }
          def id=(_)
          end

          # The safety checks reported by the API that have been acknowledged by the
          #   developer.
          sig do
            returns(
              T.nilable(
                T::Array[OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck]
              )
            )
          end
          def acknowledged_safety_checks
          end

          sig do
            params(
              _: T::Array[OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck]
            )
              .returns(
                T::Array[OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck]
              )
          end
          def acknowledged_safety_checks=(_)
          end

          # The status of the message input. One of `in_progress`, `completed`, or
          #   `incomplete`. Populated when input items are returned via API.
          sig { returns(T.nilable(OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol)) }
          def status
          end

          sig do
            params(_: OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol)
              .returns(OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol)
          end
          def status=(_)
          end

          # The output of a computer tool call.
          sig do
            params(
              call_id: String,
              output: OpenAI::Models::Responses::ResponseComputerToolCallOutputScreenshot,
              id: String,
              acknowledged_safety_checks: T::Array[OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck],
              status: OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol,
              type: Symbol
            )
              .returns(T.attached_class)
          end
          def self.new(call_id:, output:, id: nil, acknowledged_safety_checks: nil, status: nil, type: :computer_call_output)
          end

          sig do
            override
              .returns(
                {
                  call_id: String,
                  output: OpenAI::Models::Responses::ResponseComputerToolCallOutputScreenshot,
                  type: Symbol,
                  id: String,
                  acknowledged_safety_checks: T::Array[OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck],
                  status: OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol
                }
              )
          end
          def to_hash
          end

          class AcknowledgedSafetyCheck < OpenAI::BaseModel
            # The ID of the pending safety check.
            sig { returns(String) }
            def id
            end

            sig { params(_: String).returns(String) }
            def id=(_)
            end

            # The type of the pending safety check.
            sig { returns(String) }
            def code
            end

            sig { params(_: String).returns(String) }
            def code=(_)
            end

            # Details about the pending safety check.
            sig { returns(String) }
            def message
            end

            sig { params(_: String).returns(String) }
            def message=(_)
            end

            # A pending safety check for the computer call.
            sig { params(id: String, code: String, message: String).returns(T.attached_class) }
            def self.new(id:, code:, message:)
            end

            sig { override.returns({id: String, code: String, message: String}) }
            def to_hash
            end
          end

          # The status of the message input. One of `in_progress`, `completed`, or
          #   `incomplete`. Populated when input items are returned via API.
          module Status
            extend OpenAI::Enum

            TaggedSymbol =
              T.type_alias { T.all(Symbol, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status) }
            OrSymbol =
              T.type_alias { T.any(Symbol, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::TaggedSymbol) }

            IN_PROGRESS =
              T.let(:in_progress, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol)
            COMPLETED =
              T.let(:completed, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol)
            INCOMPLETE =
              T.let(:incomplete, OpenAI::Models::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol)
          end
        end

        class FunctionCallOutput < OpenAI::BaseModel
          # The unique ID of the function tool call generated by the model.
          sig { returns(String) }
          def call_id
          end

          sig { params(_: String).returns(String) }
          def call_id=(_)
          end

          # A JSON string of the output of the function tool call.
          sig { returns(String) }
          def output
          end

          sig { params(_: String).returns(String) }
          def output=(_)
          end

          # The type of the function tool call output. Always `function_call_output`.
          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          # The unique ID of the function tool call output. Populated when this item is
          #   returned via API.
          sig { returns(T.nilable(String)) }
          def id
          end

          sig { params(_: String).returns(String) }
          def id=(_)
          end

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          #   Populated when items are returned via API.
          sig { returns(T.nilable(OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol)) }
          def status
          end

          sig do
            params(_: OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol)
              .returns(OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol)
          end
          def status=(_)
          end

          # The output of a function tool call.
          sig do
            params(
              call_id: String,
              output: String,
              id: String,
              status: OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol,
              type: Symbol
            )
              .returns(T.attached_class)
          end
          def self.new(call_id:, output:, id: nil, status: nil, type: :function_call_output)
          end

          sig do
            override
              .returns(
                {
                  call_id: String,
                  output: String,
                  type: Symbol,
                  id: String,
                  status: OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol
                }
              )
          end
          def to_hash
          end

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          #   Populated when items are returned via API.
          module Status
            extend OpenAI::Enum

            TaggedSymbol =
              T.type_alias { T.all(Symbol, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status) }
            OrSymbol =
              T.type_alias { T.any(Symbol, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::TaggedSymbol) }

            IN_PROGRESS =
              T.let(:in_progress, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol)
            COMPLETED =
              T.let(:completed, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol)
            INCOMPLETE =
              T.let(:incomplete, OpenAI::Models::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol)
          end
        end

        class ItemReference < OpenAI::BaseModel
          # The ID of the item to reference.
          sig { returns(String) }
          def id
          end

          sig { params(_: String).returns(String) }
          def id=(_)
          end

          # The type of item to reference. Always `item_reference`.
          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          # An internal identifier for an item to reference.
          sig { params(id: String, type: Symbol).returns(T.attached_class) }
          def self.new(id:, type: :item_reference)
          end

          sig { override.returns({id: String, type: Symbol}) }
          def to_hash
          end
        end
      end
    end
  end
end
