# typed: strong

module OpenAI
  module Models
    module Chat
      class ChatCompletionMessage < OpenAI::BaseModel
        # The contents of the message.
        sig { returns(T.nilable(String)) }
        def content
        end

        sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
        def content=(_)
        end

        # The refusal message generated by the model.
        sig { returns(T.nilable(String)) }
        def refusal
        end

        sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
        def refusal=(_)
        end

        # The role of the author of this message.
        sig { returns(Symbol) }
        def role
        end

        sig { params(_: Symbol).returns(Symbol) }
        def role=(_)
        end

        # Annotations for the message, when applicable, as when using the
        #   [web search tool](https://platform.openai.com/docs/guides/tools-web-search?api-mode=chat).
        sig { returns(T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation])) }
        def annotations
        end

        sig do
          params(_: T::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation])
            .returns(T::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation])
        end
        def annotations=(_)
        end

        # If the audio output modality is requested, this object contains data about the
        #   audio response from the model.
        #   [Learn more](https://platform.openai.com/docs/guides/audio).
        sig { returns(T.nilable(OpenAI::Models::Chat::ChatCompletionAudio)) }
        def audio
        end

        sig do
          params(_: T.nilable(OpenAI::Models::Chat::ChatCompletionAudio))
            .returns(T.nilable(OpenAI::Models::Chat::ChatCompletionAudio))
        end
        def audio=(_)
        end

        # Deprecated and replaced by `tool_calls`. The name and arguments of a function
        #   that should be called, as generated by the model.
        sig { returns(T.nilable(OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall)) }
        def function_call
        end

        sig do
          params(_: OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall)
            .returns(OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall)
        end
        def function_call=(_)
        end

        # The tool calls generated by the model, such as function calls.
        sig { returns(T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall])) }
        def tool_calls
        end

        sig do
          params(_: T::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall])
            .returns(T::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall])
        end
        def tool_calls=(_)
        end

        # A chat completion message generated by the model.
        sig do
          params(
            content: T.nilable(String),
            refusal: T.nilable(String),
            annotations: T::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation],
            audio: T.nilable(OpenAI::Models::Chat::ChatCompletionAudio),
            function_call: OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall,
            tool_calls: T::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall],
            role: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(content:, refusal:, annotations: nil, audio: nil, function_call: nil, tool_calls: nil, role: :assistant)
        end

        sig do
          override
            .returns(
              {
                content: T.nilable(String),
                refusal: T.nilable(String),
                role: Symbol,
                annotations: T::Array[OpenAI::Models::Chat::ChatCompletionMessage::Annotation],
                audio: T.nilable(OpenAI::Models::Chat::ChatCompletionAudio),
                function_call: OpenAI::Models::Chat::ChatCompletionMessage::FunctionCall,
                tool_calls: T::Array[OpenAI::Models::Chat::ChatCompletionMessageToolCall]
              }
            )
        end
        def to_hash
        end

        class Annotation < OpenAI::BaseModel
          # The type of the URL citation. Always `url_citation`.
          sig { returns(Symbol) }
          def type
          end

          sig { params(_: Symbol).returns(Symbol) }
          def type=(_)
          end

          # A URL citation when using web search.
          sig { returns(OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation) }
          def url_citation
          end

          sig do
            params(_: OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation)
              .returns(OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation)
          end
          def url_citation=(_)
          end

          # A URL citation when using web search.
          sig do
            params(url_citation: OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation, type: Symbol)
              .returns(T.attached_class)
          end
          def self.new(url_citation:, type: :url_citation)
          end

          sig do
            override
              .returns(
                {type: Symbol, url_citation: OpenAI::Models::Chat::ChatCompletionMessage::Annotation::URLCitation}
              )
          end
          def to_hash
          end

          class URLCitation < OpenAI::BaseModel
            # The index of the last character of the URL citation in the message.
            sig { returns(Integer) }
            def end_index
            end

            sig { params(_: Integer).returns(Integer) }
            def end_index=(_)
            end

            # The index of the first character of the URL citation in the message.
            sig { returns(Integer) }
            def start_index
            end

            sig { params(_: Integer).returns(Integer) }
            def start_index=(_)
            end

            # The title of the web resource.
            sig { returns(String) }
            def title
            end

            sig { params(_: String).returns(String) }
            def title=(_)
            end

            # The URL of the web resource.
            sig { returns(String) }
            def url
            end

            sig { params(_: String).returns(String) }
            def url=(_)
            end

            # A URL citation when using web search.
            sig do
              params(
                end_index: Integer,
                start_index: Integer,
                title: String,
                url: String
              ).returns(T.attached_class)
            end
            def self.new(end_index:, start_index:, title:, url:)
            end

            sig { override.returns({end_index: Integer, start_index: Integer, title: String, url: String}) }
            def to_hash
            end
          end
        end

        class FunctionCall < OpenAI::BaseModel
          # The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          sig { returns(String) }
          def arguments
          end

          sig { params(_: String).returns(String) }
          def arguments=(_)
          end

          # The name of the function to call.
          sig { returns(String) }
          def name
          end

          sig { params(_: String).returns(String) }
          def name=(_)
          end

          # Deprecated and replaced by `tool_calls`. The name and arguments of a function
          #   that should be called, as generated by the model.
          sig { params(arguments: String, name: String).returns(T.attached_class) }
          def self.new(arguments:, name:)
          end

          sig { override.returns({arguments: String, name: String}) }
          def to_hash
          end
        end
      end
    end

    ChatCompletionMessage = Chat::ChatCompletionMessage
  end
end
