# typed: strong

module OpenAI
  module Models
    ChatCompletionChunk = T.type_alias { Chat::ChatCompletionChunk }

    module Chat
      class ChatCompletionChunk < OpenAI::BaseModel
        # A unique identifier for the chat completion. Each chunk has the same ID.
        sig { returns(String) }
        def id
        end

        sig { params(_: String).returns(String) }
        def id=(_)
        end

        # A list of chat completion choices. Can contain more than one elements if `n` is
        #   greater than 1. Can also be empty for the last chunk if you set
        #   `stream_options: {"include_usage": true}`.
        sig { returns(T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice]) }
        def choices
        end

        sig do
          params(_: T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice])
            .returns(T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice])
        end
        def choices=(_)
        end

        # The Unix timestamp (in seconds) of when the chat completion was created. Each
        #   chunk has the same timestamp.
        sig { returns(Integer) }
        def created
        end

        sig { params(_: Integer).returns(Integer) }
        def created=(_)
        end

        # The model to generate the completion.
        sig { returns(String) }
        def model
        end

        sig { params(_: String).returns(String) }
        def model=(_)
        end

        # The object type, which is always `chat.completion.chunk`.
        sig { returns(Symbol) }
        def object
        end

        sig { params(_: Symbol).returns(Symbol) }
        def object=(_)
        end

        # The service tier used for processing the request.
        sig { returns(T.nilable(Symbol)) }
        def service_tier
        end

        sig { params(_: T.nilable(Symbol)).returns(T.nilable(Symbol)) }
        def service_tier=(_)
        end

        # This fingerprint represents the backend configuration that the model runs with.
        #   Can be used in conjunction with the `seed` request parameter to understand when
        #   backend changes have been made that might impact determinism.
        sig { returns(T.nilable(String)) }
        def system_fingerprint
        end

        sig { params(_: String).returns(String) }
        def system_fingerprint=(_)
        end

        # An optional field that will only be present when you set
        #   `stream_options: {"include_usage": true}` in your request. When present, it
        #   contains a null value except for the last chunk which contains the token usage
        #   statistics for the entire request.
        sig { returns(T.nilable(OpenAI::Models::CompletionUsage)) }
        def usage
        end

        sig { params(_: T.nilable(OpenAI::Models::CompletionUsage)).returns(T.nilable(OpenAI::Models::CompletionUsage)) }
        def usage=(_)
        end

        # Represents a streamed chunk of a chat completion response returned by the model,
        #   based on the provided input.
        #   [Learn more](https://platform.openai.com/docs/guides/streaming-responses).
        sig do
          params(
            id: String,
            choices: T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice],
            created: Integer,
            model: String,
            service_tier: T.nilable(Symbol),
            system_fingerprint: String,
            usage: T.nilable(OpenAI::Models::CompletionUsage),
            object: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(
          id:,
          choices:,
          created:,
          model:,
          service_tier: nil,
          system_fingerprint: nil,
          usage: nil,
          object: :"chat.completion.chunk"
        )
        end

        sig do
          override
            .returns(
              {
                id: String,
                choices: T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice],
                created: Integer,
                model: String,
                object: Symbol,
                service_tier: T.nilable(Symbol),
                system_fingerprint: String,
                usage: T.nilable(OpenAI::Models::CompletionUsage)
              }
            )
        end
        def to_hash
        end

        class Choice < OpenAI::BaseModel
          # A chat completion delta generated by streamed model responses.
          sig { returns(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta) }
          def delta
          end

          sig do
            params(_: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta)
              .returns(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta)
          end
          def delta=(_)
          end

          # The reason the model stopped generating tokens. This will be `stop` if the model
          #   hit a natural stop point or a provided stop sequence, `length` if the maximum
          #   number of tokens specified in the request was reached, `content_filter` if
          #   content was omitted due to a flag from our content filters, `tool_calls` if the
          #   model called a tool, or `function_call` (deprecated) if the model called a
          #   function.
          sig { returns(T.nilable(Symbol)) }
          def finish_reason
          end

          sig { params(_: T.nilable(Symbol)).returns(T.nilable(Symbol)) }
          def finish_reason=(_)
          end

          # The index of the choice in the list of choices.
          sig { returns(Integer) }
          def index
          end

          sig { params(_: Integer).returns(Integer) }
          def index=(_)
          end

          # Log probability information for the choice.
          sig { returns(T.nilable(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Logprobs)) }
          def logprobs
          end

          sig do
            params(_: T.nilable(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Logprobs))
              .returns(T.nilable(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Logprobs))
          end
          def logprobs=(_)
          end

          sig do
            params(
              delta: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta,
              finish_reason: T.nilable(Symbol),
              index: Integer,
              logprobs: T.nilable(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Logprobs)
            )
              .returns(T.attached_class)
          end
          def self.new(delta:, finish_reason:, index:, logprobs: nil)
          end

          sig do
            override
              .returns(
                {
                  delta: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta,
                  finish_reason: T.nilable(Symbol),
                  index: Integer,
                  logprobs: T.nilable(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Logprobs)
                }
              )
          end
          def to_hash
          end

          class Delta < OpenAI::BaseModel
            # The contents of the chunk message.
            sig { returns(T.nilable(String)) }
            def content
            end

            sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
            def content=(_)
            end

            # Deprecated and replaced by `tool_calls`. The name and arguments of a function
            #   that should be called, as generated by the model.
            sig { returns(T.nilable(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::FunctionCall)) }
            def function_call
            end

            sig do
              params(_: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::FunctionCall)
                .returns(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::FunctionCall)
            end
            def function_call=(_)
            end

            # The refusal message generated by the model.
            sig { returns(T.nilable(String)) }
            def refusal
            end

            sig { params(_: T.nilable(String)).returns(T.nilable(String)) }
            def refusal=(_)
            end

            # The role of the author of this message.
            sig { returns(T.nilable(Symbol)) }
            def role
            end

            sig { params(_: Symbol).returns(Symbol) }
            def role=(_)
            end

            sig { returns(T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall])) }
            def tool_calls
            end

            sig do
              params(_: T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall])
                .returns(T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall])
            end
            def tool_calls=(_)
            end

            # A chat completion delta generated by streamed model responses.
            sig do
              params(
                content: T.nilable(String),
                function_call: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::FunctionCall,
                refusal: T.nilable(String),
                role: Symbol,
                tool_calls: T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall]
              )
                .returns(T.attached_class)
            end
            def self.new(content: nil, function_call: nil, refusal: nil, role: nil, tool_calls: nil)
            end

            sig do
              override
                .returns(
                  {
                    content: T.nilable(String),
                    function_call: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::FunctionCall,
                    refusal: T.nilable(String),
                    role: Symbol,
                    tool_calls: T::Array[OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall]
                  }
                )
            end
            def to_hash
            end

            class FunctionCall < OpenAI::BaseModel
              # The arguments to call the function with, as generated by the model in JSON
              #   format. Note that the model does not always generate valid JSON, and may
              #   hallucinate parameters not defined by your function schema. Validate the
              #   arguments in your code before calling your function.
              sig { returns(T.nilable(String)) }
              def arguments
              end

              sig { params(_: String).returns(String) }
              def arguments=(_)
              end

              # The name of the function to call.
              sig { returns(T.nilable(String)) }
              def name
              end

              sig { params(_: String).returns(String) }
              def name=(_)
              end

              # Deprecated and replaced by `tool_calls`. The name and arguments of a function
              #   that should be called, as generated by the model.
              sig { params(arguments: String, name: String).returns(T.attached_class) }
              def self.new(arguments: nil, name: nil)
              end

              sig { override.returns({arguments: String, name: String}) }
              def to_hash
              end
            end

            # The role of the author of this message.
            class Role < OpenAI::Enum
              abstract!

              Value = type_template(:out) { {fixed: Symbol} }

              DEVELOPER = :developer
              SYSTEM = :system
              USER = :user
              ASSISTANT = :assistant
              TOOL = :tool
            end

            class ToolCall < OpenAI::BaseModel
              sig { returns(Integer) }
              def index
              end

              sig { params(_: Integer).returns(Integer) }
              def index=(_)
              end

              # The ID of the tool call.
              sig { returns(T.nilable(String)) }
              def id
              end

              sig { params(_: String).returns(String) }
              def id=(_)
              end

              sig { returns(T.nilable(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall::Function)) }
              def function
              end

              sig do
                params(_: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall::Function)
                  .returns(OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall::Function)
              end
              def function=(_)
              end

              # The type of the tool. Currently, only `function` is supported.
              sig { returns(T.nilable(Symbol)) }
              def type
              end

              sig { params(_: Symbol).returns(Symbol) }
              def type=(_)
              end

              sig do
                params(
                  index: Integer,
                  id: String,
                  function: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall::Function,
                  type: Symbol
                )
                  .returns(T.attached_class)
              end
              def self.new(index:, id: nil, function: nil, type: nil)
              end

              sig do
                override
                  .returns(
                    {
                      index: Integer,
                      id: String,
                      function: OpenAI::Models::Chat::ChatCompletionChunk::Choice::Delta::ToolCall::Function,
                      type: Symbol
                    }
                  )
              end
              def to_hash
              end

              class Function < OpenAI::BaseModel
                # The arguments to call the function with, as generated by the model in JSON
                #   format. Note that the model does not always generate valid JSON, and may
                #   hallucinate parameters not defined by your function schema. Validate the
                #   arguments in your code before calling your function.
                sig { returns(T.nilable(String)) }
                def arguments
                end

                sig { params(_: String).returns(String) }
                def arguments=(_)
                end

                # The name of the function to call.
                sig { returns(T.nilable(String)) }
                def name
                end

                sig { params(_: String).returns(String) }
                def name=(_)
                end

                sig { params(arguments: String, name: String).returns(T.attached_class) }
                def self.new(arguments: nil, name: nil)
                end

                sig { override.returns({arguments: String, name: String}) }
                def to_hash
                end
              end

              # The type of the tool. Currently, only `function` is supported.
              class Type < OpenAI::Enum
                abstract!

                Value = type_template(:out) { {fixed: Symbol} }

                FUNCTION = :function
              end
            end
          end

          # The reason the model stopped generating tokens. This will be `stop` if the model
          #   hit a natural stop point or a provided stop sequence, `length` if the maximum
          #   number of tokens specified in the request was reached, `content_filter` if
          #   content was omitted due to a flag from our content filters, `tool_calls` if the
          #   model called a tool, or `function_call` (deprecated) if the model called a
          #   function.
          class FinishReason < OpenAI::Enum
            abstract!

            Value = type_template(:out) { {fixed: Symbol} }

            STOP = :stop
            LENGTH = :length
            TOOL_CALLS = :tool_calls
            CONTENT_FILTER = :content_filter
            FUNCTION_CALL = :function_call
          end

          class Logprobs < OpenAI::BaseModel
            # A list of message content tokens with log probability information.
            sig { returns(T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob])) }
            def content
            end

            sig do
              params(_: T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob]))
                .returns(T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob]))
            end
            def content=(_)
            end

            # A list of message refusal tokens with log probability information.
            sig { returns(T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob])) }
            def refusal
            end

            sig do
              params(_: T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob]))
                .returns(T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob]))
            end
            def refusal=(_)
            end

            # Log probability information for the choice.
            sig do
              params(
                content: T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob]),
                refusal: T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob])
              )
                .returns(T.attached_class)
            end
            def self.new(content:, refusal:)
            end

            sig do
              override
                .returns(
                  {
                    content: T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob]),
                    refusal: T.nilable(T::Array[OpenAI::Models::Chat::ChatCompletionTokenLogprob])
                  }
                )
            end
            def to_hash
            end
          end
        end

        # The service tier used for processing the request.
        class ServiceTier < OpenAI::Enum
          abstract!

          Value = type_template(:out) { {fixed: Symbol} }

          SCALE = :scale
          DEFAULT = :default
        end
      end
    end
  end
end
