# typed: strong

module OpenAI
  module Models
    module Chat
      class ChatCompletionMessageToolCall < OpenAI::BaseModel
        # The ID of the tool call.
        sig { returns(String) }
        def id
        end

        sig { params(_: String).returns(String) }
        def id=(_)
        end

        # The function that the model called.
        sig { returns(OpenAI::Models::Chat::ChatCompletionMessageToolCall::Function) }
        def function
        end

        sig do
          params(_: T.any(OpenAI::Models::Chat::ChatCompletionMessageToolCall::Function, OpenAI::Util::AnyHash))
            .returns(T.any(OpenAI::Models::Chat::ChatCompletionMessageToolCall::Function, OpenAI::Util::AnyHash))
        end
        def function=(_)
        end

        # The type of the tool. Currently, only `function` is supported.
        sig { returns(Symbol) }
        def type
        end

        sig { params(_: Symbol).returns(Symbol) }
        def type=(_)
        end

        sig do
          params(id: String, function: OpenAI::Models::Chat::ChatCompletionMessageToolCall::Function, type: Symbol)
            .returns(T.attached_class)
        end
        def self.new(id:, function:, type: :function)
        end

        sig do
          override
            .returns(
              {id: String, function: OpenAI::Models::Chat::ChatCompletionMessageToolCall::Function, type: Symbol}
            )
        end
        def to_hash
        end

        class Function < OpenAI::BaseModel
          # The arguments to call the function with, as generated by the model in JSON
          #   format. Note that the model does not always generate valid JSON, and may
          #   hallucinate parameters not defined by your function schema. Validate the
          #   arguments in your code before calling your function.
          sig { returns(String) }
          def arguments
          end

          sig { params(_: String).returns(String) }
          def arguments=(_)
          end

          # The name of the function to call.
          sig { returns(String) }
          def name
          end

          sig { params(_: String).returns(String) }
          def name=(_)
          end

          # The function that the model called.
          sig { params(arguments: String, name: String).returns(T.attached_class) }
          def self.new(arguments:, name:)
          end

          sig { override.returns({arguments: String, name: String}) }
          def to_hash
          end
        end
      end
    end

    ChatCompletionMessageToolCall = Chat::ChatCompletionMessageToolCall
  end
end
