module OpenAI
  module Resources
    class Responses
      class InputItems
        def list:
          (
            String response_id,
            ?OpenAI::Models::Responses::InputItemListParams
            | ::Hash[Symbol, top] params
          ) -> OpenAI::CursorPage[OpenAI::Models::Responses::response_item]
          | (
            String response_id,
            after: String,
            before: String,
            limit: Integer,
            order: OpenAI::Models::Responses::InputItemListParams::order,
            request_options: OpenAI::request_opts
          ) -> OpenAI::CursorPage[OpenAI::Models::Responses::response_item]

        def initialize: (client: OpenAI::Client) -> void
      end
    end
  end
end
