module OpenAI
  module Models
    module Beta
      module Threads
        type image_file_delta =
          {
            detail: OpenAI::Beta::Threads::ImageFileDelta::detail,
            file_id: String
          }

        class ImageFileDelta < OpenAI::Internal::Type::BaseModel
          attr_reader detail: OpenAI::Beta::Threads::ImageFileDelta::detail?

          def detail=: (
            OpenAI::Beta::Threads::ImageFileDelta::detail
          ) -> OpenAI::Beta::Threads::ImageFileDelta::detail

          attr_reader file_id: String?

          def file_id=: (String) -> String

          def initialize: (
            ?detail: OpenAI::Beta::Threads::ImageFileDelta::detail,
            ?file_id: String
          ) -> void

          type detail = :auto | :low | :high

          module Detail
            extend OpenAI::Internal::Type::Enum

            AUTO: :auto
            LOW: :low
            HIGH: :high

            def self?.values: -> ::Array[OpenAI::Beta::Threads::ImageFileDelta::detail]
          end
        end
      end
    end
  end
end
