module OpenAI
  module Models
    module Beta
      module Threads
        type image_url =
          { url: String, detail: OpenAI::Beta::Threads::ImageURL::detail }

        class ImageURL < OpenAI::Internal::Type::BaseModel
          attr_accessor url: String

          attr_reader detail: OpenAI::Beta::Threads::ImageURL::detail?

          def detail=: (
            OpenAI::Beta::Threads::ImageURL::detail
          ) -> OpenAI::Beta::Threads::ImageURL::detail

          def initialize: (
            url: String,
            ?detail: OpenAI::Beta::Threads::ImageURL::detail
          ) -> void

          type detail = :auto | :low | :high

          module Detail
            extend OpenAI::Internal::Type::Enum

            AUTO: :auto
            LOW: :low
            HIGH: :high

            def self?.values: -> ::Array[OpenAI::Beta::Threads::ImageURL::detail]
          end
        end
      end
    end
  end
end
