module OpenAI
  module Models
    module Beta
      module Threads
        type refusal_delta_block =
          { index: Integer, type: :refusal, refusal: String }

        class RefusalDeltaBlock < OpenAI::Internal::Type::BaseModel
          attr_accessor index: Integer

          attr_accessor type: :refusal

          attr_reader refusal: String?

          def refusal=: (String) -> String

          def initialize: (
            index: Integer,
            ?refusal: String,
            ?type: :refusal
          ) -> void

          def to_hash: -> { index: Integer, type: :refusal, refusal: String }
        end
      end
    end
  end
end
