module OpenAI
  module Models
    module Webhooks
      type webhook_rotate_secret_params =
        {
          webhook_endpoint_id: String,
          ?:keep_old_secret_active_for_24_hours => bool,
          ?request_options: OpenAI::request_opts
        }

      class WebhookRotateSecretParams < OpenAI::Internal::Type::BaseModel
        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        attr_accessor webhook_endpoint_id: String

        attr_reader keep_old_secret_active_for_24_hours: bool?

        def keep_old_secret_active_for_24_hours=: (bool) -> bool

        def initialize: (
          webhook_endpoint_id: String,
          ?keep_old_secret_active_for_24_hours: bool,
          ?request_options: OpenAI::request_opts
        ) -> void

        def to_hash: -> {
          webhook_endpoint_id: String,
          ?:keep_old_secret_active_for_24_hours => bool,
          ?request_options: OpenAI::RequestOptions
        }
      end
    end
  end
end
