# typed: strong

module OpenAI
  module Models

    module Beta

      class AgentTextParam < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::AgentTextParam,
            OpenAI::Internal::AnyHash
          )
        end

        # The output format for generated text.
        sig {
          returns(T.nilable(T.any(OpenAI::Beta::TextFormatParam::Text, OpenAI::Beta::TextFormatParam::JSONSchema)))
        }
        attr_accessor :format_

        # The amount of text the model should produce.
        sig { returns(T.nilable(OpenAI::Beta::AgentTextParam::Verbosity::OrSymbol)) }
        attr_accessor :verbosity

        # Configuration for text generated by the agent.
        sig do
          params(

            format_: T.nilable(
              T.any(OpenAI::Beta::TextFormatParam::Text::OrHash, OpenAI::Beta::TextFormatParam::JSONSchema::OrHash)
            ),

            verbosity: T.nilable(OpenAI::Beta::AgentTextParam::Verbosity::OrSymbol)
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The output format for generated text.
          format_: nil,

          # The amount of text the model should produce.

          verbosity: nil
        )
        end

        sig do
          override.returns(
            {
              format_: T.nilable(T.any(OpenAI::Beta::TextFormatParam::Text, OpenAI::Beta::TextFormatParam::JSONSchema)),
              verbosity: T.nilable(OpenAI::Beta::AgentTextParam::Verbosity::OrSymbol)
            }
          )
        end
        def to_hash
        end

        # The amount of text the model should produce.
        module Verbosity
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::AgentTextParam::Verbosity) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          # Produces less text.
          LOW = T.let(:low, OpenAI::Beta::AgentTextParam::Verbosity::TaggedSymbol)

          # Uses the default amount of text.
          MEDIUM = T.let(:medium, OpenAI::Beta::AgentTextParam::Verbosity::TaggedSymbol)

          # Produces more text.
          HIGH = T.let(:high, OpenAI::Beta::AgentTextParam::Verbosity::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Beta::AgentTextParam::Verbosity::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
