# typed: strong

module OpenAI
  module Models

    module Beta

      class Agent < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::Agent,
            OpenAI::Internal::AnyHash
          )
        end

        # The ID of the reusable agent.
        sig { returns(String) }
        attr_accessor :id

        # The Unix timestamp, in seconds, when the agent was created.
        sig { returns(Integer) }
        attr_accessor :created_at

        # Custom instructions appended to the agent's default base instructions.
        sig { returns(T.nilable(String)) }
        attr_accessor :instructions

        # Custom string key-value pairs attached to the agent.
        sig { returns(T::Hash[Symbol, String]) }
        attr_accessor :metadata

        # The requested model name used for inference.
        sig { returns(String) }
        attr_accessor :model

        # The resolved configuration for creating and coordinating subagents.
        sig { returns(OpenAI::Beta::MultiAgentConfig) }
        attr_reader :multi_agent

        sig { params(multi_agent: OpenAI::Beta::MultiAgentConfig::OrHash).void }
        attr_writer :multi_agent

        # A human-readable name for the agent, or null if it is unnamed.
        sig { returns(T.nilable(String)) }
        attr_accessor :name

        # The object type. Always `agent`.
        sig { returns(Symbol) }
        attr_accessor :object

        # The resolved reasoning configuration, including the model default for an omitted
        # effort.
        sig { returns(OpenAI::Beta::AgentReasoning) }
        attr_reader :reasoning

        sig { params(reasoning: OpenAI::Beta::AgentReasoning::OrHash).void }
        attr_writer :reasoning

        # The resolved service-tier policy used for model requests.
        sig { returns(OpenAI::Beta::Agent::ServiceTier::TaggedSymbol) }
        attr_accessor :service_tier

        # The resolved configuration for text generated by the agent.
        sig { returns(OpenAI::Beta::AgentText) }
        attr_reader :text

        sig { params(text: OpenAI::Beta::AgentText::OrHash).void }
        attr_writer :text

        # Tools available to the agent.
        sig { returns(T::Array[OpenAI::Beta::PersistedAgentTool::Variants]) }
        attr_accessor :tools

        # The Unix timestamp, in seconds, when the agent was last updated.
        sig { returns(Integer) }
        attr_accessor :updated_at

        # A reusable agent scoped to the caller's project.
        sig do
          params(

            id: String,

            created_at: Integer,

            instructions: T.nilable(String),

            metadata: T::Hash[Symbol, String],

            model: String,

            multi_agent: OpenAI::Beta::MultiAgentConfig::OrHash,

            name: T.nilable(String),

            reasoning: OpenAI::Beta::AgentReasoning::OrHash,

            service_tier: OpenAI::Beta::Agent::ServiceTier::OrSymbol,

            text: OpenAI::Beta::AgentText::OrHash,

            tools: T::Array[
              T.any(
                OpenAI::Beta::PersistedAgentTool::Function::OrHash,
                OpenAI::Beta::PersistedAgentTool::ToolSearch::OrHash,
                OpenAI::Beta::PersistedAgentTool::ProgrammaticToolCalling::OrHash,
                OpenAI::Beta::PersistedAgentTool::Mcp::OrHash,
                OpenAI::Beta::PersistedAgentTool::WebSearch::OrHash
              )
            ],

            updated_at: Integer,

            object: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The ID of the reusable agent.
          id:,

          # The Unix timestamp, in seconds, when the agent was created.
          created_at:,

          # Custom instructions appended to the agent's default base instructions.
          instructions:,

          # Custom string key-value pairs attached to the agent.
          metadata:,

          # The requested model name used for inference.
          model:,

          # The resolved configuration for creating and coordinating subagents.
          multi_agent:,

          # A human-readable name for the agent, or null if it is unnamed.
          name:,

          # The resolved reasoning configuration, including the model default for an omitted
          # effort.
          reasoning:,

          # The resolved service-tier policy used for model requests.
          service_tier:,

          # The resolved configuration for text generated by the agent.
          text:,

          # Tools available to the agent.
          tools:,

          # The Unix timestamp, in seconds, when the agent was last updated.
          updated_at:,

          # The object type. Always `agent`.

          object: :agent
        )
        end

        sig do
          override.returns(
            {
              id: String,
              created_at: Integer,
              instructions: T.nilable(String),
              metadata: T::Hash[Symbol, String],
              model: String,
              multi_agent: OpenAI::Beta::MultiAgentConfig,
              name: T.nilable(String),
              object: Symbol,
              reasoning: OpenAI::Beta::AgentReasoning,
              service_tier: OpenAI::Beta::Agent::ServiceTier::TaggedSymbol,
              text: OpenAI::Beta::AgentText,
              tools: T::Array[OpenAI::Beta::PersistedAgentTool::Variants],
              updated_at: Integer
            }
          )
        end
        def to_hash
        end

        # The resolved service-tier policy used for model requests.
        module ServiceTier
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::Agent::ServiceTier) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          AUTO = T.let(:auto, OpenAI::Beta::Agent::ServiceTier::TaggedSymbol)
          DEFAULT = T.let(:default, OpenAI::Beta::Agent::ServiceTier::TaggedSymbol)
          FLEX = T.let(:flex, OpenAI::Beta::Agent::ServiceTier::TaggedSymbol)
          PRIORITY = T.let(:priority, OpenAI::Beta::Agent::ServiceTier::TaggedSymbol)
          FAST = T.let(:fast, OpenAI::Beta::Agent::ServiceTier::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Beta::Agent::ServiceTier::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
