# typed: strong

module OpenAI
  module Models

    module Beta

      class AgentCreateParams < OpenAI::Internal::Type::BaseModel

        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::AgentCreateParams,
            OpenAI::Internal::AnyHash
          )
        end

        # The model to use for the agent. The requested model name is preserved.
        sig { returns(String) }
        attr_accessor :model

        # Additional instructions appended to the agent's default base instructions. Omit
        # or set to null to add no custom instructions.
        sig { returns(T.nilable(String)) }
        attr_accessor :instructions

        # Up to 16 string key-value pairs, with keys up to 64 and values up to 512
        # characters. Omission or null defaults to an empty map.
        sig { returns(T.nilable(T::Hash[Symbol, String])) }
        attr_accessor :metadata

        # Explicit configuration for creating and coordinating subagents.
        sig { returns(T.nilable(OpenAI::Beta::MultiAgentConfigParam)) }
        attr_reader :multi_agent

        sig { params(multi_agent: T.nilable(OpenAI::Beta::MultiAgentConfigParam::OrHash)).void }
        attr_writer :multi_agent

        # A human-readable name for the agent. Omission or null leaves the agent unnamed.
        sig { returns(T.nilable(String)) }
        attr_accessor :name

        # Reasoning configuration for the agent.
        sig { returns(T.nilable(OpenAI::Beta::AgentReasoningParam)) }
        attr_reader :reasoning

        sig { params(reasoning: T.nilable(OpenAI::Beta::AgentReasoningParam::OrHash)).void }
        attr_writer :reasoning

        # The service tier used for model requests.
        sig { returns(T.nilable(OpenAI::Beta::AgentCreateParams::ServiceTier::OrSymbol)) }
        attr_accessor :service_tier

        # Configuration for text generated by the agent.
        sig { returns(T.nilable(OpenAI::Beta::AgentTextParam)) }
        attr_reader :text

        sig { params(text: T.nilable(OpenAI::Beta::AgentTextParam::OrHash)).void }
        attr_writer :text

        # Tools available to the agent. Defaults to an empty list.
        sig {
          returns(
            T.nilable(
              T::Array[
                T.any(
                  OpenAI::Beta::PersistedAgentToolParam::Function,
                  OpenAI::Beta::PersistedAgentToolParam::ToolSearch,
                  OpenAI::Beta::PersistedAgentToolParam::ProgrammaticToolCalling,
                  OpenAI::Beta::PersistedAgentToolParam::Mcp,
                  OpenAI::Beta::PersistedAgentToolParam::WebSearch
                )
              ]
            )
          )
        }
        attr_accessor :tools

        sig do
          params(

            model: String,

            instructions: T.nilable(String),

            metadata: T.nilable(T::Hash[Symbol, String]),

            multi_agent: T.nilable(OpenAI::Beta::MultiAgentConfigParam::OrHash),

            name: T.nilable(String),

            reasoning: T.nilable(OpenAI::Beta::AgentReasoningParam::OrHash),

            service_tier: T.nilable(OpenAI::Beta::AgentCreateParams::ServiceTier::OrSymbol),

            text: T.nilable(OpenAI::Beta::AgentTextParam::OrHash),

            tools: T.nilable(
              T::Array[
                T.any(
                  OpenAI::Beta::PersistedAgentToolParam::Function::OrHash,
                  OpenAI::Beta::PersistedAgentToolParam::ToolSearch::OrHash,
                  OpenAI::Beta::PersistedAgentToolParam::ProgrammaticToolCalling::OrHash,
                  OpenAI::Beta::PersistedAgentToolParam::Mcp::OrHash,
                  OpenAI::Beta::PersistedAgentToolParam::WebSearch::OrHash
                )
              ]
            ),

            request_options: OpenAI::RequestOptions::OrHash
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The model to use for the agent. The requested model name is preserved.
          model:,

          # Additional instructions appended to the agent's default base instructions. Omit
          # or set to null to add no custom instructions.
          instructions: nil,

          # Up to 16 string key-value pairs, with keys up to 64 and values up to 512
          # characters. Omission or null defaults to an empty map.
          metadata: nil,

          # Explicit configuration for creating and coordinating subagents.
          multi_agent: nil,

          # A human-readable name for the agent. Omission or null leaves the agent unnamed.
          name: nil,

          # Reasoning configuration for the agent.
          reasoning: nil,

          # The service tier used for model requests.
          service_tier: nil,

          # Configuration for text generated by the agent.
          text: nil,

          # Tools available to the agent. Defaults to an empty list.
          tools: nil,

          request_options: {}
        )
        end

        sig do
          override.returns(
            {
              model: String,
              instructions: T.nilable(String),
              metadata: T.nilable(T::Hash[Symbol, String]),
              multi_agent: T.nilable(OpenAI::Beta::MultiAgentConfigParam),
              name: T.nilable(String),
              reasoning: T.nilable(OpenAI::Beta::AgentReasoningParam),
              service_tier: T.nilable(OpenAI::Beta::AgentCreateParams::ServiceTier::OrSymbol),
              text: T.nilable(OpenAI::Beta::AgentTextParam),
              tools: T.nilable(
                T::Array[
                  T.any(
                    OpenAI::Beta::PersistedAgentToolParam::Function,
                    OpenAI::Beta::PersistedAgentToolParam::ToolSearch,
                    OpenAI::Beta::PersistedAgentToolParam::ProgrammaticToolCalling,
                    OpenAI::Beta::PersistedAgentToolParam::Mcp,
                    OpenAI::Beta::PersistedAgentToolParam::WebSearch
                  )
                ]
              ),
              request_options: OpenAI::RequestOptions
            }
          )
        end
        def to_hash
        end

        # The service tier used for model requests.
        module ServiceTier
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::AgentCreateParams::ServiceTier) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          # Selects the service tier automatically.
          AUTO = T.let(:auto, OpenAI::Beta::AgentCreateParams::ServiceTier::TaggedSymbol)

          # Uses the default service tier.
          DEFAULT = T.let(:default, OpenAI::Beta::AgentCreateParams::ServiceTier::TaggedSymbol)

          # Uses the flex service tier.
          FLEX = T.let(:flex, OpenAI::Beta::AgentCreateParams::ServiceTier::TaggedSymbol)

          # Uses the priority service tier.
          PRIORITY = T.let(:priority, OpenAI::Beta::AgentCreateParams::ServiceTier::TaggedSymbol)

          # Uses the fast service tier.
          FAST = T.let(:fast, OpenAI::Beta::AgentCreateParams::ServiceTier::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Beta::AgentCreateParams::ServiceTier::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
