# typed: strong

module OpenAI
  module Models

    BetaResponseFunctionToolCallItem = Beta::BetaResponseFunctionToolCallItem

    module Beta

      class BetaResponseFunctionToolCallItem < OpenAI::Models::Beta::BetaResponseFunctionToolCall

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::BetaResponseFunctionToolCallItem,
            OpenAI::Internal::AnyHash
          )
        end

        # The unique ID of the function tool call.
        sig { returns(String) }
        attr_accessor :id

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig { returns(OpenAI::Beta::BetaResponseFunctionToolCallItem::Status::TaggedSymbol) }
        attr_accessor :status

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A tool call to run a function. See the
        # [function calling guide](https://platform.openai.com/docs/guides/function-calling)
        # for more information.
        sig do
          params(

            arguments: String,

            call_id: String,

            name: String,

            id: String,

            status: OpenAI::Beta::BetaResponseFunctionToolCallItem::Status::OrSymbol,

            agent: T.nilable(OpenAI::Beta::BetaResponseFunctionToolCall::Agent::OrHash),

            async: T::Boolean,

            caller_: T.nilable(
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct::OrHash,
                OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program::OrHash
              )
            ),

            namespace: String,

            created_by: String,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # A JSON string of the arguments to pass to the function.
          arguments:,

          # The unique ID of the function tool call generated by the model.
          call_id:,

          # The name of the function to run.
          name:,

          # The unique ID of the function tool call.
          id:,

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,

          # The agent that produced this item.
          agent: nil,

          # Whether the function tool call runs asynchronously.
          async: nil,

          # The execution context that produced this tool call.
          caller_: nil,

          # The namespace of the function to run.
          namespace: nil,

          # The identifier of the actor that created the item.
          created_by: nil,

          # The type of the function tool call. Always `function_call`.

          type: :function_call
        )
        end

        sig do
          override.returns(
            {
              arguments: String,
              call_id: String,
              name: String,
              id: String,
              status: OpenAI::Beta::BetaResponseFunctionToolCallItem::Status::TaggedSymbol,
              type: Symbol,
              agent: T.nilable(OpenAI::Beta::BetaResponseFunctionToolCall::Agent),
              async: T::Boolean,
              caller_: T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct,
                  OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program
                )
              ),
              namespace: String,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::BetaResponseFunctionToolCallItem::Status) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS = T.let(:in_progress, OpenAI::Beta::BetaResponseFunctionToolCallItem::Status::TaggedSymbol)
          COMPLETED = T.let(:completed, OpenAI::Beta::BetaResponseFunctionToolCallItem::Status::TaggedSymbol)
          INCOMPLETE = T.let(:incomplete, OpenAI::Beta::BetaResponseFunctionToolCallItem::Status::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Beta::BetaResponseFunctionToolCallItem::Status::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
