# typed: strong

module OpenAI
  module Models

    BetaResponseFunctionToolCallOutputItem = Beta::BetaResponseFunctionToolCallOutputItem

    module Beta

      class BetaResponseFunctionToolCallOutputItem < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::BetaResponseFunctionToolCallOutputItem,
            OpenAI::Internal::AnyHash
          )
        end

        # The unique ID of the function call tool output.
        sig { returns(String) }
        attr_accessor :id

        # The output from the function call generated by your code. Can be a string or an
        # list of output content.
        sig { returns(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants) }
        attr_accessor :output

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig { returns(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol) }
        attr_accessor :status

        # The type of the function tool call output. Always `function_call_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent)) }
        attr_reader :agent

        sig { params(agent: T.nilable(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent::OrHash)).void }
        attr_writer :agent

        # The unique ID of the function tool call generated by the model.
        sig { returns(T.nilable(String)) }
        attr_reader :call_id

        sig { params(call_id: String).void }
        attr_writer :call_id

        # The execution context that produced this tool call.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Variants)) }
        attr_accessor :caller_

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # The name of the tool that produced the output.
        sig { returns(T.nilable(String)) }
        attr_reader :name

        sig { params(name: String).void }
        attr_writer :name

        # The namespace of the tool that produced the output.
        sig { returns(T.nilable(String)) }
        attr_reader :namespace

        sig { params(namespace: String).void }
        attr_writer :namespace

        sig do
          params(

            id: String,

            output: OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants,

            status: OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::OrSymbol,

            agent: T.nilable(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent::OrHash),

            call_id: String,

            caller_: T.nilable(
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct::OrHash,
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program::OrHash
              )
            ),

            created_by: String,

            name: String,

            namespace: String,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The unique ID of the function call tool output.
          id:,

          # The output from the function call generated by your code. Can be a string or an
          # list of output content.
          output:,

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,

          # The agent that produced this item.
          agent: nil,

          # The unique ID of the function tool call generated by the model.
          call_id: nil,

          # The execution context that produced this tool call.
          caller_: nil,

          # The identifier of the actor that created the item.
          created_by: nil,

          # The name of the tool that produced the output.
          name: nil,

          # The namespace of the tool that produced the output.
          namespace: nil,

          # The type of the function tool call output. Always `function_call_output`.

          type: :function_call_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              output: OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants,
              status: OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol,
              type: Symbol,
              agent: T.nilable(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent),
              call_id: String,
              caller_: T.nilable(OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Variants),
              created_by: String,
              name: String,
              namespace: String
            }
          )
        end
        def to_hash
        end

        # The output from the function call generated by your code. Can be a string or an
        # list of output content.
        module Output
          extend OpenAI::Internal::Type::Union

          Variants = T.type_alias {
            T.any(
              String,
              T::Array[OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentList::Variants]
            )
          }

          # A text input to the model.
          module OutputContentList
            extend OpenAI::Internal::Type::Union

            Variants = T.type_alias {
              T.any(
                OpenAI::Beta::BetaResponseInputText,
                OpenAI::Beta::BetaResponseInputImage,
                OpenAI::Beta::BetaResponseInputFile
              )
            }

            sig {
              override.returns(
                T::Array[OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentList::Variants]
              )
            }
            def self.variants
            end

          end

          sig { override.returns(T::Array[OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants]) }
          def self.variants
          end

          OutputContentListArray = T.let(
            OpenAI::Internal::Type::ArrayOf[
              union: OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentList
            ],
            OpenAI::Internal::Type::Converter
          )

        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS = T.let(:in_progress, OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol)
          COMPLETED = T.let(:completed, OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol)
          INCOMPLETE = T.let(:incomplete, OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol)

          sig {
            override.returns(T::Array[OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol])
          }
          def self.values
          end
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent,
              OpenAI::Internal::AnyHash
            )
          end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig do
            params(

              agent_name: String
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The canonical name of the agent that produced this item.

            agent_name:
          )
          end

          sig do
            override.returns(
              {agent_name: String}
            )
          end
          def to_hash
          end

        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants = T.type_alias {
            T.any(
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct,
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program
            )
          }

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct,
                OpenAI::Internal::AnyHash
              )
            end

            # The caller type. Always `direct`.
            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              # The caller type. Always `direct`.

              type: :direct
            )
            end

            sig do
              override.returns(
                {type: Symbol}
              )
            end
            def to_hash
            end

          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program,
                OpenAI::Internal::AnyHash
              )
            end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            # The caller type. Always `program`.
            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                caller_id: String,

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              # The call ID of the program item that produced this tool call.
              caller_id:,

              # The caller type. Always `program`.

              type: :program
            )
            end

            sig do
              override.returns(
                {caller_id: String, type: Symbol}
              )
            end
            def to_hash
            end

          end

          sig { override.returns(T::Array[OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Variants]) }
          def self.variants
          end

        end

      end

    end

  end
end
