# typed: strong

module OpenAI
  module Models
    BetaResponseFunctionShellToolCallOutput =
      Beta::BetaResponseFunctionShellToolCallOutput

    module Beta
      class BetaResponseFunctionShellToolCallOutput < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the shell call output. Populated when this item is returned via
        # API.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the shell tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The maximum length of the shell command output. This is generated by the model
        # and should be passed back with the raw output.
        sig { returns(T.nilable(Integer)) }
        attr_accessor :max_output_length

        # An array of shell call output contents
        sig do
          returns(
            T::Array[
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output
            ]
          )
        end
        attr_accessor :output

        # The status of the shell call output. One of `in_progress`, `completed`, or
        # `incomplete`.
        sig do
          returns(
            OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the shell call output. Always `shell_call_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Agent
            )
          )
        end
        attr_reader :agent

        sig do
          params(
            agent:
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Agent::OrHash
          ).void
        end
        attr_writer :agent

        # The execution context that produced this tool call.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Variants
            )
          )
        end
        attr_accessor :caller_

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # The output of a shell tool call that was emitted.
        sig do
          params(
            id: String,
            call_id: String,
            max_output_length: T.nilable(Integer),
            output:
              T::Array[
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::OrHash
              ],
            status:
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status::OrSymbol,
            agent:
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Agent::OrHash,
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Direct::OrHash,
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Program::OrHash
                )
              ),
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the shell call output. Populated when this item is returned via
          # API.
          id:,
          # The unique ID of the shell tool call generated by the model.
          call_id:,
          # The maximum length of the shell command output. This is generated by the model
          # and should be passed back with the raw output.
          max_output_length:,
          # An array of shell call output contents
          output:,
          # The status of the shell call output. One of `in_progress`, `completed`, or
          # `incomplete`.
          status:,
          # The agent that produced this item.
          agent: nil,
          # The execution context that produced this tool call.
          caller_: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the shell call output. Always `shell_call_output`.
          type: :shell_call_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: String,
              max_output_length: T.nilable(Integer),
              output:
                T::Array[
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output
                ],
              status:
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status::TaggedSymbol,
              type: Symbol,
              agent:
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Agent,
              caller_:
                T.nilable(
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Variants
                ),
              created_by: String
            }
          )
        end
        def to_hash
        end

        class Output < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output,
                OpenAI::Internal::AnyHash
              )
            end

          # Represents either an exit outcome (with an exit code) or a timeout outcome for a
          # shell call output chunk.
          sig do
            returns(
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Variants
            )
          end
          attr_accessor :outcome

          # The standard error output that was captured.
          sig { returns(String) }
          attr_accessor :stderr

          # The standard output that was captured.
          sig { returns(String) }
          attr_accessor :stdout

          # The identifier of the actor that created the item.
          sig { returns(T.nilable(String)) }
          attr_reader :created_by

          sig { params(created_by: String).void }
          attr_writer :created_by

          # The content of a shell tool call output that was emitted.
          sig do
            params(
              outcome:
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Timeout::OrHash,
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Exit::OrHash
                ),
              stderr: String,
              stdout: String,
              created_by: String
            ).returns(T.attached_class)
          end
          def self.new(
            # Represents either an exit outcome (with an exit code) or a timeout outcome for a
            # shell call output chunk.
            outcome:,
            # The standard error output that was captured.
            stderr:,
            # The standard output that was captured.
            stdout:,
            # The identifier of the actor that created the item.
            created_by: nil
          )
          end

          sig do
            override.returns(
              {
                outcome:
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Variants,
                stderr: String,
                stdout: String,
                created_by: String
              }
            )
          end
          def to_hash
          end

          # Represents either an exit outcome (with an exit code) or a timeout outcome for a
          # shell call output chunk.
          module Outcome
            extend OpenAI::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Timeout,
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Exit
                )
              end

            class Timeout < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Timeout,
                    OpenAI::Internal::AnyHash
                  )
                end

              # The outcome type. Always `timeout`.
              sig { returns(Symbol) }
              attr_accessor :type

              # Indicates that the shell call exceeded its configured time limit.
              sig { params(type: Symbol).returns(T.attached_class) }
              def self.new(
                # The outcome type. Always `timeout`.
                type: :timeout
              )
              end

              sig { override.returns({ type: Symbol }) }
              def to_hash
              end
            end

            class Exit < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Exit,
                    OpenAI::Internal::AnyHash
                  )
                end

              # Exit code from the shell process.
              sig { returns(Integer) }
              attr_accessor :exit_code

              # The outcome type. Always `exit`.
              sig { returns(Symbol) }
              attr_accessor :type

              # Indicates that the shell commands finished and returned an exit code.
              sig do
                params(exit_code: Integer, type: Symbol).returns(
                  T.attached_class
                )
              end
              def self.new(
                # Exit code from the shell process.
                exit_code:,
                # The outcome type. Always `exit`.
                type: :exit
              )
              end

              sig { override.returns({ exit_code: Integer, type: Symbol }) }
              def to_hash
              end
            end

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Output::Outcome::Variants
                ]
              )
            end
            def self.variants
            end
          end
        end

        # The status of the shell call output. One of `in_progress`, `completed`, or
        # `incomplete`.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Direct,
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Program
              )
            end

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Direct,
                  OpenAI::Internal::AnyHash
                )
              end

            sig { returns(Symbol) }
            attr_accessor :type

            sig { params(type: Symbol).returns(T.attached_class) }
            def self.new(type: :direct)
            end

            sig { override.returns({ type: Symbol }) }
            def to_hash
            end
          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Program,
                  OpenAI::Internal::AnyHash
                )
              end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(caller_id: String, type: Symbol).returns(T.attached_class)
            end
            def self.new(
              # The call ID of the program item that produced this tool call.
              caller_id:,
              type: :program
            )
            end

            sig { override.returns({ caller_id: String, type: Symbol }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::Caller::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
