# typed: strong

module OpenAI
  module Models
    BetaEasyInputMessage = Beta::BetaEasyInputMessage

    module Beta
      class BetaEasyInputMessage < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(OpenAI::Beta::BetaEasyInputMessage, OpenAI::Internal::AnyHash)
          end

        # Text, image, or audio input to the model, used to generate a response. Can also
        # contain previous assistant responses.
        sig { returns(OpenAI::Beta::BetaEasyInputMessage::Content::Variants) }
        attr_accessor :content

        # The role of the message input. One of `user`, `assistant`, `system`, or
        # `developer`.
        sig { returns(OpenAI::Beta::BetaEasyInputMessage::Role::OrSymbol) }
        attr_accessor :role

        # Labels an `assistant` message as intermediate commentary (`commentary`) or the
        # final answer (`final_answer`). For models like `gpt-5.3-codex` and beyond, when
        # sending follow-up requests, preserve and resend phase on all assistant messages
        # — dropping it can degrade performance. Not used for user messages.
        sig do
          returns(
            T.nilable(OpenAI::Beta::BetaEasyInputMessage::Phase::OrSymbol)
          )
        end
        attr_accessor :phase

        # The type of the message input. Always `message`.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaEasyInputMessage::Type::OrSymbol))
        end
        attr_reader :type

        sig do
          params(type: OpenAI::Beta::BetaEasyInputMessage::Type::OrSymbol).void
        end
        attr_writer :type

        # A message input to the model with a role indicating instruction following
        # hierarchy. Instructions given with the `developer` or `system` role take
        # precedence over instructions given with the `user` role. Messages with the
        # `assistant` role are presumed to have been generated by the model in previous
        # interactions.
        sig do
          params(
            content: OpenAI::Beta::BetaEasyInputMessage::Content::Variants,
            role: OpenAI::Beta::BetaEasyInputMessage::Role::OrSymbol,
            phase:
              T.nilable(OpenAI::Beta::BetaEasyInputMessage::Phase::OrSymbol),
            type: OpenAI::Beta::BetaEasyInputMessage::Type::OrSymbol
          ).returns(T.attached_class)
        end
        def self.new(
          # Text, image, or audio input to the model, used to generate a response. Can also
          # contain previous assistant responses.
          content:,
          # The role of the message input. One of `user`, `assistant`, `system`, or
          # `developer`.
          role:,
          # Labels an `assistant` message as intermediate commentary (`commentary`) or the
          # final answer (`final_answer`). For models like `gpt-5.3-codex` and beyond, when
          # sending follow-up requests, preserve and resend phase on all assistant messages
          # — dropping it can degrade performance. Not used for user messages.
          phase: nil,
          # The type of the message input. Always `message`.
          type: nil
        )
        end

        sig do
          override.returns(
            {
              content: OpenAI::Beta::BetaEasyInputMessage::Content::Variants,
              role: OpenAI::Beta::BetaEasyInputMessage::Role::OrSymbol,
              phase:
                T.nilable(OpenAI::Beta::BetaEasyInputMessage::Phase::OrSymbol),
              type: OpenAI::Beta::BetaEasyInputMessage::Type::OrSymbol
            }
          )
        end
        def to_hash
        end

        # Text, image, or audio input to the model, used to generate a response. Can also
        # contain previous assistant responses.
        module Content
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                String,
                T::Array[OpenAI::Beta::BetaResponseInputContent::Variants]
              )
            end

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaEasyInputMessage::Content::Variants]
            )
          end
          def self.variants
          end
        end

        # The role of the message input. One of `user`, `assistant`, `system`, or
        # `developer`.
        module Role
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaEasyInputMessage::Role)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          USER =
            T.let(:user, OpenAI::Beta::BetaEasyInputMessage::Role::TaggedSymbol)
          ASSISTANT =
            T.let(
              :assistant,
              OpenAI::Beta::BetaEasyInputMessage::Role::TaggedSymbol
            )
          SYSTEM =
            T.let(
              :system,
              OpenAI::Beta::BetaEasyInputMessage::Role::TaggedSymbol
            )
          DEVELOPER =
            T.let(
              :developer,
              OpenAI::Beta::BetaEasyInputMessage::Role::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaEasyInputMessage::Role::TaggedSymbol]
            )
          end
          def self.values
          end
        end

        # Labels an `assistant` message as intermediate commentary (`commentary`) or the
        # final answer (`final_answer`). For models like `gpt-5.3-codex` and beyond, when
        # sending follow-up requests, preserve and resend phase on all assistant messages
        # — dropping it can degrade performance. Not used for user messages.
        module Phase
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaEasyInputMessage::Phase)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          COMMENTARY =
            T.let(
              :commentary,
              OpenAI::Beta::BetaEasyInputMessage::Phase::TaggedSymbol
            )
          FINAL_ANSWER =
            T.let(
              :final_answer,
              OpenAI::Beta::BetaEasyInputMessage::Phase::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaEasyInputMessage::Phase::TaggedSymbol]
            )
          end
          def self.values
          end
        end

        # The type of the message input. Always `message`.
        module Type
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaEasyInputMessage::Type)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          MESSAGE =
            T.let(
              :message,
              OpenAI::Beta::BetaEasyInputMessage::Type::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaEasyInputMessage::Type::TaggedSymbol]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
