# typed: strong

module OpenAI
  module Models
    BetaResponseCustomToolCallItem = Beta::BetaResponseCustomToolCallItem

    module Beta
      class BetaResponseCustomToolCallItem < OpenAI::Models::Beta::BetaResponseCustomToolCall
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseCustomToolCallItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the custom tool call item.
        sig { returns(String) }
        attr_accessor :id

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig do
          returns(
            OpenAI::Beta::BetaResponseCustomToolCallItem::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A call to a custom tool created by the model.
        sig do
          params(
            call_id: String,
            input: String,
            name: String,
            id: String,
            status:
              OpenAI::Beta::BetaResponseCustomToolCallItem::Status::OrSymbol,
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseCustomToolCall::Agent::OrHash
              ),
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseCustomToolCall::Caller::Direct::OrHash,
                  OpenAI::Beta::BetaResponseCustomToolCall::Caller::Program::OrHash
                )
              ),
            namespace: String,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # An identifier used to map this custom tool call to a tool call output.
          call_id:,
          # The input for the custom tool call generated by the model.
          input:,
          # The name of the custom tool being called.
          name:,
          # The unique ID of the custom tool call item.
          id:,
          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,
          # The agent that produced this item.
          agent: nil,
          # The execution context that produced this tool call.
          caller_: nil,
          # The namespace of the custom tool being called.
          namespace: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the custom tool call. Always `custom_tool_call`.
          type: :custom_tool_call
        )
        end

        sig do
          override.returns(
            {
              call_id: String,
              input: String,
              name: String,
              id: String,
              status:
                OpenAI::Beta::BetaResponseCustomToolCallItem::Status::TaggedSymbol,
              type: Symbol,
              agent: T.nilable(OpenAI::Beta::BetaResponseCustomToolCall::Agent),
              caller_:
                T.nilable(
                  T.any(
                    OpenAI::Beta::BetaResponseCustomToolCall::Caller::Direct,
                    OpenAI::Beta::BetaResponseCustomToolCall::Caller::Program
                  )
                ),
              namespace: String,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Beta::BetaResponseCustomToolCallItem::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseCustomToolCallItem::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseCustomToolCallItem::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseCustomToolCallItem::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseCustomToolCallItem::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
