# typed: strong

module OpenAI
  module Models
    BetaResponseFunctionToolCall = Beta::BetaResponseFunctionToolCall

    module Beta
      class BetaResponseFunctionToolCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseFunctionToolCall,
              OpenAI::Internal::AnyHash
            )
          end

        # A JSON string of the arguments to pass to the function.
        sig { returns(String) }
        attr_accessor :arguments

        # The unique ID of the function tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The name of the function to run.
        sig { returns(String) }
        attr_accessor :name

        # The type of the function tool call. Always `function_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The unique ID of the function tool call.
        sig { returns(T.nilable(String)) }
        attr_reader :id

        sig { params(id: String).void }
        attr_writer :id

        # The agent that produced this item.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaResponseFunctionToolCall::Agent))
        end
        attr_reader :agent

        sig do
          params(
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseFunctionToolCall::Agent::OrHash
              )
          ).void
        end
        attr_writer :agent

        # The execution context that produced this tool call.
        sig do
          returns(
            T.nilable(
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct,
                OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program
              )
            )
          )
        end
        attr_accessor :caller_

        # The namespace of the function to run.
        sig { returns(T.nilable(String)) }
        attr_reader :namespace

        sig { params(namespace: String).void }
        attr_writer :namespace

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponseFunctionToolCall::Status::OrSymbol
            )
          )
        end
        attr_reader :status

        sig do
          params(
            status: OpenAI::Beta::BetaResponseFunctionToolCall::Status::OrSymbol
          ).void
        end
        attr_writer :status

        # A tool call to run a function. See the
        # [function calling guide](https://platform.openai.com/docs/guides/function-calling)
        # for more information.
        sig do
          params(
            arguments: String,
            call_id: String,
            name: String,
            id: String,
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseFunctionToolCall::Agent::OrHash
              ),
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct::OrHash,
                  OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program::OrHash
                )
              ),
            namespace: String,
            status:
              OpenAI::Beta::BetaResponseFunctionToolCall::Status::OrSymbol,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # A JSON string of the arguments to pass to the function.
          arguments:,
          # The unique ID of the function tool call generated by the model.
          call_id:,
          # The name of the function to run.
          name:,
          # The unique ID of the function tool call.
          id: nil,
          # The agent that produced this item.
          agent: nil,
          # The execution context that produced this tool call.
          caller_: nil,
          # The namespace of the function to run.
          namespace: nil,
          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status: nil,
          # The type of the function tool call. Always `function_call`.
          type: :function_call
        )
        end

        sig do
          override.returns(
            {
              arguments: String,
              call_id: String,
              name: String,
              type: Symbol,
              id: String,
              agent:
                T.nilable(OpenAI::Beta::BetaResponseFunctionToolCall::Agent),
              caller_:
                T.nilable(
                  T.any(
                    OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct,
                    OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program
                  )
                ),
              namespace: String,
              status:
                OpenAI::Beta::BetaResponseFunctionToolCall::Status::OrSymbol
            }
          )
        end
        def to_hash
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCall::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct,
                OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program
              )
            end

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Direct,
                  OpenAI::Internal::AnyHash
                )
              end

            sig { returns(Symbol) }
            attr_accessor :type

            sig { params(type: Symbol).returns(T.attached_class) }
            def self.new(type: :direct)
            end

            sig { override.returns({ type: Symbol }) }
            def to_hash
            end
          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Program,
                  OpenAI::Internal::AnyHash
                )
              end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(caller_id: String, type: Symbol).returns(T.attached_class)
            end
            def self.new(
              # The call ID of the program item that produced this tool call.
              caller_id:,
              type: :program
            )
            end

            sig { override.returns({ caller_id: String, type: Symbol }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionToolCall::Caller::Variants
              ]
            )
          end
          def self.variants
          end
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaResponseFunctionToolCall::Status)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseFunctionToolCall::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseFunctionToolCall::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseFunctionToolCall::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionToolCall::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
