# typed: strong

module OpenAI
  module Models

    BetaResponseCustomToolCallOutputItem = Beta::BetaResponseCustomToolCallOutputItem

    module Beta

      class BetaResponseCustomToolCallOutputItem < OpenAI::Models::Beta::BetaResponseCustomToolCallOutput

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::BetaResponseCustomToolCallOutputItem,
            OpenAI::Internal::AnyHash
          )
        end

        # The unique ID of the custom tool call output item.
        sig { returns(String) }
        attr_accessor :id

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig { returns(OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status::TaggedSymbol) }
        attr_accessor :status

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # The output of a custom tool call from your code, being sent back to the model.
        sig do
          params(

            call_id: String,

            output: OpenAI::Beta::BetaResponseCustomToolCallOutput::Output::Variants,

            id: String,

            status: OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status::OrSymbol,

            agent: T.nilable(OpenAI::Beta::BetaResponseCustomToolCallOutput::Agent::OrHash),

            caller_: T.nilable(
              T.any(
                OpenAI::Beta::BetaResponseCustomToolCallOutput::Caller::Direct::OrHash,
                OpenAI::Beta::BetaResponseCustomToolCallOutput::Caller::Program::OrHash
              )
            ),

            created_by: String,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The call ID, used to map this custom tool call output to a custom tool call.
          call_id:,

          # The output from the custom tool call generated by your code. Can be a string or
          # an list of output content.
          output:,

          # The unique ID of the custom tool call output item.
          id:,

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,

          # The agent that produced this item.
          agent: nil,

          # The execution context that produced this tool call.
          caller_: nil,

          # The identifier of the actor that created the item.
          created_by: nil,

          # The type of the custom tool call output. Always `custom_tool_call_output`.

          type: :custom_tool_call_output
        )
        end

        sig do
          override.returns(
            {
              call_id: String,
              output: OpenAI::Beta::BetaResponseCustomToolCallOutput::Output::Variants,
              id: String,
              status: OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status::TaggedSymbol,
              type: Symbol,
              agent: T.nilable(OpenAI::Beta::BetaResponseCustomToolCallOutput::Agent),
              caller_: T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseCustomToolCallOutput::Caller::Direct,
                  OpenAI::Beta::BetaResponseCustomToolCallOutput::Caller::Program
                )
              ),
              created_by: String
            }
          )
        end
        def to_hash
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS = T.let(:in_progress, OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status::TaggedSymbol)
          COMPLETED = T.let(:completed, OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status::TaggedSymbol)
          INCOMPLETE = T.let(:incomplete, OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Beta::BetaResponseCustomToolCallOutputItem::Status::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
