# typed: strong

module OpenAI
  module Models
    BetaResponseFunctionToolCallOutputItem =
      Beta::BetaResponseFunctionToolCallOutputItem

    module Beta
      class BetaResponseFunctionToolCallOutputItem < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the function call tool output.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the function tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The output from the function call generated by your code. Can be a string or an
        # list of output content.
        sig do
          returns(
            OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants
          )
        end
        attr_accessor :output

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig do
          returns(
            OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the function tool call output. Always `function_call_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent
            )
          )
        end
        attr_reader :agent

        sig do
          params(
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent::OrHash
              )
          ).void
        end
        attr_writer :agent

        # The execution context that produced this tool call.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Variants
            )
          )
        end
        attr_accessor :caller_

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        sig do
          params(
            id: String,
            call_id: String,
            output:
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants,
            status:
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::OrSymbol,
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent::OrHash
              ),
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct::OrHash,
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program::OrHash
                )
              ),
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the function call tool output.
          id:,
          # The unique ID of the function tool call generated by the model.
          call_id:,
          # The output from the function call generated by your code. Can be a string or an
          # list of output content.
          output:,
          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,
          # The agent that produced this item.
          agent: nil,
          # The execution context that produced this tool call.
          caller_: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the function tool call output. Always `function_call_output`.
          type: :function_call_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: String,
              output:
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants,
              status:
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol,
              type: Symbol,
              agent:
                T.nilable(
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent
                ),
              caller_:
                T.nilable(
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Variants
                ),
              created_by: String
            }
          )
        end
        def to_hash
        end

        # The output from the function call generated by your code. Can be a string or an
        # list of output content.
        module Output
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                String,
                T::Array[
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentList::Variants
                ]
              )
            end

          # A text input to the model.
          module OutputContentList
            extend OpenAI::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseInputText,
                  OpenAI::Beta::BetaResponseInputImage,
                  OpenAI::Beta::BetaResponseInputFile
                )
              end

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentList::Variants
                ]
              )
            end
            def self.variants
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::Variants
              ]
            )
          end
          def self.variants
          end

          OutputContentListArray =
            T.let(
              OpenAI::Internal::Type::ArrayOf[
                union:
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Output::OutputContentList
              ],
              OpenAI::Internal::Type::Converter
            )
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct,
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program
              )
            end

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Direct,
                  OpenAI::Internal::AnyHash
                )
              end

            # The caller type. Always `direct`.
            sig { returns(Symbol) }
            attr_accessor :type

            sig { params(type: Symbol).returns(T.attached_class) }
            def self.new(
              # The caller type. Always `direct`.
              type: :direct
            )
            end

            sig { override.returns({ type: Symbol }) }
            def to_hash
            end
          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Program,
                  OpenAI::Internal::AnyHash
                )
              end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            # The caller type. Always `program`.
            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(caller_id: String, type: Symbol).returns(T.attached_class)
            end
            def self.new(
              # The call ID of the program item that produced this tool call.
              caller_id:,
              # The caller type. Always `program`.
              type: :program
            )
            end

            sig { override.returns({ caller_id: String, type: Symbol }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::Caller::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
