# typed: strong

module OpenAI
  module Models
    BetaResponseCompactionItemParam = Beta::BetaResponseCompactionItemParam

    module Beta
      class BetaResponseCompactionItemParam < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseCompactionItemParam,
              OpenAI::Internal::AnyHash
            )
          end

        # The encrypted content of the compaction summary.
        sig { returns(String) }
        attr_accessor :encrypted_content

        # The type of the item. Always `compaction`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The ID of the compaction item.
        sig { returns(T.nilable(String)) }
        attr_accessor :id

        # The agent that produced this item.
        sig do
          returns(
            T.nilable(OpenAI::Beta::BetaResponseCompactionItemParam::Agent)
          )
        end
        attr_reader :agent

        sig do
          params(
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseCompactionItemParam::Agent::OrHash
              )
          ).void
        end
        attr_writer :agent

        # A compaction item generated by the
        # [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        sig do
          params(
            encrypted_content: String,
            id: T.nilable(String),
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseCompactionItemParam::Agent::OrHash
              ),
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The encrypted content of the compaction summary.
          encrypted_content:,
          # The ID of the compaction item.
          id: nil,
          # The agent that produced this item.
          agent: nil,
          # The type of the item. Always `compaction`.
          type: :compaction
        )
        end

        sig do
          override.returns(
            {
              encrypted_content: String,
              type: Symbol,
              id: T.nilable(String),
              agent:
                T.nilable(OpenAI::Beta::BetaResponseCompactionItemParam::Agent)
            }
          )
        end
        def to_hash
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseCompactionItemParam::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end
      end
    end
  end
end
