# typed: strong

module OpenAI
  module Models
    BetaResponseCompactionItem = Beta::BetaResponseCompactionItem

    module Beta
      class BetaResponseCompactionItem < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseCompactionItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the compaction item.
        sig { returns(String) }
        attr_accessor :id

        # The encrypted content that was produced by compaction.
        sig { returns(String) }
        attr_accessor :encrypted_content

        # The type of the item. Always `compaction`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaResponseCompactionItem::Agent))
        end
        attr_reader :agent

        sig do
          params(
            agent: OpenAI::Beta::BetaResponseCompactionItem::Agent::OrHash
          ).void
        end
        attr_writer :agent

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A compaction item generated by the
        # [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        sig do
          params(
            id: String,
            encrypted_content: String,
            agent: OpenAI::Beta::BetaResponseCompactionItem::Agent::OrHash,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the compaction item.
          id:,
          # The encrypted content that was produced by compaction.
          encrypted_content:,
          # The agent that produced this item.
          agent: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the item. Always `compaction`.
          type: :compaction
        )
        end

        sig do
          override.returns(
            {
              id: String,
              encrypted_content: String,
              type: Symbol,
              agent: OpenAI::Beta::BetaResponseCompactionItem::Agent,
              created_by: String
            }
          )
        end
        def to_hash
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseCompactionItem::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end
      end
    end
  end
end
