# typed: strong

module OpenAI
  module Models
    BetaResponseToolSearchOutputItem = Beta::BetaResponseToolSearchOutputItem

    module Beta
      class BetaResponseToolSearchOutputItem < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseToolSearchOutputItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the tool search output item.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the tool search call generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :call_id

        # Whether tool search was executed by the server or by the client.
        sig do
          returns(
            OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution::TaggedSymbol
          )
        end
        attr_accessor :execution

        # The status of the tool search output item that was recorded.
        sig do
          returns(
            OpenAI::Beta::BetaResponseToolSearchOutputItem::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The loaded tool definitions returned by tool search.
        sig { returns(T::Array[OpenAI::Beta::BetaTool::Variants]) }
        attr_accessor :tools

        # The type of the item. Always `tool_search_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig do
          returns(
            T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItem::Agent)
          )
        end
        attr_reader :agent

        sig do
          params(
            agent: OpenAI::Beta::BetaResponseToolSearchOutputItem::Agent::OrHash
          ).void
        end
        attr_writer :agent

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        sig do
          params(
            id: String,
            call_id: T.nilable(String),
            execution:
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution::OrSymbol,
            status:
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Status::OrSymbol,
            tools:
              T::Array[
                T.any(
                  OpenAI::Beta::BetaFunctionTool::OrHash,
                  OpenAI::Beta::BetaFileSearchTool::OrHash,
                  OpenAI::Beta::BetaComputerTool::OrHash,
                  OpenAI::Beta::BetaComputerUsePreviewTool::OrHash,
                  OpenAI::Beta::BetaTool::Mcp::OrHash,
                  OpenAI::Beta::BetaTool::CodeInterpreter::OrHash,
                  OpenAI::Beta::BetaTool::ProgrammaticToolCalling::OrHash,
                  OpenAI::Beta::BetaTool::ImageGeneration::OrHash,
                  OpenAI::Beta::BetaTool::LocalShell::OrHash,
                  OpenAI::Beta::BetaFunctionShellTool::OrHash,
                  OpenAI::Beta::BetaCustomTool::OrHash,
                  OpenAI::Beta::BetaNamespaceTool::OrHash,
                  OpenAI::Beta::BetaToolSearchTool::OrHash,
                  OpenAI::Beta::BetaApplyPatchTool::OrHash,
                  OpenAI::Beta::BetaWebSearchTool::OrHash,
                  OpenAI::Beta::BetaWebSearchPreviewTool::OrHash
                )
              ],
            agent:
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Agent::OrHash,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the tool search output item.
          id:,
          # The unique ID of the tool search call generated by the model.
          call_id:,
          # Whether tool search was executed by the server or by the client.
          execution:,
          # The status of the tool search output item that was recorded.
          status:,
          # The loaded tool definitions returned by tool search.
          tools:,
          # The agent that produced this item.
          agent: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the item. Always `tool_search_output`.
          type: :tool_search_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: T.nilable(String),
              execution:
                OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution::TaggedSymbol,
              status:
                OpenAI::Beta::BetaResponseToolSearchOutputItem::Status::TaggedSymbol,
              tools: T::Array[OpenAI::Beta::BetaTool::Variants],
              type: Symbol,
              agent: OpenAI::Beta::BetaResponseToolSearchOutputItem::Agent,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # Whether tool search was executed by the server or by the client.
        module Execution
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          SERVER =
            T.let(
              :server,
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution::TaggedSymbol
            )
          CLIENT =
            T.let(
              :client,
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        # The status of the tool search output item that was recorded.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Beta::BetaResponseToolSearchOutputItem::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseToolSearchOutputItem::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseToolSearchOutputItem::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseToolSearchOutputItem::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end
      end
    end
  end
end
