# typed: strong

module OpenAI
  module Models
    BetaResponseToolSearchCall = Beta::BetaResponseToolSearchCall

    module Beta
      class BetaResponseToolSearchCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseToolSearchCall,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the tool search call item.
        sig { returns(String) }
        attr_accessor :id

        # Arguments used for the tool search call.
        sig { returns(T.anything) }
        attr_accessor :arguments

        # The unique ID of the tool search call generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :call_id

        # Whether tool search was executed by the server or by the client.
        sig do
          returns(
            OpenAI::Beta::BetaResponseToolSearchCall::Execution::TaggedSymbol
          )
        end
        attr_accessor :execution

        # The status of the tool search call item that was recorded.
        sig do
          returns(
            OpenAI::Beta::BetaResponseToolSearchCall::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the item. Always `tool_search_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaResponseToolSearchCall::Agent))
        end
        attr_reader :agent

        sig do
          params(
            agent: OpenAI::Beta::BetaResponseToolSearchCall::Agent::OrHash
          ).void
        end
        attr_writer :agent

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        sig do
          params(
            id: String,
            arguments: T.anything,
            call_id: T.nilable(String),
            execution:
              OpenAI::Beta::BetaResponseToolSearchCall::Execution::OrSymbol,
            status: OpenAI::Beta::BetaResponseToolSearchCall::Status::OrSymbol,
            agent: OpenAI::Beta::BetaResponseToolSearchCall::Agent::OrHash,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the tool search call item.
          id:,
          # Arguments used for the tool search call.
          arguments:,
          # The unique ID of the tool search call generated by the model.
          call_id:,
          # Whether tool search was executed by the server or by the client.
          execution:,
          # The status of the tool search call item that was recorded.
          status:,
          # The agent that produced this item.
          agent: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the item. Always `tool_search_call`.
          type: :tool_search_call
        )
        end

        sig do
          override.returns(
            {
              id: String,
              arguments: T.anything,
              call_id: T.nilable(String),
              execution:
                OpenAI::Beta::BetaResponseToolSearchCall::Execution::TaggedSymbol,
              status:
                OpenAI::Beta::BetaResponseToolSearchCall::Status::TaggedSymbol,
              type: Symbol,
              agent: OpenAI::Beta::BetaResponseToolSearchCall::Agent,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # Whether tool search was executed by the server or by the client.
        module Execution
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaResponseToolSearchCall::Execution)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          SERVER =
            T.let(
              :server,
              OpenAI::Beta::BetaResponseToolSearchCall::Execution::TaggedSymbol
            )
          CLIENT =
            T.let(
              :client,
              OpenAI::Beta::BetaResponseToolSearchCall::Execution::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseToolSearchCall::Execution::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        # The status of the tool search call item that was recorded.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaResponseToolSearchCall::Status)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseToolSearchCall::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseToolSearchCall::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseToolSearchCall::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseToolSearchCall::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseToolSearchCall::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end
      end
    end
  end
end
