# typed: strong

module OpenAI
  module Models

    BetaResponseToolSearchOutputItemParam = Beta::BetaResponseToolSearchOutputItemParam

    module Beta

      class BetaResponseToolSearchOutputItemParam < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::BetaResponseToolSearchOutputItemParam,
            OpenAI::Internal::AnyHash
          )
        end

        # The loaded tool definitions returned by the tool search output.
        sig {
          returns(
            T::Array[
              T.any(
                OpenAI::Beta::BetaFunctionTool,
                OpenAI::Beta::BetaFileSearchTool,
                OpenAI::Beta::BetaComputerTool,
                OpenAI::Beta::BetaComputerUsePreviewTool,
                OpenAI::Beta::BetaTool::Mcp,
                OpenAI::Beta::BetaTool::CodeInterpreter,
                OpenAI::Beta::BetaTool::ProgrammaticToolCalling,
                OpenAI::Beta::BetaTool::ImageGeneration,
                OpenAI::Beta::BetaTool::LocalShell,
                OpenAI::Beta::BetaFunctionShellTool,
                OpenAI::Beta::BetaCustomTool,
                OpenAI::Beta::BetaNamespaceTool,
                OpenAI::Beta::BetaToolSearchTool,
                OpenAI::Beta::BetaApplyPatchTool,
                OpenAI::Beta::BetaWebSearchTool,
                OpenAI::Beta::BetaWebSearchPreviewTool
              )
            ]
          )
        }
        attr_accessor :tools

        # The item type. Always `tool_search_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The unique ID of this tool search output.
        sig { returns(T.nilable(String)) }
        attr_accessor :id

        # The agent that produced this item.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Agent)) }
        attr_reader :agent

        sig { params(agent: T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Agent::OrHash)).void }
        attr_writer :agent

        # The unique ID of the tool search call generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :call_id

        # Whether tool search was executed by the server or by the client.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution::OrSymbol)) }
        attr_reader :execution

        sig { params(execution: OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution::OrSymbol).void }
        attr_writer :execution

        # The status of the tool search output.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status::OrSymbol)) }
        attr_accessor :status

        sig do
          params(

            tools: T::Array[
              T.any(
                OpenAI::Beta::BetaFunctionTool::OrHash,
                OpenAI::Beta::BetaFileSearchTool::OrHash,
                OpenAI::Beta::BetaComputerTool::OrHash,
                OpenAI::Beta::BetaComputerUsePreviewTool::OrHash,
                OpenAI::Beta::BetaTool::Mcp::OrHash,
                OpenAI::Beta::BetaTool::CodeInterpreter::OrHash,
                OpenAI::Beta::BetaTool::ProgrammaticToolCalling::OrHash,
                OpenAI::Beta::BetaTool::ImageGeneration::OrHash,
                OpenAI::Beta::BetaTool::LocalShell::OrHash,
                OpenAI::Beta::BetaFunctionShellTool::OrHash,
                OpenAI::Beta::BetaCustomTool::OrHash,
                OpenAI::Beta::BetaNamespaceTool::OrHash,
                OpenAI::Beta::BetaToolSearchTool::OrHash,
                OpenAI::Beta::BetaApplyPatchTool::OrHash,
                OpenAI::Beta::BetaWebSearchTool::OrHash,
                OpenAI::Beta::BetaWebSearchPreviewTool::OrHash
              )
            ],

            id: T.nilable(String),

            agent: T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Agent::OrHash),

            call_id: T.nilable(String),

            execution: OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution::OrSymbol,

            status: T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status::OrSymbol),

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The loaded tool definitions returned by the tool search output.
          tools:,

          # The unique ID of this tool search output.
          id: nil,

          # The agent that produced this item.
          agent: nil,

          # The unique ID of the tool search call generated by the model.
          call_id: nil,

          # Whether tool search was executed by the server or by the client.
          execution: nil,

          # The status of the tool search output.
          status: nil,

          # The item type. Always `tool_search_output`.

          type: :tool_search_output
        )
        end

        sig do
          override.returns(
            {
              tools: T::Array[
                T.any(
                  OpenAI::Beta::BetaFunctionTool,
                  OpenAI::Beta::BetaFileSearchTool,
                  OpenAI::Beta::BetaComputerTool,
                  OpenAI::Beta::BetaComputerUsePreviewTool,
                  OpenAI::Beta::BetaTool::Mcp,
                  OpenAI::Beta::BetaTool::CodeInterpreter,
                  OpenAI::Beta::BetaTool::ProgrammaticToolCalling,
                  OpenAI::Beta::BetaTool::ImageGeneration,
                  OpenAI::Beta::BetaTool::LocalShell,
                  OpenAI::Beta::BetaFunctionShellTool,
                  OpenAI::Beta::BetaCustomTool,
                  OpenAI::Beta::BetaNamespaceTool,
                  OpenAI::Beta::BetaToolSearchTool,
                  OpenAI::Beta::BetaApplyPatchTool,
                  OpenAI::Beta::BetaWebSearchTool,
                  OpenAI::Beta::BetaWebSearchPreviewTool
                )
              ],
              type: Symbol,
              id: T.nilable(String),
              agent: T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Agent),
              call_id: T.nilable(String),
              execution: OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution::OrSymbol,
              status: T.nilable(OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status::OrSymbol)
            }
          )
        end
        def to_hash
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Agent,
              OpenAI::Internal::AnyHash
            )
          end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig do
            params(

              agent_name: String
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The canonical name of the agent that produced this item.

            agent_name:
          )
          end

          sig do
            override.returns(
              {agent_name: String}
            )
          end
          def to_hash
          end

        end

        # Whether tool search was executed by the server or by the client.
        module Execution
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          SERVER = T.let(:server, OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution::TaggedSymbol)
          CLIENT = T.let(:client, OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution::TaggedSymbol)

          sig {
            override.returns(T::Array[OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution::TaggedSymbol])
          }
          def self.values
          end
        end

        # The status of the tool search output.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS = T.let(:in_progress, OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status::TaggedSymbol)
          COMPLETED = T.let(:completed, OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status::TaggedSymbol)
          INCOMPLETE = T.let(:incomplete, OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
