# typed: strong

module OpenAI
  module Models
    BetaResponseFunctionShellToolCall = Beta::BetaResponseFunctionShellToolCall

    module Beta
      class BetaResponseFunctionShellToolCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseFunctionShellToolCall,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the shell tool call. Populated when this item is returned via
        # API.
        sig { returns(String) }
        attr_accessor :id

        # The shell commands and limits that describe how to run the tool call.
        sig { returns(OpenAI::Beta::BetaResponseFunctionShellToolCall::Action) }
        attr_reader :action

        sig do
          params(
            action:
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Action::OrHash
          ).void
        end
        attr_writer :action

        # The unique ID of the shell tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # Represents the use of a local environment to perform shell actions.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Environment::Variants
            )
          )
        end
        attr_accessor :environment

        # The status of the shell call. One of `in_progress`, `completed`, or
        # `incomplete`.
        sig do
          returns(
            OpenAI::Beta::BetaResponseFunctionShellToolCall::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the item. Always `shell_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig do
          returns(
            T.nilable(OpenAI::Beta::BetaResponseFunctionShellToolCall::Agent)
          )
        end
        attr_reader :agent

        sig do
          params(
            agent:
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Agent::OrHash
          ).void
        end
        attr_writer :agent

        # The execution context that produced this tool call.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Variants
            )
          )
        end
        attr_accessor :caller_

        # The ID of the entity that created this tool call.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A tool call that executes one or more shell commands in a managed environment.
        sig do
          params(
            id: String,
            action:
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Action::OrHash,
            call_id: String,
            environment:
              T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseLocalEnvironment::OrHash,
                  OpenAI::Beta::BetaResponseContainerReference::OrHash
                )
              ),
            status:
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Status::OrSymbol,
            agent:
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Agent::OrHash,
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Direct::OrHash,
                  OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Program::OrHash
                )
              ),
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the shell tool call. Populated when this item is returned via
          # API.
          id:,
          # The shell commands and limits that describe how to run the tool call.
          action:,
          # The unique ID of the shell tool call generated by the model.
          call_id:,
          # Represents the use of a local environment to perform shell actions.
          environment:,
          # The status of the shell call. One of `in_progress`, `completed`, or
          # `incomplete`.
          status:,
          # The agent that produced this item.
          agent: nil,
          # The execution context that produced this tool call.
          caller_: nil,
          # The ID of the entity that created this tool call.
          created_by: nil,
          # The type of the item. Always `shell_call`.
          type: :shell_call
        )
        end

        sig do
          override.returns(
            {
              id: String,
              action: OpenAI::Beta::BetaResponseFunctionShellToolCall::Action,
              call_id: String,
              environment:
                T.nilable(
                  OpenAI::Beta::BetaResponseFunctionShellToolCall::Environment::Variants
                ),
              status:
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Status::TaggedSymbol,
              type: Symbol,
              agent: OpenAI::Beta::BetaResponseFunctionShellToolCall::Agent,
              caller_:
                T.nilable(
                  OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Variants
                ),
              created_by: String
            }
          )
        end
        def to_hash
        end

        class Action < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Action,
                OpenAI::Internal::AnyHash
              )
            end

          sig { returns(T::Array[String]) }
          attr_accessor :commands

          # Optional maximum number of characters to return from each command.
          sig { returns(T.nilable(Integer)) }
          attr_accessor :max_output_length

          # Optional timeout in milliseconds for the commands.
          sig { returns(T.nilable(Integer)) }
          attr_accessor :timeout_ms

          # The shell commands and limits that describe how to run the tool call.
          sig do
            params(
              commands: T::Array[String],
              max_output_length: T.nilable(Integer),
              timeout_ms: T.nilable(Integer)
            ).returns(T.attached_class)
          end
          def self.new(
            commands:,
            # Optional maximum number of characters to return from each command.
            max_output_length:,
            # Optional timeout in milliseconds for the commands.
            timeout_ms:
          )
          end

          sig do
            override.returns(
              {
                commands: T::Array[String],
                max_output_length: T.nilable(Integer),
                timeout_ms: T.nilable(Integer)
              }
            )
          end
          def to_hash
          end
        end

        # Represents the use of a local environment to perform shell actions.
        module Environment
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseLocalEnvironment,
                OpenAI::Beta::BetaResponseContainerReference
              )
            end

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Environment::Variants
              ]
            )
          end
          def self.variants
          end
        end

        # The status of the shell call. One of `in_progress`, `completed`, or
        # `incomplete`.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseFunctionShellToolCall::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Direct,
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Program
              )
            end

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Direct,
                  OpenAI::Internal::AnyHash
                )
              end

            sig { returns(Symbol) }
            attr_accessor :type

            sig { params(type: Symbol).returns(T.attached_class) }
            def self.new(type: :direct)
            end

            sig { override.returns({ type: Symbol }) }
            def to_hash
            end
          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Program,
                  OpenAI::Internal::AnyHash
                )
              end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(caller_id: String, type: Symbol).returns(T.attached_class)
            end
            def self.new(
              # The call ID of the program item that produced this tool call.
              caller_id:,
              type: :program
            )
            end

            sig { override.returns({ caller_id: String, type: Symbol }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseFunctionShellToolCall::Caller::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
