# typed: strong

module OpenAI
  module Models
    BetaResponseCodeInterpreterToolCall =
      Beta::BetaResponseCodeInterpreterToolCall

    module Beta
      class BetaResponseCodeInterpreterToolCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Beta::BetaResponseCodeInterpreterToolCall,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the code interpreter tool call.
        sig { returns(String) }
        attr_accessor :id

        # The code to run, or null if not available.
        sig { returns(T.nilable(String)) }
        attr_accessor :code

        # The ID of the container used to run the code.
        sig { returns(String) }
        attr_accessor :container_id

        # The outputs generated by the code interpreter, such as logs or images. Can be
        # null if no outputs are available.
        sig do
          returns(
            T.nilable(
              T::Array[
                T.any(
                  OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs,
                  OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Image
                )
              ]
            )
          )
        end
        attr_accessor :outputs

        # The status of the code interpreter tool call. Valid values are `in_progress`,
        # `completed`, `incomplete`, `interpreting`, and `failed`.
        sig do
          returns(
            OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::OrSymbol
          )
        end
        attr_accessor :status

        # The type of the code interpreter tool call. Always `code_interpreter_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The agent that produced this item.
        sig do
          returns(
            T.nilable(OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Agent)
          )
        end
        attr_reader :agent

        sig do
          params(
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Agent::OrHash
              )
          ).void
        end
        attr_writer :agent

        # A tool call to run code.
        sig do
          params(
            id: String,
            code: T.nilable(String),
            container_id: String,
            outputs:
              T.nilable(
                T::Array[
                  T.any(
                    OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs::OrHash,
                    OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Image::OrHash
                  )
                ]
              ),
            status:
              OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::OrSymbol,
            agent:
              T.nilable(
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Agent::OrHash
              ),
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the code interpreter tool call.
          id:,
          # The code to run, or null if not available.
          code:,
          # The ID of the container used to run the code.
          container_id:,
          # The outputs generated by the code interpreter, such as logs or images. Can be
          # null if no outputs are available.
          outputs:,
          # The status of the code interpreter tool call. Valid values are `in_progress`,
          # `completed`, `incomplete`, `interpreting`, and `failed`.
          status:,
          # The agent that produced this item.
          agent: nil,
          # The type of the code interpreter tool call. Always `code_interpreter_call`.
          type: :code_interpreter_call
        )
        end

        sig do
          override.returns(
            {
              id: String,
              code: T.nilable(String),
              container_id: String,
              outputs:
                T.nilable(
                  T::Array[
                    T.any(
                      OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs,
                      OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Image
                    )
                  ]
                ),
              status:
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::OrSymbol,
              type: Symbol,
              agent:
                T.nilable(
                  OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Agent
                )
            }
          )
        end
        def to_hash
        end

        # The logs output from the code interpreter.
        module Output
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs,
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Image
              )
            end

          class Logs < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Logs,
                  OpenAI::Internal::AnyHash
                )
              end

            # The logs output from the code interpreter.
            sig { returns(String) }
            attr_accessor :logs

            # The type of the output. Always `logs`.
            sig { returns(Symbol) }
            attr_accessor :type

            # The logs output from the code interpreter.
            sig { params(logs: String, type: Symbol).returns(T.attached_class) }
            def self.new(
              # The logs output from the code interpreter.
              logs:,
              # The type of the output. Always `logs`.
              type: :logs
            )
            end

            sig { override.returns({ logs: String, type: Symbol }) }
            def to_hash
            end
          end

          class Image < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Image,
                  OpenAI::Internal::AnyHash
                )
              end

            # The type of the output. Always `image`.
            sig { returns(Symbol) }
            attr_accessor :type

            # The URL of the image output from the code interpreter.
            sig { returns(String) }
            attr_accessor :url

            # The image output from the code interpreter.
            sig { params(url: String, type: Symbol).returns(T.attached_class) }
            def self.new(
              # The URL of the image output from the code interpreter.
              url:,
              # The type of the output. Always `image`.
              type: :image
            )
            end

            sig { override.returns({ type: Symbol, url: String }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Output::Variants
              ]
            )
          end
          def self.variants
          end
        end

        # The status of the code interpreter tool call. Valid values are `in_progress`,
        # `completed`, `incomplete`, `interpreting`, and `failed`.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::TaggedSymbol
            )
          INTERPRETING =
            T.let(
              :interpreting,
              OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::TaggedSymbol
            )
          FAILED =
            T.let(
              :failed,
              OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        class Agent < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponseCodeInterpreterToolCall::Agent,
                OpenAI::Internal::AnyHash
              )
            end

          # The canonical name of the agent that produced this item.
          sig { returns(String) }
          attr_accessor :agent_name

          # The agent that produced this item.
          sig { params(agent_name: String).returns(T.attached_class) }
          def self.new(
            # The canonical name of the agent that produced this item.
            agent_name:
          )
          end

          sig { override.returns({ agent_name: String }) }
          def to_hash
          end
        end
      end
    end
  end
end
