# typed: strong

module OpenAI
  module Models
    BetaResponse = Beta::BetaResponse

    module Beta
      class BetaResponse < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(OpenAI::Beta::BetaResponse, OpenAI::Internal::AnyHash)
          end

        # Unique identifier for this Response.
        sig { returns(String) }
        attr_accessor :id

        # Unix timestamp (in seconds) of when this Response was created.
        sig { returns(Float) }
        attr_accessor :created_at

        # An error object returned when the model fails to generate a Response.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseError)) }
        attr_reader :error

        sig do
          params(error: T.nilable(OpenAI::Beta::BetaResponseError::OrHash)).void
        end
        attr_writer :error

        # Details about why the response is incomplete.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaResponse::IncompleteDetails))
        end
        attr_reader :incomplete_details

        sig do
          params(
            incomplete_details:
              T.nilable(OpenAI::Beta::BetaResponse::IncompleteDetails::OrHash)
          ).void
        end
        attr_writer :incomplete_details

        # A system (or developer) message inserted into the model's context.
        #
        # When using along with `previous_response_id`, the instructions from a previous
        # response will not be carried over to the next response. This makes it simple to
        # swap out system (or developer) messages in new responses.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaResponse::Instructions::Variants))
        end
        attr_accessor :instructions

        # Set of 16 key-value pairs that can be attached to an object. This can be useful
        # for storing additional information about the object in a structured format, and
        # querying for objects via API or the dashboard.
        #
        # Keys are strings with a maximum length of 64 characters. Values are strings with
        # a maximum length of 512 characters.
        sig { returns(T.nilable(T::Hash[Symbol, String])) }
        attr_accessor :metadata

        # Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a
        # wide range of models with different capabilities, performance characteristics,
        # and price points. Refer to the
        # [model guide](https://platform.openai.com/docs/models) to browse and compare
        # available models.
        sig { returns(OpenAI::Beta::BetaResponse::Model::Variants) }
        attr_accessor :model

        # The object type of this resource - always set to `response`.
        sig { returns(Symbol) }
        attr_accessor :object

        # An array of content items generated by the model.
        #
        # - The length and order of items in the `output` array is dependent on the
        #   model's response.
        # - Rather than accessing the first item in the `output` array and assuming it's
        #   an `assistant` message with the content generated by the model, you might
        #   consider using the `output_text` property where supported in SDKs.
        sig do
          returns(T::Array[OpenAI::Beta::BetaResponseOutputItem::Variants])
        end
        attr_accessor :output

        # Whether to allow the model to run tool calls in parallel.
        sig { returns(T::Boolean) }
        attr_accessor :parallel_tool_calls

        # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
        # make the output more random, while lower values like 0.2 will make it more
        # focused and deterministic. We generally recommend altering this or `top_p` but
        # not both.
        sig { returns(T.nilable(Float)) }
        attr_accessor :temperature

        # How the model should select which tool (or tools) to use when generating a
        # response. See the `tools` parameter to see how to specify which tools the model
        # can call.
        sig { returns(OpenAI::Beta::BetaResponse::ToolChoice::Variants) }
        attr_accessor :tool_choice

        # An array of tools the model may call while generating a response. You can
        # specify which tool to use by setting the `tool_choice` parameter.
        #
        # We support the following categories of tools:
        #
        # - **Built-in tools**: Tools that are provided by OpenAI that extend the model's
        #   capabilities, like
        #   [web search](https://platform.openai.com/docs/guides/tools-web-search) or
        #   [file search](https://platform.openai.com/docs/guides/tools-file-search).
        #   Learn more about
        #   [built-in tools](https://platform.openai.com/docs/guides/tools).
        # - **MCP Tools**: Integrations with third-party systems via custom MCP servers or
        #   predefined connectors such as Google Drive and SharePoint. Learn more about
        #   [MCP Tools](https://platform.openai.com/docs/guides/tools-connectors-mcp).
        # - **Function calls (custom tools)**: Functions that are defined by you, enabling
        #   the model to call your own code with strongly typed arguments and outputs.
        #   Learn more about
        #   [function calling](https://platform.openai.com/docs/guides/function-calling).
        #   You can also use custom tools to call your own code.
        sig { returns(T::Array[OpenAI::Beta::BetaTool::Variants]) }
        attr_accessor :tools

        # An alternative to sampling with temperature, called nucleus sampling, where the
        # model considers the results of the tokens with top_p probability mass. So 0.1
        # means only the tokens comprising the top 10% probability mass are considered.
        #
        # We generally recommend altering this or `temperature` but not both.
        sig { returns(T.nilable(Float)) }
        attr_accessor :top_p

        # Whether to run the model response in the background.
        # [Learn more](https://platform.openai.com/docs/guides/background).
        sig { returns(T.nilable(T::Boolean)) }
        attr_accessor :background

        # Unix timestamp (in seconds) of when this Response was completed. Only present
        # when the status is `completed`.
        sig { returns(T.nilable(Float)) }
        attr_accessor :completed_at

        # The conversation that this response belonged to. Input items and output items
        # from this response were automatically added to this conversation.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponse::Conversation)) }
        attr_reader :conversation

        sig do
          params(
            conversation:
              T.nilable(OpenAI::Beta::BetaResponse::Conversation::OrHash)
          ).void
        end
        attr_writer :conversation

        # An upper bound for the number of tokens that can be generated for a response,
        # including visible output tokens and
        # [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).
        sig { returns(T.nilable(Integer)) }
        attr_accessor :max_output_tokens

        # The maximum number of total calls to built-in tools that can be processed in a
        # response. This maximum number applies across all built-in tool calls, not per
        # individual tool. Any further attempts to call a tool by the model will be
        # ignored.
        sig { returns(T.nilable(Integer)) }
        attr_accessor :max_tool_calls

        # Moderation results for the response input and output, if moderated completions
        # were requested.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponse::Moderation)) }
        attr_reader :moderation

        sig do
          params(
            moderation:
              T.nilable(OpenAI::Beta::BetaResponse::Moderation::OrHash)
          ).void
        end
        attr_writer :moderation

        # The unique ID of the previous response to the model. Use this to create
        # multi-turn conversations. Learn more about
        # [conversation state](https://platform.openai.com/docs/guides/conversation-state).
        # Cannot be used in conjunction with `conversation`.
        sig { returns(T.nilable(String)) }
        attr_accessor :previous_response_id

        # Reference to a prompt template and its variables.
        # [Learn more](https://platform.openai.com/docs/guides/text?api-mode=responses#reusable-prompts).
        sig { returns(T.nilable(OpenAI::Beta::BetaResponsePrompt)) }
        attr_reader :prompt

        sig do
          params(
            prompt: T.nilable(OpenAI::Beta::BetaResponsePrompt::OrHash)
          ).void
        end
        attr_writer :prompt

        # Used by OpenAI to cache responses for similar requests to optimize your cache
        # hit rates. Replaces the `user` field.
        # [Learn more](https://platform.openai.com/docs/guides/prompt-caching).
        sig { returns(T.nilable(String)) }
        attr_accessor :prompt_cache_key

        # The prompt-caching options that were applied to the response. Supported for
        # `gpt-5.6` and later models.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaResponse::PromptCacheOptions))
        end
        attr_reader :prompt_cache_options

        sig do
          params(
            prompt_cache_options:
              OpenAI::Beta::BetaResponse::PromptCacheOptions::OrHash
          ).void
        end
        attr_writer :prompt_cache_options

        # Deprecated. Use `prompt_cache_options.ttl` instead.
        #
        # The retention policy for the prompt cache. Set to `24h` to enable extended
        # prompt caching, which keeps cached prefixes active for longer, up to a maximum
        # of 24 hours.
        # [Learn more](https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention).
        # This field expresses a maximum retention policy, while
        # `prompt_cache_options.ttl` expresses a minimum cache lifetime. The two fields
        # are independent and do not interact. For `gpt-5.5`, `gpt-5.5-pro`, and future
        # models, only `24h` is supported.
        #
        # For older models that support both `in_memory` and `24h`, the default depends on
        # your organization's data retention policy:
        #
        # - Organizations without ZDR enabled default to `24h`.
        # - Organizations with ZDR enabled default to `in_memory` when
        #   `prompt_cache_retention` is not specified.
        sig do
          returns(
            T.nilable(
              OpenAI::Beta::BetaResponse::PromptCacheRetention::TaggedSymbol
            )
          )
        end
        attr_accessor :prompt_cache_retention

        # **gpt-5 and o-series models only**
        #
        # Configuration options for
        # [reasoning models](https://platform.openai.com/docs/guides/reasoning).
        sig { returns(T.nilable(OpenAI::Beta::BetaResponse::Reasoning)) }
        attr_reader :reasoning

        sig do
          params(
            reasoning: T.nilable(OpenAI::Beta::BetaResponse::Reasoning::OrHash)
          ).void
        end
        attr_writer :reasoning

        # A stable identifier used to help detect users of your application that may be
        # violating OpenAI's usage policies. The IDs should be a string that uniquely
        # identifies each user, with a maximum length of 64 characters. We recommend
        # hashing their username or email address, in order to avoid sending us any
        # identifying information.
        # [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
        sig { returns(T.nilable(String)) }
        attr_accessor :safety_identifier

        # Specifies the processing type used for serving the request.
        #
        # - If set to 'auto', then the request will be processed with the service tier
        #   configured in the Project settings. Unless otherwise configured, the Project
        #   will use 'default'.
        # - If set to 'default', then the request will be processed with the standard
        #   pricing and performance for the selected model.
        # - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)' or
        #   '[priority](https://openai.com/api-priority-processing/)', then the request
        #   will be processed with the corresponding service tier.
        # - When not set, the default behavior is 'auto'.
        #
        # When the `service_tier` parameter is set, the response body will include the
        # `service_tier` value based on the processing mode actually used to serve the
        # request. This response value may be different from the value set in the
        # parameter.
        sig do
          returns(
            T.nilable(OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol)
          )
        end
        attr_accessor :service_tier

        # The status of the response generation. One of `completed`, `failed`,
        # `in_progress`, `cancelled`, `queued`, or `incomplete`.
        sig do
          returns(T.nilable(OpenAI::Beta::BetaResponseStatus::TaggedSymbol))
        end
        attr_reader :status

        sig { params(status: OpenAI::Beta::BetaResponseStatus::OrSymbol).void }
        attr_writer :status

        # Configuration options for a text response from the model. Can be plain text or
        # structured JSON data. Learn more:
        #
        # - [Text inputs and outputs](https://platform.openai.com/docs/guides/text)
        # - [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs)
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseTextConfig)) }
        attr_reader :text

        sig { params(text: OpenAI::Beta::BetaResponseTextConfig::OrHash).void }
        attr_writer :text

        # An integer between 0 and 20 specifying the maximum number of most likely tokens
        # to return at each token position, each with an associated log probability. In
        # some cases, the number of returned tokens may be fewer than requested.
        sig { returns(T.nilable(Integer)) }
        attr_accessor :top_logprobs

        # The truncation strategy to use for the model response.
        #
        # - `auto`: If the input to this Response exceeds the model's context window size,
        #   the model will truncate the response to fit the context window by dropping
        #   items from the beginning of the conversation.
        # - `disabled` (default): If the input size will exceed the context window size
        #   for a model, the request will fail with a 400 error.
        sig do
          returns(
            T.nilable(OpenAI::Beta::BetaResponse::Truncation::TaggedSymbol)
          )
        end
        attr_accessor :truncation

        # Represents token usage details including input tokens, output tokens, a
        # breakdown of output tokens, and the total tokens used.
        sig { returns(T.nilable(OpenAI::Beta::BetaResponseUsage)) }
        attr_reader :usage

        sig { params(usage: OpenAI::Beta::BetaResponseUsage::OrHash).void }
        attr_writer :usage

        # This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use
        # `prompt_cache_key` instead to maintain caching optimizations. A stable
        # identifier for your end-users. Used to boost cache hit rates by better bucketing
        # similar requests and to help OpenAI detect and prevent abuse.
        # [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
        sig { returns(T.nilable(String)) }
        attr_reader :user

        sig { params(user: String).void }
        attr_writer :user

        sig do
          params(
            id: String,
            created_at: Float,
            error: T.nilable(OpenAI::Beta::BetaResponseError::OrHash),
            incomplete_details:
              T.nilable(OpenAI::Beta::BetaResponse::IncompleteDetails::OrHash),
            instructions:
              T.nilable(OpenAI::Beta::BetaResponse::Instructions::Variants),
            metadata: T.nilable(T::Hash[Symbol, String]),
            model: T.any(OpenAI::Beta::BetaResponse::Model::OrSymbol, String),
            output:
              T::Array[
                T.any(
                  OpenAI::Beta::BetaResponseOutputMessage::OrHash,
                  OpenAI::Beta::BetaResponseFileSearchToolCall::OrHash,
                  OpenAI::Beta::BetaResponseFunctionToolCall::OrHash,
                  OpenAI::Beta::BetaResponseFunctionToolCallOutputItem::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::AgentMessage::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::MultiAgentCall::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::MultiAgentCallOutput::OrHash,
                  OpenAI::Beta::BetaResponseFunctionWebSearch::OrHash,
                  OpenAI::Beta::BetaResponseComputerToolCall::OrHash,
                  OpenAI::Beta::BetaResponseComputerToolCallOutputItem::OrHash,
                  OpenAI::Beta::BetaResponseReasoningItem::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::Program::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::ProgramOutput::OrHash,
                  OpenAI::Beta::BetaResponseToolSearchCall::OrHash,
                  OpenAI::Beta::BetaResponseToolSearchOutputItem::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::AdditionalTools::OrHash,
                  OpenAI::Beta::BetaResponseCompactionItem::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::ImageGenerationCall::OrHash,
                  OpenAI::Beta::BetaResponseCodeInterpreterToolCall::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::LocalShellCall::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::LocalShellCallOutput::OrHash,
                  OpenAI::Beta::BetaResponseFunctionShellToolCall::OrHash,
                  OpenAI::Beta::BetaResponseFunctionShellToolCallOutput::OrHash,
                  OpenAI::Beta::BetaResponseApplyPatchToolCall::OrHash,
                  OpenAI::Beta::BetaResponseApplyPatchToolCallOutput::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::McpCall::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::McpListTools::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::McpApprovalRequest::OrHash,
                  OpenAI::Beta::BetaResponseOutputItem::McpApprovalResponse::OrHash,
                  OpenAI::Beta::BetaResponseCustomToolCall::OrHash,
                  OpenAI::Beta::BetaResponseCustomToolCallOutputItem::OrHash
                )
              ],
            parallel_tool_calls: T::Boolean,
            temperature: T.nilable(Float),
            tool_choice:
              T.any(
                OpenAI::Beta::BetaToolChoiceOptions::OrSymbol,
                OpenAI::Beta::BetaToolChoiceAllowed::OrHash,
                OpenAI::Beta::BetaToolChoiceTypes::OrHash,
                OpenAI::Beta::BetaToolChoiceFunction::OrHash,
                OpenAI::Beta::BetaToolChoiceMcp::OrHash,
                OpenAI::Beta::BetaToolChoiceCustom::OrHash,
                OpenAI::Beta::BetaResponse::ToolChoice::BetaSpecificProgrammaticToolCallingParam::OrHash,
                OpenAI::Beta::BetaToolChoiceApplyPatch::OrHash,
                OpenAI::Beta::BetaToolChoiceShell::OrHash
              ),
            tools:
              T::Array[
                T.any(
                  OpenAI::Beta::BetaFunctionTool::OrHash,
                  OpenAI::Beta::BetaFileSearchTool::OrHash,
                  OpenAI::Beta::BetaComputerTool::OrHash,
                  OpenAI::Beta::BetaComputerUsePreviewTool::OrHash,
                  OpenAI::Beta::BetaTool::Mcp::OrHash,
                  OpenAI::Beta::BetaTool::CodeInterpreter::OrHash,
                  OpenAI::Beta::BetaTool::ProgrammaticToolCalling::OrHash,
                  OpenAI::Beta::BetaTool::ImageGeneration::OrHash,
                  OpenAI::Beta::BetaTool::LocalShell::OrHash,
                  OpenAI::Beta::BetaFunctionShellTool::OrHash,
                  OpenAI::Beta::BetaCustomTool::OrHash,
                  OpenAI::Beta::BetaNamespaceTool::OrHash,
                  OpenAI::Beta::BetaToolSearchTool::OrHash,
                  OpenAI::Beta::BetaApplyPatchTool::OrHash,
                  OpenAI::Beta::BetaWebSearchTool::OrHash,
                  OpenAI::Beta::BetaWebSearchPreviewTool::OrHash
                )
              ],
            top_p: T.nilable(Float),
            background: T.nilable(T::Boolean),
            completed_at: T.nilable(Float),
            conversation:
              T.nilable(OpenAI::Beta::BetaResponse::Conversation::OrHash),
            max_output_tokens: T.nilable(Integer),
            max_tool_calls: T.nilable(Integer),
            moderation:
              T.nilable(OpenAI::Beta::BetaResponse::Moderation::OrHash),
            previous_response_id: T.nilable(String),
            prompt: T.nilable(OpenAI::Beta::BetaResponsePrompt::OrHash),
            prompt_cache_key: T.nilable(String),
            prompt_cache_options:
              OpenAI::Beta::BetaResponse::PromptCacheOptions::OrHash,
            prompt_cache_retention:
              T.nilable(
                OpenAI::Beta::BetaResponse::PromptCacheRetention::OrSymbol
              ),
            reasoning: T.nilable(OpenAI::Beta::BetaResponse::Reasoning::OrHash),
            safety_identifier: T.nilable(String),
            service_tier:
              T.nilable(OpenAI::Beta::BetaResponse::ServiceTier::OrSymbol),
            status: OpenAI::Beta::BetaResponseStatus::OrSymbol,
            text: OpenAI::Beta::BetaResponseTextConfig::OrHash,
            top_logprobs: T.nilable(Integer),
            truncation:
              T.nilable(OpenAI::Beta::BetaResponse::Truncation::OrSymbol),
            usage: OpenAI::Beta::BetaResponseUsage::OrHash,
            user: String,
            object: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # Unique identifier for this Response.
          id:,
          # Unix timestamp (in seconds) of when this Response was created.
          created_at:,
          # An error object returned when the model fails to generate a Response.
          error:,
          # Details about why the response is incomplete.
          incomplete_details:,
          # A system (or developer) message inserted into the model's context.
          #
          # When using along with `previous_response_id`, the instructions from a previous
          # response will not be carried over to the next response. This makes it simple to
          # swap out system (or developer) messages in new responses.
          instructions:,
          # Set of 16 key-value pairs that can be attached to an object. This can be useful
          # for storing additional information about the object in a structured format, and
          # querying for objects via API or the dashboard.
          #
          # Keys are strings with a maximum length of 64 characters. Values are strings with
          # a maximum length of 512 characters.
          metadata:,
          # Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a
          # wide range of models with different capabilities, performance characteristics,
          # and price points. Refer to the
          # [model guide](https://platform.openai.com/docs/models) to browse and compare
          # available models.
          model:,
          # An array of content items generated by the model.
          #
          # - The length and order of items in the `output` array is dependent on the
          #   model's response.
          # - Rather than accessing the first item in the `output` array and assuming it's
          #   an `assistant` message with the content generated by the model, you might
          #   consider using the `output_text` property where supported in SDKs.
          output:,
          # Whether to allow the model to run tool calls in parallel.
          parallel_tool_calls:,
          # What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
          # make the output more random, while lower values like 0.2 will make it more
          # focused and deterministic. We generally recommend altering this or `top_p` but
          # not both.
          temperature:,
          # How the model should select which tool (or tools) to use when generating a
          # response. See the `tools` parameter to see how to specify which tools the model
          # can call.
          tool_choice:,
          # An array of tools the model may call while generating a response. You can
          # specify which tool to use by setting the `tool_choice` parameter.
          #
          # We support the following categories of tools:
          #
          # - **Built-in tools**: Tools that are provided by OpenAI that extend the model's
          #   capabilities, like
          #   [web search](https://platform.openai.com/docs/guides/tools-web-search) or
          #   [file search](https://platform.openai.com/docs/guides/tools-file-search).
          #   Learn more about
          #   [built-in tools](https://platform.openai.com/docs/guides/tools).
          # - **MCP Tools**: Integrations with third-party systems via custom MCP servers or
          #   predefined connectors such as Google Drive and SharePoint. Learn more about
          #   [MCP Tools](https://platform.openai.com/docs/guides/tools-connectors-mcp).
          # - **Function calls (custom tools)**: Functions that are defined by you, enabling
          #   the model to call your own code with strongly typed arguments and outputs.
          #   Learn more about
          #   [function calling](https://platform.openai.com/docs/guides/function-calling).
          #   You can also use custom tools to call your own code.
          tools:,
          # An alternative to sampling with temperature, called nucleus sampling, where the
          # model considers the results of the tokens with top_p probability mass. So 0.1
          # means only the tokens comprising the top 10% probability mass are considered.
          #
          # We generally recommend altering this or `temperature` but not both.
          top_p:,
          # Whether to run the model response in the background.
          # [Learn more](https://platform.openai.com/docs/guides/background).
          background: nil,
          # Unix timestamp (in seconds) of when this Response was completed. Only present
          # when the status is `completed`.
          completed_at: nil,
          # The conversation that this response belonged to. Input items and output items
          # from this response were automatically added to this conversation.
          conversation: nil,
          # An upper bound for the number of tokens that can be generated for a response,
          # including visible output tokens and
          # [reasoning tokens](https://platform.openai.com/docs/guides/reasoning).
          max_output_tokens: nil,
          # The maximum number of total calls to built-in tools that can be processed in a
          # response. This maximum number applies across all built-in tool calls, not per
          # individual tool. Any further attempts to call a tool by the model will be
          # ignored.
          max_tool_calls: nil,
          # Moderation results for the response input and output, if moderated completions
          # were requested.
          moderation: nil,
          # The unique ID of the previous response to the model. Use this to create
          # multi-turn conversations. Learn more about
          # [conversation state](https://platform.openai.com/docs/guides/conversation-state).
          # Cannot be used in conjunction with `conversation`.
          previous_response_id: nil,
          # Reference to a prompt template and its variables.
          # [Learn more](https://platform.openai.com/docs/guides/text?api-mode=responses#reusable-prompts).
          prompt: nil,
          # Used by OpenAI to cache responses for similar requests to optimize your cache
          # hit rates. Replaces the `user` field.
          # [Learn more](https://platform.openai.com/docs/guides/prompt-caching).
          prompt_cache_key: nil,
          # The prompt-caching options that were applied to the response. Supported for
          # `gpt-5.6` and later models.
          prompt_cache_options: nil,
          # Deprecated. Use `prompt_cache_options.ttl` instead.
          #
          # The retention policy for the prompt cache. Set to `24h` to enable extended
          # prompt caching, which keeps cached prefixes active for longer, up to a maximum
          # of 24 hours.
          # [Learn more](https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention).
          # This field expresses a maximum retention policy, while
          # `prompt_cache_options.ttl` expresses a minimum cache lifetime. The two fields
          # are independent and do not interact. For `gpt-5.5`, `gpt-5.5-pro`, and future
          # models, only `24h` is supported.
          #
          # For older models that support both `in_memory` and `24h`, the default depends on
          # your organization's data retention policy:
          #
          # - Organizations without ZDR enabled default to `24h`.
          # - Organizations with ZDR enabled default to `in_memory` when
          #   `prompt_cache_retention` is not specified.
          prompt_cache_retention: nil,
          # **gpt-5 and o-series models only**
          #
          # Configuration options for
          # [reasoning models](https://platform.openai.com/docs/guides/reasoning).
          reasoning: nil,
          # A stable identifier used to help detect users of your application that may be
          # violating OpenAI's usage policies. The IDs should be a string that uniquely
          # identifies each user, with a maximum length of 64 characters. We recommend
          # hashing their username or email address, in order to avoid sending us any
          # identifying information.
          # [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
          safety_identifier: nil,
          # Specifies the processing type used for serving the request.
          #
          # - If set to 'auto', then the request will be processed with the service tier
          #   configured in the Project settings. Unless otherwise configured, the Project
          #   will use 'default'.
          # - If set to 'default', then the request will be processed with the standard
          #   pricing and performance for the selected model.
          # - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)' or
          #   '[priority](https://openai.com/api-priority-processing/)', then the request
          #   will be processed with the corresponding service tier.
          # - When not set, the default behavior is 'auto'.
          #
          # When the `service_tier` parameter is set, the response body will include the
          # `service_tier` value based on the processing mode actually used to serve the
          # request. This response value may be different from the value set in the
          # parameter.
          service_tier: nil,
          # The status of the response generation. One of `completed`, `failed`,
          # `in_progress`, `cancelled`, `queued`, or `incomplete`.
          status: nil,
          # Configuration options for a text response from the model. Can be plain text or
          # structured JSON data. Learn more:
          #
          # - [Text inputs and outputs](https://platform.openai.com/docs/guides/text)
          # - [Structured Outputs](https://platform.openai.com/docs/guides/structured-outputs)
          text: nil,
          # An integer between 0 and 20 specifying the maximum number of most likely tokens
          # to return at each token position, each with an associated log probability. In
          # some cases, the number of returned tokens may be fewer than requested.
          top_logprobs: nil,
          # The truncation strategy to use for the model response.
          #
          # - `auto`: If the input to this Response exceeds the model's context window size,
          #   the model will truncate the response to fit the context window by dropping
          #   items from the beginning of the conversation.
          # - `disabled` (default): If the input size will exceed the context window size
          #   for a model, the request will fail with a 400 error.
          truncation: nil,
          # Represents token usage details including input tokens, output tokens, a
          # breakdown of output tokens, and the total tokens used.
          usage: nil,
          # This field is being replaced by `safety_identifier` and `prompt_cache_key`. Use
          # `prompt_cache_key` instead to maintain caching optimizations. A stable
          # identifier for your end-users. Used to boost cache hit rates by better bucketing
          # similar requests and to help OpenAI detect and prevent abuse.
          # [Learn more](https://platform.openai.com/docs/guides/safety-best-practices#safety-identifiers).
          user: nil,
          # The object type of this resource - always set to `response`.
          object: :response
        )
        end

        sig do
          override.returns(
            {
              id: String,
              created_at: Float,
              error: T.nilable(OpenAI::Beta::BetaResponseError),
              incomplete_details:
                T.nilable(OpenAI::Beta::BetaResponse::IncompleteDetails),
              instructions:
                T.nilable(OpenAI::Beta::BetaResponse::Instructions::Variants),
              metadata: T.nilable(T::Hash[Symbol, String]),
              model: OpenAI::Beta::BetaResponse::Model::Variants,
              object: Symbol,
              output: T::Array[OpenAI::Beta::BetaResponseOutputItem::Variants],
              parallel_tool_calls: T::Boolean,
              temperature: T.nilable(Float),
              tool_choice: OpenAI::Beta::BetaResponse::ToolChoice::Variants,
              tools: T::Array[OpenAI::Beta::BetaTool::Variants],
              top_p: T.nilable(Float),
              background: T.nilable(T::Boolean),
              completed_at: T.nilable(Float),
              conversation: T.nilable(OpenAI::Beta::BetaResponse::Conversation),
              max_output_tokens: T.nilable(Integer),
              max_tool_calls: T.nilable(Integer),
              moderation: T.nilable(OpenAI::Beta::BetaResponse::Moderation),
              previous_response_id: T.nilable(String),
              prompt: T.nilable(OpenAI::Beta::BetaResponsePrompt),
              prompt_cache_key: T.nilable(String),
              prompt_cache_options:
                OpenAI::Beta::BetaResponse::PromptCacheOptions,
              prompt_cache_retention:
                T.nilable(
                  OpenAI::Beta::BetaResponse::PromptCacheRetention::TaggedSymbol
                ),
              reasoning: T.nilable(OpenAI::Beta::BetaResponse::Reasoning),
              safety_identifier: T.nilable(String),
              service_tier:
                T.nilable(
                  OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol
                ),
              status: OpenAI::Beta::BetaResponseStatus::TaggedSymbol,
              text: OpenAI::Beta::BetaResponseTextConfig,
              top_logprobs: T.nilable(Integer),
              truncation:
                T.nilable(OpenAI::Beta::BetaResponse::Truncation::TaggedSymbol),
              usage: OpenAI::Beta::BetaResponseUsage,
              user: String
            }
          )
        end
        def to_hash
        end

        class IncompleteDetails < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponse::IncompleteDetails,
                OpenAI::Internal::AnyHash
              )
            end

          # The reason why the response is incomplete.
          sig do
            returns(
              T.nilable(
                OpenAI::Beta::BetaResponse::IncompleteDetails::Reason::TaggedSymbol
              )
            )
          end
          attr_reader :reason

          sig do
            params(
              reason:
                OpenAI::Beta::BetaResponse::IncompleteDetails::Reason::OrSymbol
            ).void
          end
          attr_writer :reason

          # Details about why the response is incomplete.
          sig do
            params(
              reason:
                OpenAI::Beta::BetaResponse::IncompleteDetails::Reason::OrSymbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The reason why the response is incomplete.
            reason: nil
          )
          end

          sig do
            override.returns(
              {
                reason:
                  OpenAI::Beta::BetaResponse::IncompleteDetails::Reason::TaggedSymbol
              }
            )
          end
          def to_hash
          end

          # The reason why the response is incomplete.
          module Reason
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Beta::BetaResponse::IncompleteDetails::Reason
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            MAX_OUTPUT_TOKENS =
              T.let(
                :max_output_tokens,
                OpenAI::Beta::BetaResponse::IncompleteDetails::Reason::TaggedSymbol
              )
            CONTENT_FILTER =
              T.let(
                :content_filter,
                OpenAI::Beta::BetaResponse::IncompleteDetails::Reason::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::IncompleteDetails::Reason::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        # A system (or developer) message inserted into the model's context.
        #
        # When using along with `previous_response_id`, the instructions from a previous
        # response will not be carried over to the next response. This makes it simple to
        # swap out system (or developer) messages in new responses.
        module Instructions
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                String,
                T::Array[OpenAI::Beta::BetaResponseInputItem::Variants]
              )
            end

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaResponse::Instructions::Variants]
            )
          end
          def self.variants
          end

          BetaResponseInputItemArray =
            T.let(
              OpenAI::Internal::Type::ArrayOf[
                union: OpenAI::Beta::BetaResponseInputItem
              ],
              OpenAI::Internal::Type::Converter
            )
        end

        # Model ID used to generate the response, like `gpt-4o` or `o3`. OpenAI offers a
        # wide range of models with different capabilities, performance characteristics,
        # and price points. Refer to the
        # [model guide](https://platform.openai.com/docs/models) to browse and compare
        # available models.
        module Model
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(OpenAI::Beta::BetaResponse::Model::TaggedSymbol, String)
            end

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaResponse::Model::Variants]
            )
          end
          def self.variants
          end

          TaggedSymbol =
            T.type_alias { T.all(Symbol, OpenAI::Beta::BetaResponse::Model) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          GPT_5_6_SOL =
            T.let(
              :"gpt-5.6-sol",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_6_TERRA =
            T.let(
              :"gpt-5.6-terra",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_6_LUNA =
            T.let(
              :"gpt-5.6-luna",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_4 =
            T.let(:"gpt-5.4", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_5_4_MINI =
            T.let(
              :"gpt-5.4-mini",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_4_NANO =
            T.let(
              :"gpt-5.4-nano",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_4_MINI_2026_03_17 =
            T.let(
              :"gpt-5.4-mini-2026-03-17",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_4_NANO_2026_03_17 =
            T.let(
              :"gpt-5.4-nano-2026-03-17",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_3_CHAT_LATEST =
            T.let(
              :"gpt-5.3-chat-latest",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_2 =
            T.let(:"gpt-5.2", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_5_2_2025_12_11 =
            T.let(
              :"gpt-5.2-2025-12-11",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_2_CHAT_LATEST =
            T.let(
              :"gpt-5.2-chat-latest",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_2_PRO =
            T.let(
              :"gpt-5.2-pro",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_2_PRO_2025_12_11 =
            T.let(
              :"gpt-5.2-pro-2025-12-11",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_1 =
            T.let(:"gpt-5.1", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_5_1_2025_11_13 =
            T.let(
              :"gpt-5.1-2025-11-13",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_1_CODEX =
            T.let(
              :"gpt-5.1-codex",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_1_MINI =
            T.let(
              :"gpt-5.1-mini",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_1_CHAT_LATEST =
            T.let(
              :"gpt-5.1-chat-latest",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5 =
            T.let(:"gpt-5", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_5_MINI =
            T.let(
              :"gpt-5-mini",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_NANO =
            T.let(
              :"gpt-5-nano",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_2025_08_07 =
            T.let(
              :"gpt-5-2025-08-07",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_MINI_2025_08_07 =
            T.let(
              :"gpt-5-mini-2025-08-07",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_NANO_2025_08_07 =
            T.let(
              :"gpt-5-nano-2025-08-07",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_CHAT_LATEST =
            T.let(
              :"gpt-5-chat-latest",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_1 =
            T.let(:"gpt-4.1", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_4_1_MINI =
            T.let(
              :"gpt-4.1-mini",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_1_NANO =
            T.let(
              :"gpt-4.1-nano",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_1_2025_04_14 =
            T.let(
              :"gpt-4.1-2025-04-14",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_1_MINI_2025_04_14 =
            T.let(
              :"gpt-4.1-mini-2025-04-14",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_1_NANO_2025_04_14 =
            T.let(
              :"gpt-4.1-nano-2025-04-14",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O4_MINI =
            T.let(:"o4-mini", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          O4_MINI_2025_04_16 =
            T.let(
              :"o4-mini-2025-04-16",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O3 = T.let(:o3, OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          O3_2025_04_16 =
            T.let(
              :"o3-2025-04-16",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O3_MINI =
            T.let(:"o3-mini", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          O3_MINI_2025_01_31 =
            T.let(
              :"o3-mini-2025-01-31",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O1 = T.let(:o1, OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          O1_2024_12_17 =
            T.let(
              :"o1-2024-12-17",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O1_PREVIEW =
            T.let(
              :"o1-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O1_PREVIEW_2024_09_12 =
            T.let(
              :"o1-preview-2024-09-12",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O1_MINI =
            T.let(:"o1-mini", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          O1_MINI_2024_09_12 =
            T.let(
              :"o1-mini-2024-09-12",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O =
            T.let(:"gpt-4o", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_4O_2024_11_20 =
            T.let(
              :"gpt-4o-2024-11-20",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_2024_08_06 =
            T.let(
              :"gpt-4o-2024-08-06",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_2024_05_13 =
            T.let(
              :"gpt-4o-2024-05-13",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_AUDIO_PREVIEW =
            T.let(
              :"gpt-4o-audio-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_AUDIO_PREVIEW_2024_10_01 =
            T.let(
              :"gpt-4o-audio-preview-2024-10-01",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_AUDIO_PREVIEW_2024_12_17 =
            T.let(
              :"gpt-4o-audio-preview-2024-12-17",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_AUDIO_PREVIEW_2025_06_03 =
            T.let(
              :"gpt-4o-audio-preview-2025-06-03",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_MINI_AUDIO_PREVIEW =
            T.let(
              :"gpt-4o-mini-audio-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_MINI_AUDIO_PREVIEW_2024_12_17 =
            T.let(
              :"gpt-4o-mini-audio-preview-2024-12-17",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_SEARCH_PREVIEW =
            T.let(
              :"gpt-4o-search-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_MINI_SEARCH_PREVIEW =
            T.let(
              :"gpt-4o-mini-search-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_SEARCH_PREVIEW_2025_03_11 =
            T.let(
              :"gpt-4o-search-preview-2025-03-11",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_MINI_SEARCH_PREVIEW_2025_03_11 =
            T.let(
              :"gpt-4o-mini-search-preview-2025-03-11",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          CHATGPT_4O_LATEST =
            T.let(
              :"chatgpt-4o-latest",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          CODEX_MINI_LATEST =
            T.let(
              :"codex-mini-latest",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_MINI =
            T.let(
              :"gpt-4o-mini",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4O_MINI_2024_07_18 =
            T.let(
              :"gpt-4o-mini-2024-07-18",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_TURBO =
            T.let(
              :"gpt-4-turbo",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_TURBO_2024_04_09 =
            T.let(
              :"gpt-4-turbo-2024-04-09",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_0125_PREVIEW =
            T.let(
              :"gpt-4-0125-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_TURBO_PREVIEW =
            T.let(
              :"gpt-4-turbo-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_1106_PREVIEW =
            T.let(
              :"gpt-4-1106-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_VISION_PREVIEW =
            T.let(
              :"gpt-4-vision-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4 =
            T.let(:"gpt-4", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_4_0314 =
            T.let(
              :"gpt-4-0314",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_0613 =
            T.let(
              :"gpt-4-0613",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_32K =
            T.let(:"gpt-4-32k", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_4_32K_0314 =
            T.let(
              :"gpt-4-32k-0314",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_4_32K_0613 =
            T.let(
              :"gpt-4-32k-0613",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_3_5_TURBO =
            T.let(
              :"gpt-3.5-turbo",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_3_5_TURBO_16K =
            T.let(
              :"gpt-3.5-turbo-16k",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_3_5_TURBO_0301 =
            T.let(
              :"gpt-3.5-turbo-0301",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_3_5_TURBO_0613 =
            T.let(
              :"gpt-3.5-turbo-0613",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_3_5_TURBO_1106 =
            T.let(
              :"gpt-3.5-turbo-1106",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_3_5_TURBO_0125 =
            T.let(
              :"gpt-3.5-turbo-0125",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_3_5_TURBO_16K_0613 =
            T.let(
              :"gpt-3.5-turbo-16k-0613",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O1_PRO =
            T.let(:"o1-pro", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          O1_PRO_2025_03_19 =
            T.let(
              :"o1-pro-2025-03-19",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O3_PRO =
            T.let(:"o3-pro", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          O3_PRO_2025_06_10 =
            T.let(
              :"o3-pro-2025-06-10",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O3_DEEP_RESEARCH =
            T.let(
              :"o3-deep-research",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O3_DEEP_RESEARCH_2025_06_26 =
            T.let(
              :"o3-deep-research-2025-06-26",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O4_MINI_DEEP_RESEARCH =
            T.let(
              :"o4-mini-deep-research",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          O4_MINI_DEEP_RESEARCH_2025_06_26 =
            T.let(
              :"o4-mini-deep-research-2025-06-26",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          COMPUTER_USE_PREVIEW =
            T.let(
              :"computer-use-preview",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          COMPUTER_USE_PREVIEW_2025_03_11 =
            T.let(
              :"computer-use-preview-2025-03-11",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_CODEX =
            T.let(
              :"gpt-5-codex",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_PRO =
            T.let(:"gpt-5-pro", OpenAI::Beta::BetaResponse::Model::TaggedSymbol)
          GPT_5_PRO_2025_10_06 =
            T.let(
              :"gpt-5-pro-2025-10-06",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
          GPT_5_1_CODEX_MAX =
            T.let(
              :"gpt-5.1-codex-max",
              OpenAI::Beta::BetaResponse::Model::TaggedSymbol
            )
        end

        # How the model should select which tool (or tools) to use when generating a
        # response. See the `tools` parameter to see how to specify which tools the model
        # can call.
        module ToolChoice
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaToolChoiceOptions::TaggedSymbol,
                OpenAI::Beta::BetaToolChoiceAllowed,
                OpenAI::Beta::BetaToolChoiceTypes,
                OpenAI::Beta::BetaToolChoiceFunction,
                OpenAI::Beta::BetaToolChoiceMcp,
                OpenAI::Beta::BetaToolChoiceCustom,
                OpenAI::Beta::BetaResponse::ToolChoice::BetaSpecificProgrammaticToolCallingParam,
                OpenAI::Beta::BetaToolChoiceApplyPatch,
                OpenAI::Beta::BetaToolChoiceShell
              )
            end

          class BetaSpecificProgrammaticToolCallingParam < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponse::ToolChoice::BetaSpecificProgrammaticToolCallingParam,
                  OpenAI::Internal::AnyHash
                )
              end

            # The tool to call. Always `programmatic_tool_calling`.
            sig { returns(Symbol) }
            attr_accessor :type

            sig { params(type: Symbol).returns(T.attached_class) }
            def self.new(
              # The tool to call. Always `programmatic_tool_calling`.
              type: :programmatic_tool_calling
            )
            end

            sig { override.returns({ type: Symbol }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaResponse::ToolChoice::Variants]
            )
          end
          def self.variants
          end
        end

        class Conversation < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponse::Conversation,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the conversation that this response was associated with.
          sig { returns(String) }
          attr_accessor :id

          # The conversation that this response belonged to. Input items and output items
          # from this response were automatically added to this conversation.
          sig { params(id: String).returns(T.attached_class) }
          def self.new(
            # The unique ID of the conversation that this response was associated with.
            id:
          )
          end

          sig { override.returns({ id: String }) }
          def to_hash
          end
        end

        class Moderation < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponse::Moderation,
                OpenAI::Internal::AnyHash
              )
            end

          # Moderation for the response input.
          sig do
            returns(OpenAI::Beta::BetaResponse::Moderation::Input::Variants)
          end
          attr_accessor :input

          # Moderation for the response output.
          sig do
            returns(OpenAI::Beta::BetaResponse::Moderation::Output::Variants)
          end
          attr_accessor :output

          # Moderation results for the response input and output, if moderated completions
          # were requested.
          sig do
            params(
              input:
                T.any(
                  OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::OrHash,
                  OpenAI::Beta::BetaResponse::Moderation::Input::Error::OrHash
                ),
              output:
                T.any(
                  OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::OrHash,
                  OpenAI::Beta::BetaResponse::Moderation::Output::Error::OrHash
                )
            ).returns(T.attached_class)
          end
          def self.new(
            # Moderation for the response input.
            input:,
            # Moderation for the response output.
            output:
          )
          end

          sig do
            override.returns(
              {
                input: OpenAI::Beta::BetaResponse::Moderation::Input::Variants,
                output: OpenAI::Beta::BetaResponse::Moderation::Output::Variants
              }
            )
          end
          def to_hash
          end

          # Moderation for the response input.
          module Input
            extend OpenAI::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult,
                  OpenAI::Beta::BetaResponse::Moderation::Input::Error
                )
              end

            class ModerationResult < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult,
                    OpenAI::Internal::AnyHash
                  )
                end

              # A dictionary of moderation categories to booleans, True if the input is flagged
              # under this category.
              sig { returns(T::Hash[Symbol, T::Boolean]) }
              attr_accessor :categories

              # Which modalities of input are reflected by the score for each category.
              sig do
                returns(
                  T::Hash[
                    Symbol,
                    T::Array[
                      OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                    ]
                  ]
                )
              end
              attr_accessor :category_applied_input_types

              # A dictionary of moderation categories to scores.
              sig { returns(T::Hash[Symbol, Float]) }
              attr_accessor :category_scores

              # A boolean indicating whether the content was flagged by any category.
              sig { returns(T::Boolean) }
              attr_accessor :flagged

              # The moderation model that produced this result.
              sig { returns(String) }
              attr_accessor :model

              # The object type, which was always `moderation_result` for successful moderation
              # results.
              sig { returns(Symbol) }
              attr_accessor :type

              # A moderation result produced for the response input or output.
              sig do
                params(
                  categories: T::Hash[Symbol, T::Boolean],
                  category_applied_input_types:
                    T::Hash[
                      Symbol,
                      T::Array[
                        OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::CategoryAppliedInputType::OrSymbol
                      ]
                    ],
                  category_scores: T::Hash[Symbol, Float],
                  flagged: T::Boolean,
                  model: String,
                  type: Symbol
                ).returns(T.attached_class)
              end
              def self.new(
                # A dictionary of moderation categories to booleans, True if the input is flagged
                # under this category.
                categories:,
                # Which modalities of input are reflected by the score for each category.
                category_applied_input_types:,
                # A dictionary of moderation categories to scores.
                category_scores:,
                # A boolean indicating whether the content was flagged by any category.
                flagged:,
                # The moderation model that produced this result.
                model:,
                # The object type, which was always `moderation_result` for successful moderation
                # results.
                type: :moderation_result
              )
              end

              sig do
                override.returns(
                  {
                    categories: T::Hash[Symbol, T::Boolean],
                    category_applied_input_types:
                      T::Hash[
                        Symbol,
                        T::Array[
                          OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                        ]
                      ],
                    category_scores: T::Hash[Symbol, Float],
                    flagged: T::Boolean,
                    model: String,
                    type: Symbol
                  }
                )
              end
              def to_hash
              end

              module CategoryAppliedInputType
                extend OpenAI::Internal::Type::Enum

                TaggedSymbol =
                  T.type_alias do
                    T.all(
                      Symbol,
                      OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::CategoryAppliedInputType
                    )
                  end
                OrSymbol = T.type_alias { T.any(Symbol, String) }

                TEXT =
                  T.let(
                    :text,
                    OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                  )
                IMAGE =
                  T.let(
                    :image,
                    OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                  )

                sig do
                  override.returns(
                    T::Array[
                      OpenAI::Beta::BetaResponse::Moderation::Input::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                    ]
                  )
                end
                def self.values
                end
              end
            end

            class Error < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Beta::BetaResponse::Moderation::Input::Error,
                    OpenAI::Internal::AnyHash
                  )
                end

              # The error code.
              sig { returns(String) }
              attr_accessor :code

              # The error message.
              sig { returns(String) }
              attr_accessor :message

              # The object type, which was always `error` for moderation failures.
              sig { returns(Symbol) }
              attr_accessor :type

              # An error produced while attempting moderation for the response input or output.
              sig do
                params(code: String, message: String, type: Symbol).returns(
                  T.attached_class
                )
              end
              def self.new(
                # The error code.
                code:,
                # The error message.
                message:,
                # The object type, which was always `error` for moderation failures.
                type: :error
              )
              end

              sig do
                override.returns(
                  { code: String, message: String, type: Symbol }
                )
              end
              def to_hash
              end
            end

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::Moderation::Input::Variants
                ]
              )
            end
            def self.variants
            end
          end

          # Moderation for the response output.
          module Output
            extend OpenAI::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult,
                  OpenAI::Beta::BetaResponse::Moderation::Output::Error
                )
              end

            class ModerationResult < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult,
                    OpenAI::Internal::AnyHash
                  )
                end

              # A dictionary of moderation categories to booleans, True if the input is flagged
              # under this category.
              sig { returns(T::Hash[Symbol, T::Boolean]) }
              attr_accessor :categories

              # Which modalities of input are reflected by the score for each category.
              sig do
                returns(
                  T::Hash[
                    Symbol,
                    T::Array[
                      OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                    ]
                  ]
                )
              end
              attr_accessor :category_applied_input_types

              # A dictionary of moderation categories to scores.
              sig { returns(T::Hash[Symbol, Float]) }
              attr_accessor :category_scores

              # A boolean indicating whether the content was flagged by any category.
              sig { returns(T::Boolean) }
              attr_accessor :flagged

              # The moderation model that produced this result.
              sig { returns(String) }
              attr_accessor :model

              # The object type, which was always `moderation_result` for successful moderation
              # results.
              sig { returns(Symbol) }
              attr_accessor :type

              # A moderation result produced for the response input or output.
              sig do
                params(
                  categories: T::Hash[Symbol, T::Boolean],
                  category_applied_input_types:
                    T::Hash[
                      Symbol,
                      T::Array[
                        OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::CategoryAppliedInputType::OrSymbol
                      ]
                    ],
                  category_scores: T::Hash[Symbol, Float],
                  flagged: T::Boolean,
                  model: String,
                  type: Symbol
                ).returns(T.attached_class)
              end
              def self.new(
                # A dictionary of moderation categories to booleans, True if the input is flagged
                # under this category.
                categories:,
                # Which modalities of input are reflected by the score for each category.
                category_applied_input_types:,
                # A dictionary of moderation categories to scores.
                category_scores:,
                # A boolean indicating whether the content was flagged by any category.
                flagged:,
                # The moderation model that produced this result.
                model:,
                # The object type, which was always `moderation_result` for successful moderation
                # results.
                type: :moderation_result
              )
              end

              sig do
                override.returns(
                  {
                    categories: T::Hash[Symbol, T::Boolean],
                    category_applied_input_types:
                      T::Hash[
                        Symbol,
                        T::Array[
                          OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                        ]
                      ],
                    category_scores: T::Hash[Symbol, Float],
                    flagged: T::Boolean,
                    model: String,
                    type: Symbol
                  }
                )
              end
              def to_hash
              end

              module CategoryAppliedInputType
                extend OpenAI::Internal::Type::Enum

                TaggedSymbol =
                  T.type_alias do
                    T.all(
                      Symbol,
                      OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::CategoryAppliedInputType
                    )
                  end
                OrSymbol = T.type_alias { T.any(Symbol, String) }

                TEXT =
                  T.let(
                    :text,
                    OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                  )
                IMAGE =
                  T.let(
                    :image,
                    OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                  )

                sig do
                  override.returns(
                    T::Array[
                      OpenAI::Beta::BetaResponse::Moderation::Output::ModerationResult::CategoryAppliedInputType::TaggedSymbol
                    ]
                  )
                end
                def self.values
                end
              end
            end

            class Error < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Beta::BetaResponse::Moderation::Output::Error,
                    OpenAI::Internal::AnyHash
                  )
                end

              # The error code.
              sig { returns(String) }
              attr_accessor :code

              # The error message.
              sig { returns(String) }
              attr_accessor :message

              # The object type, which was always `error` for moderation failures.
              sig { returns(Symbol) }
              attr_accessor :type

              # An error produced while attempting moderation for the response input or output.
              sig do
                params(code: String, message: String, type: Symbol).returns(
                  T.attached_class
                )
              end
              def self.new(
                # The error code.
                code:,
                # The error message.
                message:,
                # The object type, which was always `error` for moderation failures.
                type: :error
              )
              end

              sig do
                override.returns(
                  { code: String, message: String, type: Symbol }
                )
              end
              def to_hash
              end
            end

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::Moderation::Output::Variants
                ]
              )
            end
            def self.variants
            end
          end
        end

        class PromptCacheOptions < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponse::PromptCacheOptions,
                OpenAI::Internal::AnyHash
              )
            end

          # Whether implicit prompt-cache breakpoints were enabled.
          sig do
            returns(
              OpenAI::Beta::BetaResponse::PromptCacheOptions::Mode::TaggedSymbol
            )
          end
          attr_accessor :mode

          # The minimum lifetime applied to each cache breakpoint.
          sig do
            returns(
              OpenAI::Beta::BetaResponse::PromptCacheOptions::Ttl::TaggedSymbol
            )
          end
          attr_accessor :ttl

          # The prompt-caching options that were applied to the response. Supported for
          # `gpt-5.6` and later models.
          sig do
            params(
              mode:
                OpenAI::Beta::BetaResponse::PromptCacheOptions::Mode::OrSymbol,
              ttl: OpenAI::Beta::BetaResponse::PromptCacheOptions::Ttl::OrSymbol
            ).returns(T.attached_class)
          end
          def self.new(
            # Whether implicit prompt-cache breakpoints were enabled.
            mode:,
            # The minimum lifetime applied to each cache breakpoint.
            ttl:
          )
          end

          sig do
            override.returns(
              {
                mode:
                  OpenAI::Beta::BetaResponse::PromptCacheOptions::Mode::TaggedSymbol,
                ttl:
                  OpenAI::Beta::BetaResponse::PromptCacheOptions::Ttl::TaggedSymbol
              }
            )
          end
          def to_hash
          end

          # Whether implicit prompt-cache breakpoints were enabled.
          module Mode
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Beta::BetaResponse::PromptCacheOptions::Mode
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            IMPLICIT =
              T.let(
                :implicit,
                OpenAI::Beta::BetaResponse::PromptCacheOptions::Mode::TaggedSymbol
              )
            EXPLICIT =
              T.let(
                :explicit,
                OpenAI::Beta::BetaResponse::PromptCacheOptions::Mode::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::PromptCacheOptions::Mode::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end

          # The minimum lifetime applied to each cache breakpoint.
          module Ttl
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Beta::BetaResponse::PromptCacheOptions::Ttl
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            TTL_30M =
              T.let(
                :"30m",
                OpenAI::Beta::BetaResponse::PromptCacheOptions::Ttl::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::PromptCacheOptions::Ttl::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        # Deprecated. Use `prompt_cache_options.ttl` instead.
        #
        # The retention policy for the prompt cache. Set to `24h` to enable extended
        # prompt caching, which keeps cached prefixes active for longer, up to a maximum
        # of 24 hours.
        # [Learn more](https://platform.openai.com/docs/guides/prompt-caching#prompt-cache-retention).
        # This field expresses a maximum retention policy, while
        # `prompt_cache_options.ttl` expresses a minimum cache lifetime. The two fields
        # are independent and do not interact. For `gpt-5.5`, `gpt-5.5-pro`, and future
        # models, only `24h` is supported.
        #
        # For older models that support both `in_memory` and `24h`, the default depends on
        # your organization's data retention policy:
        #
        # - Organizations without ZDR enabled default to `24h`.
        # - Organizations with ZDR enabled default to `in_memory` when
        #   `prompt_cache_retention` is not specified.
        module PromptCacheRetention
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaResponse::PromptCacheRetention)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_MEMORY =
            T.let(
              :in_memory,
              OpenAI::Beta::BetaResponse::PromptCacheRetention::TaggedSymbol
            )
          PROMPT_CACHE_RETENTION_24H =
            T.let(
              :"24h",
              OpenAI::Beta::BetaResponse::PromptCacheRetention::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Beta::BetaResponse::PromptCacheRetention::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        class Reasoning < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Beta::BetaResponse::Reasoning,
                OpenAI::Internal::AnyHash
              )
            end

          # Controls which reasoning items are rendered back to the model on later turns. If
          # omitted or set to `auto`, the model determines the context mode. The `gpt-5.6`
          # model family defaults to `all_turns`; earlier models default to `current_turn`.
          #
          # When returned on a response, this is the effective reasoning context mode used
          # for the response.
          sig do
            returns(
              T.nilable(
                OpenAI::Beta::BetaResponse::Reasoning::Context::TaggedSymbol
              )
            )
          end
          attr_accessor :context

          # Constrains effort on reasoning for reasoning models. Currently supported values
          # are `none`, `minimal`, `low`, `medium`, `high`, `xhigh`, and `max`. Reducing
          # reasoning effort can result in faster responses and fewer tokens used on
          # reasoning in a response. Not all reasoning models support every value. See the
          # [reasoning guide](https://platform.openai.com/docs/guides/reasoning) for
          # model-specific support.
          sig do
            returns(
              T.nilable(
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )
            )
          end
          attr_accessor :effort

          # **Deprecated:** use `summary` instead.
          #
          # A summary of the reasoning performed by the model. This can be useful for
          # debugging and understanding the model's reasoning process. One of `auto`,
          # `concise`, or `detailed`.
          sig do
            returns(
              T.nilable(
                OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary::TaggedSymbol
              )
            )
          end
          attr_accessor :generate_summary

          # Controls the reasoning execution mode for the request.
          #
          # When returned on a response, this is the effective execution mode.
          sig do
            returns(
              T.nilable(OpenAI::Beta::BetaResponse::Reasoning::Mode::Variants)
            )
          end
          attr_reader :mode

          sig do
            params(
              mode:
                T.any(
                  String,
                  OpenAI::Beta::BetaResponse::Reasoning::Mode::OrSymbol
                )
            ).void
          end
          attr_writer :mode

          # A summary of the reasoning performed by the model. This can be useful for
          # debugging and understanding the model's reasoning process. One of `auto`,
          # `concise`, or `detailed`.
          #
          # `concise` is supported for `computer-use-preview` models and all reasoning
          # models after `gpt-5`.
          sig do
            returns(
              T.nilable(
                OpenAI::Beta::BetaResponse::Reasoning::Summary::TaggedSymbol
              )
            )
          end
          attr_accessor :summary

          # **gpt-5 and o-series models only**
          #
          # Configuration options for
          # [reasoning models](https://platform.openai.com/docs/guides/reasoning).
          sig do
            params(
              context:
                T.nilable(
                  OpenAI::Beta::BetaResponse::Reasoning::Context::OrSymbol
                ),
              effort:
                T.nilable(
                  OpenAI::Beta::BetaResponse::Reasoning::Effort::OrSymbol
                ),
              generate_summary:
                T.nilable(
                  OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary::OrSymbol
                ),
              mode:
                T.any(
                  String,
                  OpenAI::Beta::BetaResponse::Reasoning::Mode::OrSymbol
                ),
              summary:
                T.nilable(
                  OpenAI::Beta::BetaResponse::Reasoning::Summary::OrSymbol
                )
            ).returns(T.attached_class)
          end
          def self.new(
            # Controls which reasoning items are rendered back to the model on later turns. If
            # omitted or set to `auto`, the model determines the context mode. The `gpt-5.6`
            # model family defaults to `all_turns`; earlier models default to `current_turn`.
            #
            # When returned on a response, this is the effective reasoning context mode used
            # for the response.
            context: nil,
            # Constrains effort on reasoning for reasoning models. Currently supported values
            # are `none`, `minimal`, `low`, `medium`, `high`, `xhigh`, and `max`. Reducing
            # reasoning effort can result in faster responses and fewer tokens used on
            # reasoning in a response. Not all reasoning models support every value. See the
            # [reasoning guide](https://platform.openai.com/docs/guides/reasoning) for
            # model-specific support.
            effort: nil,
            # **Deprecated:** use `summary` instead.
            #
            # A summary of the reasoning performed by the model. This can be useful for
            # debugging and understanding the model's reasoning process. One of `auto`,
            # `concise`, or `detailed`.
            generate_summary: nil,
            # Controls the reasoning execution mode for the request.
            #
            # When returned on a response, this is the effective execution mode.
            mode: nil,
            # A summary of the reasoning performed by the model. This can be useful for
            # debugging and understanding the model's reasoning process. One of `auto`,
            # `concise`, or `detailed`.
            #
            # `concise` is supported for `computer-use-preview` models and all reasoning
            # models after `gpt-5`.
            summary: nil
          )
          end

          sig do
            override.returns(
              {
                context:
                  T.nilable(
                    OpenAI::Beta::BetaResponse::Reasoning::Context::TaggedSymbol
                  ),
                effort:
                  T.nilable(
                    OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
                  ),
                generate_summary:
                  T.nilable(
                    OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary::TaggedSymbol
                  ),
                mode: OpenAI::Beta::BetaResponse::Reasoning::Mode::Variants,
                summary:
                  T.nilable(
                    OpenAI::Beta::BetaResponse::Reasoning::Summary::TaggedSymbol
                  )
              }
            )
          end
          def to_hash
          end

          # Controls which reasoning items are rendered back to the model on later turns. If
          # omitted or set to `auto`, the model determines the context mode. The `gpt-5.6`
          # model family defaults to `all_turns`; earlier models default to `current_turn`.
          #
          # When returned on a response, this is the effective reasoning context mode used
          # for the response.
          module Context
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(Symbol, OpenAI::Beta::BetaResponse::Reasoning::Context)
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            AUTO =
              T.let(
                :auto,
                OpenAI::Beta::BetaResponse::Reasoning::Context::TaggedSymbol
              )
            CURRENT_TURN =
              T.let(
                :current_turn,
                OpenAI::Beta::BetaResponse::Reasoning::Context::TaggedSymbol
              )
            ALL_TURNS =
              T.let(
                :all_turns,
                OpenAI::Beta::BetaResponse::Reasoning::Context::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::Reasoning::Context::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end

          # Constrains effort on reasoning for reasoning models. Currently supported values
          # are `none`, `minimal`, `low`, `medium`, `high`, `xhigh`, and `max`. Reducing
          # reasoning effort can result in faster responses and fewer tokens used on
          # reasoning in a response. Not all reasoning models support every value. See the
          # [reasoning guide](https://platform.openai.com/docs/guides/reasoning) for
          # model-specific support.
          module Effort
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(Symbol, OpenAI::Beta::BetaResponse::Reasoning::Effort)
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            NONE =
              T.let(
                :none,
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )
            MINIMAL =
              T.let(
                :minimal,
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )
            LOW =
              T.let(
                :low,
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )
            MEDIUM =
              T.let(
                :medium,
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )
            HIGH =
              T.let(
                :high,
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )
            XHIGH =
              T.let(
                :xhigh,
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )
            MAX =
              T.let(
                :max,
                OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::Reasoning::Effort::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end

          # **Deprecated:** use `summary` instead.
          #
          # A summary of the reasoning performed by the model. This can be useful for
          # debugging and understanding the model's reasoning process. One of `auto`,
          # `concise`, or `detailed`.
          module GenerateSummary
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            AUTO =
              T.let(
                :auto,
                OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary::TaggedSymbol
              )
            CONCISE =
              T.let(
                :concise,
                OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary::TaggedSymbol
              )
            DETAILED =
              T.let(
                :detailed,
                OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::Reasoning::GenerateSummary::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end

          # Controls the reasoning execution mode for the request.
          #
          # When returned on a response, this is the effective execution mode.
          module Mode
            extend OpenAI::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  String,
                  OpenAI::Beta::BetaResponse::Reasoning::Mode::TaggedSymbol
                )
              end

            sig do
              override.returns(
                T::Array[OpenAI::Beta::BetaResponse::Reasoning::Mode::Variants]
              )
            end
            def self.variants
            end

            TaggedSymbol =
              T.type_alias do
                T.all(Symbol, OpenAI::Beta::BetaResponse::Reasoning::Mode)
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            STANDARD =
              T.let(
                :standard,
                OpenAI::Beta::BetaResponse::Reasoning::Mode::TaggedSymbol
              )
            PRO =
              T.let(
                :pro,
                OpenAI::Beta::BetaResponse::Reasoning::Mode::TaggedSymbol
              )
          end

          # A summary of the reasoning performed by the model. This can be useful for
          # debugging and understanding the model's reasoning process. One of `auto`,
          # `concise`, or `detailed`.
          #
          # `concise` is supported for `computer-use-preview` models and all reasoning
          # models after `gpt-5`.
          module Summary
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(Symbol, OpenAI::Beta::BetaResponse::Reasoning::Summary)
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            AUTO =
              T.let(
                :auto,
                OpenAI::Beta::BetaResponse::Reasoning::Summary::TaggedSymbol
              )
            CONCISE =
              T.let(
                :concise,
                OpenAI::Beta::BetaResponse::Reasoning::Summary::TaggedSymbol
              )
            DETAILED =
              T.let(
                :detailed,
                OpenAI::Beta::BetaResponse::Reasoning::Summary::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Beta::BetaResponse::Reasoning::Summary::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        # Specifies the processing type used for serving the request.
        #
        # - If set to 'auto', then the request will be processed with the service tier
        #   configured in the Project settings. Unless otherwise configured, the Project
        #   will use 'default'.
        # - If set to 'default', then the request will be processed with the standard
        #   pricing and performance for the selected model.
        # - If set to '[flex](https://platform.openai.com/docs/guides/flex-processing)' or
        #   '[priority](https://openai.com/api-priority-processing/)', then the request
        #   will be processed with the corresponding service tier.
        # - When not set, the default behavior is 'auto'.
        #
        # When the `service_tier` parameter is set, the response body will include the
        # `service_tier` value based on the processing mode actually used to serve the
        # request. This response value may be different from the value set in the
        # parameter.
        module ServiceTier
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaResponse::ServiceTier)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          AUTO =
            T.let(:auto, OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol)
          DEFAULT =
            T.let(
              :default,
              OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol
            )
          FLEX =
            T.let(:flex, OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol)
          SCALE =
            T.let(:scale, OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol)
          PRIORITY =
            T.let(
              :priority,
              OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaResponse::ServiceTier::TaggedSymbol]
            )
          end
          def self.values
          end
        end

        # The truncation strategy to use for the model response.
        #
        # - `auto`: If the input to this Response exceeds the model's context window size,
        #   the model will truncate the response to fit the context window by dropping
        #   items from the beginning of the conversation.
        # - `disabled` (default): If the input size will exceed the context window size
        #   for a model, the request will fail with a 400 error.
        module Truncation
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Beta::BetaResponse::Truncation)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          AUTO =
            T.let(:auto, OpenAI::Beta::BetaResponse::Truncation::TaggedSymbol)
          DISABLED =
            T.let(
              :disabled,
              OpenAI::Beta::BetaResponse::Truncation::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[OpenAI::Beta::BetaResponse::Truncation::TaggedSymbol]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
