# typed: strong

module OpenAI
  module Models

    module Beta

      class ThreadCreateParams < OpenAI::Internal::Type::BaseModel

        extend OpenAI::Internal::Type::RequestParameters::Converter
        include OpenAI::Internal::Type::RequestParameters

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::ThreadCreateParams,
            OpenAI::Internal::AnyHash
          )
        end

        # A list of [messages](https://platform.openai.com/docs/api-reference/messages) to
        # start the thread with.
        sig { returns(T.nilable(T::Array[OpenAI::Beta::ThreadCreateParams::Message])) }
        attr_reader :messages

        sig { params(messages: T::Array[OpenAI::Beta::ThreadCreateParams::Message::OrHash]).void }
        attr_writer :messages

        # Set of 16 key-value pairs that can be attached to an object. This can be useful
        # for storing additional information about the object in a structured format, and
        # querying for objects via API or the dashboard.
        #
        # Keys are strings with a maximum length of 64 characters. Values are strings with
        # a maximum length of 512 characters.
        sig { returns(T.nilable(T::Hash[Symbol, String])) }
        attr_accessor :metadata

        # A set of resources that are made available to the assistant's tools in this
        # thread. The resources are specific to the type of tool. For example, the
        # `code_interpreter` tool requires a list of file IDs, while the `file_search`
        # tool requires a list of vector store IDs.
        sig { returns(T.nilable(OpenAI::Beta::ThreadCreateParams::ToolResources)) }
        attr_reader :tool_resources

        sig { params(tool_resources: T.nilable(OpenAI::Beta::ThreadCreateParams::ToolResources::OrHash)).void }
        attr_writer :tool_resources

        sig do
          params(

            messages: T::Array[OpenAI::Beta::ThreadCreateParams::Message::OrHash],

            metadata: T.nilable(T::Hash[Symbol, String]),

            tool_resources: T.nilable(OpenAI::Beta::ThreadCreateParams::ToolResources::OrHash),

            request_options: OpenAI::RequestOptions::OrHash
          )
            .returns(T.attached_class)
        end
        def self.new(

          # A list of [messages](https://platform.openai.com/docs/api-reference/messages) to
          # start the thread with.
          messages: nil,

          # Set of 16 key-value pairs that can be attached to an object. This can be useful
          # for storing additional information about the object in a structured format, and
          # querying for objects via API or the dashboard.
          #
          # Keys are strings with a maximum length of 64 characters. Values are strings with
          # a maximum length of 512 characters.
          metadata: nil,

          # A set of resources that are made available to the assistant's tools in this
          # thread. The resources are specific to the type of tool. For example, the
          # `code_interpreter` tool requires a list of file IDs, while the `file_search`
          # tool requires a list of vector store IDs.
          tool_resources: nil,

          request_options: {}
        )
        end

        sig do
          override.returns(
            {
              messages: T::Array[OpenAI::Beta::ThreadCreateParams::Message],
              metadata: T.nilable(T::Hash[Symbol, String]),
              tool_resources: T.nilable(OpenAI::Beta::ThreadCreateParams::ToolResources),
              request_options: OpenAI::RequestOptions
            }
          )
        end
        def to_hash
        end

        class Message < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Beta::ThreadCreateParams::Message,
              OpenAI::Internal::AnyHash
            )
          end

          # The text contents of the message.
          sig { returns(OpenAI::Beta::ThreadCreateParams::Message::Content::Variants) }
          attr_accessor :content

          # The role of the entity that is creating the message. Allowed values include:
          #
          # - `user`: Indicates the message is sent by an actual user and should be used in
          #   most cases to represent user-generated messages.
          # - `assistant`: Indicates the message is generated by the assistant. Use this
          #   value to insert messages from the assistant into the conversation.
          sig { returns(OpenAI::Beta::ThreadCreateParams::Message::Role::OrSymbol) }
          attr_accessor :role

          # A list of files attached to the message, and the tools they should be added to.
          sig { returns(T.nilable(T::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment])) }
          attr_accessor :attachments

          # Set of 16 key-value pairs that can be attached to an object. This can be useful
          # for storing additional information about the object in a structured format, and
          # querying for objects via API or the dashboard.
          #
          # Keys are strings with a maximum length of 64 characters. Values are strings with
          # a maximum length of 512 characters.
          sig { returns(T.nilable(T::Hash[Symbol, String])) }
          attr_accessor :metadata

          sig do
            params(

              content: OpenAI::Beta::ThreadCreateParams::Message::Content::Variants,

              role: OpenAI::Beta::ThreadCreateParams::Message::Role::OrSymbol,

              attachments: T.nilable(T::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment::OrHash]),

              metadata: T.nilable(T::Hash[Symbol, String])
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The text contents of the message.
            content:,

            # The role of the entity that is creating the message. Allowed values include:
            #
            # - `user`: Indicates the message is sent by an actual user and should be used in
            #   most cases to represent user-generated messages.
            # - `assistant`: Indicates the message is generated by the assistant. Use this
            #   value to insert messages from the assistant into the conversation.
            role:,

            # A list of files attached to the message, and the tools they should be added to.
            attachments: nil,

            # Set of 16 key-value pairs that can be attached to an object. This can be useful
            # for storing additional information about the object in a structured format, and
            # querying for objects via API or the dashboard.
            #
            # Keys are strings with a maximum length of 64 characters. Values are strings with
            # a maximum length of 512 characters.

            metadata: nil
          )
          end

          sig do
            override.returns(
              {
                content: OpenAI::Beta::ThreadCreateParams::Message::Content::Variants,
                role: OpenAI::Beta::ThreadCreateParams::Message::Role::OrSymbol,
                attachments: T.nilable(T::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment]),
                metadata: T.nilable(T::Hash[Symbol, String])
              }
            )
          end
          def to_hash
          end

          # The text contents of the message.
          module Content
            extend OpenAI::Internal::Type::Union

            Variants = T.type_alias {
              T.any(String, T::Array[OpenAI::Beta::Threads::MessageContentPartParam::Variants])
            }

            sig { override.returns(T::Array[OpenAI::Beta::ThreadCreateParams::Message::Content::Variants]) }
            def self.variants
            end

            MessageContentPartParamArray = T.let(
              OpenAI::Internal::Type::ArrayOf[union: OpenAI::Beta::Threads::MessageContentPartParam],
              OpenAI::Internal::Type::Converter
            )

          end

          # The role of the entity that is creating the message. Allowed values include:
          #
          # - `user`: Indicates the message is sent by an actual user and should be used in
          #   most cases to represent user-generated messages.
          # - `assistant`: Indicates the message is generated by the assistant. Use this
          #   value to insert messages from the assistant into the conversation.
          module Role
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Beta::ThreadCreateParams::Message::Role) }
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            USER = T.let(:user, OpenAI::Beta::ThreadCreateParams::Message::Role::TaggedSymbol)
            ASSISTANT = T.let(:assistant, OpenAI::Beta::ThreadCreateParams::Message::Role::TaggedSymbol)

            sig { override.returns(T::Array[OpenAI::Beta::ThreadCreateParams::Message::Role::TaggedSymbol]) }
            def self.values
            end
          end

          class Attachment < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Beta::ThreadCreateParams::Message::Attachment,
                OpenAI::Internal::AnyHash
              )
            end

            # The ID of the file to attach to the message.
            sig { returns(T.nilable(String)) }
            attr_reader :file_id

            sig { params(file_id: String).void }
            attr_writer :file_id

            # The tools to add this file to.
            sig {
              returns(
                T.nilable(
                  T::Array[
                    T.any(
                      OpenAI::Beta::CodeInterpreterTool,
                      OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::FileSearch
                    )
                  ]
                )
              )
            }
            attr_reader :tools

            sig {
              params(
                tools: T::Array[
                  T.any(
                    OpenAI::Beta::CodeInterpreterTool::OrHash,
                    OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::FileSearch::OrHash
                  )
                ]
              )
                .void
            }
            attr_writer :tools

            sig do
              params(

                file_id: String,

                tools: T::Array[
                  T.any(
                    OpenAI::Beta::CodeInterpreterTool::OrHash,
                    OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::FileSearch::OrHash
                  )
                ]
              )
                .returns(T.attached_class)
            end
            def self.new(

              # The ID of the file to attach to the message.
              file_id: nil,

              # The tools to add this file to.

              tools: nil
            )
            end

            sig do
              override.returns(
                {
                  file_id: String,
                  tools: T::Array[
                    T.any(
                      OpenAI::Beta::CodeInterpreterTool,
                      OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::FileSearch
                    )
                  ]
                }
              )
            end
            def to_hash
            end

            module Tool
              extend OpenAI::Internal::Type::Union

              Variants = T.type_alias {
                T.any(
                  OpenAI::Beta::CodeInterpreterTool,
                  OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::FileSearch
                )
              }

              class FileSearch < OpenAI::Internal::Type::BaseModel
                OrHash = T.type_alias do
                  T.any(
                    OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::FileSearch,
                    OpenAI::Internal::AnyHash
                  )
                end

                # The type of tool being defined: `file_search`
                sig { returns(Symbol) }
                attr_accessor :type

                sig do
                  params(

                    type: Symbol
                  )
                    .returns(T.attached_class)
                end
                def self.new(

                  # The type of tool being defined: `file_search`

                  type: :file_search
                )
                end

                sig do
                  override.returns(
                    {type: Symbol}
                  )
                end
                def to_hash
                end

              end

              sig { override.returns(T::Array[OpenAI::Beta::ThreadCreateParams::Message::Attachment::Tool::Variants]) }
              def self.variants
              end

            end
          end
        end

        class ToolResources < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Beta::ThreadCreateParams::ToolResources,
              OpenAI::Internal::AnyHash
            )
          end

          sig { returns(T.nilable(OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter)) }
          attr_reader :code_interpreter

          sig {
            params(code_interpreter: OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter::OrHash).void
          }
          attr_writer :code_interpreter

          sig { returns(T.nilable(OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch)) }
          attr_reader :file_search

          sig { params(file_search: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::OrHash).void }
          attr_writer :file_search

          # A set of resources that are made available to the assistant's tools in this
          # thread. The resources are specific to the type of tool. For example, the
          # `code_interpreter` tool requires a list of file IDs, while the `file_search`
          # tool requires a list of vector store IDs.
          sig do
            params(

              code_interpreter: OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter::OrHash,

              file_search: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::OrHash
            )
              .returns(T.attached_class)
          end
          def self.new(

            code_interpreter: nil,

            file_search: nil
          )
          end

          sig do
            override.returns(
              {
                code_interpreter: OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter,
                file_search: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch
              }
            )
          end
          def to_hash
          end

          class CodeInterpreter < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Beta::ThreadCreateParams::ToolResources::CodeInterpreter,
                OpenAI::Internal::AnyHash
              )
            end

            # A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made
            # available to the `code_interpreter` tool. There can be a maximum of 20 files
            # associated with the tool.
            sig { returns(T.nilable(T::Array[String])) }
            attr_reader :file_ids

            sig { params(file_ids: T::Array[String]).void }
            attr_writer :file_ids

            sig do
              params(

                file_ids: T::Array[String]
              )
                .returns(T.attached_class)
            end
            def self.new(

              # A list of [file](https://platform.openai.com/docs/api-reference/files) IDs made
              # available to the `code_interpreter` tool. There can be a maximum of 20 files
              # associated with the tool.

              file_ids: nil
            )
            end

            sig do
              override.returns(
                {file_ids: T::Array[String]}
              )
            end
            def to_hash
            end

          end

          class FileSearch < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch,
                OpenAI::Internal::AnyHash
              )
            end

            # The
            # [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object)
            # attached to this thread. There can be a maximum of 1 vector store attached to
            # the thread.
            sig { returns(T.nilable(T::Array[String])) }
            attr_reader :vector_store_ids

            sig { params(vector_store_ids: T::Array[String]).void }
            attr_writer :vector_store_ids

            # A helper to create a
            # [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object)
            # with file_ids and attach it to this thread. There can be a maximum of 1 vector
            # store attached to the thread.
            sig {
              returns(T.nilable(T::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]))
            }
            attr_reader :vector_stores

            sig {
              params(
                vector_stores: T::Array[
                  OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::OrHash
                ]
              )
                .void
            }
            attr_writer :vector_stores

            sig do
              params(

                vector_store_ids: T::Array[String],

                vector_stores: T::Array[
                  OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::OrHash
                ]
              )
                .returns(T.attached_class)
            end
            def self.new(

              # The
              # [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object)
              # attached to this thread. There can be a maximum of 1 vector store attached to
              # the thread.
              vector_store_ids: nil,

              # A helper to create a
              # [vector store](https://platform.openai.com/docs/api-reference/vector-stores/object)
              # with file_ids and attach it to this thread. There can be a maximum of 1 vector
              # store attached to the thread.

              vector_stores: nil
            )
            end

            sig do
              override.returns(
                {
                  vector_store_ids: T::Array[String],
                  vector_stores: T::Array[OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore]
                }
              )
            end
            def to_hash
            end

            class VectorStore < OpenAI::Internal::Type::BaseModel
              OrHash = T.type_alias do
                T.any(
                  OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore,
                  OpenAI::Internal::AnyHash
                )
              end

              # The chunking strategy used to chunk the file(s). If not set, will use the `auto`
              # strategy.
              sig {
                returns(
                  T.nilable(
                    T.any(
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Auto,
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static
                    )
                  )
                )
              }
              attr_reader :chunking_strategy

              sig {
                params(
                  chunking_strategy: T.any(
                    OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Auto::OrHash,
                    OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::OrHash
                  )
                )
                  .void
              }
              attr_writer :chunking_strategy

              # A list of [file](https://platform.openai.com/docs/api-reference/files) IDs to
              # add to the vector store. For vector stores created before Nov 2025, there can be
              # a maximum of 10,000 files in a vector store. For vector stores created starting
              # in Nov 2025, the limit is 100,000,000 files.
              sig { returns(T.nilable(T::Array[String])) }
              attr_reader :file_ids

              sig { params(file_ids: T::Array[String]).void }
              attr_writer :file_ids

              # Set of 16 key-value pairs that can be attached to an object. This can be useful
              # for storing additional information about the object in a structured format, and
              # querying for objects via API or the dashboard.
              #
              # Keys are strings with a maximum length of 64 characters. Values are strings with
              # a maximum length of 512 characters.
              sig { returns(T.nilable(T::Hash[Symbol, String])) }
              attr_accessor :metadata

              sig do
                params(

                  chunking_strategy: T.any(
                    OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Auto::OrHash,
                    OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::OrHash
                  ),

                  file_ids: T::Array[String],

                  metadata: T.nilable(T::Hash[Symbol, String])
                )
                  .returns(T.attached_class)
              end
              def self.new(

                # The chunking strategy used to chunk the file(s). If not set, will use the `auto`
                # strategy.
                chunking_strategy: nil,

                # A list of [file](https://platform.openai.com/docs/api-reference/files) IDs to
                # add to the vector store. For vector stores created before Nov 2025, there can be
                # a maximum of 10,000 files in a vector store. For vector stores created starting
                # in Nov 2025, the limit is 100,000,000 files.
                file_ids: nil,

                # Set of 16 key-value pairs that can be attached to an object. This can be useful
                # for storing additional information about the object in a structured format, and
                # querying for objects via API or the dashboard.
                #
                # Keys are strings with a maximum length of 64 characters. Values are strings with
                # a maximum length of 512 characters.

                metadata: nil
              )
              end

              sig do
                override.returns(
                  {
                    chunking_strategy: T.any(
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Auto,
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static
                    ),
                    file_ids: T::Array[String],
                    metadata: T.nilable(T::Hash[Symbol, String])
                  }
                )
              end
              def to_hash
              end

              # The chunking strategy used to chunk the file(s). If not set, will use the `auto`
              # strategy.
              module ChunkingStrategy
                extend OpenAI::Internal::Type::Union

                Variants = T.type_alias {
                  T.any(
                    OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Auto,
                    OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static
                  )
                }

                class Auto < OpenAI::Internal::Type::BaseModel
                  OrHash = T.type_alias do
                    T.any(
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Auto,
                      OpenAI::Internal::AnyHash
                    )
                  end

                  # Always `auto`.
                  sig { returns(Symbol) }
                  attr_accessor :type

                  # The default strategy. This strategy currently uses a `max_chunk_size_tokens` of
                  # `800` and `chunk_overlap_tokens` of `400`.
                  sig do
                    params(

                      type: Symbol
                    )
                      .returns(T.attached_class)
                  end
                  def self.new(

                    # Always `auto`.

                    type: :auto
                  )
                  end

                  sig do
                    override.returns(
                      {type: Symbol}
                    )
                  end
                  def to_hash
                  end

                end

                class Static < OpenAI::Internal::Type::BaseModel
                  OrHash = T.type_alias do
                    T.any(
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static,
                      OpenAI::Internal::AnyHash
                    )
                  end

                  sig {
                    returns(
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static
                    )
                  }
                  attr_reader :static

                  sig {
                    params(
                      static: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static::OrHash
                    )
                      .void
                  }
                  attr_writer :static

                  # Always `static`.
                  sig { returns(Symbol) }
                  attr_accessor :type

                  sig do
                    params(

                      static: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static::OrHash,

                      type: Symbol
                    )
                      .returns(T.attached_class)
                  end
                  def self.new(

                    static:,

                    # Always `static`.

                    type: :static
                  )
                  end

                  sig do
                    override.returns(
                      {
                        static: OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static,
                        type: Symbol
                      }
                    )
                  end
                  def to_hash
                  end

                  class Static < OpenAI::Internal::Type::BaseModel
                    OrHash = T.type_alias do
                      T.any(
                        OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Static::Static,
                        OpenAI::Internal::AnyHash
                      )
                    end

                    # The number of tokens that overlap between chunks. The default value is `400`.
                    #
                    # Note that the overlap must not exceed half of `max_chunk_size_tokens`.
                    sig { returns(Integer) }
                    attr_accessor :chunk_overlap_tokens

                    # The maximum number of tokens in each chunk. The default value is `800`. The
                    # minimum value is `100` and the maximum value is `4096`.
                    sig { returns(Integer) }
                    attr_accessor :max_chunk_size_tokens

                    sig do
                      params(

                        chunk_overlap_tokens: Integer,

                        max_chunk_size_tokens: Integer
                      )
                        .returns(T.attached_class)
                    end
                    def self.new(

                      # The number of tokens that overlap between chunks. The default value is `400`.
                      #
                      # Note that the overlap must not exceed half of `max_chunk_size_tokens`.
                      chunk_overlap_tokens:,

                      # The maximum number of tokens in each chunk. The default value is `800`. The
                      # minimum value is `100` and the maximum value is `4096`.

                      max_chunk_size_tokens:
                    )
                    end

                    sig do
                      override.returns(
                        {chunk_overlap_tokens: Integer, max_chunk_size_tokens: Integer}
                      )
                    end
                    def to_hash
                    end

                  end
                end

                sig {
                  override.returns(
                    T::Array[
                      OpenAI::Beta::ThreadCreateParams::ToolResources::FileSearch::VectorStore::ChunkingStrategy::Variants
                    ]
                  )
                }
                def self.variants
                end

              end
            end
          end
        end

      end

    end

  end
end
