# typed: strong

module OpenAI
  module Models

    module Beta

      class TokenUsage < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Beta::TokenUsage,
            OpenAI::Internal::AnyHash
          )
        end

        # The number of input tokens used by the agent.
        sig { returns(Integer) }
        attr_accessor :input_tokens

        # A breakdown of the agent's input token usage.
        sig { returns(OpenAI::Beta::TokenUsage::InputTokensDetails) }
        attr_reader :input_tokens_details

        sig { params(input_tokens_details: OpenAI::Beta::TokenUsage::InputTokensDetails::OrHash).void }
        attr_writer :input_tokens_details

        # The number of output tokens generated by the agent.
        sig { returns(Integer) }
        attr_accessor :output_tokens

        # A breakdown of the agent's output token usage.
        sig { returns(OpenAI::Beta::TokenUsage::OutputTokensDetails) }
        attr_reader :output_tokens_details

        sig { params(output_tokens_details: OpenAI::Beta::TokenUsage::OutputTokensDetails::OrHash).void }
        attr_writer :output_tokens_details

        # The total number of input and output tokens used by the agent.
        sig { returns(Integer) }
        attr_accessor :total_tokens

        # Recorded token usage for a session or turn. Usage is best effort and may change.
        sig do
          params(

            input_tokens: Integer,

            input_tokens_details: OpenAI::Beta::TokenUsage::InputTokensDetails::OrHash,

            output_tokens: Integer,

            output_tokens_details: OpenAI::Beta::TokenUsage::OutputTokensDetails::OrHash,

            total_tokens: Integer
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The number of input tokens used by the agent.
          input_tokens:,

          # A breakdown of the agent's input token usage.
          input_tokens_details:,

          # The number of output tokens generated by the agent.
          output_tokens:,

          # A breakdown of the agent's output token usage.
          output_tokens_details:,

          # The total number of input and output tokens used by the agent.

          total_tokens:
        )
        end

        sig do
          override.returns(
            {
              input_tokens: Integer,
              input_tokens_details: OpenAI::Beta::TokenUsage::InputTokensDetails,
              output_tokens: Integer,
              output_tokens_details: OpenAI::Beta::TokenUsage::OutputTokensDetails,
              total_tokens: Integer
            }
          )
        end
        def to_hash
        end

        class InputTokensDetails < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Beta::TokenUsage::InputTokensDetails,
              OpenAI::Internal::AnyHash
            )
          end

          # The number of input tokens retrieved from the prompt cache.
          sig { returns(Integer) }
          attr_accessor :cached_tokens

          # A breakdown of the agent's input token usage.
          sig do
            params(

              cached_tokens: Integer
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The number of input tokens retrieved from the prompt cache.

            cached_tokens:
          )
          end

          sig do
            override.returns(
              {cached_tokens: Integer}
            )
          end
          def to_hash
          end

        end

        class OutputTokensDetails < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Beta::TokenUsage::OutputTokensDetails,
              OpenAI::Internal::AnyHash
            )
          end

          # The number of output tokens used for reasoning.
          sig { returns(Integer) }
          attr_accessor :reasoning_tokens

          # A breakdown of the agent's output token usage.
          sig do
            params(

              reasoning_tokens: Integer
            )
              .returns(T.attached_class)
          end
          def self.new(

            # The number of output tokens used for reasoning.

            reasoning_tokens:
          )
          end

          sig do
            override.returns(
              {reasoning_tokens: Integer}
            )
          end
          def to_hash
          end

        end

      end

    end

  end
end
