module OpenAI
  module Helpers
    module Streaming
      type response_stream_event =
        OpenAI::Helpers::Streaming::ResponseTextDeltaEvent
        | OpenAI::Helpers::Streaming::ResponseTextDoneEvent
        | OpenAI::Helpers::Streaming::ResponseFunctionCallArgumentsDeltaEvent
        | OpenAI::Helpers::Streaming::ResponseCompletedEvent
        | OpenAI::Models::Responses::response_stream_event
        | OpenAI::Helpers::Streaming::UnknownStreamEvent

      class ResponseTextDeltaEvent < OpenAI::Models::Responses::ResponseTextDeltaEvent
        def snapshot: -> String?
      end

      class ResponseTextDoneEvent < OpenAI::Models::Responses::ResponseTextDoneEvent
        def parsed: -> untyped
      end

      class ResponseFunctionCallArgumentsDeltaEvent < OpenAI::Models::Responses::ResponseFunctionCallArgumentsDeltaEvent
        def snapshot: -> String?
      end

      class ResponseCompletedEvent < OpenAI::Models::Responses::ResponseCompletedEvent
        def response: -> OpenAI::Responses::Response
      end

      class ResponseStream
        include OpenAI::Internal::Type::BaseStream[OpenAI::Models::Responses::response_stream_event
        | OpenAI::Helpers::Streaming::UnknownStreamEvent, OpenAI::Helpers::Streaming::response_stream_event]

        # @api private
        def initialize: (
          raw_stream: OpenAI::Internal::Stream[OpenAI::Models::Responses::response_stream_event
          | OpenAI::Helpers::Streaming::UnknownStreamEvent],
          ?text_format: untyped,
          ?starting_after: Integer?
        ) -> void

        def until_done: -> self
        def text: -> Enumerator[String]
        def get_final_response: -> OpenAI::Responses::Response
        def get_output_text: -> String
      end
    end
  end
end
