# typed: strong

module OpenAI
  module Models

    module Responses

      class ResponseCustomToolCall < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Responses::ResponseCustomToolCall,
            OpenAI::Internal::AnyHash
          )
        end

        # An identifier used to map this custom tool call to a tool call output.
        sig { returns(String) }
        attr_accessor :call_id

        # The input for the custom tool call generated by the model.
        sig { returns(String) }
        attr_accessor :input

        # The name of the custom tool being called.
        sig { returns(String) }
        attr_accessor :name

        # The type of the custom tool call. Always `custom_tool_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The unique ID of the custom tool call in the OpenAI platform.
        sig { returns(T.nilable(String)) }
        attr_reader :id

        sig { params(id: String).void }
        attr_writer :id

        # Whether the custom tool call runs asynchronously.
        sig { returns(T.nilable(T::Boolean)) }
        attr_reader :async

        sig { params(async: T::Boolean).void }
        attr_writer :async

        # The execution context that produced this tool call.
        sig {
          returns(
            T.nilable(
              T.any(
                OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                OpenAI::Responses::ResponseCustomToolCall::Caller::Program
              )
            )
          )
        }
        attr_accessor :caller_

        # The namespace of the custom tool being called.
        sig { returns(T.nilable(String)) }
        attr_reader :namespace

        sig { params(namespace: String).void }
        attr_writer :namespace

        # A call to a custom tool created by the model.
        sig do
          params(

            call_id: String,

            input: String,

            name: String,

            id: String,

            async: T::Boolean,

            caller_: T.nilable(
              T.any(
                OpenAI::Responses::ResponseCustomToolCall::Caller::Direct::OrHash,
                OpenAI::Responses::ResponseCustomToolCall::Caller::Program::OrHash
              )
            ),

            namespace: String,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # An identifier used to map this custom tool call to a tool call output.
          call_id:,

          # The input for the custom tool call generated by the model.
          input:,

          # The name of the custom tool being called.
          name:,

          # The unique ID of the custom tool call in the OpenAI platform.
          id: nil,

          # Whether the custom tool call runs asynchronously.
          async: nil,

          # The execution context that produced this tool call.
          caller_: nil,

          # The namespace of the custom tool being called.
          namespace: nil,

          # The type of the custom tool call. Always `custom_tool_call`.

          type: :custom_tool_call
        )
        end

        sig do
          override.returns(
            {
              call_id: String,
              input: String,
              name: String,
              type: Symbol,
              id: String,
              async: T::Boolean,
              caller_: T.nilable(
                T.any(
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Program
                )
              ),
              namespace: String
            }
          )
        end
        def to_hash
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants = T.type_alias {
            T.any(
              OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
              OpenAI::Responses::ResponseCustomToolCall::Caller::Program
            )
          }

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                OpenAI::Internal::AnyHash
              )
            end

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              type: :direct
            )
            end

            sig do
              override.returns(
                {type: Symbol}
              )
            end
            def to_hash
            end

          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Responses::ResponseCustomToolCall::Caller::Program,
                OpenAI::Internal::AnyHash
              )
            end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                caller_id: String,

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              # The call ID of the program item that produced this tool call.
              caller_id:,

              type: :program
            )
            end

            sig do
              override.returns(
                {caller_id: String, type: Symbol}
              )
            end
            def to_hash
            end

          end

          sig { override.returns(T::Array[OpenAI::Responses::ResponseCustomToolCall::Caller::Variants]) }
          def self.variants
          end

        end

      end

    end

  end
end
