# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseApplyPatchToolCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseApplyPatchToolCall,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the apply patch tool call. Populated when this item is returned
        # via API.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the apply patch tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The status of the apply patch tool call. One of `in_progress` or `completed`.
        sig do
          returns(
            OpenAI::Responses::ResponseApplyPatchToolCall::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the item. Always `apply_patch_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The ID of the entity that created this tool call.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # One of the create_file, delete_file, or update_file operations applied via
        # apply_patch.
        sig do
          returns(
            T.nilable(
              OpenAI::Responses::ResponseApplyPatchToolCall::Operation::Variants
            )
          )
        end
        attr_reader :operation

        sig do
          params(
            operation:
              T.any(
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::CreateFile::OrHash,
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile::OrHash,
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile::OrHash
              )
          ).void
        end
        attr_writer :operation

        # A tool call that applies file diffs by creating, deleting, or updating files.
        sig do
          params(
            id: String,
            call_id: String,
            status:
              OpenAI::Responses::ResponseApplyPatchToolCall::Status::OrSymbol,
            created_by: String,
            operation:
              T.any(
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::CreateFile::OrHash,
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile::OrHash,
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile::OrHash
              ),
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the apply patch tool call. Populated when this item is returned
          # via API.
          id:,
          # The unique ID of the apply patch tool call generated by the model.
          call_id:,
          # The status of the apply patch tool call. One of `in_progress` or `completed`.
          status:,
          # The ID of the entity that created this tool call.
          created_by: nil,
          # One of the create_file, delete_file, or update_file operations applied via
          # apply_patch.
          operation: nil,
          # The type of the item. Always `apply_patch_call`.
          type: :apply_patch_call
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: String,
              status:
                OpenAI::Responses::ResponseApplyPatchToolCall::Status::TaggedSymbol,
              type: Symbol,
              created_by: String,
              operation:
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::Variants
            }
          )
        end
        def to_hash
        end

        # The status of the apply patch tool call. One of `in_progress` or `completed`.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseApplyPatchToolCall::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Responses::ResponseApplyPatchToolCall::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseApplyPatchToolCall::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseApplyPatchToolCall::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        # One of the create_file, delete_file, or update_file operations applied via
        # apply_patch.
        module Operation
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::CreateFile,
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile,
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile
              )
            end

          class CreateFile < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseApplyPatchToolCall::Operation::CreateFile,
                  OpenAI::Internal::AnyHash
                )
              end

            # Diff to apply.
            sig { returns(String) }
            attr_accessor :diff

            # Path of the file to create.
            sig { returns(String) }
            attr_accessor :path

            # Create a new file with the provided diff.
            sig { returns(Symbol) }
            attr_accessor :type

            # Instruction describing how to create a file via the apply_patch tool.
            sig do
              params(diff: String, path: String, type: Symbol).returns(
                T.attached_class
              )
            end
            def self.new(
              # Diff to apply.
              diff:,
              # Path of the file to create.
              path:,
              # Create a new file with the provided diff.
              type: :create_file
            )
            end

            sig do
              override.returns({ diff: String, path: String, type: Symbol })
            end
            def to_hash
            end
          end

          class DeleteFile < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseApplyPatchToolCall::Operation::DeleteFile,
                  OpenAI::Internal::AnyHash
                )
              end

            # Path of the file to delete.
            sig { returns(String) }
            attr_accessor :path

            # Delete the specified file.
            sig { returns(Symbol) }
            attr_accessor :type

            # Instruction describing how to delete a file via the apply_patch tool.
            sig { params(path: String, type: Symbol).returns(T.attached_class) }
            def self.new(
              # Path of the file to delete.
              path:,
              # Delete the specified file.
              type: :delete_file
            )
            end

            sig { override.returns({ path: String, type: Symbol }) }
            def to_hash
            end
          end

          class UpdateFile < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseApplyPatchToolCall::Operation::UpdateFile,
                  OpenAI::Internal::AnyHash
                )
              end

            # Diff to apply.
            sig { returns(String) }
            attr_accessor :diff

            # Path of the file to update.
            sig { returns(String) }
            attr_accessor :path

            # Update an existing file with the provided diff.
            sig { returns(Symbol) }
            attr_accessor :type

            # Instruction describing how to update a file via the apply_patch tool.
            sig do
              params(diff: String, path: String, type: Symbol).returns(
                T.attached_class
              )
            end
            def self.new(
              # Diff to apply.
              diff:,
              # Path of the file to update.
              path:,
              # Update an existing file with the provided diff.
              type: :update_file
            )
            end

            sig do
              override.returns({ diff: String, path: String, type: Symbol })
            end
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseApplyPatchToolCall::Operation::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
