# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseFunctionShellToolCallOutput < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseFunctionShellToolCallOutput,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the shell call output. Populated when this item is returned via
        # API.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the shell tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The maximum length of the shell command output. This is generated by the model
        # and should be passed back with the raw output.
        sig { returns(T.nilable(Integer)) }
        attr_accessor :max_output_length

        # An array of shell call output contents
        sig do
          returns(
            T::Array[
              OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output
            ]
          )
        end
        attr_accessor :output

        # The type of the shell call output. Always `shell_call_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # The output of a shell tool call.
        sig do
          params(
            id: String,
            call_id: String,
            max_output_length: T.nilable(Integer),
            output:
              T::Array[
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::OrHash
              ],
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the shell call output. Populated when this item is returned via
          # API.
          id:,
          # The unique ID of the shell tool call generated by the model.
          call_id:,
          # The maximum length of the shell command output. This is generated by the model
          # and should be passed back with the raw output.
          max_output_length:,
          # An array of shell call output contents
          output:,
          created_by: nil,
          # The type of the shell call output. Always `shell_call_output`.
          type: :shell_call_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: String,
              max_output_length: T.nilable(Integer),
              output:
                T::Array[
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output
                ],
              type: Symbol,
              created_by: String
            }
          )
        end
        def to_hash
        end

        class Output < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output,
                OpenAI::Internal::AnyHash
              )
            end

          # Represents either an exit outcome (with an exit code) or a timeout outcome for a
          # shell call output chunk.
          sig do
            returns(
              OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Variants
            )
          end
          attr_accessor :outcome

          sig { returns(String) }
          attr_accessor :stderr

          sig { returns(String) }
          attr_accessor :stdout

          sig { returns(T.nilable(String)) }
          attr_reader :created_by

          sig { params(created_by: String).void }
          attr_writer :created_by

          # The content of a shell call output.
          sig do
            params(
              outcome:
                T.any(
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout::OrHash,
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit::OrHash
                ),
              stderr: String,
              stdout: String,
              created_by: String
            ).returns(T.attached_class)
          end
          def self.new(
            # Represents either an exit outcome (with an exit code) or a timeout outcome for a
            # shell call output chunk.
            outcome:,
            stderr:,
            stdout:,
            created_by: nil
          )
          end

          sig do
            override.returns(
              {
                outcome:
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Variants,
                stderr: String,
                stdout: String,
                created_by: String
              }
            )
          end
          def to_hash
          end

          # Represents either an exit outcome (with an exit code) or a timeout outcome for a
          # shell call output chunk.
          module Outcome
            extend OpenAI::Internal::Type::Union

            Variants =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout,
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit
                )
              end

            class Timeout < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout,
                    OpenAI::Internal::AnyHash
                  )
                end

              # The outcome type. Always `timeout`.
              sig { returns(Symbol) }
              attr_accessor :type

              # Indicates that the function shell call exceeded its configured time limit.
              sig { params(type: Symbol).returns(T.attached_class) }
              def self.new(
                # The outcome type. Always `timeout`.
                type: :timeout
              )
              end

              sig { override.returns({ type: Symbol }) }
              def to_hash
              end
            end

            class Exit < OpenAI::Internal::Type::BaseModel
              OrHash =
                T.type_alias do
                  T.any(
                    OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit,
                    OpenAI::Internal::AnyHash
                  )
                end

              # Exit code from the shell process.
              sig { returns(Integer) }
              attr_accessor :exit_code

              # The outcome type. Always `exit`.
              sig { returns(Symbol) }
              attr_accessor :type

              # Indicates that the shell commands finished and returned an exit code.
              sig do
                params(exit_code: Integer, type: Symbol).returns(
                  T.attached_class
                )
              end
              def self.new(
                # Exit code from the shell process.
                exit_code:,
                # The outcome type. Always `exit`.
                type: :exit
              )
              end

              sig { override.returns({ exit_code: Integer, type: Symbol }) }
              def to_hash
              end
            end

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Variants
                ]
              )
            end
            def self.variants
            end
          end
        end
      end
    end
  end
end
