# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseToolSearchCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseToolSearchCall,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the tool search call item.
        sig { returns(String) }
        attr_accessor :id

        # Arguments used for the tool search call.
        sig { returns(T.anything) }
        attr_accessor :arguments

        # The unique ID of the tool search call generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :call_id

        # Whether tool search was executed by the server or by the client.
        sig do
          returns(
            OpenAI::Responses::ResponseToolSearchCall::Execution::TaggedSymbol
          )
        end
        attr_accessor :execution

        # The status of the tool search call item that was recorded.
        sig do
          returns(
            OpenAI::Responses::ResponseToolSearchCall::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the item. Always `tool_search_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        sig do
          params(
            id: String,
            arguments: T.anything,
            call_id: T.nilable(String),
            execution:
              OpenAI::Responses::ResponseToolSearchCall::Execution::OrSymbol,
            status: OpenAI::Responses::ResponseToolSearchCall::Status::OrSymbol,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the tool search call item.
          id:,
          # Arguments used for the tool search call.
          arguments:,
          # The unique ID of the tool search call generated by the model.
          call_id:,
          # Whether tool search was executed by the server or by the client.
          execution:,
          # The status of the tool search call item that was recorded.
          status:,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the item. Always `tool_search_call`.
          type: :tool_search_call
        )
        end

        sig do
          override.returns(
            {
              id: String,
              arguments: T.anything,
              call_id: T.nilable(String),
              execution:
                OpenAI::Responses::ResponseToolSearchCall::Execution::TaggedSymbol,
              status:
                OpenAI::Responses::ResponseToolSearchCall::Status::TaggedSymbol,
              type: Symbol,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # Whether tool search was executed by the server or by the client.
        module Execution
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseToolSearchCall::Execution
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          SERVER =
            T.let(
              :server,
              OpenAI::Responses::ResponseToolSearchCall::Execution::TaggedSymbol
            )
          CLIENT =
            T.let(
              :client,
              OpenAI::Responses::ResponseToolSearchCall::Execution::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseToolSearchCall::Execution::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        # The status of the tool search call item that was recorded.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(Symbol, OpenAI::Responses::ResponseToolSearchCall::Status)
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Responses::ResponseToolSearchCall::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseToolSearchCall::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Responses::ResponseToolSearchCall::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseToolSearchCall::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
