# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseCompactionItem < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseCompactionItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the compaction item.
        sig { returns(String) }
        attr_accessor :id

        # The encrypted content that was produced by compaction.
        sig { returns(String) }
        attr_accessor :encrypted_content

        # The type of the item. Always `compaction`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A compaction item generated by the
        # [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        sig do
          params(
            id: String,
            encrypted_content: String,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the compaction item.
          id:,
          # The encrypted content that was produced by compaction.
          encrypted_content:,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the item. Always `compaction`.
          type: :compaction
        )
        end

        sig do
          override.returns(
            {
              id: String,
              encrypted_content: String,
              type: Symbol,
              created_by: String
            }
          )
        end
        def to_hash
        end
      end
    end
  end
end
