# typed: strong

module OpenAI
  module Models

    module Responses

      class ResponseFunctionToolCall < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Responses::ResponseFunctionToolCall,
            OpenAI::Internal::AnyHash
          )
        end

        # A JSON string of the arguments to pass to the function.
        sig { returns(String) }
        attr_accessor :arguments

        # The parsed contents of the arguments.
        sig { returns(T.anything) }
        attr_accessor :parsed

        # The unique ID of the function tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The name of the function to run.
        sig { returns(String) }
        attr_accessor :name

        # The type of the function tool call. Always `function_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The unique ID of the function tool call.
        sig { returns(T.nilable(String)) }
        attr_reader :id

        sig { params(id: String).void }
        attr_writer :id

        # The execution context that produced this tool call.
        sig {
          returns(
            T.nilable(
              T.any(
                OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct,
                OpenAI::Responses::ResponseFunctionToolCall::Caller::Program
              )
            )
          )
        }
        attr_accessor :caller_

        # The namespace of the function to run.
        sig { returns(T.nilable(String)) }
        attr_reader :namespace

        sig { params(namespace: String).void }
        attr_writer :namespace

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig { returns(T.nilable(OpenAI::Responses::ResponseFunctionToolCall::Status::OrSymbol)) }
        attr_reader :status

        sig { params(status: OpenAI::Responses::ResponseFunctionToolCall::Status::OrSymbol).void }
        attr_writer :status

        # A tool call to run a function. See the
        # [function calling guide](https://platform.openai.com/docs/guides/function-calling)
        # for more information.
        sig do
          params(

            arguments: String,

            call_id: String,

            name: String,

            id: String,

            caller_: T.nilable(
              T.any(
                OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct::OrHash,
                OpenAI::Responses::ResponseFunctionToolCall::Caller::Program::OrHash
              )
            ),

            namespace: String,

            status: OpenAI::Responses::ResponseFunctionToolCall::Status::OrSymbol,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # A JSON string of the arguments to pass to the function.
          arguments:,

          # The unique ID of the function tool call generated by the model.
          call_id:,

          # The name of the function to run.
          name:,

          # The unique ID of the function tool call.
          id: nil,

          # The execution context that produced this tool call.
          caller_: nil,

          # The namespace of the function to run.
          namespace: nil,

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status: nil,

          # The type of the function tool call. Always `function_call`.

          type: :function_call
        )
        end

        sig do
          override.returns(
            {
              arguments: String,
              call_id: String,
              name: String,
              type: Symbol,
              id: String,
              caller_: T.nilable(
                T.any(
                  OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct,
                  OpenAI::Responses::ResponseFunctionToolCall::Caller::Program
                )
              ),
              namespace: String,
              status: OpenAI::Responses::ResponseFunctionToolCall::Status::OrSymbol
            }
          )
        end
        def to_hash
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants = T.type_alias {
            T.any(
              OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct,
              OpenAI::Responses::ResponseFunctionToolCall::Caller::Program
            )
          }

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct,
                OpenAI::Internal::AnyHash
              )
            end

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              type: :direct
            )
            end

            sig do
              override.returns(
                {type: Symbol}
              )
            end
            def to_hash
            end

          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Responses::ResponseFunctionToolCall::Caller::Program,
                OpenAI::Internal::AnyHash
              )
            end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                caller_id: String,

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              # The call ID of the program item that produced this tool call.
              caller_id:,

              type: :program
            )
            end

            sig do
              override.returns(
                {caller_id: String, type: Symbol}
              )
            end
            def to_hash
            end

          end

          sig { override.returns(T::Array[OpenAI::Responses::ResponseFunctionToolCall::Caller::Variants]) }
          def self.variants
          end

        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Responses::ResponseFunctionToolCall::Status) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS = T.let(:in_progress, OpenAI::Responses::ResponseFunctionToolCall::Status::TaggedSymbol)
          COMPLETED = T.let(:completed, OpenAI::Responses::ResponseFunctionToolCall::Status::TaggedSymbol)
          INCOMPLETE = T.let(:incomplete, OpenAI::Responses::ResponseFunctionToolCall::Status::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Responses::ResponseFunctionToolCall::Status::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
