# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseCustomToolCallOutputItem < OpenAI::Models::Responses::ResponseCustomToolCallOutput
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseCustomToolCallOutputItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the custom tool call output item.
        sig { returns(String) }
        attr_accessor :id

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig do
          returns(
            OpenAI::Responses::ResponseCustomToolCallOutputItem::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # The output of a custom tool call from your code, being sent back to the model.
        sig do
          params(
            call_id: String,
            output:
              OpenAI::Responses::ResponseCustomToolCallOutput::Output::Variants,
            id: String,
            status:
              OpenAI::Responses::ResponseCustomToolCallOutputItem::Status::OrSymbol,
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Responses::ResponseCustomToolCallOutput::Caller::Direct::OrHash,
                  OpenAI::Responses::ResponseCustomToolCallOutput::Caller::Program::OrHash
                )
              ),
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The call ID, used to map this custom tool call output to a custom tool call.
          call_id:,
          # The output from the custom tool call generated by your code. Can be a string or
          # an list of output content.
          output:,
          # The unique ID of the custom tool call output item.
          id:,
          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,
          # The execution context that produced this tool call.
          caller_: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the custom tool call output. Always `custom_tool_call_output`.
          type: :custom_tool_call_output
        )
        end

        sig do
          override.returns(
            {
              call_id: String,
              output:
                OpenAI::Responses::ResponseCustomToolCallOutput::Output::Variants,
              id: String,
              status:
                OpenAI::Responses::ResponseCustomToolCallOutputItem::Status::TaggedSymbol,
              type: Symbol,
              caller_:
                T.nilable(
                  T.any(
                    OpenAI::Responses::ResponseCustomToolCallOutput::Caller::Direct,
                    OpenAI::Responses::ResponseCustomToolCallOutput::Caller::Program
                  )
                ),
              created_by: String
            }
          )
        end
        def to_hash
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseCustomToolCallOutputItem::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Responses::ResponseCustomToolCallOutputItem::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseCustomToolCallOutputItem::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Responses::ResponseCustomToolCallOutputItem::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseCustomToolCallOutputItem::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
