# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseCustomToolCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseCustomToolCall,
              OpenAI::Internal::AnyHash
            )
          end

        # An identifier used to map this custom tool call to a tool call output.
        sig { returns(String) }
        attr_accessor :call_id

        # The input for the custom tool call generated by the model.
        sig { returns(String) }
        attr_accessor :input

        # The name of the custom tool being called.
        sig { returns(String) }
        attr_accessor :name

        # The type of the custom tool call. Always `custom_tool_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The unique ID of the custom tool call in the OpenAI platform.
        sig { returns(T.nilable(String)) }
        attr_reader :id

        sig { params(id: String).void }
        attr_writer :id

        # The execution context that produced this tool call.
        sig do
          returns(
            T.nilable(
              T.any(
                OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                OpenAI::Responses::ResponseCustomToolCall::Caller::Program
              )
            )
          )
        end
        attr_accessor :caller_

        # The namespace of the custom tool being called.
        sig { returns(T.nilable(String)) }
        attr_reader :namespace

        sig { params(namespace: String).void }
        attr_writer :namespace

        # A call to a custom tool created by the model.
        sig do
          params(
            call_id: String,
            input: String,
            name: String,
            id: String,
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Direct::OrHash,
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Program::OrHash
                )
              ),
            namespace: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # An identifier used to map this custom tool call to a tool call output.
          call_id:,
          # The input for the custom tool call generated by the model.
          input:,
          # The name of the custom tool being called.
          name:,
          # The unique ID of the custom tool call in the OpenAI platform.
          id: nil,
          # The execution context that produced this tool call.
          caller_: nil,
          # The namespace of the custom tool being called.
          namespace: nil,
          # The type of the custom tool call. Always `custom_tool_call`.
          type: :custom_tool_call
        )
        end

        sig do
          override.returns(
            {
              call_id: String,
              input: String,
              name: String,
              type: Symbol,
              id: String,
              caller_:
                T.nilable(
                  T.any(
                    OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                    OpenAI::Responses::ResponseCustomToolCall::Caller::Program
                  )
                ),
              namespace: String
            }
          )
        end
        def to_hash
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                OpenAI::Responses::ResponseCustomToolCall::Caller::Program
              )
            end

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                  OpenAI::Internal::AnyHash
                )
              end

            sig { returns(Symbol) }
            attr_accessor :type

            sig { params(type: Symbol).returns(T.attached_class) }
            def self.new(type: :direct)
            end

            sig { override.returns({ type: Symbol }) }
            def to_hash
            end
          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Program,
                  OpenAI::Internal::AnyHash
                )
              end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(caller_id: String, type: Symbol).returns(T.attached_class)
            end
            def self.new(
              # The call ID of the program item that produced this tool call.
              caller_id:,
              type: :program
            )
            end

            sig { override.returns({ caller_id: String, type: Symbol }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseCustomToolCall::Caller::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
