# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseToolSearchOutputItemParam < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseToolSearchOutputItemParam,
              OpenAI::Internal::AnyHash
            )
          end

        # The loaded tool definitions returned by the tool search output.
        sig do
          returns(
            T::Array[
              T.any(
                OpenAI::Responses::FunctionTool,
                OpenAI::Responses::FileSearchTool,
                OpenAI::Responses::ComputerTool,
                OpenAI::Responses::ComputerUsePreviewTool,
                OpenAI::Responses::Tool::Mcp,
                OpenAI::Responses::Tool::CodeInterpreter,
                OpenAI::Responses::Tool::ImageGeneration,
                OpenAI::Responses::Tool::LocalShell,
                OpenAI::Responses::FunctionShellTool,
                OpenAI::Responses::CustomTool,
                OpenAI::Responses::NamespaceTool,
                OpenAI::Responses::ToolSearchTool,
                OpenAI::Responses::ApplyPatchTool,
                OpenAI::Responses::WebSearchTool,
                OpenAI::Responses::WebSearchPreviewTool
              )
            ]
          )
        end
        attr_accessor :tools

        # The item type. Always `tool_search_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The unique ID of this tool search output.
        sig { returns(T.nilable(String)) }
        attr_accessor :id

        # The unique ID of the tool search call generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :call_id

        # Whether tool search was executed by the server or by the client.
        sig do
          returns(
            T.nilable(
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution::OrSymbol
            )
          )
        end
        attr_reader :execution

        sig do
          params(
            execution:
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution::OrSymbol
          ).void
        end
        attr_writer :execution

        # The status of the tool search output.
        sig do
          returns(
            T.nilable(
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Status::OrSymbol
            )
          )
        end
        attr_accessor :status

        sig do
          params(
            tools:
              T::Array[
                T.any(
                  OpenAI::Responses::FunctionTool::OrHash,
                  OpenAI::Responses::FileSearchTool::OrHash,
                  OpenAI::Responses::ComputerTool::OrHash,
                  OpenAI::Responses::ComputerUsePreviewTool::OrHash,
                  OpenAI::Responses::Tool::Mcp::OrHash,
                  OpenAI::Responses::Tool::CodeInterpreter::OrHash,
                  OpenAI::Responses::Tool::ImageGeneration::OrHash,
                  OpenAI::Responses::Tool::LocalShell::OrHash,
                  OpenAI::Responses::FunctionShellTool::OrHash,
                  OpenAI::Responses::CustomTool::OrHash,
                  OpenAI::Responses::NamespaceTool::OrHash,
                  OpenAI::Responses::ToolSearchTool::OrHash,
                  OpenAI::Responses::ApplyPatchTool::OrHash,
                  OpenAI::Responses::WebSearchTool::OrHash,
                  OpenAI::Responses::WebSearchPreviewTool::OrHash
                )
              ],
            id: T.nilable(String),
            call_id: T.nilable(String),
            execution:
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution::OrSymbol,
            status:
              T.nilable(
                OpenAI::Responses::ResponseToolSearchOutputItemParam::Status::OrSymbol
              ),
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The loaded tool definitions returned by the tool search output.
          tools:,
          # The unique ID of this tool search output.
          id: nil,
          # The unique ID of the tool search call generated by the model.
          call_id: nil,
          # Whether tool search was executed by the server or by the client.
          execution: nil,
          # The status of the tool search output.
          status: nil,
          # The item type. Always `tool_search_output`.
          type: :tool_search_output
        )
        end

        sig do
          override.returns(
            {
              tools:
                T::Array[
                  T.any(
                    OpenAI::Responses::FunctionTool,
                    OpenAI::Responses::FileSearchTool,
                    OpenAI::Responses::ComputerTool,
                    OpenAI::Responses::ComputerUsePreviewTool,
                    OpenAI::Responses::Tool::Mcp,
                    OpenAI::Responses::Tool::CodeInterpreter,
                    OpenAI::Responses::Tool::ImageGeneration,
                    OpenAI::Responses::Tool::LocalShell,
                    OpenAI::Responses::FunctionShellTool,
                    OpenAI::Responses::CustomTool,
                    OpenAI::Responses::NamespaceTool,
                    OpenAI::Responses::ToolSearchTool,
                    OpenAI::Responses::ApplyPatchTool,
                    OpenAI::Responses::WebSearchTool,
                    OpenAI::Responses::WebSearchPreviewTool
                  )
                ],
              type: Symbol,
              id: T.nilable(String),
              call_id: T.nilable(String),
              execution:
                OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution::OrSymbol,
              status:
                T.nilable(
                  OpenAI::Responses::ResponseToolSearchOutputItemParam::Status::OrSymbol
                )
            }
          )
        end
        def to_hash
        end

        # Whether tool search was executed by the server or by the client.
        module Execution
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          SERVER =
            T.let(
              :server,
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution::TaggedSymbol
            )
          CLIENT =
            T.let(
              :client,
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseToolSearchOutputItemParam::Execution::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        # The status of the tool search output.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseToolSearchOutputItemParam::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Responses::ResponseToolSearchOutputItemParam::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseToolSearchOutputItemParam::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
