# typed: strong

module OpenAI
  module Models
    module Responses
      # A message input to the model with a role indicating instruction following
      # hierarchy. Instructions given with the `developer` or `system` role take
      # precedence over instructions given with the `user` role. Messages with the
      # `assistant` role are presumed to have been generated by the model in previous
      # interactions.
      module ResponseInputItem
        extend OpenAI::Internal::Type::Union

        Variants =
          T.type_alias do
            T.any(
              OpenAI::Responses::EasyInputMessage,
              OpenAI::Responses::ResponseInputItem::Message,
              OpenAI::Responses::ResponseOutputMessage,
              OpenAI::Responses::ResponseFileSearchToolCall,
              OpenAI::Responses::ResponseComputerToolCall,
              OpenAI::Responses::ResponseInputItem::ComputerCallOutput,
              OpenAI::Responses::ResponseFunctionWebSearch,
              OpenAI::Responses::ResponseFunctionToolCall,
              OpenAI::Responses::ResponseInputItem::FunctionCallOutput,
              OpenAI::Responses::ResponseReasoningItem,
              OpenAI::Responses::ResponseInputItem::ImageGenerationCall,
              OpenAI::Responses::ResponseCodeInterpreterToolCall,
              OpenAI::Responses::ResponseInputItem::LocalShellCall,
              OpenAI::Responses::ResponseInputItem::LocalShellCallOutput,
              OpenAI::Responses::ResponseInputItem::McpListTools,
              OpenAI::Responses::ResponseInputItem::McpApprovalRequest,
              OpenAI::Responses::ResponseInputItem::McpApprovalResponse,
              OpenAI::Responses::ResponseInputItem::McpCall,
              OpenAI::Responses::ResponseCustomToolCallOutput,
              OpenAI::Responses::ResponseCustomToolCall,
              OpenAI::Responses::ResponseInputItem::ItemReference
            )
          end

        class Message < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::Message,
                OpenAI::Internal::AnyHash
              )
            end

          # A list of one or many input items to the model, containing different content
          # types.
          sig do
            returns(
              T::Array[
                T.any(
                  OpenAI::Responses::ResponseInputText,
                  OpenAI::Responses::ResponseInputImage,
                  OpenAI::Responses::ResponseInputFile,
                  OpenAI::Responses::ResponseInputAudio
                )
              ]
            )
          end
          attr_accessor :content

          # The role of the message input. One of `user`, `system`, or `developer`.
          sig do
            returns(
              OpenAI::Responses::ResponseInputItem::Message::Role::OrSymbol
            )
          end
          attr_accessor :role

          # The status of item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          sig do
            returns(
              T.nilable(
                OpenAI::Responses::ResponseInputItem::Message::Status::OrSymbol
              )
            )
          end
          attr_reader :status

          sig do
            params(
              status:
                OpenAI::Responses::ResponseInputItem::Message::Status::OrSymbol
            ).void
          end
          attr_writer :status

          # The type of the message input. Always set to `message`.
          sig do
            returns(
              T.nilable(
                OpenAI::Responses::ResponseInputItem::Message::Type::OrSymbol
              )
            )
          end
          attr_reader :type

          sig do
            params(
              type:
                OpenAI::Responses::ResponseInputItem::Message::Type::OrSymbol
            ).void
          end
          attr_writer :type

          # A message input to the model with a role indicating instruction following
          # hierarchy. Instructions given with the `developer` or `system` role take
          # precedence over instructions given with the `user` role.
          sig do
            params(
              content:
                T::Array[
                  T.any(
                    OpenAI::Responses::ResponseInputText::OrHash,
                    OpenAI::Responses::ResponseInputImage::OrHash,
                    OpenAI::Responses::ResponseInputFile::OrHash,
                    OpenAI::Responses::ResponseInputAudio::OrHash
                  )
                ],
              role:
                OpenAI::Responses::ResponseInputItem::Message::Role::OrSymbol,
              status:
                OpenAI::Responses::ResponseInputItem::Message::Status::OrSymbol,
              type:
                OpenAI::Responses::ResponseInputItem::Message::Type::OrSymbol
            ).returns(T.attached_class)
          end
          def self.new(
            # A list of one or many input items to the model, containing different content
            # types.
            content:,
            # The role of the message input. One of `user`, `system`, or `developer`.
            role:,
            # The status of item. One of `in_progress`, `completed`, or `incomplete`.
            # Populated when items are returned via API.
            status: nil,
            # The type of the message input. Always set to `message`.
            type: nil
          )
          end

          sig do
            override.returns(
              {
                content:
                  T::Array[
                    T.any(
                      OpenAI::Responses::ResponseInputText,
                      OpenAI::Responses::ResponseInputImage,
                      OpenAI::Responses::ResponseInputFile,
                      OpenAI::Responses::ResponseInputAudio
                    )
                  ],
                role:
                  OpenAI::Responses::ResponseInputItem::Message::Role::OrSymbol,
                status:
                  OpenAI::Responses::ResponseInputItem::Message::Status::OrSymbol,
                type:
                  OpenAI::Responses::ResponseInputItem::Message::Type::OrSymbol
              }
            )
          end
          def to_hash
          end

          # The role of the message input. One of `user`, `system`, or `developer`.
          module Role
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::Message::Role
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            USER =
              T.let(
                :user,
                OpenAI::Responses::ResponseInputItem::Message::Role::TaggedSymbol
              )
            SYSTEM =
              T.let(
                :system,
                OpenAI::Responses::ResponseInputItem::Message::Role::TaggedSymbol
              )
            DEVELOPER =
              T.let(
                :developer,
                OpenAI::Responses::ResponseInputItem::Message::Role::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::Message::Role::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end

          # The status of item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          module Status
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::Message::Status
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            IN_PROGRESS =
              T.let(
                :in_progress,
                OpenAI::Responses::ResponseInputItem::Message::Status::TaggedSymbol
              )
            COMPLETED =
              T.let(
                :completed,
                OpenAI::Responses::ResponseInputItem::Message::Status::TaggedSymbol
              )
            INCOMPLETE =
              T.let(
                :incomplete,
                OpenAI::Responses::ResponseInputItem::Message::Status::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::Message::Status::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end

          # The type of the message input. Always set to `message`.
          module Type
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::Message::Type
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            MESSAGE =
              T.let(
                :message,
                OpenAI::Responses::ResponseInputItem::Message::Type::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::Message::Type::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        class ComputerCallOutput < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::ComputerCallOutput,
                OpenAI::Internal::AnyHash
              )
            end

          # The ID of the computer tool call that produced the output.
          sig { returns(String) }
          attr_accessor :call_id

          # A computer screenshot image used with the computer use tool.
          sig do
            returns(OpenAI::Responses::ResponseComputerToolCallOutputScreenshot)
          end
          attr_reader :output

          sig do
            params(
              output:
                OpenAI::Responses::ResponseComputerToolCallOutputScreenshot::OrHash
            ).void
          end
          attr_writer :output

          # The type of the computer tool call output. Always `computer_call_output`.
          sig { returns(Symbol) }
          attr_accessor :type

          # The ID of the computer tool call output.
          sig { returns(T.nilable(String)) }
          attr_accessor :id

          # The safety checks reported by the API that have been acknowledged by the
          # developer.
          sig do
            returns(
              T.nilable(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck
                ]
              )
            )
          end
          attr_accessor :acknowledged_safety_checks

          # The status of the message input. One of `in_progress`, `completed`, or
          # `incomplete`. Populated when input items are returned via API.
          sig do
            returns(
              T.nilable(
                OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol
              )
            )
          end
          attr_accessor :status

          # The output of a computer tool call.
          sig do
            params(
              call_id: String,
              output:
                OpenAI::Responses::ResponseComputerToolCallOutputScreenshot::OrHash,
              id: T.nilable(String),
              acknowledged_safety_checks:
                T.nilable(
                  T::Array[
                    OpenAI::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck::OrHash
                  ]
                ),
              status:
                T.nilable(
                  OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol
                ),
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The ID of the computer tool call that produced the output.
            call_id:,
            # A computer screenshot image used with the computer use tool.
            output:,
            # The ID of the computer tool call output.
            id: nil,
            # The safety checks reported by the API that have been acknowledged by the
            # developer.
            acknowledged_safety_checks: nil,
            # The status of the message input. One of `in_progress`, `completed`, or
            # `incomplete`. Populated when input items are returned via API.
            status: nil,
            # The type of the computer tool call output. Always `computer_call_output`.
            type: :computer_call_output
          )
          end

          sig do
            override.returns(
              {
                call_id: String,
                output:
                  OpenAI::Responses::ResponseComputerToolCallOutputScreenshot,
                type: Symbol,
                id: T.nilable(String),
                acknowledged_safety_checks:
                  T.nilable(
                    T::Array[
                      OpenAI::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck
                    ]
                  ),
                status:
                  T.nilable(
                    OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status::OrSymbol
                  )
              }
            )
          end
          def to_hash
          end

          class AcknowledgedSafetyCheck < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseInputItem::ComputerCallOutput::AcknowledgedSafetyCheck,
                  OpenAI::Internal::AnyHash
                )
              end

            # The ID of the pending safety check.
            sig { returns(String) }
            attr_accessor :id

            # The type of the pending safety check.
            sig { returns(T.nilable(String)) }
            attr_accessor :code

            # Details about the pending safety check.
            sig { returns(T.nilable(String)) }
            attr_accessor :message

            # A pending safety check for the computer call.
            sig do
              params(
                id: String,
                code: T.nilable(String),
                message: T.nilable(String)
              ).returns(T.attached_class)
            end
            def self.new(
              # The ID of the pending safety check.
              id:,
              # The type of the pending safety check.
              code: nil,
              # Details about the pending safety check.
              message: nil
            )
            end

            sig do
              override.returns(
                {
                  id: String,
                  code: T.nilable(String),
                  message: T.nilable(String)
                }
              )
            end
            def to_hash
            end
          end

          # The status of the message input. One of `in_progress`, `completed`, or
          # `incomplete`. Populated when input items are returned via API.
          module Status
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            IN_PROGRESS =
              T.let(
                :in_progress,
                OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status::TaggedSymbol
              )
            COMPLETED =
              T.let(
                :completed,
                OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status::TaggedSymbol
              )
            INCOMPLETE =
              T.let(
                :incomplete,
                OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::ComputerCallOutput::Status::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        class FunctionCallOutput < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::FunctionCallOutput,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the function tool call generated by the model.
          sig { returns(String) }
          attr_accessor :call_id

          # A JSON string of the output of the function tool call.
          sig { returns(String) }
          attr_accessor :output

          # The type of the function tool call output. Always `function_call_output`.
          sig { returns(Symbol) }
          attr_accessor :type

          # The unique ID of the function tool call output. Populated when this item is
          # returned via API.
          sig { returns(T.nilable(String)) }
          attr_accessor :id

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          sig do
            returns(
              T.nilable(
                OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol
              )
            )
          end
          attr_accessor :status

          # The output of a function tool call.
          sig do
            params(
              call_id: String,
              output: String,
              id: T.nilable(String),
              status:
                T.nilable(
                  OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol
                ),
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique ID of the function tool call generated by the model.
            call_id:,
            # A JSON string of the output of the function tool call.
            output:,
            # The unique ID of the function tool call output. Populated when this item is
            # returned via API.
            id: nil,
            # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
            # Populated when items are returned via API.
            status: nil,
            # The type of the function tool call output. Always `function_call_output`.
            type: :function_call_output
          )
          end

          sig do
            override.returns(
              {
                call_id: String,
                output: String,
                type: Symbol,
                id: T.nilable(String),
                status:
                  T.nilable(
                    OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status::OrSymbol
                  )
              }
            )
          end
          def to_hash
          end

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          module Status
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            IN_PROGRESS =
              T.let(
                :in_progress,
                OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status::TaggedSymbol
              )
            COMPLETED =
              T.let(
                :completed,
                OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status::TaggedSymbol
              )
            INCOMPLETE =
              T.let(
                :incomplete,
                OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::FunctionCallOutput::Status::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        class ImageGenerationCall < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::ImageGenerationCall,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the image generation call.
          sig { returns(String) }
          attr_accessor :id

          # The generated image encoded in base64.
          sig { returns(T.nilable(String)) }
          attr_accessor :result

          # The status of the image generation call.
          sig do
            returns(
              OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::OrSymbol
            )
          end
          attr_accessor :status

          # The type of the image generation call. Always `image_generation_call`.
          sig { returns(Symbol) }
          attr_accessor :type

          # An image generation request made by the model.
          sig do
            params(
              id: String,
              result: T.nilable(String),
              status:
                OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::OrSymbol,
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique ID of the image generation call.
            id:,
            # The generated image encoded in base64.
            result:,
            # The status of the image generation call.
            status:,
            # The type of the image generation call. Always `image_generation_call`.
            type: :image_generation_call
          )
          end

          sig do
            override.returns(
              {
                id: String,
                result: T.nilable(String),
                status:
                  OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::OrSymbol,
                type: Symbol
              }
            )
          end
          def to_hash
          end

          # The status of the image generation call.
          module Status
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            IN_PROGRESS =
              T.let(
                :in_progress,
                OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::TaggedSymbol
              )
            COMPLETED =
              T.let(
                :completed,
                OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::TaggedSymbol
              )
            GENERATING =
              T.let(
                :generating,
                OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::TaggedSymbol
              )
            FAILED =
              T.let(
                :failed,
                OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::ImageGenerationCall::Status::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        class LocalShellCall < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::LocalShellCall,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the local shell call.
          sig { returns(String) }
          attr_accessor :id

          # Execute a shell command on the server.
          sig do
            returns(
              OpenAI::Responses::ResponseInputItem::LocalShellCall::Action
            )
          end
          attr_reader :action

          sig do
            params(
              action:
                OpenAI::Responses::ResponseInputItem::LocalShellCall::Action::OrHash
            ).void
          end
          attr_writer :action

          # The unique ID of the local shell tool call generated by the model.
          sig { returns(String) }
          attr_accessor :call_id

          # The status of the local shell call.
          sig do
            returns(
              OpenAI::Responses::ResponseInputItem::LocalShellCall::Status::OrSymbol
            )
          end
          attr_accessor :status

          # The type of the local shell call. Always `local_shell_call`.
          sig { returns(Symbol) }
          attr_accessor :type

          # A tool call to run a command on the local shell.
          sig do
            params(
              id: String,
              action:
                OpenAI::Responses::ResponseInputItem::LocalShellCall::Action::OrHash,
              call_id: String,
              status:
                OpenAI::Responses::ResponseInputItem::LocalShellCall::Status::OrSymbol,
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique ID of the local shell call.
            id:,
            # Execute a shell command on the server.
            action:,
            # The unique ID of the local shell tool call generated by the model.
            call_id:,
            # The status of the local shell call.
            status:,
            # The type of the local shell call. Always `local_shell_call`.
            type: :local_shell_call
          )
          end

          sig do
            override.returns(
              {
                id: String,
                action:
                  OpenAI::Responses::ResponseInputItem::LocalShellCall::Action,
                call_id: String,
                status:
                  OpenAI::Responses::ResponseInputItem::LocalShellCall::Status::OrSymbol,
                type: Symbol
              }
            )
          end
          def to_hash
          end

          class Action < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseInputItem::LocalShellCall::Action,
                  OpenAI::Internal::AnyHash
                )
              end

            # The command to run.
            sig { returns(T::Array[String]) }
            attr_accessor :command

            # Environment variables to set for the command.
            sig { returns(T::Hash[Symbol, String]) }
            attr_accessor :env

            # The type of the local shell action. Always `exec`.
            sig { returns(Symbol) }
            attr_accessor :type

            # Optional timeout in milliseconds for the command.
            sig { returns(T.nilable(Integer)) }
            attr_accessor :timeout_ms

            # Optional user to run the command as.
            sig { returns(T.nilable(String)) }
            attr_accessor :user

            # Optional working directory to run the command in.
            sig { returns(T.nilable(String)) }
            attr_accessor :working_directory

            # Execute a shell command on the server.
            sig do
              params(
                command: T::Array[String],
                env: T::Hash[Symbol, String],
                timeout_ms: T.nilable(Integer),
                user: T.nilable(String),
                working_directory: T.nilable(String),
                type: Symbol
              ).returns(T.attached_class)
            end
            def self.new(
              # The command to run.
              command:,
              # Environment variables to set for the command.
              env:,
              # Optional timeout in milliseconds for the command.
              timeout_ms: nil,
              # Optional user to run the command as.
              user: nil,
              # Optional working directory to run the command in.
              working_directory: nil,
              # The type of the local shell action. Always `exec`.
              type: :exec
            )
            end

            sig do
              override.returns(
                {
                  command: T::Array[String],
                  env: T::Hash[Symbol, String],
                  type: Symbol,
                  timeout_ms: T.nilable(Integer),
                  user: T.nilable(String),
                  working_directory: T.nilable(String)
                }
              )
            end
            def to_hash
            end
          end

          # The status of the local shell call.
          module Status
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::LocalShellCall::Status
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            IN_PROGRESS =
              T.let(
                :in_progress,
                OpenAI::Responses::ResponseInputItem::LocalShellCall::Status::TaggedSymbol
              )
            COMPLETED =
              T.let(
                :completed,
                OpenAI::Responses::ResponseInputItem::LocalShellCall::Status::TaggedSymbol
              )
            INCOMPLETE =
              T.let(
                :incomplete,
                OpenAI::Responses::ResponseInputItem::LocalShellCall::Status::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::LocalShellCall::Status::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        class LocalShellCallOutput < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::LocalShellCallOutput,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the local shell tool call generated by the model.
          sig { returns(String) }
          attr_accessor :id

          # A JSON string of the output of the local shell tool call.
          sig { returns(String) }
          attr_accessor :output

          # The type of the local shell tool call output. Always `local_shell_call_output`.
          sig { returns(Symbol) }
          attr_accessor :type

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          sig do
            returns(
              T.nilable(
                OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status::OrSymbol
              )
            )
          end
          attr_accessor :status

          # The output of a local shell tool call.
          sig do
            params(
              id: String,
              output: String,
              status:
                T.nilable(
                  OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status::OrSymbol
                ),
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique ID of the local shell tool call generated by the model.
            id:,
            # A JSON string of the output of the local shell tool call.
            output:,
            # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
            status: nil,
            # The type of the local shell tool call output. Always `local_shell_call_output`.
            type: :local_shell_call_output
          )
          end

          sig do
            override.returns(
              {
                id: String,
                output: String,
                type: Symbol,
                status:
                  T.nilable(
                    OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status::OrSymbol
                  )
              }
            )
          end
          def to_hash
          end

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          module Status
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            IN_PROGRESS =
              T.let(
                :in_progress,
                OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status::TaggedSymbol
              )
            COMPLETED =
              T.let(
                :completed,
                OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status::TaggedSymbol
              )
            INCOMPLETE =
              T.let(
                :incomplete,
                OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::LocalShellCallOutput::Status::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        class McpListTools < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::McpListTools,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the list.
          sig { returns(String) }
          attr_accessor :id

          # The label of the MCP server.
          sig { returns(String) }
          attr_accessor :server_label

          # The tools available on the server.
          sig do
            returns(
              T::Array[OpenAI::Responses::ResponseInputItem::McpListTools::Tool]
            )
          end
          attr_accessor :tools

          # The type of the item. Always `mcp_list_tools`.
          sig { returns(Symbol) }
          attr_accessor :type

          # Error message if the server could not list tools.
          sig { returns(T.nilable(String)) }
          attr_accessor :error

          # A list of tools available on an MCP server.
          sig do
            params(
              id: String,
              server_label: String,
              tools:
                T::Array[
                  OpenAI::Responses::ResponseInputItem::McpListTools::Tool::OrHash
                ],
              error: T.nilable(String),
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique ID of the list.
            id:,
            # The label of the MCP server.
            server_label:,
            # The tools available on the server.
            tools:,
            # Error message if the server could not list tools.
            error: nil,
            # The type of the item. Always `mcp_list_tools`.
            type: :mcp_list_tools
          )
          end

          sig do
            override.returns(
              {
                id: String,
                server_label: String,
                tools:
                  T::Array[
                    OpenAI::Responses::ResponseInputItem::McpListTools::Tool
                  ],
                type: Symbol,
                error: T.nilable(String)
              }
            )
          end
          def to_hash
          end

          class Tool < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseInputItem::McpListTools::Tool,
                  OpenAI::Internal::AnyHash
                )
              end

            # The JSON schema describing the tool's input.
            sig { returns(T.anything) }
            attr_accessor :input_schema

            # The name of the tool.
            sig { returns(String) }
            attr_accessor :name

            # Additional annotations about the tool.
            sig { returns(T.nilable(T.anything)) }
            attr_accessor :annotations

            # The description of the tool.
            sig { returns(T.nilable(String)) }
            attr_accessor :description

            # A tool available on an MCP server.
            sig do
              params(
                input_schema: T.anything,
                name: String,
                annotations: T.nilable(T.anything),
                description: T.nilable(String)
              ).returns(T.attached_class)
            end
            def self.new(
              # The JSON schema describing the tool's input.
              input_schema:,
              # The name of the tool.
              name:,
              # Additional annotations about the tool.
              annotations: nil,
              # The description of the tool.
              description: nil
            )
            end

            sig do
              override.returns(
                {
                  input_schema: T.anything,
                  name: String,
                  annotations: T.nilable(T.anything),
                  description: T.nilable(String)
                }
              )
            end
            def to_hash
            end
          end
        end

        class McpApprovalRequest < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::McpApprovalRequest,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the approval request.
          sig { returns(String) }
          attr_accessor :id

          # A JSON string of arguments for the tool.
          sig { returns(String) }
          attr_accessor :arguments

          # The name of the tool to run.
          sig { returns(String) }
          attr_accessor :name

          # The label of the MCP server making the request.
          sig { returns(String) }
          attr_accessor :server_label

          # The type of the item. Always `mcp_approval_request`.
          sig { returns(Symbol) }
          attr_accessor :type

          # A request for human approval of a tool invocation.
          sig do
            params(
              id: String,
              arguments: String,
              name: String,
              server_label: String,
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique ID of the approval request.
            id:,
            # A JSON string of arguments for the tool.
            arguments:,
            # The name of the tool to run.
            name:,
            # The label of the MCP server making the request.
            server_label:,
            # The type of the item. Always `mcp_approval_request`.
            type: :mcp_approval_request
          )
          end

          sig do
            override.returns(
              {
                id: String,
                arguments: String,
                name: String,
                server_label: String,
                type: Symbol
              }
            )
          end
          def to_hash
          end
        end

        class McpApprovalResponse < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::McpApprovalResponse,
                OpenAI::Internal::AnyHash
              )
            end

          # The ID of the approval request being answered.
          sig { returns(String) }
          attr_accessor :approval_request_id

          # Whether the request was approved.
          sig { returns(T::Boolean) }
          attr_accessor :approve

          # The type of the item. Always `mcp_approval_response`.
          sig { returns(Symbol) }
          attr_accessor :type

          # The unique ID of the approval response
          sig { returns(T.nilable(String)) }
          attr_accessor :id

          # Optional reason for the decision.
          sig { returns(T.nilable(String)) }
          attr_accessor :reason

          # A response to an MCP approval request.
          sig do
            params(
              approval_request_id: String,
              approve: T::Boolean,
              id: T.nilable(String),
              reason: T.nilable(String),
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The ID of the approval request being answered.
            approval_request_id:,
            # Whether the request was approved.
            approve:,
            # The unique ID of the approval response
            id: nil,
            # Optional reason for the decision.
            reason: nil,
            # The type of the item. Always `mcp_approval_response`.
            type: :mcp_approval_response
          )
          end

          sig do
            override.returns(
              {
                approval_request_id: String,
                approve: T::Boolean,
                type: Symbol,
                id: T.nilable(String),
                reason: T.nilable(String)
              }
            )
          end
          def to_hash
          end
        end

        class McpCall < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::McpCall,
                OpenAI::Internal::AnyHash
              )
            end

          # The unique ID of the tool call.
          sig { returns(String) }
          attr_accessor :id

          # A JSON string of the arguments passed to the tool.
          sig { returns(String) }
          attr_accessor :arguments

          # The name of the tool that was run.
          sig { returns(String) }
          attr_accessor :name

          # The label of the MCP server running the tool.
          sig { returns(String) }
          attr_accessor :server_label

          # The type of the item. Always `mcp_call`.
          sig { returns(Symbol) }
          attr_accessor :type

          # The error from the tool call, if any.
          sig { returns(T.nilable(String)) }
          attr_accessor :error

          # The output from the tool call.
          sig { returns(T.nilable(String)) }
          attr_accessor :output

          # An invocation of a tool on an MCP server.
          sig do
            params(
              id: String,
              arguments: String,
              name: String,
              server_label: String,
              error: T.nilable(String),
              output: T.nilable(String),
              type: Symbol
            ).returns(T.attached_class)
          end
          def self.new(
            # The unique ID of the tool call.
            id:,
            # A JSON string of the arguments passed to the tool.
            arguments:,
            # The name of the tool that was run.
            name:,
            # The label of the MCP server running the tool.
            server_label:,
            # The error from the tool call, if any.
            error: nil,
            # The output from the tool call.
            output: nil,
            # The type of the item. Always `mcp_call`.
            type: :mcp_call
          )
          end

          sig do
            override.returns(
              {
                id: String,
                arguments: String,
                name: String,
                server_label: String,
                type: Symbol,
                error: T.nilable(String),
                output: T.nilable(String)
              }
            )
          end
          def to_hash
          end
        end

        class ItemReference < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseInputItem::ItemReference,
                OpenAI::Internal::AnyHash
              )
            end

          # The ID of the item to reference.
          sig { returns(String) }
          attr_accessor :id

          # The type of item to reference. Always `item_reference`.
          sig do
            returns(
              T.nilable(
                OpenAI::Responses::ResponseInputItem::ItemReference::Type::OrSymbol
              )
            )
          end
          attr_accessor :type

          # An internal identifier for an item to reference.
          sig do
            params(
              id: String,
              type:
                T.nilable(
                  OpenAI::Responses::ResponseInputItem::ItemReference::Type::OrSymbol
                )
            ).returns(T.attached_class)
          end
          def self.new(
            # The ID of the item to reference.
            id:,
            # The type of item to reference. Always `item_reference`.
            type: nil
          )
          end

          sig do
            override.returns(
              {
                id: String,
                type:
                  T.nilable(
                    OpenAI::Responses::ResponseInputItem::ItemReference::Type::OrSymbol
                  )
              }
            )
          end
          def to_hash
          end

          # The type of item to reference. Always `item_reference`.
          module Type
            extend OpenAI::Internal::Type::Enum

            TaggedSymbol =
              T.type_alias do
                T.all(
                  Symbol,
                  OpenAI::Responses::ResponseInputItem::ItemReference::Type
                )
              end
            OrSymbol = T.type_alias { T.any(Symbol, String) }

            ITEM_REFERENCE =
              T.let(
                :item_reference,
                OpenAI::Responses::ResponseInputItem::ItemReference::Type::TaggedSymbol
              )

            sig do
              override.returns(
                T::Array[
                  OpenAI::Responses::ResponseInputItem::ItemReference::Type::TaggedSymbol
                ]
              )
            end
            def self.values
            end
          end
        end

        sig do
          override.returns(
            T::Array[OpenAI::Responses::ResponseInputItem::Variants]
          )
        end
        def self.variants
        end
      end
    end
  end
end
