# typed: strong

module OpenAI
  module Models

    module Responses

      class ResponseCustomToolCallItem < OpenAI::Models::Responses::ResponseCustomToolCall

        OrHash = T.type_alias do
          T.any(
            OpenAI::Responses::ResponseCustomToolCallItem,
            OpenAI::Internal::AnyHash
          )
        end

        # The unique ID of the custom tool call item.
        sig { returns(String) }
        attr_accessor :id

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig { returns(OpenAI::Responses::ResponseCustomToolCallItem::Status::TaggedSymbol) }
        attr_accessor :status

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A call to a custom tool created by the model.
        sig do
          params(

            call_id: String,

            input: String,

            name: String,

            id: String,

            status: OpenAI::Responses::ResponseCustomToolCallItem::Status::OrSymbol,

            async: T::Boolean,

            caller_: T.nilable(
              T.any(
                OpenAI::Responses::ResponseCustomToolCall::Caller::Direct::OrHash,
                OpenAI::Responses::ResponseCustomToolCall::Caller::Program::OrHash
              )
            ),

            namespace: String,

            created_by: String,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # An identifier used to map this custom tool call to a tool call output.
          call_id:,

          # The input for the custom tool call generated by the model.
          input:,

          # The name of the custom tool being called.
          name:,

          # The unique ID of the custom tool call item.
          id:,

          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,

          # Whether the custom tool call runs asynchronously.
          async: nil,

          # The execution context that produced this tool call.
          caller_: nil,

          # The namespace of the custom tool being called.
          namespace: nil,

          # The identifier of the actor that created the item.
          created_by: nil,

          # The type of the custom tool call. Always `custom_tool_call`.

          type: :custom_tool_call
        )
        end

        sig do
          override.returns(
            {
              call_id: String,
              input: String,
              name: String,
              id: String,
              status: OpenAI::Responses::ResponseCustomToolCallItem::Status::TaggedSymbol,
              type: Symbol,
              async: T::Boolean,
              caller_: T.nilable(
                T.any(
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Direct,
                  OpenAI::Responses::ResponseCustomToolCall::Caller::Program
                )
              ),
              namespace: String,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Responses::ResponseCustomToolCallItem::Status) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS = T.let(:in_progress, OpenAI::Responses::ResponseCustomToolCallItem::Status::TaggedSymbol)
          COMPLETED = T.let(:completed, OpenAI::Responses::ResponseCustomToolCallItem::Status::TaggedSymbol)
          INCOMPLETE = T.let(:incomplete, OpenAI::Responses::ResponseCustomToolCallItem::Status::TaggedSymbol)

          sig { override.returns(T::Array[OpenAI::Responses::ResponseCustomToolCallItem::Status::TaggedSymbol]) }
          def self.values
          end
        end

      end

    end

  end
end
