# typed: strong

module OpenAI
  module Models

    module Responses

      class ResponseFunctionShellToolCallOutput < OpenAI::Internal::Type::BaseModel

        OrHash = T.type_alias do
          T.any(
            OpenAI::Responses::ResponseFunctionShellToolCallOutput,
            OpenAI::Internal::AnyHash
          )
        end

        # The unique ID of the shell call output. Populated when this item is returned via
        # API.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the shell tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The maximum length of the shell command output. This is generated by the model
        # and should be passed back with the raw output.
        sig { returns(T.nilable(Integer)) }
        attr_accessor :max_output_length

        # An array of shell call output contents
        sig { returns(T::Array[OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output]) }
        attr_accessor :output

        # The status of the shell call output. One of `in_progress`, `completed`, or
        # `incomplete`.
        sig { returns(OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status::TaggedSymbol) }
        attr_accessor :status

        # The type of the shell call output. Always `shell_call_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The execution context that produced this tool call.
        sig { returns(T.nilable(OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Variants)) }
        attr_accessor :caller_

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # The output of a shell tool call that was emitted.
        sig do
          params(

            id: String,

            call_id: String,

            max_output_length: T.nilable(Integer),

            output: T::Array[OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::OrHash],

            status: OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status::OrSymbol,

            caller_: T.nilable(
              T.any(
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Direct::OrHash,
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Program::OrHash
              )
            ),

            created_by: String,

            type: Symbol
          )
            .returns(T.attached_class)
        end
        def self.new(

          # The unique ID of the shell call output. Populated when this item is returned via
          # API.
          id:,

          # The unique ID of the shell tool call generated by the model.
          call_id:,

          # The maximum length of the shell command output. This is generated by the model
          # and should be passed back with the raw output.
          max_output_length:,

          # An array of shell call output contents
          output:,

          # The status of the shell call output. One of `in_progress`, `completed`, or
          # `incomplete`.
          status:,

          # The execution context that produced this tool call.
          caller_: nil,

          # The identifier of the actor that created the item.
          created_by: nil,

          # The type of the shell call output. Always `shell_call_output`.

          type: :shell_call_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: String,
              max_output_length: T.nilable(Integer),
              output: T::Array[OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output],
              status: OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status::TaggedSymbol,
              type: Symbol,
              caller_: T.nilable(OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Variants),
              created_by: String
            }
          )
        end
        def to_hash
        end

        class Output < OpenAI::Internal::Type::BaseModel
          OrHash = T.type_alias do
            T.any(
              OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output,
              OpenAI::Internal::AnyHash
            )
          end

          # Represents either an exit outcome (with an exit code) or a timeout outcome for a
          # shell call output chunk.
          sig { returns(OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Variants) }
          attr_accessor :outcome

          # The standard error output that was captured.
          sig { returns(String) }
          attr_accessor :stderr

          # The standard output that was captured.
          sig { returns(String) }
          attr_accessor :stdout

          # The identifier of the actor that created the item.
          sig { returns(T.nilable(String)) }
          attr_reader :created_by

          sig { params(created_by: String).void }
          attr_writer :created_by

          # The content of a shell tool call output that was emitted.
          sig do
            params(

              outcome: T.any(
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout::OrHash,
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit::OrHash
              ),

              stderr: String,

              stdout: String,

              created_by: String
            )
              .returns(T.attached_class)
          end
          def self.new(

            # Represents either an exit outcome (with an exit code) or a timeout outcome for a
            # shell call output chunk.
            outcome:,

            # The standard error output that was captured.
            stderr:,

            # The standard output that was captured.
            stdout:,

            # The identifier of the actor that created the item.

            created_by: nil
          )
          end

          sig do
            override.returns(
              {
                outcome: OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Variants,
                stderr: String,
                stdout: String,
                created_by: String
              }
            )
          end
          def to_hash
          end

          # Represents either an exit outcome (with an exit code) or a timeout outcome for a
          # shell call output chunk.
          module Outcome
            extend OpenAI::Internal::Type::Union

            Variants = T.type_alias {
              T.any(
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout,
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit
              )
            }

            class Timeout < OpenAI::Internal::Type::BaseModel
              OrHash = T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Timeout,
                  OpenAI::Internal::AnyHash
                )
              end

              # The outcome type. Always `timeout`.
              sig { returns(Symbol) }
              attr_accessor :type

              # Indicates that the shell call exceeded its configured time limit.
              sig do
                params(

                  type: Symbol
                )
                  .returns(T.attached_class)
              end
              def self.new(

                # The outcome type. Always `timeout`.

                type: :timeout
              )
              end

              sig do
                override.returns(
                  {type: Symbol}
                )
              end
              def to_hash
              end

            end

            class Exit < OpenAI::Internal::Type::BaseModel
              OrHash = T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Exit,
                  OpenAI::Internal::AnyHash
                )
              end

              # Exit code from the shell process.
              sig { returns(Integer) }
              attr_accessor :exit_code

              # The outcome type. Always `exit`.
              sig { returns(Symbol) }
              attr_accessor :type

              # Indicates that the shell commands finished and returned an exit code.
              sig do
                params(

                  exit_code: Integer,

                  type: Symbol
                )
                  .returns(T.attached_class)
              end
              def self.new(

                # Exit code from the shell process.
                exit_code:,

                # The outcome type. Always `exit`.

                type: :exit
              )
              end

              sig do
                override.returns(
                  {exit_code: Integer, type: Symbol}
                )
              end
              def to_hash
              end

            end

            sig {
              override.returns(
                T::Array[OpenAI::Responses::ResponseFunctionShellToolCallOutput::Output::Outcome::Variants]
              )
            }
            def self.variants
            end

          end
        end

        # The status of the shell call output. One of `in_progress`, `completed`, or
        # `incomplete`.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol = T.type_alias { T.all(Symbol, OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status) }
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS = T.let(
            :in_progress,
            OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status::TaggedSymbol
          )
          COMPLETED = T.let(:completed, OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status::TaggedSymbol)
          INCOMPLETE = T.let(:incomplete, OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status::TaggedSymbol)

          sig {
            override.returns(T::Array[OpenAI::Responses::ResponseFunctionShellToolCallOutput::Status::TaggedSymbol])
          }
          def self.values
          end
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants = T.type_alias {
            T.any(
              OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Direct,
              OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Program
            )
          }

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Direct,
                OpenAI::Internal::AnyHash
              )
            end

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              type: :direct
            )
            end

            sig do
              override.returns(
                {type: Symbol}
              )
            end
            def to_hash
            end

          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash = T.type_alias do
              T.any(
                OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Program,
                OpenAI::Internal::AnyHash
              )
            end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(

                caller_id: String,

                type: Symbol
              )
                .returns(T.attached_class)
            end
            def self.new(

              # The call ID of the program item that produced this tool call.
              caller_id:,

              type: :program
            )
            end

            sig do
              override.returns(
                {caller_id: String, type: Symbol}
              )
            end
            def to_hash
            end

          end

          sig { override.returns(T::Array[OpenAI::Responses::ResponseFunctionShellToolCallOutput::Caller::Variants]) }
          def self.variants
          end

        end

      end

    end

  end
end
