# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseFunctionToolCallItem < OpenAI::Models::Responses::ResponseFunctionToolCall
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseFunctionToolCallItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the function tool call.
        sig { returns(String) }
        attr_accessor :id

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        sig do
          returns(
            OpenAI::Responses::ResponseFunctionToolCallItem::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A tool call to run a function. See the
        # [function calling guide](https://platform.openai.com/docs/guides/function-calling)
        # for more information.
        sig do
          params(
            arguments: String,
            call_id: String,
            name: String,
            id: String,
            status:
              OpenAI::Responses::ResponseFunctionToolCallItem::Status::OrSymbol,
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct::OrHash,
                  OpenAI::Responses::ResponseFunctionToolCall::Caller::Program::OrHash
                )
              ),
            namespace: String,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # A JSON string of the arguments to pass to the function.
          arguments:,
          # The unique ID of the function tool call generated by the model.
          call_id:,
          # The name of the function to run.
          name:,
          # The unique ID of the function tool call.
          id:,
          # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
          # Populated when items are returned via API.
          status:,
          # The execution context that produced this tool call.
          caller_: nil,
          # The namespace of the function to run.
          namespace: nil,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the function tool call. Always `function_call`.
          type: :function_call
        )
        end

        sig do
          override.returns(
            {
              arguments: String,
              call_id: String,
              name: String,
              id: String,
              status:
                OpenAI::Responses::ResponseFunctionToolCallItem::Status::TaggedSymbol,
              type: Symbol,
              caller_:
                T.nilable(
                  T.any(
                    OpenAI::Responses::ResponseFunctionToolCall::Caller::Direct,
                    OpenAI::Responses::ResponseFunctionToolCall::Caller::Program
                  )
                ),
              namespace: String,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # The status of the item. One of `in_progress`, `completed`, or `incomplete`.
        # Populated when items are returned via API.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseFunctionToolCallItem::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Responses::ResponseFunctionToolCallItem::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseFunctionToolCallItem::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Responses::ResponseFunctionToolCallItem::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseFunctionToolCallItem::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
