# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseFunctionShellToolCall < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseFunctionShellToolCall,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the shell tool call. Populated when this item is returned via
        # API.
        sig { returns(String) }
        attr_accessor :id

        # The shell commands and limits that describe how to run the tool call.
        sig do
          returns(OpenAI::Responses::ResponseFunctionShellToolCall::Action)
        end
        attr_reader :action

        sig do
          params(
            action:
              OpenAI::Responses::ResponseFunctionShellToolCall::Action::OrHash
          ).void
        end
        attr_writer :action

        # The unique ID of the shell tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The status of the shell call. One of `in_progress`, `completed`, or
        # `incomplete`.
        sig do
          returns(
            OpenAI::Responses::ResponseFunctionShellToolCall::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the item. Always `shell_call`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The ID of the entity that created this tool call.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # A tool call that executes one or more shell commands in a managed environment.
        sig do
          params(
            id: String,
            action:
              OpenAI::Responses::ResponseFunctionShellToolCall::Action::OrHash,
            call_id: String,
            status:
              OpenAI::Responses::ResponseFunctionShellToolCall::Status::OrSymbol,
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the shell tool call. Populated when this item is returned via
          # API.
          id:,
          # The shell commands and limits that describe how to run the tool call.
          action:,
          # The unique ID of the shell tool call generated by the model.
          call_id:,
          # The status of the shell call. One of `in_progress`, `completed`, or
          # `incomplete`.
          status:,
          # The ID of the entity that created this tool call.
          created_by: nil,
          # The type of the item. Always `shell_call`.
          type: :shell_call
        )
        end

        sig do
          override.returns(
            {
              id: String,
              action: OpenAI::Responses::ResponseFunctionShellToolCall::Action,
              call_id: String,
              status:
                OpenAI::Responses::ResponseFunctionShellToolCall::Status::TaggedSymbol,
              type: Symbol,
              created_by: String
            }
          )
        end
        def to_hash
        end

        class Action < OpenAI::Internal::Type::BaseModel
          OrHash =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseFunctionShellToolCall::Action,
                OpenAI::Internal::AnyHash
              )
            end

          sig { returns(T::Array[String]) }
          attr_accessor :commands

          # Optional maximum number of characters to return from each command.
          sig { returns(T.nilable(Integer)) }
          attr_accessor :max_output_length

          # Optional timeout in milliseconds for the commands.
          sig { returns(T.nilable(Integer)) }
          attr_accessor :timeout_ms

          # The shell commands and limits that describe how to run the tool call.
          sig do
            params(
              commands: T::Array[String],
              max_output_length: T.nilable(Integer),
              timeout_ms: T.nilable(Integer)
            ).returns(T.attached_class)
          end
          def self.new(
            commands:,
            # Optional maximum number of characters to return from each command.
            max_output_length:,
            # Optional timeout in milliseconds for the commands.
            timeout_ms:
          )
          end

          sig do
            override.returns(
              {
                commands: T::Array[String],
                max_output_length: T.nilable(Integer),
                timeout_ms: T.nilable(Integer)
              }
            )
          end
          def to_hash
          end
        end

        # The status of the shell call. One of `in_progress`, `completed`, or
        # `incomplete`.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseFunctionShellToolCall::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Responses::ResponseFunctionShellToolCall::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseFunctionShellToolCall::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Responses::ResponseFunctionShellToolCall::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseFunctionShellToolCall::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
