# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseCompactionItemParam < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseCompactionItemParam,
              OpenAI::Internal::AnyHash
            )
          end

        sig { returns(String) }
        attr_accessor :encrypted_content

        # The type of the item. Always `compaction`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The ID of the compaction item.
        sig { returns(T.nilable(String)) }
        attr_accessor :id

        # A compaction item generated by the
        # [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        sig do
          params(
            encrypted_content: String,
            id: T.nilable(String),
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          encrypted_content:,
          # The ID of the compaction item.
          id: nil,
          # The type of the item. Always `compaction`.
          type: :compaction
        )
        end

        sig do
          override.returns(
            { encrypted_content: String, type: Symbol, id: T.nilable(String) }
          )
        end
        def to_hash
        end
      end
    end
  end
end
