# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseToolSearchOutputItem < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseToolSearchOutputItem,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the tool search output item.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the tool search call generated by the model.
        sig { returns(T.nilable(String)) }
        attr_accessor :call_id

        # Whether tool search was executed by the server or by the client.
        sig do
          returns(
            OpenAI::Responses::ResponseToolSearchOutputItem::Execution::TaggedSymbol
          )
        end
        attr_accessor :execution

        # The status of the tool search output item that was recorded.
        sig do
          returns(
            OpenAI::Responses::ResponseToolSearchOutputItem::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The loaded tool definitions returned by tool search.
        sig { returns(T::Array[OpenAI::Responses::Tool::Variants]) }
        attr_accessor :tools

        # The type of the item. Always `tool_search_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The identifier of the actor that created the item.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        sig do
          params(
            id: String,
            call_id: T.nilable(String),
            execution:
              OpenAI::Responses::ResponseToolSearchOutputItem::Execution::OrSymbol,
            status:
              OpenAI::Responses::ResponseToolSearchOutputItem::Status::OrSymbol,
            tools:
              T::Array[
                T.any(
                  OpenAI::Responses::FunctionTool::OrHash,
                  OpenAI::Responses::FileSearchTool::OrHash,
                  OpenAI::Responses::ComputerTool::OrHash,
                  OpenAI::Responses::ComputerUsePreviewTool::OrHash,
                  OpenAI::Responses::Tool::Mcp::OrHash,
                  OpenAI::Responses::Tool::CodeInterpreter::OrHash,
                  OpenAI::Responses::Tool::ImageGeneration::OrHash,
                  OpenAI::Responses::Tool::LocalShell::OrHash,
                  OpenAI::Responses::FunctionShellTool::OrHash,
                  OpenAI::Responses::CustomTool::OrHash,
                  OpenAI::Responses::NamespaceTool::OrHash,
                  OpenAI::Responses::ToolSearchTool::OrHash,
                  OpenAI::Responses::ApplyPatchTool::OrHash,
                  OpenAI::Responses::WebSearchTool::OrHash,
                  OpenAI::Responses::WebSearchPreviewTool::OrHash
                )
              ],
            created_by: String,
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the tool search output item.
          id:,
          # The unique ID of the tool search call generated by the model.
          call_id:,
          # Whether tool search was executed by the server or by the client.
          execution:,
          # The status of the tool search output item that was recorded.
          status:,
          # The loaded tool definitions returned by tool search.
          tools:,
          # The identifier of the actor that created the item.
          created_by: nil,
          # The type of the item. Always `tool_search_output`.
          type: :tool_search_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: T.nilable(String),
              execution:
                OpenAI::Responses::ResponseToolSearchOutputItem::Execution::TaggedSymbol,
              status:
                OpenAI::Responses::ResponseToolSearchOutputItem::Status::TaggedSymbol,
              tools: T::Array[OpenAI::Responses::Tool::Variants],
              type: Symbol,
              created_by: String
            }
          )
        end
        def to_hash
        end

        # Whether tool search was executed by the server or by the client.
        module Execution
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseToolSearchOutputItem::Execution
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          SERVER =
            T.let(
              :server,
              OpenAI::Responses::ResponseToolSearchOutputItem::Execution::TaggedSymbol
            )
          CLIENT =
            T.let(
              :client,
              OpenAI::Responses::ResponseToolSearchOutputItem::Execution::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseToolSearchOutputItem::Execution::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        # The status of the tool search output item that was recorded.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseToolSearchOutputItem::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          IN_PROGRESS =
            T.let(
              :in_progress,
              OpenAI::Responses::ResponseToolSearchOutputItem::Status::TaggedSymbol
            )
          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseToolSearchOutputItem::Status::TaggedSymbol
            )
          INCOMPLETE =
            T.let(
              :incomplete,
              OpenAI::Responses::ResponseToolSearchOutputItem::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseToolSearchOutputItem::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end
      end
    end
  end
end
