# typed: strong

module OpenAI
  module Models
    module Responses
      class ResponseApplyPatchToolCallOutput < OpenAI::Internal::Type::BaseModel
        OrHash =
          T.type_alias do
            T.any(
              OpenAI::Responses::ResponseApplyPatchToolCallOutput,
              OpenAI::Internal::AnyHash
            )
          end

        # The unique ID of the apply patch tool call output. Populated when this item is
        # returned via API.
        sig { returns(String) }
        attr_accessor :id

        # The unique ID of the apply patch tool call generated by the model.
        sig { returns(String) }
        attr_accessor :call_id

        # The status of the apply patch tool call output. One of `completed` or `failed`.
        sig do
          returns(
            OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status::TaggedSymbol
          )
        end
        attr_accessor :status

        # The type of the item. Always `apply_patch_call_output`.
        sig { returns(Symbol) }
        attr_accessor :type

        # The execution context that produced this tool call.
        sig do
          returns(
            T.nilable(
              OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Variants
            )
          )
        end
        attr_accessor :caller_

        # The ID of the entity that created this tool call output.
        sig { returns(T.nilable(String)) }
        attr_reader :created_by

        sig { params(created_by: String).void }
        attr_writer :created_by

        # Optional textual output returned by the apply patch tool.
        sig { returns(T.nilable(String)) }
        attr_accessor :output

        # The output emitted by an apply patch tool call.
        sig do
          params(
            id: String,
            call_id: String,
            status:
              OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status::OrSymbol,
            caller_:
              T.nilable(
                T.any(
                  OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Direct::OrHash,
                  OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Program::OrHash
                )
              ),
            created_by: String,
            output: T.nilable(String),
            type: Symbol
          ).returns(T.attached_class)
        end
        def self.new(
          # The unique ID of the apply patch tool call output. Populated when this item is
          # returned via API.
          id:,
          # The unique ID of the apply patch tool call generated by the model.
          call_id:,
          # The status of the apply patch tool call output. One of `completed` or `failed`.
          status:,
          # The execution context that produced this tool call.
          caller_: nil,
          # The ID of the entity that created this tool call output.
          created_by: nil,
          # Optional textual output returned by the apply patch tool.
          output: nil,
          # The type of the item. Always `apply_patch_call_output`.
          type: :apply_patch_call_output
        )
        end

        sig do
          override.returns(
            {
              id: String,
              call_id: String,
              status:
                OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status::TaggedSymbol,
              type: Symbol,
              caller_:
                T.nilable(
                  OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Variants
                ),
              created_by: String,
              output: T.nilable(String)
            }
          )
        end
        def to_hash
        end

        # The status of the apply patch tool call output. One of `completed` or `failed`.
        module Status
          extend OpenAI::Internal::Type::Enum

          TaggedSymbol =
            T.type_alias do
              T.all(
                Symbol,
                OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status
              )
            end
          OrSymbol = T.type_alias { T.any(Symbol, String) }

          COMPLETED =
            T.let(
              :completed,
              OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status::TaggedSymbol
            )
          FAILED =
            T.let(
              :failed,
              OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status::TaggedSymbol
            )

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseApplyPatchToolCallOutput::Status::TaggedSymbol
              ]
            )
          end
          def self.values
          end
        end

        # The execution context that produced this tool call.
        module Caller
          extend OpenAI::Internal::Type::Union

          Variants =
            T.type_alias do
              T.any(
                OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Direct,
                OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Program
              )
            end

          class Direct < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Direct,
                  OpenAI::Internal::AnyHash
                )
              end

            sig { returns(Symbol) }
            attr_accessor :type

            sig { params(type: Symbol).returns(T.attached_class) }
            def self.new(type: :direct)
            end

            sig { override.returns({ type: Symbol }) }
            def to_hash
            end
          end

          class Program < OpenAI::Internal::Type::BaseModel
            OrHash =
              T.type_alias do
                T.any(
                  OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Program,
                  OpenAI::Internal::AnyHash
                )
              end

            # The call ID of the program item that produced this tool call.
            sig { returns(String) }
            attr_accessor :caller_id

            sig { returns(Symbol) }
            attr_accessor :type

            sig do
              params(caller_id: String, type: Symbol).returns(T.attached_class)
            end
            def self.new(
              # The call ID of the program item that produced this tool call.
              caller_id:,
              type: :program
            )
            end

            sig { override.returns({ caller_id: String, type: Symbol }) }
            def to_hash
            end
          end

          sig do
            override.returns(
              T::Array[
                OpenAI::Responses::ResponseApplyPatchToolCallOutput::Caller::Variants
              ]
            )
          end
          def self.variants
          end
        end
      end
    end
  end
end
