# frozen_string_literal: true

module OpenAI
  module Resources
    class Beta
      class Agents
        # @return [OpenAI::Resources::Beta::Agents::Environments]
        attr_reader :environments

        # @return [OpenAI::Resources::Beta::Agents::Vaults]
        attr_reader :vaults

        # @return [OpenAI::Resources::Beta::Agents::Sessions]
        attr_reader :sessions

        # Creates a reusable agent without storing credentials. See
        # [agent configuration](https://developers.openai.com/api/docs/guides/agents-api/configuration).
        #
        # @overload create(model:, instructions: nil, metadata: nil, multi_agent: nil, name: nil, reasoning: nil, service_tier: nil, text: nil, tools: nil, request_options: {})
        #
        # @param model [String]
        #   The model to use for the agent. The requested model name is preserved.
        #
        # @param instructions [String, nil]
        #   Additional instructions appended to the agent's default base instructions. Omit
        #   or set to null to add no custom instructions.
        #
        # @param metadata [Hash{Symbol=>String}, nil]
        #   Up to 16 string key-value pairs, with keys up to 64 and values up to 512
        #   characters. Omission or null defaults to an empty map.
        #
        # @param multi_agent [OpenAI::Models::Beta::MultiAgentConfigParam, nil]
        #   Explicit configuration for creating and coordinating subagents.
        #
        # @param name [String, nil]
        #   A human-readable name for the agent. Omission or null leaves the agent unnamed.
        #
        # @param reasoning [OpenAI::Models::Beta::AgentReasoningParam, nil]
        #   Reasoning configuration for the agent.
        #
        # @param service_tier [Symbol, OpenAI::Models::Beta::AgentCreateParams::ServiceTier, nil]
        #   The service tier used for model requests.
        #
        # @param text [OpenAI::Models::Beta::AgentTextParam, nil]
        #   Configuration for text generated by the agent.
        #
        # @param tools [Array<OpenAI::Models::Beta::PersistedAgentToolParam::Function, OpenAI::Models::Beta::PersistedAgentToolParam::ToolSearch, OpenAI::Models::Beta::PersistedAgentToolParam::ProgrammaticToolCalling, OpenAI::Models::Beta::PersistedAgentToolParam::Mcp, OpenAI::Models::Beta::PersistedAgentToolParam::WebSearch>, nil]
        #   Tools available to the agent. Defaults to an empty list.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [OpenAI::Models::Beta::Agent]
        #
        # @see OpenAI::Models::Beta::AgentCreateParams
        def create(params)
          parsed, options = OpenAI::Beta::AgentCreateParams.dump_request(params)
          @client.request(
            method: :post,
            path: "agents",
            body: parsed,
            model: OpenAI::Beta::Agent,
            security: {bearer_auth: true},
            options: {extra_headers: {"OpenAI-Beta" => "agents=v1"}, **options}
          )
        end

        # Retrieves a reusable agent by ID. See
        # [agent configuration](https://developers.openai.com/api/docs/guides/agents-api/configuration).
        #
        # @overload retrieve(agent_id, request_options: {})
        #
        # @param agent_id [String]
        #   The ID of the reusable agent.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [OpenAI::Models::Beta::Agent]
        #
        # @see OpenAI::Models::Beta::AgentRetrieveParams
        def retrieve(agent_id, params = {})
          @client.request(
            method: :get,
            path: ["agents/%1$s", agent_id],
            model: OpenAI::Beta::Agent,
            security: {bearer_auth: true},
            options: {extra_headers: {"OpenAI-Beta" => "agents=v1"}, **params[:request_options].to_h}
          )
        end

        # Updates a reusable agent. See
        # [agent configuration](https://developers.openai.com/api/docs/guides/agents-api/configuration).
        #
        # @overload update(agent_id, instructions: nil, metadata: nil, model: nil, multi_agent: nil, name: nil, reasoning: nil, service_tier: nil, text: nil, tools: nil, request_options: {})
        #
        # @param agent_id [String]
        #   The ID of the reusable agent.
        #
        # @param instructions [String, nil]
        #   Additional instructions appended to the agent's default base instructions. Omit
        #   to leave unchanged.
        #
        # @param metadata [Hash{Symbol=>String}, nil]
        #   Replaces all metadata. Omit to leave unchanged, or pass null or {} to clear it.
        #   Up to 16 string key-value pairs, with keys up to 64 and values up to 512
        #   characters.
        #
        # @param model [String]
        #   The model to use for the agent. The requested model name is preserved.
        #
        # @param multi_agent [OpenAI::Models::Beta::MultiAgentConfigParam, nil]
        #   Explicit configuration for creating and coordinating subagents.
        #
        # @param name [String, nil]
        #   A replacement name. Omit to leave unchanged, or pass null to clear it.
        #
        # @param reasoning [OpenAI::Models::Beta::AgentReasoningParam, nil]
        #   Reasoning configuration for the agent.
        #
        # @param service_tier [Symbol, OpenAI::Models::Beta::AgentUpdateParams::ServiceTier, nil]
        #   The service tier used for model requests.
        #
        # @param text [OpenAI::Models::Beta::AgentTextParam, nil]
        #   Configuration for text generated by the agent.
        #
        # @param tools [Array<OpenAI::Models::Beta::PersistedAgentToolParam::Function, OpenAI::Models::Beta::PersistedAgentToolParam::ToolSearch, OpenAI::Models::Beta::PersistedAgentToolParam::ProgrammaticToolCalling, OpenAI::Models::Beta::PersistedAgentToolParam::Mcp, OpenAI::Models::Beta::PersistedAgentToolParam::WebSearch>, nil]
        #   Tools available to the agent.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [OpenAI::Models::Beta::Agent]
        #
        # @see OpenAI::Models::Beta::AgentUpdateParams
        def update(agent_id, params = {})
          parsed, options = OpenAI::Beta::AgentUpdateParams.dump_request(params)
          @client.request(
            method: :post,
            path: ["agents/%1$s", agent_id],
            body: parsed,
            model: OpenAI::Beta::Agent,
            security: {bearer_auth: true},
            options: {extra_headers: {"OpenAI-Beta" => "agents=v1"}, **options}
          )
        end

        # Lists reusable agents in the current project. See
        # [agent configuration](https://developers.openai.com/api/docs/guides/agents-api/configuration).
        #
        # @overload list(after: nil, limit: nil, order: nil, request_options: {})
        #
        # @param after [String]
        #   Return resources after this resource ID in the selected order.
        #
        # @param limit [Integer, nil]
        #   The maximum number of resources to return.
        #
        # @param order [Symbol, OpenAI::Models::Beta::AgentListParams::Order]
        #   The order in which resources are returned. Defaults to `desc`.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [OpenAI::Internal::CursorPage<OpenAI::Models::Beta::Agent>]
        #
        # @see OpenAI::Models::Beta::AgentListParams
        def list(params = {})
          parsed, options = OpenAI::Beta::AgentListParams.dump_request(params)
          query = OpenAI::Internal::Util.encode_query_params(parsed)
          @client.request(
            method: :get,
            path: "agents",
            query: query,
            page: OpenAI::Internal::CursorPage,
            model: OpenAI::Beta::Agent,
            security: {bearer_auth: true},
            options: {extra_headers: {"OpenAI-Beta" => "agents=v1"}, **options}
          )
        end

        # Deletes a reusable agent. See
        # [agent configuration](https://developers.openai.com/api/docs/guides/agents-api/configuration).
        #
        # @overload delete(agent_id, request_options: {})
        #
        # @param agent_id [String]
        #   The ID of the reusable agent.
        #
        # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
        #
        # @return [OpenAI::Models::Beta::AgentDeleted]
        #
        # @see OpenAI::Models::Beta::AgentDeleteParams
        def delete(agent_id, params = {})
          @client.request(
            method: :delete,
            path: ["agents/%1$s", agent_id],
            model: OpenAI::Beta::AgentDeleted,
            security: {bearer_auth: true},
            options: {extra_headers: {"OpenAI-Beta" => "agents=v1"}, **params[:request_options].to_h}
          )
        end

        # @api private
        #
        # @param client [OpenAI::Client]
        def initialize(client:)
          @client = client
          @environments = OpenAI::Resources::Beta::Agents::Environments.new(client: client)
          @vaults = OpenAI::Resources::Beta::Agents::Vaults.new(client: client)
          @sessions = OpenAI::Resources::Beta::Agents::Sessions.new(client: client)
        end
      end
    end
  end
end
