module OpenAI
  module Resources
    class FineTuning
      class Jobs
        class Checkpoints
          def list: (
            String fine_tuning_job_id,
            ?after: String,
            ?limit: Integer,
            ?request_options: OpenAI::request_opts
          ) -> OpenAI::Internal::CursorPage[OpenAI::Models::FineTuning::Jobs::FineTuningJobCheckpoint]

          def initialize: (client: OpenAI::Client) -> void
        end
      end
    end
  end
end
