# frozen_string_literal: true

module OpenAI
  module Models
    module Graders
      class ScoreModelGrader < OpenAI::Internal::Type::BaseModel
        # @!attribute input
        #   The input text. This may include template strings.
        #
        #   @return [Array<OpenAI::Graders::ScoreModelGrader::Input>]
        required :input, -> { OpenAI::Internal::Type::ArrayOf[OpenAI::Graders::ScoreModelGrader::Input] }

        # @!attribute model
        #   The model to use for the evaluation.
        #
        #   @return [String]
        required :model, String

        # @!attribute name
        #   The name of the grader.
        #
        #   @return [String]
        required :name, String

        # @!attribute type
        #   The object type, which is always `score_model`.
        #
        #   @return [Symbol, :score_model]
        required :type, const: :score_model

        # @!attribute range
        #   The range of the score. Defaults to `[0, 1]`.
        #
        #   @return [Array<Float>, nil]
        optional :range, OpenAI::Internal::Type::ArrayOf[Float]

        # @!attribute sampling_params
        #   The sampling parameters for the model.
        #
        #   @return [Object, nil]
        optional :sampling_params, OpenAI::Internal::Type::Unknown

        # @!method initialize(input:, model:, name:, range: nil, sampling_params: nil, type: :score_model)
        #   A ScoreModelGrader object that uses a model to assign a score to the input.
        #
        #   @param input [Array<OpenAI::Graders::ScoreModelGrader::Input>] The input text. This may include template strings.
        #
        #   @param model [String] The model to use for the evaluation.
        #
        #   @param name [String] The name of the grader.
        #
        #   @param range [Array<Float>] The range of the score. Defaults to `[0, 1]`.
        #
        #   @param sampling_params [Object] The sampling parameters for the model.
        #
        #   @param type [Symbol, :score_model] The object type, which is always `score_model`.

        class Input < OpenAI::Internal::Type::BaseModel
          # @!attribute content
          #   Text inputs to the model - can contain template strings.
          #
          #   @return [String, OpenAI::Responses::ResponseInputText, OpenAI::Graders::ScoreModelGrader::Input::Content::OutputText]
          required :content, union: -> { OpenAI::Graders::ScoreModelGrader::Input::Content }

          # @!attribute role
          #   The role of the message input. One of `user`, `assistant`, `system`, or
          #   `developer`.
          #
          #   @return [Symbol, OpenAI::Graders::ScoreModelGrader::Input::Role]
          required :role, enum: -> { OpenAI::Graders::ScoreModelGrader::Input::Role }

          # @!attribute type
          #   The type of the message input. Always `message`.
          #
          #   @return [Symbol, OpenAI::Graders::ScoreModelGrader::Input::Type, nil]
          optional :type, enum: -> { OpenAI::Graders::ScoreModelGrader::Input::Type }

          # @!method initialize(content:, role:, type: nil)
          #   Some parameter documentations has been truncated, see
          #   {OpenAI::Graders::ScoreModelGrader::Input} for more details.
          #
          #   A message input to the model with a role indicating instruction following
          #   hierarchy. Instructions given with the `developer` or `system` role take
          #   precedence over instructions given with the `user` role. Messages with the
          #   `assistant` role are presumed to have been generated by the model in previous
          #   interactions.
          #
          #   @param content [String, OpenAI::Responses::ResponseInputText, OpenAI::Graders::ScoreModelGrader::Input::Content::OutputText] Text inputs to the model - can contain template strings.
          #
          #   @param role [Symbol, OpenAI::Graders::ScoreModelGrader::Input::Role] The role of the message input. One of `user`, `assistant`, `system`, or
          #
          #   @param type [Symbol, OpenAI::Graders::ScoreModelGrader::Input::Type] The type of the message input. Always `message`.

          # Text inputs to the model - can contain template strings.
          #
          # @see OpenAI::Graders::ScoreModelGrader::Input#content
          module Content
            extend OpenAI::Internal::Type::Union

            # A text input to the model.
            variant String

            # A text input to the model.
            variant -> { OpenAI::Responses::ResponseInputText }

            # A text output from the model.
            variant -> { OpenAI::Graders::ScoreModelGrader::Input::Content::OutputText }

            class OutputText < OpenAI::Internal::Type::BaseModel
              # @!attribute text
              #   The text output from the model.
              #
              #   @return [String]
              required :text, String

              # @!attribute type
              #   The type of the output text. Always `output_text`.
              #
              #   @return [Symbol, :output_text]
              required :type, const: :output_text

              # @!method initialize(text:, type: :output_text)
              #   Some parameter documentations has been truncated, see
              #   {OpenAI::Graders::ScoreModelGrader::Input::Content::OutputText} for more
              #   details.
              #
              #   A text output from the model.
              #
              #   @param text [String] The text output from the model.
              #
              #   @param type [Symbol, :output_text] The type of the output text. Always `output_text`.
            end

            # @!method self.variants
            #   @return [Array(String, OpenAI::Responses::ResponseInputText, OpenAI::Graders::ScoreModelGrader::Input::Content::OutputText)]

            define_sorbet_constant!(:Variants) do
              T.type_alias do
                T.any(
                  String,
                  OpenAI::Responses::ResponseInputText,
                  OpenAI::Graders::ScoreModelGrader::Input::Content::OutputText
                )
              end
            end
          end

          # The role of the message input. One of `user`, `assistant`, `system`, or
          # `developer`.
          #
          # @see OpenAI::Graders::ScoreModelGrader::Input#role
          module Role
            extend OpenAI::Internal::Type::Enum

            USER = :user
            ASSISTANT = :assistant
            SYSTEM = :system
            DEVELOPER = :developer

            # @!method self.values
            #   @return [Array<Symbol>]
          end

          # The type of the message input. Always `message`.
          #
          # @see OpenAI::Graders::ScoreModelGrader::Input#type
          module Type
            extend OpenAI::Internal::Type::Enum

            MESSAGE = :message

            # @!method self.values
            #   @return [Array<Symbol>]
          end
        end
      end
    end

    ScoreModelGrader = Graders::ScoreModelGrader
  end
end
