# frozen_string_literal: true

module OpenAI
  module Resources
    # Given a prompt, the model will return one or more predicted completions, and can
    # also return the probabilities of alternative tokens at each position.
    class Completions
      # See {OpenAI::Resources::Completions#create_streaming} for streaming counterpart.
      #
      # Creates a completion for the provided prompt and parameters.
      #
      # Returns a completion object, or a sequence of completion objects if the request
      # is streamed.
      #
      # @overload create(model:, prompt:, best_of: nil, echo: nil, frequency_penalty: nil, logit_bias: nil, logprobs: nil, max_tokens: nil, n: nil, presence_penalty: nil, seed: nil, stop: nil, stream_options: nil, suffix: nil, temperature: nil, top_p: nil, user: nil, request_options: {})
      #
      # @param model [String, Symbol, OpenAI::Models::CompletionCreateParams::Model]
      #   ID of the model to use. You can use the
      #   [List models](https://developers.openai.com/api/reference/resources/models/methods/list)
      #   API to see all of your available models, or see our
      #   [Model overview](https://developers.openai.com/api/docs/models) for descriptions
      #   of them.
      #
      # @param prompt [String, Array<String>, Array<Integer>, Array<Array<Integer>>, nil]
      #   The prompt(s) to generate completions for, encoded as a string, array of
      #   strings, array of tokens, or array of token arrays.
      #
      #   Note that <|endoftext|> is the document separator that the model sees during
      #   training, so if a prompt is not specified the model will generate as if from the
      #   beginning of a new document.
      #
      # @param best_of [Integer, nil]
      #   Generates `best_of` completions server-side and returns the "best" (the one with
      #   the highest log probability per token). Results cannot be streamed.
      #
      #   When used with `n`, `best_of` controls the number of candidate completions and
      #   `n` specifies how many to return – `best_of` must be greater than `n`.
      #
      #   **Note:** Because this parameter generates many completions, it can quickly
      #   consume your token quota. Use carefully and ensure that you have reasonable
      #   settings for `max_tokens` and `stop`.
      #
      # @param echo [Boolean, nil]
      #   Echo back the prompt in addition to the completion
      #
      # @param frequency_penalty [Float, nil]
      #   Number between -2.0 and 2.0. Positive values penalize new tokens based on their
      #   existing frequency in the text so far, decreasing the model's likelihood to
      #   repeat the same line verbatim.
      #
      #   [See more information about frequency and presence penalties.](https://developers.openai.com/api/docs/guides/text)
      #
      # @param logit_bias [Hash{Symbol=>Integer}, nil]
      #   Modify the likelihood of specified tokens appearing in the completion.
      #
      #   Accepts a JSON object that maps tokens (specified by their token ID in the GPT
      #   tokenizer) to an associated bias value from -100 to 100. You can use this
      #   [tokenizer tool](https://platform.openai.com/tokenizer?view=bpe) to convert text
      #   to token IDs. Mathematically, the bias is added to the logits generated by the
      #   model prior to sampling. The exact effect will vary per model, but values
      #   between -1 and 1 should decrease or increase likelihood of selection; values
      #   like -100 or 100 should result in a ban or exclusive selection of the relevant
      #   token.
      #
      #   As an example, you can pass `{"50256": -100}` to prevent the <|endoftext|> token
      #   from being generated.
      #
      # @param logprobs [Integer, nil]
      #   Include the log probabilities on the `logprobs` most likely output tokens, as
      #   well the chosen tokens. For example, if `logprobs` is 5, the API will return a
      #   list of the 5 most likely tokens. The API will always return the `logprob` of
      #   the sampled token, so there may be up to `logprobs+1` elements in the response.
      #
      #   The maximum value for `logprobs` is 5.
      #
      # @param max_tokens [Integer, nil]
      #   The maximum number of [tokens](https://platform.openai.com/tokenizer) that can
      #   be generated in the completion.
      #
      #   The token count of your prompt plus `max_tokens` cannot exceed the model's
      #   context length.
      #   [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken)
      #   for counting tokens.
      #
      # @param n [Integer, nil]
      #   How many completions to generate for each prompt.
      #
      #   **Note:** Because this parameter generates many completions, it can quickly
      #   consume your token quota. Use carefully and ensure that you have reasonable
      #   settings for `max_tokens` and `stop`.
      #
      # @param presence_penalty [Float, nil]
      #   Number between -2.0 and 2.0. Positive values penalize new tokens based on
      #   whether they appear in the text so far, increasing the model's likelihood to
      #   talk about new topics.
      #
      #   [See more information about frequency and presence penalties.](https://developers.openai.com/api/docs/guides/text)
      #
      # @param seed [Integer, nil]
      #   If specified, our system will make a best effort to sample deterministically,
      #   such that repeated requests with the same `seed` and parameters should return
      #   the same result.
      #
      #   Determinism is not guaranteed, and you should refer to the `system_fingerprint`
      #   response parameter to monitor changes in the backend.
      #
      # @param stop [String, Array<String>, nil]
      #   Not supported with latest reasoning models `o3` and `o4-mini`.
      #
      #   Up to 4 sequences where the API will stop generating further tokens. The
      #   returned text will not contain the stop sequence.
      #
      # @param stream_options [OpenAI::Models::Chat::ChatCompletionStreamOptions, nil]
      #   Options for streaming response. Only set this when you set `stream: true`.
      #
      # @param suffix [String, nil]
      #   The suffix that comes after a completion of inserted text.
      #
      #   This parameter is only supported for `gpt-3.5-turbo-instruct`.
      #
      # @param temperature [Float, nil]
      #   What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
      #   make the output more random, while lower values like 0.2 will make it more
      #   focused and deterministic.
      #
      #   We generally recommend altering this or `top_p` but not both.
      #
      # @param top_p [Float, nil]
      #   An alternative to sampling with temperature, called nucleus sampling, where the
      #   model considers the results of the tokens with top_p probability mass. So 0.1
      #   means only the tokens comprising the top 10% probability mass are considered.
      #
      #   We generally recommend altering this or `temperature` but not both.
      #
      # @param user [String]
      #   A unique identifier representing your end-user, which can help OpenAI to monitor
      #   and detect abuse.
      #   [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers).
      #
      # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [OpenAI::Models::Completion]
      #
      # @see OpenAI::Models::CompletionCreateParams
      def create(params)
        parsed, options = OpenAI::CompletionCreateParams.dump_request(params)
        if parsed[:stream]
          message = "Please use `#create_streaming` for the streaming use case."
          raise ArgumentError.new(message)
        end

        @client.request(
          method: :post,
          path: "completions",
          body: parsed,
          model: OpenAI::Completion,
          security: {bearer_auth: true},
          options: options
        )
      end

      # See {OpenAI::Resources::Completions#create} for non-streaming counterpart.
      #
      # Creates a completion for the provided prompt and parameters.
      #
      # Returns a completion object, or a sequence of completion objects if the request
      # is streamed.
      #
      # @overload create_streaming(model:, prompt:, best_of: nil, echo: nil, frequency_penalty: nil, logit_bias: nil, logprobs: nil, max_tokens: nil, n: nil, presence_penalty: nil, seed: nil, stop: nil, stream_options: nil, suffix: nil, temperature: nil, top_p: nil, user: nil, request_options: {})
      #
      # @param model [String, Symbol, OpenAI::Models::CompletionCreateParams::Model]
      #   ID of the model to use. You can use the
      #   [List models](https://developers.openai.com/api/reference/resources/models/methods/list)
      #   API to see all of your available models, or see our
      #   [Model overview](https://developers.openai.com/api/docs/models) for descriptions
      #   of them.
      #
      # @param prompt [String, Array<String>, Array<Integer>, Array<Array<Integer>>, nil]
      #   The prompt(s) to generate completions for, encoded as a string, array of
      #   strings, array of tokens, or array of token arrays.
      #
      #   Note that <|endoftext|> is the document separator that the model sees during
      #   training, so if a prompt is not specified the model will generate as if from the
      #   beginning of a new document.
      #
      # @param best_of [Integer, nil]
      #   Generates `best_of` completions server-side and returns the "best" (the one with
      #   the highest log probability per token). Results cannot be streamed.
      #
      #   When used with `n`, `best_of` controls the number of candidate completions and
      #   `n` specifies how many to return – `best_of` must be greater than `n`.
      #
      #   **Note:** Because this parameter generates many completions, it can quickly
      #   consume your token quota. Use carefully and ensure that you have reasonable
      #   settings for `max_tokens` and `stop`.
      #
      # @param echo [Boolean, nil]
      #   Echo back the prompt in addition to the completion
      #
      # @param frequency_penalty [Float, nil]
      #   Number between -2.0 and 2.0. Positive values penalize new tokens based on their
      #   existing frequency in the text so far, decreasing the model's likelihood to
      #   repeat the same line verbatim.
      #
      #   [See more information about frequency and presence penalties.](https://developers.openai.com/api/docs/guides/text)
      #
      # @param logit_bias [Hash{Symbol=>Integer}, nil]
      #   Modify the likelihood of specified tokens appearing in the completion.
      #
      #   Accepts a JSON object that maps tokens (specified by their token ID in the GPT
      #   tokenizer) to an associated bias value from -100 to 100. You can use this
      #   [tokenizer tool](https://platform.openai.com/tokenizer?view=bpe) to convert text
      #   to token IDs. Mathematically, the bias is added to the logits generated by the
      #   model prior to sampling. The exact effect will vary per model, but values
      #   between -1 and 1 should decrease or increase likelihood of selection; values
      #   like -100 or 100 should result in a ban or exclusive selection of the relevant
      #   token.
      #
      #   As an example, you can pass `{"50256": -100}` to prevent the <|endoftext|> token
      #   from being generated.
      #
      # @param logprobs [Integer, nil]
      #   Include the log probabilities on the `logprobs` most likely output tokens, as
      #   well the chosen tokens. For example, if `logprobs` is 5, the API will return a
      #   list of the 5 most likely tokens. The API will always return the `logprob` of
      #   the sampled token, so there may be up to `logprobs+1` elements in the response.
      #
      #   The maximum value for `logprobs` is 5.
      #
      # @param max_tokens [Integer, nil]
      #   The maximum number of [tokens](https://platform.openai.com/tokenizer) that can
      #   be generated in the completion.
      #
      #   The token count of your prompt plus `max_tokens` cannot exceed the model's
      #   context length.
      #   [Example Python code](https://cookbook.openai.com/examples/how_to_count_tokens_with_tiktoken)
      #   for counting tokens.
      #
      # @param n [Integer, nil]
      #   How many completions to generate for each prompt.
      #
      #   **Note:** Because this parameter generates many completions, it can quickly
      #   consume your token quota. Use carefully and ensure that you have reasonable
      #   settings for `max_tokens` and `stop`.
      #
      # @param presence_penalty [Float, nil]
      #   Number between -2.0 and 2.0. Positive values penalize new tokens based on
      #   whether they appear in the text so far, increasing the model's likelihood to
      #   talk about new topics.
      #
      #   [See more information about frequency and presence penalties.](https://developers.openai.com/api/docs/guides/text)
      #
      # @param seed [Integer, nil]
      #   If specified, our system will make a best effort to sample deterministically,
      #   such that repeated requests with the same `seed` and parameters should return
      #   the same result.
      #
      #   Determinism is not guaranteed, and you should refer to the `system_fingerprint`
      #   response parameter to monitor changes in the backend.
      #
      # @param stop [String, Array<String>, nil]
      #   Not supported with latest reasoning models `o3` and `o4-mini`.
      #
      #   Up to 4 sequences where the API will stop generating further tokens. The
      #   returned text will not contain the stop sequence.
      #
      # @param stream_options [OpenAI::Models::Chat::ChatCompletionStreamOptions, nil]
      #   Options for streaming response. Only set this when you set `stream: true`.
      #
      # @param suffix [String, nil]
      #   The suffix that comes after a completion of inserted text.
      #
      #   This parameter is only supported for `gpt-3.5-turbo-instruct`.
      #
      # @param temperature [Float, nil]
      #   What sampling temperature to use, between 0 and 2. Higher values like 0.8 will
      #   make the output more random, while lower values like 0.2 will make it more
      #   focused and deterministic.
      #
      #   We generally recommend altering this or `top_p` but not both.
      #
      # @param top_p [Float, nil]
      #   An alternative to sampling with temperature, called nucleus sampling, where the
      #   model considers the results of the tokens with top_p probability mass. So 0.1
      #   means only the tokens comprising the top 10% probability mass are considered.
      #
      #   We generally recommend altering this or `temperature` but not both.
      #
      # @param user [String]
      #   A unique identifier representing your end-user, which can help OpenAI to monitor
      #   and detect abuse.
      #   [Learn more](https://developers.openai.com/api/docs/guides/safety-best-practices#implement-safety-identifiers).
      #
      # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [OpenAI::Internal::Stream<OpenAI::Models::Completion>]
      #
      # @see OpenAI::Models::CompletionCreateParams
      def create_streaming(params)
        parsed, options = OpenAI::CompletionCreateParams.dump_request(params)
        unless parsed.fetch(:stream, true)
          message = "Please use `#create` for the non-streaming use case."
          raise ArgumentError.new(message)
        end

        parsed.store(:stream, true)
        @client.request(
          method: :post,
          path: "completions",
          headers: {"accept" => "text/event-stream", "accept-encoding" => "identity"},
          body: parsed,
          stream: OpenAI::Internal::Stream,
          model: OpenAI::Completion,
          security: {bearer_auth: true},
          options: options
        )
      end

      # @api private
      #
      # @param client [OpenAI::Client]
      def initialize(client:)
        @client = client
      end
    end
  end
end
