# frozen_string_literal: true

module OpenAI
  module Resources
    class ContentProvenanceChecks
      # Returns a wrapper that exposes the raw HTTP response for each request.
      #
      # @return [ContentProvenanceChecks::WithRawResponse]
      def with_raw_response
        WithRawResponse.new(
          resource: ContentProvenanceChecks.new(
            client: OpenAI::Internal::Transport::RawResponseClient.new(@client)
          )
        )
      end

      # Check whether an image or audio file contains known OpenAI provenance signals.
      # [Learn more about content provenance](/api/docs/guides/content-provenance).
      #
      # If `not_detected`, it means the tool did not find supported signals in the
      # uploaded file. The content could still have been generated by OpenAI if the
      # metadata was stripped or has evidence of tampering, the watermark was degraded,
      # it comes from a legacy generation model, or it was created before provenance
      # signals were available. Content could also still be AI-generated by another
      # company's model, which the tool currently does not detect.
      #
      # @overload create(file:, request_options: {})
      #
      # @param file [Pathname, StringIO, IO, String, OpenAI::FilePart] The image or audio file to check for supported OpenAI provenance signals.
      #
      # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [OpenAI::Models::ContentProvenanceCheck]
      #
      # @see OpenAI::Models::ContentProvenanceCheckCreateParams
      def create(params)
        parsed, options = OpenAI::ContentProvenanceCheckCreateParams.dump_request(params)
        @client.request(
          method: :post,
          path: "content_provenance_checks",
          headers: {"content-type" => "multipart/form-data"},
          body: parsed,
          model: OpenAI::ContentProvenanceCheck,
          security: {bearer_auth: true},
          options: options
        )
      end

      # @api private
      #
      # @param client [OpenAI::Internal::Transport::RequestClient]
      def initialize(client:)
        @client = client
      end

      class WithRawResponse
        def create(params)
          @resource.create(params)
        end

        # @api private
        #
        # @param resource [ContentProvenanceChecks]
        def initialize(resource:)
          @resource = resource
        end
      end
    end
  end
end
