# frozen_string_literal: true

module OpenAI
  module Resources
    class ContentProvenanceChecks
      # Check whether an image or audio file contains known OpenAI provenance signals.
      # [Learn more about content provenance](/api/docs/guides/content-provenance).
      #
      # If `not_detected`, it means the tool did not find supported signals in the
      # uploaded file. The content could still have been generated by OpenAI if the
      # metadata was stripped or has evidence of tampering, the watermark was degraded,
      # it comes from a legacy generation model, or it was created before provenance
      # signals were available. Content could also still be AI-generated by another
      # company's model, which the tool currently does not detect.
      #
      # `String`, `StringIO`, and pathless `IO` inputs are sent with generic upload
      # metadata. Use `OpenAI::FilePart` when you need to override the filename or
      # content type.
      #
      # @overload create(file:, request_options: {})
      #
      # @param file [Pathname, StringIO, IO, String, OpenAI::FilePart] The image or audio file to check for supported OpenAI provenance signals.
      #
      # @param request_options [OpenAI::RequestOptions, Hash{Symbol=>Object}, nil]
      #
      # @return [OpenAI::Models::ContentProvenanceCheck]
      #
      # @see OpenAI::Models::ContentProvenanceCheckCreateParams
      def create(params)
        parsed, options = OpenAI::ContentProvenanceCheckCreateParams.dump_request(params)
        @client.request(
          method: :post,
          path: "content_provenance_checks",
          headers: {"content-type" => "multipart/form-data"},
          body: parsed,
          model: OpenAI::ContentProvenanceCheck,
          security: {bearer_auth: true},
          options: options
        )
      end

      # @api private
      #
      # @param client [OpenAI::Client]
      def initialize(client:)
        @client = client
      end
    end
  end
end
