module OpenAI
  module Resources
    class Beta
      class Agents
        class Vaults
          class Credentials
            def create: (
              String vault_id,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth_create_param,
              name: String,
              ?request_options: OpenAI::request_opts
            ) -> OpenAI::Beta::Agents::Vaults::Credential

            def retrieve: (
              String credential_id,
              vault_id: String,
              ?request_options: OpenAI::request_opts
            ) -> OpenAI::Beta::Agents::Vaults::Credential

            def update: (
              String credential_id,
              vault_id: String,
              auth: OpenAI::Models::Beta::Agents::Vaults::credential_auth_rotate_param,
              ?request_options: OpenAI::request_opts
            ) -> OpenAI::Beta::Agents::Vaults::Credential

            def list: (
              String vault_id,
              ?after: String,
              ?limit: Integer?,
              ?order: OpenAI::Models::Beta::Agents::Vaults::CredentialListParams::order,
              ?status: OpenAI::Models::Beta::Agents::vault_status_filter,
              ?request_options: OpenAI::request_opts
            ) -> OpenAI::Internal::CursorPage[OpenAI::Beta::Agents::Vaults::Credential]

            def delete: (
              String credential_id,
              vault_id: String,
              ?request_options: OpenAI::request_opts
            ) -> OpenAI::Beta::Agents::Vaults::CredentialDeleted

            def initialize: (client: OpenAI::Client) -> void
          end
        end
      end
    end
  end
end
