module OpenAI
  module Models
    module Responses
      type apply_patch_tool =
        {
          type: :apply_patch,
          allowed_callers: ::Array[OpenAI::Models::Responses::ApplyPatchTool::allowed_caller]?
        }

      class ApplyPatchTool < OpenAI::Internal::Type::BaseModel
        attr_accessor type: :apply_patch

        attr_accessor allowed_callers: ::Array[OpenAI::Models::Responses::ApplyPatchTool::allowed_caller]?

        def initialize: (
          ?allowed_callers: ::Array[OpenAI::Models::Responses::ApplyPatchTool::allowed_caller]?,
          ?type: :apply_patch
        ) -> void

        def to_hash: -> {
          type: :apply_patch,
          allowed_callers: ::Array[OpenAI::Models::Responses::ApplyPatchTool::allowed_caller]?
        }

        type allowed_caller = :direct | :programmatic

        module AllowedCaller
          extend OpenAI::Internal::Type::Enum

          DIRECT: :direct
          PROGRAMMATIC: :programmatic

          def self?.values: -> ::Array[OpenAI::Models::Responses::ApplyPatchTool::allowed_caller]
        end
      end
    end
  end
end
