module OpenAI
  module Models
    module Responses
      type computer_tool =
        {
          display_height: Float,
          display_width: Float,
          environment: OpenAI::Models::Responses::ComputerTool::environment,
          type: :computer_use_preview
        }

      class ComputerTool < OpenAI::BaseModel
        attr_accessor display_height: Float

        attr_accessor display_width: Float

        attr_accessor environment: OpenAI::Models::Responses::ComputerTool::environment

        attr_accessor type: :computer_use_preview

        def initialize: (
          display_height: Float,
          display_width: Float,
          environment: OpenAI::Models::Responses::ComputerTool::environment,
          ?type: :computer_use_preview
        ) -> void

        def to_hash: -> OpenAI::Models::Responses::computer_tool

        type environment = :mac | :windows | :ubuntu | :browser

        module Environment
          extend OpenAI::Enum

          MAC: :mac
          WINDOWS: :windows
          UBUNTU: :ubuntu
          BROWSER: :browser

          def self.values: -> ::Array[OpenAI::Models::Responses::ComputerTool::environment]
        end
      end
    end
  end
end
