module OpenAI
  module Models
    module Responses
      type computer_tool = { type: :computer }

      class ComputerTool < OpenAI::Internal::Type::BaseModel
        attr_accessor type: :computer

        def initialize: (?type: :computer) -> void

        def to_hash: -> { type: :computer }
      end
    end
  end
end
