module OpenAI
  module Models
    module Responses
      type container_network_policy_domain_secret =
        { domain: String, name: String, value: String }

      class ContainerNetworkPolicyDomainSecret < OpenAI::Internal::Type::BaseModel
        attr_accessor domain: String

        attr_accessor name: String

        attr_accessor value: String

        def initialize: (domain: String, name: String, value: String) -> void

        def to_hash: -> { domain: String, name: String, value: String }
      end
    end
  end
end
