module OpenAI
  module Models
    module Responses
      type container_network_policy_disabled = { ?type: :disabled }

      class ContainerNetworkPolicyDisabled < OpenAI::Internal::Type::BaseModel
        # Disable outbound network access. Always `disabled`.
        attr_accessor type: :disabled

        # @param type
        #   Disable outbound network access. Always `disabled`.
        def initialize: (?type: :disabled) -> void

        def to_hash: -> { ?type: :disabled }
      end
    end
  end
end
