module OpenAI
  module Models
    module Responses
      type container_network_policy_allowlist =
        {
          allowed_domains: ::Array[String],
          ?type: :allowlist,
          ?domain_secrets: ::Array[OpenAI::Responses::ContainerNetworkPolicyDomainSecret]
        }

      class ContainerNetworkPolicyAllowlist < OpenAI::Internal::Type::BaseModel
        # A list of allowed domains when type is `allowlist`.
        attr_accessor allowed_domains: ::Array[String]

        # Allow outbound network access only to specified domains. Always `allowlist`.
        attr_accessor type: :allowlist

        # Optional domain-scoped secrets for allowlisted domains.
        attr_reader domain_secrets: ::Array[OpenAI::Responses::ContainerNetworkPolicyDomainSecret]?

        # Optional domain-scoped secrets for allowlisted domains.
        def domain_secrets=: (
          ::Array[OpenAI::Responses::ContainerNetworkPolicyDomainSecret]
        ) -> ::Array[OpenAI::Responses::ContainerNetworkPolicyDomainSecret]

        # @param allowed_domains
        #   A list of allowed domains when type is `allowlist`.
        # @param domain_secrets
        #   Optional domain-scoped secrets for allowlisted domains.
        # @param type
        #   Allow outbound network access only to specified domains. Always `allowlist`.
        def initialize: (
          allowed_domains: ::Array[String],
          ?domain_secrets: ::Array[OpenAI::Responses::ContainerNetworkPolicyDomainSecret],
          ?type: :allowlist
        ) -> void

        def to_hash: -> {
          allowed_domains: ::Array[String],
          ?type: :allowlist,
          ?domain_secrets: ::Array[OpenAI::Responses::ContainerNetworkPolicyDomainSecret]
        }
      end
    end
  end
end
