module OpenAI
  module Models
    module Responses
      type function_shell_tool = { type: :shell }

      class FunctionShellTool < OpenAI::Internal::Type::BaseModel
        attr_accessor type: :shell

        def initialize: (?type: :shell) -> void

        def to_hash: -> { type: :shell }
      end
    end
  end
end
