module OpenAI
  module Models
    module Responses
      type function_tool =
        {
          name: String,
          parameters: ::Hash[Symbol, top]?,
          strict: bool?,
          type: :function,
          defer_loading: bool,
          description: String?
        }

      class FunctionTool < OpenAI::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor parameters: ::Hash[Symbol, top]?

        attr_accessor strict: bool?

        attr_accessor type: :function

        attr_reader defer_loading: bool?

        def defer_loading=: (bool) -> bool

        attr_accessor description: String?

        def initialize: (
          name: String,
          parameters: ::Hash[Symbol, top]?,
          strict: bool?,
          ?defer_loading: bool,
          ?description: String?,
          ?type: :function
        ) -> void

        def to_hash: -> {
          name: String,
          parameters: ::Hash[Symbol, top]?,
          strict: bool?,
          type: :function,
          defer_loading: bool,
          description: String?
        }
      end
    end
  end
end
