module OpenAI
  module Models
    module Responses
      type response_code_interpreter_tool_call =
        {
          id: String,
          code: String,
          results: ::Array[OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::result],
          status: OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::status,
          type: :code_interpreter_call
        }

      class ResponseCodeInterpreterToolCall < OpenAI::BaseModel
        attr_accessor id: String

        attr_accessor code: String

        attr_accessor results: ::Array[OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::result]

        attr_accessor status: OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::status

        attr_accessor type: :code_interpreter_call

        def initialize: (
          id: String,
          code: String,
          results: ::Array[OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::result],
          status: OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::status,
          ?type: :code_interpreter_call
        ) -> void

        def to_hash: -> OpenAI::Models::Responses::response_code_interpreter_tool_call

        type result =
          OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Logs
          | OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Files

        class Result < OpenAI::Union
          type logs = { logs: String, type: :logs }

          class Logs < OpenAI::BaseModel
            attr_accessor logs: String

            attr_accessor type: :logs

            def initialize: (logs: String, ?type: :logs) -> void

            def to_hash: -> OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::logs
          end

          type files =
            {
              files: ::Array[OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Files::File],
              type: :files
            }

          class Files < OpenAI::BaseModel
            attr_accessor files: ::Array[OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Files::File]

            attr_accessor type: :files

            def initialize: (
              files: ::Array[OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Files::File],
              ?type: :files
            ) -> void

            def to_hash: -> OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::files

            type file = { file_id: String, mime_type: String }

            class File < OpenAI::BaseModel
              attr_accessor file_id: String

              attr_accessor mime_type: String

              def initialize: (file_id: String, mime_type: String) -> void

              def to_hash: -> OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Files::file
            end
          end

          def self.variants: -> [OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Logs, OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::Result::Files]
        end

        type status = :in_progress | :interpreting | :completed

        class Status < OpenAI::Enum
          IN_PROGRESS: :in_progress
          INTERPRETING: :interpreting
          COMPLETED: :completed

          def self.values: -> ::Array[OpenAI::Models::Responses::ResponseCodeInterpreterToolCall::status]
        end
      end
    end
  end
end
