module OpenAI
  module Models
    module Responses
      type response_steer_event =
        {
          input: OpenAI::Models::Responses::response_steer_input,
          previous_response_id: String,
          type: :"response.steer"
        }

      class ResponseSteerEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor input: OpenAI::Models::Responses::response_steer_input

        attr_accessor previous_response_id: String

        attr_accessor type: :"response.steer"

        def initialize: (
          input: OpenAI::Models::Responses::response_steer_input,
          previous_response_id: String,
          ?type: :"response.steer"
        ) -> void

        def to_hash: -> {
          input: OpenAI::Models::Responses::response_steer_input,
          previous_response_id: String,
          type: :"response.steer"
        }
      end
    end
  end
end
