module OpenAI
  module Models
    module Responses
      type response_format_text_config =
        OpenAI::Models::ResponseFormatText
        | OpenAI::Models::Responses::ResponseFormatTextJSONSchemaConfig
        | OpenAI::Models::ResponseFormatJSONObject

      module ResponseFormatTextConfig
        extend OpenAI::Internal::Type::Union

        def self?.variants: -> [OpenAI::Models::ResponseFormatText, OpenAI::Models::Responses::ResponseFormatTextJSONSchemaConfig, OpenAI::Models::ResponseFormatJSONObject]
      end
    end
  end
end
