module OpenAI
  module Models
    module Responses
      type response_incomplete_event =
        {
          response: OpenAI::Models::Responses::Response,
          type: :"response.incomplete"
        }

      class ResponseIncompleteEvent < OpenAI::BaseModel
        attr_accessor response: OpenAI::Models::Responses::Response

        attr_accessor type: :"response.incomplete"

        def initialize:
          (
            response: OpenAI::Models::Responses::Response,
            ?type: :"response.incomplete"
          ) -> void
          | (
            ?OpenAI::Models::Responses::response_incomplete_event
            | OpenAI::BaseModel data
          ) -> void

        def to_hash: -> OpenAI::Models::Responses::response_incomplete_event
      end
    end
  end
end
