module OpenAI
  module Models
    module Responses
      type response_function_tool_call_item = { id: String }

      class ResponseFunctionToolCallItem < OpenAI::Models::Responses::ResponseFunctionToolCall
        def id: -> String

        def id=: (String _) -> String

        def initialize: (id: String) -> void

        def to_hash: -> { id: String }
      end
    end
  end
end
