module OpenAI
  module Models
    module Responses
      type response_output_text =
        {
          annotations: ::Array[OpenAI::Responses::ResponseOutputText::annotation],
          text: String,
          type: :output_text
        }

      class ResponseOutputText < OpenAI::Internal::Type::BaseModel
        attr_accessor annotations: ::Array[OpenAI::Responses::ResponseOutputText::annotation]

        attr_accessor text: String

        attr_accessor type: :output_text

        def initialize: (
          annotations: ::Array[OpenAI::Responses::ResponseOutputText::annotation],
          text: String,
          ?type: :output_text
        ) -> void

        type annotation =
          OpenAI::Responses::ResponseOutputText::Annotation::FileCitation
          | OpenAI::Responses::ResponseOutputText::Annotation::URLCitation
          | OpenAI::Responses::ResponseOutputText::Annotation::FilePath

        module Annotation
          extend OpenAI::Internal::Type::Union

          type file_citation =
            { file_id: String, index: Integer, type: :file_citation }

          class FileCitation < OpenAI::Internal::Type::BaseModel
            attr_accessor file_id: String

            attr_accessor index: Integer

            attr_accessor type: :file_citation

            def initialize: (
              file_id: String,
              index: Integer,
              ?type: :file_citation
            ) -> void
          end

          type url_citation =
            {
              end_index: Integer,
              start_index: Integer,
              title: String,
              type: :url_citation,
              url: String
            }

          class URLCitation < OpenAI::Internal::Type::BaseModel
            attr_accessor end_index: Integer

            attr_accessor start_index: Integer

            attr_accessor title: String

            attr_accessor type: :url_citation

            attr_accessor url: String

            def initialize: (
              end_index: Integer,
              start_index: Integer,
              title: String,
              url: String,
              ?type: :url_citation
            ) -> void
          end

          type file_path = { file_id: String, index: Integer, type: :file_path }

          class FilePath < OpenAI::Internal::Type::BaseModel
            attr_accessor file_id: String

            attr_accessor index: Integer

            attr_accessor type: :file_path

            def initialize: (
              file_id: String,
              index: Integer,
              ?type: :file_path
            ) -> void
          end

          def self?.variants: -> ::Array[OpenAI::Responses::ResponseOutputText::annotation]
        end
      end
    end
  end
end
