module OpenAI
  module Models
    module Responses
      type response_refusal_done_event =
        {
          content_index: Integer,
          item_id: String,
          output_index: Integer,
          refusal: String,
          sequence_number: Integer,
          type: :"response.refusal.done"
        }

      class ResponseRefusalDoneEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor content_index: Integer

        attr_accessor item_id: String

        attr_accessor output_index: Integer

        attr_accessor refusal: String

        attr_accessor sequence_number: Integer

        attr_accessor type: :"response.refusal.done"

        def initialize: (
          content_index: Integer,
          item_id: String,
          output_index: Integer,
          refusal: String,
          sequence_number: Integer,
          ?type: :"response.refusal.done"
        ) -> void

        def to_hash: -> {
          content_index: Integer,
          item_id: String,
          output_index: Integer,
          refusal: String,
          sequence_number: Integer,
          type: :"response.refusal.done"
        }
      end
    end
  end
end
