module OpenAI
  module Models
    module Responses
      type response_custom_tool_call_input_delta_event =
        {
          delta: String,
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.custom_tool_call_input.delta"
        }

      class ResponseCustomToolCallInputDeltaEvent < OpenAI::Internal::Type::BaseModel
        # The incremental input data (delta) for the custom tool call.
        attr_accessor delta: String

        # Unique identifier for the API item associated with this event.
        attr_accessor item_id: String

        # The index of the output this delta applies to.
        attr_accessor output_index: Integer

        # The sequence number of this event.
        attr_accessor sequence_number: Integer

        # The event type identifier.
        attr_accessor type: :"response.custom_tool_call_input.delta"

        # @param delta
        #   The incremental input data (delta) for the custom tool call.
        # @param item_id
        #   Unique identifier for the API item associated with this event.
        # @param output_index
        #   The index of the output this delta applies to.
        # @param sequence_number
        #   The sequence number of this event.
        # @param type
        #   The event type identifier.
        def initialize: (
          delta: String,
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.custom_tool_call_input.delta"
        ) -> void

        def to_hash: -> {
          delta: String,
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.custom_tool_call_input.delta"
        }
      end
    end
  end
end
