module OpenAI
  module Models
    module Responses
      type response_created_event =
        { response: OpenAI::Responses::Response, type: :"response.created" }

      class ResponseCreatedEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor response: OpenAI::Responses::Response

        attr_accessor type: :"response.created"

        def initialize: (
          response: OpenAI::Responses::Response,
          ?type: :"response.created"
        ) -> void
      end
    end
  end
end
