module OpenAI
  module Models
    module Responses
      type response_text_config =
        { format_: OpenAI::Models::Responses::response_format_text_config }

      class ResponseTextConfig < OpenAI::Internal::Type::BaseModel
        attr_reader format_: OpenAI::Models::Responses::response_format_text_config?

        def format_=: (
          OpenAI::Models::Responses::response_format_text_config
        ) -> OpenAI::Models::Responses::response_format_text_config

        def initialize: (
          ?format_: OpenAI::Models::Responses::response_format_text_config
        ) -> void
      end
    end
  end
end
