module OpenAI
  module Models
    module Responses
      type response_item =
        OpenAI::Responses::ResponseInputMessageItem
        | OpenAI::Responses::ResponseOutputMessage
        | OpenAI::Responses::ResponseFileSearchToolCall
        | OpenAI::Responses::ResponseComputerToolCall
        | OpenAI::Responses::ResponseComputerToolCallOutputItem
        | OpenAI::Responses::ResponseFunctionWebSearch
        | OpenAI::Responses::ResponseFunctionToolCallItem
        | OpenAI::Responses::ResponseFunctionToolCallOutputItem
        | OpenAI::Responses::ResponseItem::ImageGenerationCall
        | OpenAI::Responses::ResponseCodeInterpreterToolCall
        | OpenAI::Responses::ResponseItem::LocalShellCall
        | OpenAI::Responses::ResponseItem::LocalShellCallOutput
        | OpenAI::Responses::ResponseItem::McpListTools
        | OpenAI::Responses::ResponseItem::McpApprovalRequest
        | OpenAI::Responses::ResponseItem::McpApprovalResponse
        | OpenAI::Responses::ResponseItem::McpCall

      module ResponseItem
        extend OpenAI::Internal::Type::Union

        type image_generation_call =
          {
            id: String,
            result: String?,
            status: OpenAI::Responses::ResponseItem::ImageGenerationCall::status,
            type: :image_generation_call
          }

        class ImageGenerationCall < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor result: String?

          attr_accessor status: OpenAI::Responses::ResponseItem::ImageGenerationCall::status

          attr_accessor type: :image_generation_call

          def initialize: (
            id: String,
            result: String?,
            status: OpenAI::Responses::ResponseItem::ImageGenerationCall::status,
            ?type: :image_generation_call
          ) -> void

          type status = :in_progress | :completed | :generating | :failed

          module Status
            extend OpenAI::Internal::Type::Enum

            IN_PROGRESS: :in_progress
            COMPLETED: :completed
            GENERATING: :generating
            FAILED: :failed

            def self?.values: -> ::Array[OpenAI::Responses::ResponseItem::ImageGenerationCall::status]
          end
        end

        type local_shell_call =
          {
            id: String,
            action: OpenAI::Responses::ResponseItem::LocalShellCall::Action,
            call_id: String,
            status: OpenAI::Responses::ResponseItem::LocalShellCall::status,
            type: :local_shell_call
          }

        class LocalShellCall < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor action: OpenAI::Responses::ResponseItem::LocalShellCall::Action

          attr_accessor call_id: String

          attr_accessor status: OpenAI::Responses::ResponseItem::LocalShellCall::status

          attr_accessor type: :local_shell_call

          def initialize: (
            id: String,
            action: OpenAI::Responses::ResponseItem::LocalShellCall::Action,
            call_id: String,
            status: OpenAI::Responses::ResponseItem::LocalShellCall::status,
            ?type: :local_shell_call
          ) -> void

          type action =
            {
              command: ::Array[String],
              env: ::Hash[Symbol, String],
              type: :exec,
              timeout_ms: Integer?,
              user: String?,
              working_directory: String?
            }

          class Action < OpenAI::Internal::Type::BaseModel
            attr_accessor command: ::Array[String]

            attr_accessor env: ::Hash[Symbol, String]

            attr_accessor type: :exec

            attr_accessor timeout_ms: Integer?

            attr_accessor user: String?

            attr_accessor working_directory: String?

            def initialize: (
              command: ::Array[String],
              env: ::Hash[Symbol, String],
              ?timeout_ms: Integer?,
              ?user: String?,
              ?working_directory: String?,
              ?type: :exec
            ) -> void
          end

          type status = :in_progress | :completed | :incomplete

          module Status
            extend OpenAI::Internal::Type::Enum

            IN_PROGRESS: :in_progress
            COMPLETED: :completed
            INCOMPLETE: :incomplete

            def self?.values: -> ::Array[OpenAI::Responses::ResponseItem::LocalShellCall::status]
          end
        end

        type local_shell_call_output =
          {
            id: String,
            output: String,
            type: :local_shell_call_output,
            status: OpenAI::Responses::ResponseItem::LocalShellCallOutput::status?
          }

        class LocalShellCallOutput < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor output: String

          attr_accessor type: :local_shell_call_output

          attr_accessor status: OpenAI::Responses::ResponseItem::LocalShellCallOutput::status?

          def initialize: (
            id: String,
            output: String,
            ?status: OpenAI::Responses::ResponseItem::LocalShellCallOutput::status?,
            ?type: :local_shell_call_output
          ) -> void

          type status = :in_progress | :completed | :incomplete

          module Status
            extend OpenAI::Internal::Type::Enum

            IN_PROGRESS: :in_progress
            COMPLETED: :completed
            INCOMPLETE: :incomplete

            def self?.values: -> ::Array[OpenAI::Responses::ResponseItem::LocalShellCallOutput::status]
          end
        end

        type mcp_list_tools =
          {
            id: String,
            server_label: String,
            tools: ::Array[OpenAI::Responses::ResponseItem::McpListTools::Tool],
            type: :mcp_list_tools,
            error: String?
          }

        class McpListTools < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor server_label: String

          attr_accessor tools: ::Array[OpenAI::Responses::ResponseItem::McpListTools::Tool]

          attr_accessor type: :mcp_list_tools

          attr_accessor error: String?

          def initialize: (
            id: String,
            server_label: String,
            tools: ::Array[OpenAI::Responses::ResponseItem::McpListTools::Tool],
            ?error: String?,
            ?type: :mcp_list_tools
          ) -> void

          type tool =
            {
              input_schema: top,
              name: String,
              annotations: top?,
              description: String?
            }

          class Tool < OpenAI::Internal::Type::BaseModel
            attr_accessor input_schema: top

            attr_accessor name: String

            attr_accessor annotations: top?

            attr_accessor description: String?

            def initialize: (
              input_schema: top,
              name: String,
              ?annotations: top?,
              ?description: String?
            ) -> void
          end
        end

        type mcp_approval_request =
          {
            id: String,
            arguments: String,
            name: String,
            server_label: String,
            type: :mcp_approval_request
          }

        class McpApprovalRequest < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor arguments: String

          attr_accessor name: String

          attr_accessor server_label: String

          attr_accessor type: :mcp_approval_request

          def initialize: (
            id: String,
            arguments: String,
            name: String,
            server_label: String,
            ?type: :mcp_approval_request
          ) -> void
        end

        type mcp_approval_response =
          {
            id: String,
            approval_request_id: String,
            approve: bool,
            type: :mcp_approval_response,
            reason: String?
          }

        class McpApprovalResponse < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor approval_request_id: String

          attr_accessor approve: bool

          attr_accessor type: :mcp_approval_response

          attr_accessor reason: String?

          def initialize: (
            id: String,
            approval_request_id: String,
            approve: bool,
            ?reason: String?,
            ?type: :mcp_approval_response
          ) -> void
        end

        type mcp_call =
          {
            id: String,
            arguments: String,
            name: String,
            server_label: String,
            type: :mcp_call,
            error: String?,
            output: String?
          }

        class McpCall < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor arguments: String

          attr_accessor name: String

          attr_accessor server_label: String

          attr_accessor type: :mcp_call

          attr_accessor error: String?

          attr_accessor output: String?

          def initialize: (
            id: String,
            arguments: String,
            name: String,
            server_label: String,
            ?error: String?,
            ?output: String?,
            ?type: :mcp_call
          ) -> void
        end

        def self?.variants: -> ::Array[OpenAI::Models::Responses::response_item]
      end
    end
  end
end
