module OpenAI
  module Models
    module Responses
      type response_steer_pending_event =
        {
          reason: OpenAI::Models::Responses::response_steer_pending_reason,
          required_input: ::Array[OpenAI::Models::Responses::response_steer_required_input],
          sequence_number: Integer,
          steer: OpenAI::Responses::ResponseSteerPendingEvent::Steer,
          ?type: :"response.steer.pending",
          ?stream_id: String
        }

      class ResponseSteerPendingEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor reason: OpenAI::Models::Responses::response_steer_pending_reason

        attr_accessor required_input: ::Array[OpenAI::Models::Responses::response_steer_required_input]

        attr_accessor sequence_number: Integer

        attr_accessor steer: OpenAI::Responses::ResponseSteerPendingEvent::Steer

        attr_accessor type: :"response.steer.pending"

        attr_reader stream_id: String?

        def stream_id=: (String) -> String

        def initialize: (
          reason: OpenAI::Models::Responses::response_steer_pending_reason,
          required_input: ::Array[OpenAI::Models::Responses::response_steer_required_input],
          sequence_number: Integer,
          steer: OpenAI::Responses::ResponseSteerPendingEvent::Steer,
          ?stream_id: String,
          ?type: :"response.steer.pending"
        ) -> void

        def to_hash: -> {
          reason: OpenAI::Models::Responses::response_steer_pending_reason,
          required_input: ::Array[OpenAI::Models::Responses::response_steer_required_input],
          sequence_number: Integer,
          steer: OpenAI::Responses::ResponseSteerPendingEvent::Steer,
          ?type: :"response.steer.pending",
          ?stream_id: String
        }

        type steer = { id: String, previous_response_id: String }

        class Steer < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor previous_response_id: String

          def initialize: (id: String, previous_response_id: String) -> void

          def to_hash: -> { id: String, previous_response_id: String }
        end
      end
    end
  end
end
