module OpenAI
  module Models
    module Responses
      type response_input_file =
        {
          type: :input_file,
          detail: OpenAI::Models::Responses::ResponseInputFile::detail,
          file_data: String,
          file_id: String?,
          file_url: String,
          filename: String
        }

      class ResponseInputFile < OpenAI::Internal::Type::BaseModel
        attr_accessor type: :input_file

        attr_reader detail: OpenAI::Models::Responses::ResponseInputFile::detail?

        def detail=: (
          OpenAI::Models::Responses::ResponseInputFile::detail
        ) -> OpenAI::Models::Responses::ResponseInputFile::detail

        attr_reader file_data: String?

        def file_data=: (String) -> String

        attr_accessor file_id: String?

        attr_reader file_url: String?

        def file_url=: (String) -> String

        attr_reader filename: String?

        def filename=: (String) -> String

        def initialize: (
          ?detail: OpenAI::Models::Responses::ResponseInputFile::detail,
          ?file_data: String,
          ?file_id: String?,
          ?file_url: String,
          ?filename: String,
          ?type: :input_file
        ) -> void

        def to_hash: -> {
          type: :input_file,
          detail: OpenAI::Models::Responses::ResponseInputFile::detail,
          file_data: String,
          file_id: String?,
          file_url: String,
          filename: String
        }

        type detail = :low | :high

        module Detail
          extend OpenAI::Internal::Type::Enum

          LOW: :low
          HIGH: :high

          def self?.values: -> ::Array[OpenAI::Models::Responses::ResponseInputFile::detail]
        end
      end
    end
  end
end
