module OpenAI
  module Models
    module Responses
      type response_code_interpreter_call_interpreting_event =
        {
          code_interpreter_call: OpenAI::Responses::ResponseCodeInterpreterToolCall,
          output_index: Integer,
          sequence_number: Integer,
          type: :"response.code_interpreter_call.interpreting"
        }

      class ResponseCodeInterpreterCallInterpretingEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor code_interpreter_call: OpenAI::Responses::ResponseCodeInterpreterToolCall

        attr_accessor output_index: Integer

        attr_accessor sequence_number: Integer

        attr_accessor type: :"response.code_interpreter_call.interpreting"

        def initialize: (
          code_interpreter_call: OpenAI::Responses::ResponseCodeInterpreterToolCall,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.code_interpreter_call.interpreting"
        ) -> void
      end
    end
  end
end
