module OpenAI
  module Models
    module Responses
      type response_output_refusal = { refusal: String, type: :refusal }

      class ResponseOutputRefusal < OpenAI::BaseModel
        attr_accessor refusal: String

        attr_accessor type: :refusal

        def initialize:
          (refusal: String, type: :refusal) -> void
          | (
            ?OpenAI::Models::Responses::response_output_refusal
            | OpenAI::BaseModel data
          ) -> void

        def to_hash: -> OpenAI::Models::Responses::response_output_refusal
      end
    end
  end
end
