module OpenAI
  module Models
    module Responses
      type response_function_call_arguments_done_event =
        {
          arguments: String,
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.function_call_arguments.done"
        }

      class ResponseFunctionCallArgumentsDoneEvent < OpenAI::Internal::Type::BaseModel
        # The function-call arguments.
        attr_accessor arguments: String

        # The ID of the item.
        attr_accessor item_id: String

        # The index of the output item.
        attr_accessor output_index: Integer

        # The sequence number of this event.
        attr_accessor sequence_number: Integer

        attr_accessor type: :"response.function_call_arguments.done"

        # @param arguments
        #   The function-call arguments.
        # @param item_id
        #   The ID of the item.
        # @param output_index
        #   The index of the output item.
        # @param sequence_number
        #   The sequence number of this event.
        def initialize: (
          arguments: String,
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.function_call_arguments.done"
        ) -> void

        def to_hash: -> {
          arguments: String,
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.function_call_arguments.done"
        }
      end
    end
  end
end
