module OpenAI
  module Models
    class ResponseItemList = Responses::ResponseItemList

    module Responses
      type response_item_list =
        {
          data: ::Array[OpenAI::Models::Responses::response_item],
          first_id: String,
          has_more: bool,
          last_id: String,
          object: :list
        }

      class ResponseItemList < OpenAI::Internal::Type::BaseModel
        attr_accessor data: ::Array[OpenAI::Models::Responses::response_item]

        attr_accessor first_id: String

        attr_accessor has_more: bool

        attr_accessor last_id: String

        attr_accessor object: :list

        def initialize: (
          data: ::Array[OpenAI::Models::Responses::response_item],
          first_id: String,
          has_more: bool,
          last_id: String,
          ?object: :list
        ) -> void
      end
    end
  end
end
