module OpenAI
  module Models
    module Responses
      type response_output_item =
        OpenAI::Models::Responses::ResponseOutputMessage
        | OpenAI::Models::Responses::ResponseFileSearchToolCall
        | OpenAI::Models::Responses::ResponseFunctionToolCall
        | OpenAI::Models::Responses::ResponseFunctionWebSearch
        | OpenAI::Models::Responses::ResponseComputerToolCall
        | OpenAI::Models::Responses::ResponseReasoningItem

      module ResponseOutputItem
        extend OpenAI::Union

        def self?.variants: -> [OpenAI::Models::Responses::ResponseOutputMessage, OpenAI::Models::Responses::ResponseFileSearchToolCall, OpenAI::Models::Responses::ResponseFunctionToolCall, OpenAI::Models::Responses::ResponseFunctionWebSearch, OpenAI::Models::Responses::ResponseComputerToolCall, OpenAI::Models::Responses::ResponseReasoningItem]
      end
    end
  end
end
