module OpenAI
  module Models
    module Responses
      type response_input =
        ::Array[OpenAI::Models::Responses::response_input_item]

      ResponseInput: OpenAI::Internal::Type::Converter
    end
  end
end
