module OpenAI
  module Models
    module Responses
      type response_output_message =
        {
          id: String,
          content: ::Array[OpenAI::Responses::ResponseOutputMessage::content],
          role: :assistant,
          status: OpenAI::Responses::ResponseOutputMessage::status,
          type: :message
        }

      class ResponseOutputMessage < OpenAI::Internal::Type::BaseModel
        attr_accessor id: String

        attr_accessor content: ::Array[OpenAI::Responses::ResponseOutputMessage::content]

        attr_accessor role: :assistant

        attr_accessor status: OpenAI::Responses::ResponseOutputMessage::status

        attr_accessor type: :message

        def initialize: (
          id: String,
          content: ::Array[OpenAI::Responses::ResponseOutputMessage::content],
          status: OpenAI::Responses::ResponseOutputMessage::status,
          ?role: :assistant,
          ?type: :message
        ) -> void

        type content =
          OpenAI::Responses::ResponseOutputText
          | OpenAI::Responses::ResponseOutputRefusal

        module Content
          extend OpenAI::Internal::Type::Union

          def self?.variants: -> ::Array[OpenAI::Responses::ResponseOutputMessage::content]
        end

        type status = :in_progress | :completed | :incomplete

        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS: :in_progress
          COMPLETED: :completed
          INCOMPLETE: :incomplete

          def self?.values: -> ::Array[OpenAI::Responses::ResponseOutputMessage::status]
        end
      end
    end
  end
end
