module OpenAI
  module Models
    class ResponseItemList = Responses::ResponseItemList

    module Responses
      type response_item_list =
        {
          data: ::Array[OpenAI::Models::Responses::response_item],
          first_id: String,
          has_more: bool,
          last_id: String,
          ?object: :list
        }

      class ResponseItemList < OpenAI::Internal::Type::BaseModel
        # A list of items used to generate this response.
        attr_accessor data: ::Array[OpenAI::Models::Responses::response_item]

        # The ID of the first item in the list.
        attr_accessor first_id: String

        # Whether there are more items available.
        attr_accessor has_more: bool

        # The ID of the last item in the list.
        attr_accessor last_id: String

        # The type of object returned, must be `list`.
        attr_accessor object: :list

        # @param data
        #   A list of items used to generate this response.
        # @param first_id
        #   The ID of the first item in the list.
        # @param has_more
        #   Whether there are more items available.
        # @param last_id
        #   The ID of the last item in the list.
        # @param object
        #   The type of object returned, must be `list`.
        def initialize: (
          data: ::Array[OpenAI::Models::Responses::response_item],
          first_id: String,
          has_more: bool,
          last_id: String,
          ?object: :list
        ) -> void

        def to_hash: -> {
          data: ::Array[OpenAI::Models::Responses::response_item],
          first_id: String,
          has_more: bool,
          last_id: String,
          ?object: :list
        }
      end
    end
  end
end
