module OpenAI
  module Models
    module Responses
      type response_item =
        OpenAI::Models::Responses::ResponseInputMessageItem
        | OpenAI::Models::Responses::ResponseOutputMessage
        | OpenAI::Models::Responses::ResponseFileSearchToolCall
        | OpenAI::Models::Responses::ResponseComputerToolCall
        | OpenAI::Models::Responses::ResponseComputerToolCallOutputItem
        | OpenAI::Models::Responses::ResponseFunctionWebSearch
        | OpenAI::Models::Responses::ResponseFunctionToolCallItem
        | OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem

      module ResponseItem
        extend OpenAI::Internal::Type::Union

        def self?.variants: -> [OpenAI::Models::Responses::ResponseInputMessageItem, OpenAI::Models::Responses::ResponseOutputMessage, OpenAI::Models::Responses::ResponseFileSearchToolCall, OpenAI::Models::Responses::ResponseComputerToolCall, OpenAI::Models::Responses::ResponseComputerToolCallOutputItem, OpenAI::Models::Responses::ResponseFunctionWebSearch, OpenAI::Models::Responses::ResponseFunctionToolCallItem, OpenAI::Models::Responses::ResponseFunctionToolCallOutputItem]
      end
    end
  end
end
