module OpenAI
  module Models
    module Responses
      type response_input_message_content_list =
        ::Array[OpenAI::Models::Responses::response_input_content]

      ResponseInputMessageContentList: OpenAI::Internal::Type::Converter
    end
  end
end
