module OpenAI
  module Models
    module Responses
      type response_web_search_call_completed_event =
        {
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.web_search_call.completed"
        }

      class ResponseWebSearchCallCompletedEvent < OpenAI::Internal::Type::BaseModel
        # Unique ID for the output item associated with the web search call.
        attr_accessor item_id: String

        # The index of the output item that the web search call is associated with.
        attr_accessor output_index: Integer

        # The sequence number of the web search call being processed.
        attr_accessor sequence_number: Integer

        # The type of the event. Always `response.web_search_call.completed`.
        attr_accessor type: :"response.web_search_call.completed"

        # @param item_id
        #   Unique ID for the output item associated with the web search call.
        # @param output_index
        #   The index of the output item that the web search call is associated with.
        # @param sequence_number
        #   The sequence number of the web search call being processed.
        # @param type
        #   The type of the event. Always `response.web_search_call.completed`.
        def initialize: (
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.web_search_call.completed"
        ) -> void

        def to_hash: -> {
          item_id: String,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.web_search_call.completed"
        }
      end
    end
  end
end
