module OpenAI
  module Models
    module Responses
      type response_input_file_content =
        {
          type: :input_file,
          detail: OpenAI::Models::Responses::ResponseInputFileContent::detail,
          file_data: String?,
          file_id: String?,
          file_url: String?,
          filename: String?
        }

      class ResponseInputFileContent < OpenAI::Internal::Type::BaseModel
        attr_accessor type: :input_file

        attr_reader detail: OpenAI::Models::Responses::ResponseInputFileContent::detail?

        def detail=: (
          OpenAI::Models::Responses::ResponseInputFileContent::detail
        ) -> OpenAI::Models::Responses::ResponseInputFileContent::detail

        attr_accessor file_data: String?

        attr_accessor file_id: String?

        attr_accessor file_url: String?

        attr_accessor filename: String?

        def initialize: (
          ?detail: OpenAI::Models::Responses::ResponseInputFileContent::detail,
          ?file_data: String?,
          ?file_id: String?,
          ?file_url: String?,
          ?filename: String?,
          ?type: :input_file
        ) -> void

        def to_hash: -> {
          type: :input_file,
          detail: OpenAI::Models::Responses::ResponseInputFileContent::detail,
          file_data: String?,
          file_id: String?,
          file_url: String?,
          filename: String?
        }

        type detail = :high | :low

        module Detail
          extend OpenAI::Internal::Type::Enum

          HIGH: :high
          LOW: :low

          def self?.values: -> ::Array[OpenAI::Models::Responses::ResponseInputFileContent::detail]
        end
      end
    end
  end
end
