module OpenAI
  module Models
    module Responses
      type response_image_gen_call_partial_image_event =
        {
          item_id: String,
          output_index: Integer,
          :partial_image_b64 => String,
          partial_image_index: Integer,
          sequence_number: Integer,
          type: :"response.image_generation_call.partial_image"
        }

      class ResponseImageGenCallPartialImageEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor item_id: String

        attr_accessor output_index: Integer

        attr_accessor partial_image_b64: String

        attr_accessor partial_image_index: Integer

        attr_accessor sequence_number: Integer

        attr_accessor type: :"response.image_generation_call.partial_image"

        def initialize: (
          item_id: String,
          output_index: Integer,
          partial_image_b64: String,
          partial_image_index: Integer,
          sequence_number: Integer,
          ?type: :"response.image_generation_call.partial_image"
        ) -> void

        def to_hash: -> {
          item_id: String,
          output_index: Integer,
          :partial_image_b64 => String,
          partial_image_index: Integer,
          sequence_number: Integer,
          type: :"response.image_generation_call.partial_image"
        }
      end
    end
  end
end
