module OpenAI
  module Models
    module Responses
      type response_output_item_added_event =
        {
          item: OpenAI::Models::Responses::response_output_item,
          output_index: Integer,
          sequence_number: Integer,
          type: :"response.output_item.added"
        }

      class ResponseOutputItemAddedEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor item: OpenAI::Models::Responses::response_output_item

        attr_accessor output_index: Integer

        attr_accessor sequence_number: Integer

        attr_accessor type: :"response.output_item.added"

        def initialize: (
          item: OpenAI::Models::Responses::response_output_item,
          output_index: Integer,
          sequence_number: Integer,
          ?type: :"response.output_item.added"
        ) -> void

        def to_hash: -> {
          item: OpenAI::Models::Responses::response_output_item,
          output_index: Integer,
          sequence_number: Integer,
          type: :"response.output_item.added"
        }
      end
    end
  end
end
