module OpenAI
  module Models
    module Responses
      type response_mcp_list_tools_completed_event =
        { sequence_number: Integer, type: :"response.mcp_list_tools.completed" }

      class ResponseMcpListToolsCompletedEvent < OpenAI::Internal::Type::BaseModel
        attr_accessor sequence_number: Integer

        attr_accessor type: :"response.mcp_list_tools.completed"

        def initialize: (
          sequence_number: Integer,
          ?type: :"response.mcp_list_tools.completed"
        ) -> void
      end
    end
  end
end
