module OpenAI
  module Models
    module Responses
      type tool_choice_allowed =
        {
          mode: OpenAI::Models::Responses::ToolChoiceAllowed::mode,
          tools: ::Array[::Hash[Symbol, top]],
          type: :allowed_tools
        }

      class ToolChoiceAllowed < OpenAI::Internal::Type::BaseModel
        attr_accessor mode: OpenAI::Models::Responses::ToolChoiceAllowed::mode

        attr_accessor tools: ::Array[::Hash[Symbol, top]]

        attr_accessor type: :allowed_tools

        def initialize: (
          mode: OpenAI::Models::Responses::ToolChoiceAllowed::mode,
          tools: ::Array[::Hash[Symbol, top]],
          ?type: :allowed_tools
        ) -> void

        def to_hash: -> {
          mode: OpenAI::Models::Responses::ToolChoiceAllowed::mode,
          tools: ::Array[::Hash[Symbol, top]],
          type: :allowed_tools
        }

        type mode = :auto | :required

        module Mode
          extend OpenAI::Internal::Type::Enum

          AUTO: :auto
          REQUIRED: :required

          def self?.values: -> ::Array[OpenAI::Models::Responses::ToolChoiceAllowed::mode]
        end
      end
    end
  end
end
