module OpenAI
  module Models
    module Responses
      type tool =
        OpenAI::Responses::FileSearchTool
        | OpenAI::Responses::FunctionTool
        | OpenAI::Responses::ComputerTool
        | OpenAI::Responses::WebSearchTool

      module Tool
        extend OpenAI::Internal::Type::Union

        def self?.variants: -> ::Array[OpenAI::Models::Responses::tool]
      end
    end
  end
end
