module OpenAI
  module Models
    module Responses
      type tool_choice_function = { name: String, type: :function }

      class ToolChoiceFunction < OpenAI::Internal::Type::BaseModel
        attr_accessor name: String

        attr_accessor type: :function

        def initialize: (name: String, ?type: :function) -> void
      end
    end
  end
end
