module OpenAI
  module Models
    module Responses
      type tool =
        OpenAI::Models::Responses::FileSearchTool
        | OpenAI::Models::Responses::FunctionTool
        | OpenAI::Models::Responses::ComputerTool
        | OpenAI::Models::Responses::WebSearchTool

      module Tool
        extend OpenAI::Union

        def self?.variants: -> [OpenAI::Models::Responses::FileSearchTool, OpenAI::Models::Responses::FunctionTool, OpenAI::Models::Responses::ComputerTool, OpenAI::Models::Responses::WebSearchTool]
      end
    end
  end
end
