module OpenAI
  module Models
    module Responses
      type web_search_tool =
        {
          type: OpenAI::Models::Responses::WebSearchTool::type_,
          ?external_web_access: bool,
          ?filters: OpenAI::Responses::WebSearchTool::Filters?,
          ?search_context_size: OpenAI::Models::Responses::WebSearchTool::search_context_size,
          ?user_location: OpenAI::Responses::WebSearchTool::UserLocation?
        }

      class WebSearchTool < OpenAI::Internal::Type::BaseModel
        # The type of the web search tool. One of `web_search` or `web_search_2025_08_26`.
        attr_accessor type: OpenAI::Models::Responses::WebSearchTool::type_

        # Allow live internet access for web search. Defaults to true when omitted. When
        # false, the web search tool runs in offline/cache-only mode and will not fetch
        # new external content.
        attr_reader external_web_access: bool?

        # Allow live internet access for web search. Defaults to true when omitted. When
        # false, the web search tool runs in offline/cache-only mode and will not fetch
        # new external content.
        def external_web_access=: (bool) -> bool

        # Filters for the search.
        attr_accessor filters: OpenAI::Responses::WebSearchTool::Filters?

        # High level guidance for the amount of context window space to use for the
        # search. One of `low`, `medium`, or `high`. `medium` is the default.
        attr_reader search_context_size: OpenAI::Models::Responses::WebSearchTool::search_context_size?

        # High level guidance for the amount of context window space to use for the
        # search. One of `low`, `medium`, or `high`. `medium` is the default.
        def search_context_size=: (
          OpenAI::Models::Responses::WebSearchTool::search_context_size
        ) -> OpenAI::Models::Responses::WebSearchTool::search_context_size

        # The approximate location of the user.
        attr_accessor user_location: OpenAI::Responses::WebSearchTool::UserLocation?

        # @param type
        #   The type of the web search tool. One of `web_search` or `web_search_2025_08_26`.
        # @param external_web_access
        #   Allow live internet access for web search. Defaults to true when omitted. When
        #   false, the web search tool runs in offline/cache-only mode and will not fetch
        #   new external content.
        # @param filters
        #   Filters for the search.
        # @param search_context_size
        #   High level guidance for the amount of context window space to use for the
        #   search. One of `low`, `medium`, or `high`. `medium` is the default.
        # @param user_location
        #   The approximate location of the user.
        def initialize: (
          type: OpenAI::Models::Responses::WebSearchTool::type_,
          ?external_web_access: bool,
          ?filters: OpenAI::Responses::WebSearchTool::Filters?,
          ?search_context_size: OpenAI::Models::Responses::WebSearchTool::search_context_size,
          ?user_location: OpenAI::Responses::WebSearchTool::UserLocation?
        ) -> void

        def to_hash: -> {
          type: OpenAI::Models::Responses::WebSearchTool::type_,
          ?external_web_access: bool,
          ?filters: OpenAI::Responses::WebSearchTool::Filters?,
          ?search_context_size: OpenAI::Models::Responses::WebSearchTool::search_context_size,
          ?user_location: OpenAI::Responses::WebSearchTool::UserLocation?
        }

        type type_ = :web_search | :web_search_2025_08_26

        module Type
          extend OpenAI::Internal::Type::Enum

          WEB_SEARCH: :web_search
          WEB_SEARCH_2025_08_26: :web_search_2025_08_26

          def self?.values: -> ::Array[OpenAI::Models::Responses::WebSearchTool::type_]
        end

        type filters = { ?allowed_domains: ::Array[String]? }

        class Filters < OpenAI::Internal::Type::BaseModel
          # Allowed domains for the search. If not provided, all domains are allowed.
          # Subdomains of the provided domains are allowed as well.
          #
          # Example: `["pubmed.ncbi.nlm.nih.gov"]`
          attr_accessor allowed_domains: ::Array[String]?

          # @param allowed_domains
          #   Allowed domains for the search. If not provided, all domains are allowed.
          #   Subdomains of the provided domains are allowed as well.
          #
          #   Example: `["pubmed.ncbi.nlm.nih.gov"]`
          def initialize: (?allowed_domains: ::Array[String]?) -> void

          def to_hash: -> { ?allowed_domains: ::Array[String]? }
        end

        type search_context_size = :low | :medium | :high

        module SearchContextSize
          extend OpenAI::Internal::Type::Enum

          LOW: :low
          MEDIUM: :medium
          HIGH: :high

          def self?.values: -> ::Array[OpenAI::Models::Responses::WebSearchTool::search_context_size]
        end

        type user_location =
          {
            ?city: String?,
            ?country: String?,
            ?region: String?,
            ?timezone: String?,
            ?type: OpenAI::Models::Responses::WebSearchTool::UserLocation::type_
          }

        class UserLocation < OpenAI::Internal::Type::BaseModel
          # Free text input for the city of the user, e.g. `San Francisco`.
          attr_accessor city: String?

          # The two-letter [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of
          # the user, e.g. `US`.
          attr_accessor country: String?

          # Free text input for the region of the user, e.g. `California`.
          attr_accessor region: String?

          # The [IANA timezone](https://timeapi.io/documentation/iana-timezones) of the
          # user, e.g. `America/Los_Angeles`.
          attr_accessor timezone: String?

          # The type of location approximation. Always `approximate`.
          attr_reader type: OpenAI::Models::Responses::WebSearchTool::UserLocation::type_?

          # The type of location approximation. Always `approximate`.
          def type=: (
            OpenAI::Models::Responses::WebSearchTool::UserLocation::type_
          ) -> OpenAI::Models::Responses::WebSearchTool::UserLocation::type_

          # @param city
          #   Free text input for the city of the user, e.g. `San Francisco`.
          # @param country
          #   The two-letter [ISO country code](https://en.wikipedia.org/wiki/ISO_3166-1) of
          #   the user, e.g. `US`.
          # @param region
          #   Free text input for the region of the user, e.g. `California`.
          # @param timezone
          #   The [IANA timezone](https://timeapi.io/documentation/iana-timezones) of the
          #   user, e.g. `America/Los_Angeles`.
          # @param type
          #   The type of location approximation. Always `approximate`.
          def initialize: (
            ?city: String?,
            ?country: String?,
            ?region: String?,
            ?timezone: String?,
            ?type: OpenAI::Models::Responses::WebSearchTool::UserLocation::type_
          ) -> void

          def to_hash: -> {
            ?city: String?,
            ?country: String?,
            ?region: String?,
            ?timezone: String?,
            ?type: OpenAI::Models::Responses::WebSearchTool::UserLocation::type_
          }

          type type_ = :approximate

          module Type
            extend OpenAI::Internal::Type::Enum

            APPROXIMATE: :approximate

            def self?.values: -> ::Array[OpenAI::Models::Responses::WebSearchTool::UserLocation::type_]
          end
        end
      end
    end
  end
end
