# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      # @see OpenAI::Resources::Beta::Agents#create
      class Agent < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The ID of the reusable agent.
        #
        #   @return [String]
        required :id, String

        # @!attribute created_at
        #   The Unix timestamp, in seconds, when the agent was created.
        #
        #   @return [Integer]
        required :created_at, Integer

        # @!attribute instructions
        #   Custom instructions appended to the agent's default base instructions.
        #
        #   @return [String, nil]
        required :instructions, String, nil?: true

        # @!attribute metadata
        #   Custom string key-value pairs attached to the agent.
        #
        #   @return [Hash{Symbol=>String}]
        required :metadata, OpenAI::Internal::Type::HashOf[String]

        # @!attribute model
        #   The requested model name used for inference.
        #
        #   @return [String]
        required :model, String

        # @!attribute multi_agent
        #   The resolved configuration for creating and coordinating subagents.
        #
        #   @return [OpenAI::Models::Beta::MultiAgentConfig]
        required :multi_agent, -> { OpenAI::Beta::MultiAgentConfig }

        # @!attribute name
        #   A human-readable name for the agent, or null if it is unnamed.
        #
        #   @return [String, nil]
        required :name, String, nil?: true

        # @!attribute object
        #   The object type. Always `agent`.
        #
        #   @return [Symbol, :agent]
        required :object, const: :agent

        # @!attribute reasoning
        #   The resolved reasoning configuration, including the model default for an omitted
        #   effort.
        #
        #   @return [OpenAI::Models::Beta::AgentReasoning]
        required :reasoning, -> { OpenAI::Beta::AgentReasoning }

        # @!attribute service_tier
        #   The resolved service-tier policy used for model requests.
        #
        #   @return [Symbol, OpenAI::Models::Beta::Agent::ServiceTier]
        required :service_tier, enum: -> { OpenAI::Beta::Agent::ServiceTier }

        # @!attribute text
        #   The resolved configuration for text generated by the agent.
        #
        #   @return [OpenAI::Models::Beta::AgentText]
        required :text, -> { OpenAI::Beta::AgentText }

        # @!attribute tools
        #   Tools available to the agent.
        #
        #   @return [Array<OpenAI::Models::Beta::PersistedAgentTool::Function, OpenAI::Models::Beta::PersistedAgentTool::ToolSearch, OpenAI::Models::Beta::PersistedAgentTool::ProgrammaticToolCalling, OpenAI::Models::Beta::PersistedAgentTool::Mcp, OpenAI::Models::Beta::PersistedAgentTool::WebSearch>]
        required :tools, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Beta::PersistedAgentTool] }

        # @!attribute updated_at
        #   The Unix timestamp, in seconds, when the agent was last updated.
        #
        #   @return [Integer]
        required :updated_at, Integer

        # @!method initialize(id:, created_at:, instructions:, metadata:, model:, multi_agent:, name:, reasoning:, service_tier:, text:, tools:, updated_at:, object: :agent)
        #   A reusable agent scoped to the caller's project.
        #
        #   @param id [String]
        #     The ID of the reusable agent.
        #
        #   @param created_at [Integer]
        #     The Unix timestamp, in seconds, when the agent was created.
        #
        #   @param instructions [String, nil]
        #     Custom instructions appended to the agent's default base instructions.
        #
        #   @param metadata [Hash{Symbol=>String}]
        #     Custom string key-value pairs attached to the agent.
        #
        #   @param model [String]
        #     The requested model name used for inference.
        #
        #   @param multi_agent [OpenAI::Models::Beta::MultiAgentConfig]
        #     The resolved configuration for creating and coordinating subagents.
        #
        #   @param name [String, nil]
        #     A human-readable name for the agent, or null if it is unnamed.
        #
        #   @param reasoning [OpenAI::Models::Beta::AgentReasoning]
        #     The resolved reasoning configuration, including the model default for an omitted
        #     effort.
        #
        #   @param service_tier [Symbol, OpenAI::Models::Beta::Agent::ServiceTier]
        #     The resolved service-tier policy used for model requests.
        #
        #   @param text [OpenAI::Models::Beta::AgentText]
        #     The resolved configuration for text generated by the agent.
        #
        #   @param tools [Array<OpenAI::Models::Beta::PersistedAgentTool::Function, OpenAI::Models::Beta::PersistedAgentTool::ToolSearch, OpenAI::Models::Beta::PersistedAgentTool::ProgrammaticToolCalling, OpenAI::Models::Beta::PersistedAgentTool::Mcp, OpenAI::Models::Beta::PersistedAgentTool::WebSearch>]
        #     Tools available to the agent.
        #
        #   @param updated_at [Integer]
        #     The Unix timestamp, in seconds, when the agent was last updated.
        #
        #   @param object [Symbol, :agent]
        #     The object type. Always `agent`.

        # The resolved service-tier policy used for model requests.
        #
        # @see OpenAI::Models::Beta::Agent#service_tier
        module ServiceTier
          extend OpenAI::Internal::Type::Enum

          AUTO = :auto
          DEFAULT = :default
          FLEX = :flex
          PRIORITY = :priority
          FAST = :fast

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
