# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class AgentTextParam < OpenAI::Internal::Type::BaseModel
        # @!attribute format_
        #   The output format. Omission uses ordinary text (`{"type": "text"}`).
        #
        #   @return [OpenAI::Models::Beta::TextFormatParam::Text, OpenAI::Models::Beta::TextFormatParam::JSONSchema, nil]
        optional :format_, union: -> { OpenAI::Beta::TextFormatParam }, api_name: :format, nil?: true

        # @!attribute verbosity
        #   The amount of text the model should produce. Defaults to `medium`, matching
        #   Responses.
        #
        #   @return [Symbol, OpenAI::Models::Beta::AgentTextParam::Verbosity, nil]
        optional :verbosity, enum: -> { OpenAI::Beta::AgentTextParam::Verbosity }, nil?: true

        # @!method initialize(format_: nil, verbosity: nil)
        #   Configuration for text generated by the agent.
        #
        #   @param format_ [OpenAI::Models::Beta::TextFormatParam::Text, OpenAI::Models::Beta::TextFormatParam::JSONSchema, nil]
        #     The output format. Omission uses ordinary text (`{"type": "text"}`).
        #
        #   @param verbosity [Symbol, OpenAI::Models::Beta::AgentTextParam::Verbosity, nil]
        #     The amount of text the model should produce. Defaults to `medium`, matching
        #     Responses.

        # The amount of text the model should produce. Defaults to `medium`, matching
        # Responses.
        #
        # @see OpenAI::Models::Beta::AgentTextParam#verbosity
        module Verbosity
          extend OpenAI::Internal::Type::Enum

          # Produces less text.
          LOW = :low

          # Uses the default amount of text.
          MEDIUM = :medium

          # Produces more text.
          HIGH = :high

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end
  end
end
