# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseCompactionItem < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the compaction item.
        #
        #   @return [String]
        required :id, String

        # @!attribute encrypted_content
        #   The encrypted content that was produced by compaction.
        #
        #   @return [String]
        required :encrypted_content, String

        # @!attribute type
        #   The type of the item. Always `compaction`.
        #
        #   @return [Symbol, :compaction]
        required :type, const: :compaction

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseCompactionItem::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseCompactionItem::Agent }

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, encrypted_content:, agent: nil, created_by: nil, type: :compaction)
        #   A compaction item generated by the
        #   [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        #
        #   @param id [String] The unique ID of the compaction item.
        #
        #   @param encrypted_content [String] The encrypted content that was produced by compaction.
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseCompactionItem::Agent] The agent that produced this item.
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :compaction] The type of the item. Always `compaction`.

        # @see OpenAI::Models::Beta::BetaResponseCompactionItem#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end
      end
    end

    BetaResponseCompactionItem = Beta::BetaResponseCompactionItem
  end
end
