# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseToolSearchOutputItemParam < OpenAI::Internal::Type::BaseModel
        # @!attribute tools
        #   The loaded tool definitions returned by the tool search output.
        #
        #   @return [Array<OpenAI::Models::Beta::BetaFunctionTool, OpenAI::Models::Beta::BetaFileSearchTool, OpenAI::Models::Beta::BetaComputerTool, OpenAI::Models::Beta::BetaComputerUsePreviewTool, OpenAI::Models::Beta::BetaTool::Mcp, OpenAI::Models::Beta::BetaTool::CodeInterpreter, OpenAI::Models::Beta::BetaTool::ProgrammaticToolCalling, OpenAI::Models::Beta::BetaTool::ImageGeneration, OpenAI::Models::Beta::BetaTool::LocalShell, OpenAI::Models::Beta::BetaFunctionShellTool, OpenAI::Models::Beta::BetaCustomTool, OpenAI::Models::Beta::BetaNamespaceTool, OpenAI::Models::Beta::BetaToolSearchTool, OpenAI::Models::Beta::BetaApplyPatchTool, OpenAI::Models::Beta::BetaWebSearchTool, OpenAI::Models::Beta::BetaWebSearchPreviewTool>]
        required :tools, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Beta::BetaTool] }

        # @!attribute type
        #   The item type. Always `tool_search_output`.
        #
        #   @return [Symbol, :tool_search_output]
        required :type, const: :tool_search_output

        # @!attribute id
        #   The unique ID of this tool search output.
        #
        #   @return [String, nil]
        optional :id, String, nil?: true

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Agent }, nil?: true

        # @!attribute call_id
        #   The unique ID of the tool search call generated by the model.
        #
        #   @return [String, nil]
        optional :call_id, String, nil?: true

        # @!attribute execution
        #   Whether tool search was executed by the server or by the client.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam::Execution, nil]
        optional :execution, enum: -> { OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Execution }

        # @!attribute status
        #   The status of the tool search output.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam::Status, nil]
        optional :status, enum: -> { OpenAI::Beta::BetaResponseToolSearchOutputItemParam::Status }, nil?: true

        # @!method initialize(tools:, id: nil, agent: nil, call_id: nil, execution: nil, status: nil, type: :tool_search_output)
        #   @param tools [Array<OpenAI::Models::Beta::BetaFunctionTool, OpenAI::Models::Beta::BetaFileSearchTool, OpenAI::Models::Beta::BetaComputerTool, OpenAI::Models::Beta::BetaComputerUsePreviewTool, OpenAI::Models::Beta::BetaTool::Mcp, OpenAI::Models::Beta::BetaTool::CodeInterpreter, OpenAI::Models::Beta::BetaTool::ProgrammaticToolCalling, OpenAI::Models::Beta::BetaTool::ImageGeneration, OpenAI::Models::Beta::BetaTool::LocalShell, OpenAI::Models::Beta::BetaFunctionShellTool, OpenAI::Models::Beta::BetaCustomTool, OpenAI::Models::Beta::BetaNamespaceTool, OpenAI::Models::Beta::BetaToolSearchTool, OpenAI::Models::Beta::BetaApplyPatchTool, OpenAI::Models::Beta::BetaWebSearchTool, OpenAI::Models::Beta::BetaWebSearchPreviewTool>] The loaded tool definitions returned by the tool search output.
        #
        #   @param id [String, nil] The unique ID of this tool search output.
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam::Agent, nil] The agent that produced this item.
        #
        #   @param call_id [String, nil] The unique ID of the tool search call generated by the model.
        #
        #   @param execution [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam::Execution] Whether tool search was executed by the server or by the client.
        #
        #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam::Status, nil] The status of the tool search output.
        #
        #   @param type [Symbol, :tool_search_output] The item type. Always `tool_search_output`.

        # @see OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end

        # Whether tool search was executed by the server or by the client.
        #
        # @see OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam#execution
        module Execution
          extend OpenAI::Internal::Type::Enum

          SERVER = :server
          CLIENT = :client

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The status of the tool search output.
        #
        # @see OpenAI::Models::Beta::BetaResponseToolSearchOutputItemParam#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end
      end
    end

    BetaResponseToolSearchOutputItemParam = Beta::BetaResponseToolSearchOutputItemParam
  end
end
