# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseToolSearchCall < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the tool search call item.
        #
        #   @return [String]
        required :id, String

        # @!attribute arguments
        #   Arguments used for the tool search call.
        #
        #   @return [Object]
        required :arguments, OpenAI::Internal::Type::Unknown

        # @!attribute call_id
        #   The unique ID of the tool search call generated by the model.
        #
        #   @return [String, nil]
        required :call_id, String, nil?: true

        # @!attribute execution
        #   Whether tool search was executed by the server or by the client.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchCall::Execution]
        required :execution, enum: -> { OpenAI::Beta::BetaResponseToolSearchCall::Execution }

        # @!attribute status
        #   The status of the tool search call item that was recorded.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchCall::Status]
        required :status, enum: -> { OpenAI::Beta::BetaResponseToolSearchCall::Status }

        # @!attribute type
        #   The type of the item. Always `tool_search_call`.
        #
        #   @return [Symbol, :tool_search_call]
        required :type, const: :tool_search_call

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseToolSearchCall::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseToolSearchCall::Agent }

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, arguments:, call_id:, execution:, status:, agent: nil, created_by: nil, type: :tool_search_call)
        #   @param id [String] The unique ID of the tool search call item.
        #
        #   @param arguments [Object] Arguments used for the tool search call.
        #
        #   @param call_id [String, nil] The unique ID of the tool search call generated by the model.
        #
        #   @param execution [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchCall::Execution] Whether tool search was executed by the server or by the client.
        #
        #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchCall::Status] The status of the tool search call item that was recorded.
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseToolSearchCall::Agent] The agent that produced this item.
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :tool_search_call] The type of the item. Always `tool_search_call`.

        # Whether tool search was executed by the server or by the client.
        #
        # @see OpenAI::Models::Beta::BetaResponseToolSearchCall#execution
        module Execution
          extend OpenAI::Internal::Type::Enum

          SERVER = :server
          CLIENT = :client

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The status of the tool search call item that was recorded.
        #
        # @see OpenAI::Models::Beta::BetaResponseToolSearchCall#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @see OpenAI::Models::Beta::BetaResponseToolSearchCall#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end
      end
    end

    BetaResponseToolSearchCall = Beta::BetaResponseToolSearchCall
  end
end
