# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseCompactionItemParam < OpenAI::Internal::Type::BaseModel
        # @!attribute encrypted_content
        #   The encrypted content of the compaction summary.
        #
        #   @return [String]
        required :encrypted_content, String

        # @!attribute type
        #   The type of the item. Always `compaction`.
        #
        #   @return [Symbol, :compaction]
        required :type, const: :compaction

        # @!attribute id
        #   The ID of the compaction item.
        #
        #   @return [String, nil]
        optional :id, String, nil?: true

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseCompactionItemParam::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseCompactionItemParam::Agent }, nil?: true

        # @!method initialize(encrypted_content:, id: nil, agent: nil, type: :compaction)
        #   A compaction item generated by the
        #   [`v1/responses/compact` API](https://platform.openai.com/docs/api-reference/responses/compact).
        #
        #   @param encrypted_content [String] The encrypted content of the compaction summary.
        #
        #   @param id [String, nil] The ID of the compaction item.
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseCompactionItemParam::Agent, nil] The agent that produced this item.
        #
        #   @param type [Symbol, :compaction] The type of the item. Always `compaction`.

        # @see OpenAI::Models::Beta::BetaResponseCompactionItemParam#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end
      end
    end

    BetaResponseCompactionItemParam = Beta::BetaResponseCompactionItemParam
  end
end
