# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class BetaResponseToolSearchOutputItem < OpenAI::Internal::Type::BaseModel
        # @!attribute id
        #   The unique ID of the tool search output item.
        #
        #   @return [String]
        required :id, String

        # @!attribute call_id
        #   The unique ID of the tool search call generated by the model.
        #
        #   @return [String, nil]
        required :call_id, String, nil?: true

        # @!attribute execution
        #   Whether tool search was executed by the server or by the client.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItem::Execution]
        required :execution, enum: -> { OpenAI::Beta::BetaResponseToolSearchOutputItem::Execution }

        # @!attribute status
        #   The status of the tool search output item that was recorded.
        #
        #   @return [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItem::Status]
        required :status, enum: -> { OpenAI::Beta::BetaResponseToolSearchOutputItem::Status }

        # @!attribute tools
        #   The loaded tool definitions returned by tool search.
        #
        #   @return [Array<OpenAI::Models::Beta::BetaFunctionTool, OpenAI::Models::Beta::BetaFileSearchTool, OpenAI::Models::Beta::BetaComputerTool, OpenAI::Models::Beta::BetaComputerUsePreviewTool, OpenAI::Models::Beta::BetaTool::Mcp, OpenAI::Models::Beta::BetaTool::CodeInterpreter, OpenAI::Models::Beta::BetaTool::ProgrammaticToolCalling, OpenAI::Models::Beta::BetaTool::ImageGeneration, OpenAI::Models::Beta::BetaTool::LocalShell, OpenAI::Models::Beta::BetaFunctionShellTool, OpenAI::Models::Beta::BetaCustomTool, OpenAI::Models::Beta::BetaNamespaceTool, OpenAI::Models::Beta::BetaToolSearchTool, OpenAI::Models::Beta::BetaApplyPatchTool, OpenAI::Models::Beta::BetaWebSearchTool, OpenAI::Models::Beta::BetaWebSearchPreviewTool>]
        required :tools, -> { OpenAI::Internal::Type::ArrayOf[union: OpenAI::Beta::BetaTool] }

        # @!attribute type
        #   The type of the item. Always `tool_search_output`.
        #
        #   @return [Symbol, :tool_search_output]
        required :type, const: :tool_search_output

        # @!attribute agent
        #   The agent that produced this item.
        #
        #   @return [OpenAI::Models::Beta::BetaResponseToolSearchOutputItem::Agent, nil]
        optional :agent, -> { OpenAI::Beta::BetaResponseToolSearchOutputItem::Agent }

        # @!attribute created_by
        #   The identifier of the actor that created the item.
        #
        #   @return [String, nil]
        optional :created_by, String

        # @!method initialize(id:, call_id:, execution:, status:, tools:, agent: nil, created_by: nil, type: :tool_search_output)
        #   @param id [String] The unique ID of the tool search output item.
        #
        #   @param call_id [String, nil] The unique ID of the tool search call generated by the model.
        #
        #   @param execution [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItem::Execution] Whether tool search was executed by the server or by the client.
        #
        #   @param status [Symbol, OpenAI::Models::Beta::BetaResponseToolSearchOutputItem::Status] The status of the tool search output item that was recorded.
        #
        #   @param tools [Array<OpenAI::Models::Beta::BetaFunctionTool, OpenAI::Models::Beta::BetaFileSearchTool, OpenAI::Models::Beta::BetaComputerTool, OpenAI::Models::Beta::BetaComputerUsePreviewTool, OpenAI::Models::Beta::BetaTool::Mcp, OpenAI::Models::Beta::BetaTool::CodeInterpreter, OpenAI::Models::Beta::BetaTool::ProgrammaticToolCalling, OpenAI::Models::Beta::BetaTool::ImageGeneration, OpenAI::Models::Beta::BetaTool::LocalShell, OpenAI::Models::Beta::BetaFunctionShellTool, OpenAI::Models::Beta::BetaCustomTool, OpenAI::Models::Beta::BetaNamespaceTool, OpenAI::Models::Beta::BetaToolSearchTool, OpenAI::Models::Beta::BetaApplyPatchTool, OpenAI::Models::Beta::BetaWebSearchTool, OpenAI::Models::Beta::BetaWebSearchPreviewTool>] The loaded tool definitions returned by tool search.
        #
        #   @param agent [OpenAI::Models::Beta::BetaResponseToolSearchOutputItem::Agent] The agent that produced this item.
        #
        #   @param created_by [String] The identifier of the actor that created the item.
        #
        #   @param type [Symbol, :tool_search_output] The type of the item. Always `tool_search_output`.

        # Whether tool search was executed by the server or by the client.
        #
        # @see OpenAI::Models::Beta::BetaResponseToolSearchOutputItem#execution
        module Execution
          extend OpenAI::Internal::Type::Enum

          SERVER = :server
          CLIENT = :client

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # The status of the tool search output item that was recorded.
        #
        # @see OpenAI::Models::Beta::BetaResponseToolSearchOutputItem#status
        module Status
          extend OpenAI::Internal::Type::Enum

          IN_PROGRESS = :in_progress
          COMPLETED = :completed
          INCOMPLETE = :incomplete

          # @!method self.values
          #   @return [Array<Symbol>]
        end

        # @see OpenAI::Models::Beta::BetaResponseToolSearchOutputItem#agent
        class Agent < OpenAI::Internal::Type::BaseModel
          # @!attribute agent_name
          #   The canonical name of the agent that produced this item.
          #
          #   @return [String]
          required :agent_name, String

          # @!method initialize(agent_name:)
          #   The agent that produced this item.
          #
          #   @param agent_name [String] The canonical name of the agent that produced this item.
        end
      end
    end

    BetaResponseToolSearchOutputItem = Beta::BetaResponseToolSearchOutputItem
  end
end
