# frozen_string_literal: true

module OpenAI
  module Models
    module Beta
      class TokenUsage < OpenAI::Internal::Type::BaseModel
        # @!attribute input_tokens
        #   The number of input tokens used by the agent.
        #
        #   @return [Integer]
        required :input_tokens, Integer

        # @!attribute input_tokens_details
        #   A breakdown of the agent's input token usage.
        #
        #   @return [OpenAI::Models::Beta::TokenUsage::InputTokensDetails]
        required :input_tokens_details, -> { OpenAI::Beta::TokenUsage::InputTokensDetails }

        # @!attribute output_tokens
        #   The number of output tokens generated by the agent.
        #
        #   @return [Integer]
        required :output_tokens, Integer

        # @!attribute output_tokens_details
        #   A breakdown of the agent's output token usage.
        #
        #   @return [OpenAI::Models::Beta::TokenUsage::OutputTokensDetails]
        required :output_tokens_details, -> { OpenAI::Beta::TokenUsage::OutputTokensDetails }

        # @!attribute total_tokens
        #   The total number of input and output tokens used by the agent.
        #
        #   @return [Integer]
        required :total_tokens, Integer

        # @!method initialize(input_tokens:, input_tokens_details:, output_tokens:, output_tokens_details:, total_tokens:)
        #   Recorded token usage for a session or turn. Usage is best effort and may change.
        #
        #   @param input_tokens [Integer]
        #     The number of input tokens used by the agent.
        #
        #   @param input_tokens_details [OpenAI::Models::Beta::TokenUsage::InputTokensDetails]
        #     A breakdown of the agent's input token usage.
        #
        #   @param output_tokens [Integer]
        #     The number of output tokens generated by the agent.
        #
        #   @param output_tokens_details [OpenAI::Models::Beta::TokenUsage::OutputTokensDetails]
        #     A breakdown of the agent's output token usage.
        #
        #   @param total_tokens [Integer]
        #     The total number of input and output tokens used by the agent.

        # @see OpenAI::Models::Beta::TokenUsage#input_tokens_details
        class InputTokensDetails < OpenAI::Internal::Type::BaseModel
          # @!attribute cached_tokens
          #   The number of input tokens retrieved from the prompt cache.
          #
          #   @return [Integer]
          required :cached_tokens, Integer

          # @!method initialize(cached_tokens:)
          #   A breakdown of the agent's input token usage.
          #
          #   @param cached_tokens [Integer]
          #     The number of input tokens retrieved from the prompt cache.
        end

        # @see OpenAI::Models::Beta::TokenUsage#output_tokens_details
        class OutputTokensDetails < OpenAI::Internal::Type::BaseModel
          # @!attribute reasoning_tokens
          #   The number of output tokens used for reasoning.
          #
          #   @return [Integer]
          required :reasoning_tokens, Integer

          # @!method initialize(reasoning_tokens:)
          #   A breakdown of the agent's output token usage.
          #
          #   @param reasoning_tokens [Integer]
          #     The number of output tokens used for reasoning.
        end
      end
    end
  end
end
