module OpenAI
  module Internal
    module Type
      module BasePage[Elem]
        def next_page?: -> bool

        def next_page: -> instance

        def auto_paging_each: { (Elem arg0) -> void } -> void

        def to_enum: -> Enumerable[Elem]

        alias enum_for to_enum

        def response_headers: -> ::Hash[String, String]?

        def initialize: (
          client: OpenAI::Internal::Transport::BaseClient,
          req: OpenAI::Internal::Transport::BaseClient::request_components,
          headers: ::Hash[String, String],
          page_data: top
        ) -> void

        def __set_response_headers: (::Hash[String, String] headers) -> self
      end
    end
  end
end
