module OpenAI
  module Models
    module Admin
      module Organization
        type admin_api_key_delete_params =
          { key_id: String } & OpenAI::Internal::Type::request_parameters

        class AdminAPIKeyDeleteParams < OpenAI::Internal::Type::BaseModel
          extend OpenAI::Internal::Type::RequestParameters::Converter
          include OpenAI::Internal::Type::RequestParameters

          attr_accessor key_id: String

          def initialize: (
            key_id: String,
            ?request_options: OpenAI::request_opts
          ) -> void

          def to_hash: -> {
            key_id: String,
            request_options: OpenAI::RequestOptions
          }
        end
      end
    end
  end
end
