module OpenAI
  module Models
    module Admin
      module Organization
        type invite_create_params =
          {
            email: String,
            role: OpenAI::Models::Admin::Organization::InviteCreateParams::role,
            ?projects: ::Array[OpenAI::Admin::Organization::InviteCreateParams::Project],
            ?request_options: OpenAI::request_opts
          }

        class InviteCreateParams < OpenAI::Internal::Type::BaseModel
          extend OpenAI::Internal::Type::RequestParameters::Converter
          include OpenAI::Internal::Type::RequestParameters

          # Send an email to this address
          attr_accessor email: String

          # `owner` or `reader`
          attr_accessor role: OpenAI::Models::Admin::Organization::InviteCreateParams::role

          # An array of projects to which membership is granted at the same time the org
          # invite is accepted. If omitted, the user will be invited to the default project
          # for compatibility with legacy behavior. If empty list is passed, the user will
          # not be invited to any projects, including the default one.
          attr_reader projects: ::Array[OpenAI::Admin::Organization::InviteCreateParams::Project]?

          # An array of projects to which membership is granted at the same time the org
          # invite is accepted. If omitted, the user will be invited to the default project
          # for compatibility with legacy behavior. If empty list is passed, the user will
          # not be invited to any projects, including the default one.
          def projects=: (
            ::Array[OpenAI::Admin::Organization::InviteCreateParams::Project]
          ) -> ::Array[OpenAI::Admin::Organization::InviteCreateParams::Project]

          # @param email
          #   Send an email to this address
          # @param role
          #   `owner` or `reader`
          # @param projects
          #   An array of projects to which membership is granted at the same time the org
          #   invite is accepted. If omitted, the user will be invited to the default project
          #   for compatibility with legacy behavior. If empty list is passed, the user will
          #   not be invited to any projects, including the default one.
          def initialize: (
            email: String,
            role: OpenAI::Models::Admin::Organization::InviteCreateParams::role,
            ?projects: ::Array[OpenAI::Admin::Organization::InviteCreateParams::Project],
            ?request_options: OpenAI::request_opts
          ) -> void

          def to_hash: -> {
            email: String,
            role: OpenAI::Models::Admin::Organization::InviteCreateParams::role,
            ?projects: ::Array[OpenAI::Admin::Organization::InviteCreateParams::Project],
            ?request_options: OpenAI::RequestOptions
          }

          type role = :reader | :owner

          module Role
            extend OpenAI::Internal::Type::Enum

            READER: :reader
            OWNER: :owner

            def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::InviteCreateParams::role]
          end

          type project =
            {
              id: String,
              role: OpenAI::Models::Admin::Organization::InviteCreateParams::Project::role
            }

          class Project < OpenAI::Internal::Type::BaseModel
            # Project's public ID
            attr_accessor id: String

            # Project membership role
            attr_accessor role: OpenAI::Models::Admin::Organization::InviteCreateParams::Project::role

            # @param id
            #   Project's public ID
            # @param role
            #   Project membership role
            def initialize: (
              id: String,
              role: OpenAI::Models::Admin::Organization::InviteCreateParams::Project::role
            ) -> void

            def to_hash: -> {
              id: String,
              role: OpenAI::Models::Admin::Organization::InviteCreateParams::Project::role
            }

            type role = :member | :owner

            module Role
              extend OpenAI::Internal::Type::Enum

              MEMBER: :member
              OWNER: :owner

              def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::InviteCreateParams::Project::role]
            end
          end
        end
      end
    end
  end
end
