module OpenAI
  module Models
    module Admin
      class OrganizationSpendAlertDeleted = Organization::OrganizationSpendAlertDeleted

      module Organization
        type organization_spend_alert_deleted =
          {
            id: String,
            deleted: bool,
            ?object: :"organization.spend_alert.deleted"
          }

        class OrganizationSpendAlertDeleted < OpenAI::Internal::Type::BaseModel
          # The deleted spend alert ID.
          attr_accessor id: String

          # Whether the spend alert was deleted.
          attr_accessor deleted: bool

          # Always `organization.spend_alert.deleted`.
          attr_accessor object: :"organization.spend_alert.deleted"

          # @param id
          #   The deleted spend alert ID.
          # @param deleted
          #   Whether the spend alert was deleted.
          # @param object
          #   Always `organization.spend_alert.deleted`.
          def initialize: (
            id: String,
            deleted: bool,
            ?object: :"organization.spend_alert.deleted"
          ) -> void

          def to_hash: -> {
            id: String,
            deleted: bool,
            ?object: :"organization.spend_alert.deleted"
          }
        end
      end
    end
  end
end
