module OpenAI
  module Models
    module Admin
      module Organization
        type project =
          {
            id: String,
            created_at: Integer,
            name: String,
            object: :"organization.project",
            status: OpenAI::Models::Admin::Organization::Project::status,
            archived_at: Integer?
          }

        class Project < OpenAI::Internal::Type::BaseModel
          attr_accessor id: String

          attr_accessor created_at: Integer

          attr_accessor name: String

          attr_accessor object: :"organization.project"

          attr_accessor status: OpenAI::Models::Admin::Organization::Project::status

          attr_accessor archived_at: Integer?

          def initialize: (
            id: String,
            created_at: Integer,
            name: String,
            status: OpenAI::Models::Admin::Organization::Project::status,
            ?archived_at: Integer?,
            ?object: :"organization.project"
          ) -> void

          def to_hash: -> {
            id: String,
            created_at: Integer,
            name: String,
            object: :"organization.project",
            status: OpenAI::Models::Admin::Organization::Project::status,
            archived_at: Integer?
          }

          type status = :active | :archived

          module Status
            extend OpenAI::Internal::Type::Enum

            ACTIVE: :active
            ARCHIVED: :archived

            def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::Project::status]
          end
        end
      end
    end
  end
end
