module OpenAI
  module Models
    module Admin
      module Organization
        type spend_alert_list_params =
          {
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?order: OpenAI::Models::Admin::Organization::SpendAlertListParams::order,
            ?request_options: OpenAI::request_opts
          }

        class SpendAlertListParams < OpenAI::Internal::Type::BaseModel
          extend OpenAI::Internal::Type::RequestParameters::Converter
          include OpenAI::Internal::Type::RequestParameters

          # Cursor for pagination. Provide the ID of the last spend alert from the previous
          # response to fetch the next page.
          attr_reader after: String?

          # Cursor for pagination. Provide the ID of the last spend alert from the previous
          # response to fetch the next page.
          def after=: (String) -> String

          # Cursor for pagination. Provide the ID of the first spend alert from the previous
          # response to fetch the previous page.
          attr_reader before: String?

          # Cursor for pagination. Provide the ID of the first spend alert from the previous
          # response to fetch the previous page.
          def before=: (String) -> String

          # A limit on the number of spend alerts to return. Defaults to 20.
          attr_reader limit: Integer?

          # A limit on the number of spend alerts to return. Defaults to 20.
          def limit=: (Integer) -> Integer

          # Sort order for the returned spend alerts.
          attr_reader order: OpenAI::Models::Admin::Organization::SpendAlertListParams::order?

          # Sort order for the returned spend alerts.
          def order=: (
            OpenAI::Models::Admin::Organization::SpendAlertListParams::order
          ) -> OpenAI::Models::Admin::Organization::SpendAlertListParams::order

          # @param after
          #   Cursor for pagination. Provide the ID of the last spend alert from the previous
          #   response to fetch the next page.
          # @param before
          #   Cursor for pagination. Provide the ID of the first spend alert from the previous
          #   response to fetch the previous page.
          # @param limit
          #   A limit on the number of spend alerts to return. Defaults to 20.
          # @param order
          #   Sort order for the returned spend alerts.
          def initialize: (
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?order: OpenAI::Models::Admin::Organization::SpendAlertListParams::order,
            ?request_options: OpenAI::request_opts
          ) -> void

          def to_hash: -> {
            ?after: String,
            ?before: String,
            ?limit: Integer,
            ?order: OpenAI::Models::Admin::Organization::SpendAlertListParams::order,
            ?request_options: OpenAI::RequestOptions
          }

          type order = :asc | :desc

          module Order
            extend OpenAI::Internal::Type::Enum

            ASC: :asc
            DESC: :desc

            def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::SpendAlertListParams::order]
          end
        end
      end
    end
  end
end
