module OpenAI
  module Models
    module Admin
      module Organization
        type spend_limit_update_params =
          {
            currency: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::currency,
            interval: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::interval,
            threshold_amount: Integer,
            ?request_options: OpenAI::request_opts
          }

        class SpendLimitUpdateParams < OpenAI::Internal::Type::BaseModel
          extend OpenAI::Internal::Type::RequestParameters::Converter
          include OpenAI::Internal::Type::RequestParameters

          # The currency for the threshold amount. Currently, only `USD` is supported.
          attr_accessor currency: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::currency

          # The time interval for evaluating spend against the threshold. Currently, only
          # `month` is supported.
          attr_accessor interval: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::interval

          # The hard spend limit amount, in cents.
          attr_accessor threshold_amount: Integer

          # @param currency
          #   The currency for the threshold amount. Currently, only `USD` is supported.
          # @param interval
          #   The time interval for evaluating spend against the threshold. Currently, only
          #   `month` is supported.
          # @param threshold_amount
          #   The hard spend limit amount, in cents.
          def initialize: (
            currency: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::currency,
            interval: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::interval,
            threshold_amount: Integer,
            ?request_options: OpenAI::request_opts
          ) -> void

          def to_hash: -> {
            currency: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::currency,
            interval: OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::interval,
            threshold_amount: Integer,
            ?request_options: OpenAI::RequestOptions
          }

          type currency = :USD

          module Currency
            extend OpenAI::Internal::Type::Enum

            USD: :USD

            def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::currency]
          end

          type interval = :month

          module Interval
            extend OpenAI::Internal::Type::Enum

            MONTH: :month

            def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::SpendLimitUpdateParams::interval]
          end
        end
      end
    end
  end
end
