module OpenAI
  module Models
    module Admin
      module Organization
        type usage_costs_params =
          {
            start_time: Integer,
            ?api_key_ids: ::Array[String],
            ?bucket_width: OpenAI::Models::Admin::Organization::UsageCostsParams::bucket_width,
            ?end_time: Integer,
            ?group_by: ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::group_by],
            ?limit: Integer,
            ?line_items: ::Array[String],
            ?page: String,
            ?project_ids: ::Array[String],
            ?request_options: OpenAI::request_opts
          }

        class UsageCostsParams < OpenAI::Internal::Type::BaseModel
          extend OpenAI::Internal::Type::RequestParameters::Converter
          include OpenAI::Internal::Type::RequestParameters

          # Start time (Unix seconds) of the query time range, inclusive.
          attr_accessor start_time: Integer

          # Return only costs for these API keys.
          attr_reader api_key_ids: ::Array[String]?

          # Return only costs for these API keys.
          def api_key_ids=: (::Array[String]) -> ::Array[String]

          # Width of each time bucket in response. Currently only `1d` is supported, default
          # to `1d`.
          attr_reader bucket_width: OpenAI::Models::Admin::Organization::UsageCostsParams::bucket_width?

          # Width of each time bucket in response. Currently only `1d` is supported, default
          # to `1d`.
          def bucket_width=: (
            OpenAI::Models::Admin::Organization::UsageCostsParams::bucket_width
          ) -> OpenAI::Models::Admin::Organization::UsageCostsParams::bucket_width

          # End time (Unix seconds) of the query time range, exclusive.
          attr_reader end_time: Integer?

          # End time (Unix seconds) of the query time range, exclusive.
          def end_time=: (Integer) -> Integer

          # Group the costs by the specified fields. Support fields include `project_id`,
          # `line_item`, `api_key_id` and any combination of them.
          attr_reader group_by: ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::group_by]?

          # Group the costs by the specified fields. Support fields include `project_id`,
          # `line_item`, `api_key_id` and any combination of them.
          def group_by=: (
            ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::group_by]
          ) -> ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::group_by]

          # A limit on the number of buckets to be returned. Limit can range between 1 and
          # 180, and the default is 7.
          attr_reader limit: Integer?

          # A limit on the number of buckets to be returned. Limit can range between 1 and
          # 180, and the default is 7.
          def limit=: (Integer) -> Integer

          # Return only costs for these exact line item names. Each value must match the
          # complete `line_item` value, for example `gpt-6-astra, input_tokens`.
          attr_reader line_items: ::Array[String]?

          # Return only costs for these exact line item names. Each value must match the
          # complete `line_item` value, for example `gpt-6-astra, input_tokens`.
          def line_items=: (::Array[String]) -> ::Array[String]

          # A cursor for use in pagination. Corresponding to the `next_page` field from the
          # previous response.
          attr_reader page: String?

          # A cursor for use in pagination. Corresponding to the `next_page` field from the
          # previous response.
          def page=: (String) -> String

          # Return only costs for these projects.
          attr_reader project_ids: ::Array[String]?

          # Return only costs for these projects.
          def project_ids=: (::Array[String]) -> ::Array[String]

          # @param start_time
          #   Start time (Unix seconds) of the query time range, inclusive.
          # @param api_key_ids
          #   Return only costs for these API keys.
          # @param bucket_width
          #   Width of each time bucket in response. Currently only `1d` is supported, default
          #   to `1d`.
          # @param end_time
          #   End time (Unix seconds) of the query time range, exclusive.
          # @param group_by
          #   Group the costs by the specified fields. Support fields include `project_id`,
          #   `line_item`, `api_key_id` and any combination of them.
          # @param limit
          #   A limit on the number of buckets to be returned. Limit can range between 1 and
          #   180, and the default is 7.
          # @param line_items
          #   Return only costs for these exact line item names. Each value must match the
          #   complete `line_item` value, for example `gpt-6-astra, input_tokens`.
          # @param page
          #   A cursor for use in pagination. Corresponding to the `next_page` field from the
          #   previous response.
          # @param project_ids
          #   Return only costs for these projects.
          def initialize: (
            start_time: Integer,
            ?api_key_ids: ::Array[String],
            ?bucket_width: OpenAI::Models::Admin::Organization::UsageCostsParams::bucket_width,
            ?end_time: Integer,
            ?group_by: ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::group_by],
            ?limit: Integer,
            ?line_items: ::Array[String],
            ?page: String,
            ?project_ids: ::Array[String],
            ?request_options: OpenAI::request_opts
          ) -> void

          def to_hash: -> {
            start_time: Integer,
            ?api_key_ids: ::Array[String],
            ?bucket_width: OpenAI::Models::Admin::Organization::UsageCostsParams::bucket_width,
            ?end_time: Integer,
            ?group_by: ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::group_by],
            ?limit: Integer,
            ?line_items: ::Array[String],
            ?page: String,
            ?project_ids: ::Array[String],
            ?request_options: OpenAI::RequestOptions
          }

          type bucket_width = :"1d"

          module BucketWidth
            extend OpenAI::Internal::Type::Enum

            BUCKET_WIDTH_1D: :"1d"

            def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::bucket_width]
          end

          type group_by = :project_id | :line_item | :api_key_id

          module GroupBy
            extend OpenAI::Internal::Type::Enum

            PROJECT_ID: :project_id
            LINE_ITEM: :line_item
            API_KEY_ID: :api_key_id

            def self?.values: -> ::Array[OpenAI::Models::Admin::Organization::UsageCostsParams::group_by]
          end
        end
      end
    end
  end
end
