module OpenAI
  module Models
    module Admin
      module Organization
        type user_update_params =
          {
            user_id: String,
            ?developer_persona: String?,
            ?role: String?,
            ?role_id: String?,
            ?technical_level: String?,
            ?request_options: OpenAI::request_opts
          }

        class UserUpdateParams < OpenAI::Internal::Type::BaseModel
          extend OpenAI::Internal::Type::RequestParameters::Converter
          include OpenAI::Internal::Type::RequestParameters

          attr_accessor user_id: String

          # Developer persona metadata.
          attr_accessor developer_persona: String?

          # `owner` or `reader`
          attr_accessor role: String?

          # Role ID to assign to the user.
          attr_accessor role_id: String?

          # Technical level metadata.
          attr_accessor technical_level: String?

          # @param developer_persona
          #   Developer persona metadata.
          # @param role
          #   `owner` or `reader`
          # @param role_id
          #   Role ID to assign to the user.
          # @param technical_level
          #   Technical level metadata.
          def initialize: (
            user_id: String,
            ?developer_persona: String?,
            ?role: String?,
            ?role_id: String?,
            ?technical_level: String?,
            ?request_options: OpenAI::request_opts
          ) -> void

          def to_hash: -> {
            user_id: String,
            ?developer_persona: String?,
            ?role: String?,
            ?role_id: String?,
            ?technical_level: String?,
            ?request_options: OpenAI::RequestOptions
          }
        end
      end
    end
  end
end
