# workflow for re-running publishing to rubygems.org in case it fails for some reason
# you can run this workflow by navigating to https://www.github.com/openai/openai-python/actions/workflows/publish-gem.yml
name: Publish Gem
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
          ruby-version: '3.1'
      - run: |-
          bundle install

      - name: Publish to RubyGems.org
        run: |
          bash ./bin/publish-gem
        env:
          # `RUBYGEMS_HOST` is only required for private gem repositories, not https://rubygems.org
          RUBYGEMS_HOST: ${{ secrets.OPENAI_RUBYGEMS_HOST || secrets.RUBYGEMS_HOST }}
          GEM_HOST_API_KEY: ${{ secrets.OPENAI_GEM_HOST_API_KEY || secrets.GEM_HOST_API_KEY }}
